### ISSUE TITLE
Dialog boxes for remove vs delete

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#10]

**Comment by miledivovic** [comment]
Added dialog for delete in b76fc93.

**Comment by eddavies** [comment]
Works as intended

**Comment by Lomilar** [comment]
Regression. Please test with remove/delete for a single competency or an entire framework. (or update from another issue).

**Comment by Lomilar** [comment]
Remove lacks dialog box. "This will remove the competency from your framework (but not delete it), do you wish to continue?"

**Comment by eddavies** [comment]
For deleting a single competency the dialog box states that the competency will be removed from the entire server. However, currently that is not the case. Deleting a competency does not remove the competency from other frameworks that have added it.

**Comment by Lomilar** [comment]
Due to security issues (one individual is not permitted to modify another individual's frameworks) this is a true and valid restriction.

The dialog may wish to declare the number of frameworks that will break as part of the dialog message (in a similar way to the function conditionalDelete) to help inform the user of this issue.

**Comment by miledivovic** [comment]
Fixed in c7f8238

**Comment by eddavies** [comment]
competency remove dialog: 👍
framework deletion dialog: 👍

competency delete dialog: Just made a new competency in a framework and went to delete it immediately after creating and the message said that "Up to 2 frameworks may break". Is up to 2 a minimum?

**Comment by Lomilar** [comment]
The normal search will return two records: One for the competency and one for the framework. I scoped the search to just frameworks, which makes the logic work more better.

This could cause some other types of objects to break like relations, but relations shouldn't exist in frameworks that don't include the competencies.
