### ISSUE TITLE
CaSS updates on staging is creating log files that used all available space on the C drive

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1003]
The C drive on the staging server has run out of space.
I tried to clear various files/folders and in no time all space is used again.
I then found the folder: C:\Users\cassAdmin\.pm2\logs contains over 60gb of files.

![image](https://user-images.githubusercontent.com/58825866/147397422-bc972068-3d80-4d16-92e7-6e836050dfdc.png)

**Comment by woodkri** [comment]
Evidently the log rotation module I was trying out only halfway works on Windows. Is there anything you're currently using for log rotation on these machines that we could also use to manage these, or should I look into options for Windows?

**Comment by mparsons-ce** [comment]
We use an internal custom process for logs, so nothing to help you. 
One of the single log files was many gb, so I deleted it. I didn't look too closely at the errors to assess if there was some source on our side.
