### ISSUE TITLE
CTDL+ASN export in other RDF forms.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#101]

**Comment by stuartasutton** [comment]
Primary serializations for CTDL+ASN expert should be as json-ld (.jsonld), turtle (.ttl), and rdf/xml (.rdf) with the noted file extensions.

**Comment by jeannekitchens** [comment]
@stuartasutton is this still open?  Can we close it?

**Comment by stuartasutton** [comment]
I've not review the array of exports in some time. This has obviously been hanging around for a long time.

**Comment by woodkri** [comment]
We currently have CTDL-ASN exports available in json-ld and csv formats.

**Comment by stuartasutton** [comment]
I guess we can assume that if someone downstream wants the RDF data in ttl or rdf/xml that they can use one of the available public converters to generate those versions off the json-ld
