### ISSUE TITLE
Lots of errors when trying to create a concept scheme

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1035]
1. On sandbox, go to the concept scheme editor
2. Select organization
3. Click new > Concept (this should say "Concept Scheme")
4. Immediately receive two errors:
![image](https://user-images.githubusercontent.com/21346519/151434246-f03ac2a9-1778-4d40-b201-367c043bc5c3.png)

5. Enter a name
6. Wait a few seconds for the AJAX requests to update the data
7. Receive 4 more errors over the course of that process:
![image](https://user-images.githubusercontent.com/21346519/151434410-29ca74c1-874c-4c81-bfb6-ac72668c7151.png)

8. Enter a description
9. Tab to the next text box
10. Receive more errors:
![image](https://user-images.githubusercontent.com/21346519/151434541-903782e1-b812-4a5b-b53d-779d36498c6a.png)

11. Attempt to tab to the "done" button"
12. Become overwhelmed
![image](https://user-images.githubusercontent.com/21346519/151434793-8501dfba-f42e-4200-9481-fffd30baffdb.png)

I realize this is likely the same process throwing a few errors repeatedly, but what's causing this? Is this on our side or CaSS's side?

**Comment by woodkri** [comment]
See #1029. It's up on staging but not yet on sandbox.

**Comment by woodkri** [comment]
Closing as duplicate.
