### ISSUE TITLE
Long delays and inability to edit concepts in a scheme

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1036]
@woodkri On staging:

After creating a concept scheme, clicking "add concept" > "create new" doesn't do anything (in the UI).  In the console, I see some errors that show up each time I try.  Note that some of these errors appeared during the process of trying to create the concept scheme itself, but I was ultimately able to do that.
![image](https://user-images.githubusercontent.com/21346519/151436845-8aee5ad6-771d-4647-a896-c7d922d0ddde.png)

While I was typing up this issue, two of the concepts suddenly appeared.  It seems that something was happening after all, but there's no indication to the user that a process is started/ongoing.
![image](https://user-images.githubusercontent.com/21346519/151436793-b267a32b-9e36-4b0b-a486-d224126332da.png)

Clicking on either of the concepts does nothing - not even a new network request is triggered.  So it seems I'm able to create concepts (slowly), but not able to edit them.

Is this just a matter of staging being slow/misconfigured?  There should be some kind of UI feedback to let the user know that something is happening in the background.

**Comment by siuc-nate** [comment]
It seems I'm also unable to edit the scheme itself.  When I click on the edit button, the modal window appears immediately and when I click the "done" button after making a change, the modal behaves as if it worked properly - but the change (such as a different name) does not show in the data.

**Comment by siuc-nate** [comment]
Actually, it did save the changes - but for some reason I was taken to the editor for a new concept scheme instead:
![image](https://user-images.githubusercontent.com/21346519/151438480-b26b23b4-6c44-4dc9-90fe-ecdd4327d248.png)

**Comment by woodkri** [comment]
This one might be because I've been trying some things on the staging server in an attempt to solve the Tech Skills import issue. Those 502s might have been when I was restarting the server.

Editing concept schemes and adding concepts is working for me right now anyway.

**Comment by jeannekitchens** [comment]
@siuc-nate was just ahead of posting this on staging finding these issues.  Is that timing hitting up against your working on staging @woodkri .  I recommend that we use the CaSS private slack channel to announce to the CE group when working on the staging server and making it bi-directional so we all know what's going on.

**Comment by woodkri** [comment]
@siuc-nate Have you come across these issues again or was it only happening the day I was debugging on staging?

**Comment by siuc-nate** [comment]
Not since then, no. Server lag would make sense I think.

**Comment by siuc-nate** [comment]
Actually, on testing it again this morning, there are still some long delays in competency edits.  With this framework:
https://staging.credentialengineregistry.org/graph/ce-52b6840f-0264-4708-ab50-52f4b4bdd463

Every time I try to edit the competency text, the edit never seems to take effect until I make another edit (at which point I usually see the previous edit reflected on the framework's page).  Sometimes the edit works, sometimes it does not.  There's no indication of "something is happening, please wait" so it's hard to tell exactly where the problem is.

**Comment by woodkri** [comment]
@siuc-nate This is now on production; let me know if you're still seeing issues or if this can be closed.

**Comment by siuc-nate** [comment]
I'm unable to add any competencies to this framework:
[https://staging.credentialengineregistry.org/resources/ce-0907a5d9-57c1-4dd4-8bb1-6f63ca00ce7f]()

I click the "add competency" button, then the "create new" button, and no modal is displayed. The only thing that happens is that the "create new" button goes away and the "add competency" button reappears.

**Comment by woodkri** [comment]
Reviewed in meeting 3/16, ready for staging/prod.
