### ISSUE TITLE
Strange bugs when creating/editing a competency framework

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1037]
On staging:

When creating a new competency framework, the Publisher Name field does not have any language assigned to it by default:
![image](https://user-images.githubusercontent.com/21346519/151440052-66b9807c-0e53-4539-a3aa-9cfd597c1431.png)

After typing in a language, I see an error message:
![image](https://user-images.githubusercontent.com/21346519/151440154-43f97765-4c6c-4606-88f6-7e0438b10c6a.png)

It isn't until I clear that out and start typing "english" and click the autofill suggestion that it works - but now that language field looks different from the other language fields in the form:
![image](https://user-images.githubusercontent.com/21346519/151440298-279facd9-d6dc-483b-a666-04b768b673f0.png)

If I then clear out that box again, no error message shows and I am able to create the framework.  That seems like it shouldn't be allowed.
![image](https://user-images.githubusercontent.com/21346519/151440586-8ba74d19-1a2c-42ff-9fc4-96605263f117.png)

When I click the edit button, it has now defaulted to "en" instead of "en-US"
![image](https://user-images.githubusercontent.com/21346519/151440543-6f61f3f7-ad0f-40b2-a806-296dc93d4bd2.png)

If I edit the name, but click the X in the upper-right instead of clicking "done", the change appears to be ignored (as is the intended behavior) - however, if I click edit again, the change is still present.  If I didn't think to look for that, it's possible I might publish the framework with an unintended change to its data. If I click the X button again, however, the change now shows up:
![image](https://user-images.githubusercontent.com/21346519/151440853-8439d944-7acf-4075-86a0-fe7248f5a096.png)
![image](https://user-images.githubusercontent.com/21346519/151441034-364abf4c-0b73-4848-802e-13a5c98e9f9a.png)

I repeated the above process again, but this time, the change was immediately reflected in the display (perhaps another strange AJAX delay in the process?).  However, because I was clicking X and not "done", no change should have ever been applied.

**Comment by woodkri** [comment]
The language should show up for publisherName in the next update.

Changes are auto-saved so clicking the x does not stop changes from occurring, it just closes the modal. We may want to revisit having an x on this modal.
