### ISSUE TITLE
Bugs when editing a competency

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1039]
While editing a competency on staging:

- I tried to add "performance level type" via the search, but the concepts were not associated after clicking "add selected"
- I tried to add "inferred competency" via the search, but the competencies were not associated after clicking "add selected"

I was able to add both via URL but not via the built-in search.

**Comment by woodkri** [comment]
Fix for performance level type coming. I'm not able to reproduce the issue for inferred competency.

**Comment by woodkri** [comment]
Performance level type is now fixed on production. I was never able to reproduce the issue for inferred competency; let me know if this is still an issue or if it can be closed.

**Comment by jeannekitchens** [comment]
@siuc-nate see above from Kristin.  Indicate if there's still an issue or close this please.

**Comment by siuc-nate** [comment]
I will check as soon as I get a chance.

**Comment by siuc-nate** [comment]
These are working, but the labels don't appear to be correct:
![image](https://user-images.githubusercontent.com/21346519/156027794-e4287081-33d9-414e-af4f-e2d97518489a.png)

**Comment by jeannekitchens** [comment]
The label needs to be corrected with casing and spacing.

**Comment by woodkri** [comment]
Reviewed in meeting 3/16, ready for staging/prod.
