### ISSUE TITLE
Accessibility of ceterms concept schemes to CASS editor.

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#104]
@Lomilar, @jkitchensSIUC, & @siuc-nate, currently, the thinking is that all concept schemes and competency frameworks "in" CASS also live in the Registry. However, none of the CTDL-authored concept schemes in the Registry are "in" or accessible to CASS. **That needs to be rectified**. We already have a need in CASS editing for the [ceterms:AudienceLevel](http://purl.org/ctdl/terms/AudienceLevel) vocabulary. The viewer TOC for concept schemes in CASS should reflect (and make available) **all** of the concept schemes at http://credreg.net/ctdl/terms/AudienceLevel#conceptschemes.

**Comment by Lomilar** [comment]
Depends on a mechanism for streaming updates from the CR to CASS.

https://github.com/CredentialEngine/CredentialRegistry/issues/152
