### ISSUE TITLE
Collection: Keyword should be a list not single

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1041]
re: collection: _Collection of useful competencies_

Per https://github.com/cassproject/cass-editor/issues/952, keyword is to be a list, and currently the interface (and export) is a single lang string.

ALSO:
The properties: InLanguage and codedNotation have data in the UI but not present in the export..

**Comment by woodkri** [comment]
Keyword will be an array per language in the export in the next push. It's currently available in the interface as multiple.

For inLanguage and codedNotation, I'm noticing these are defined in your contexts (https://credreg.net/ctdlasn/schema/context/json & https://credreg.net/ctdl/schema/context/json) as @type: @id, have they always been this way? I have them in our translations as xsd:language and xsd:string so they're not compacting properly.

**Comment by woodkri** [comment]
Keyword is now an array.

**Comment by jeannekitchens** [comment]
@woodkri this is addressed?

**Comment by woodkri** [comment]
Keyword as an array is addressed. I had a question above about inLanguage and codedNotation in CE's context that I haven't heard back on so those are not exporting yet.
