### ISSUE TITLE
Collection: on create of a new collection, the owned by property should be set to the user's organization

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1043]
When creating a framework, the publisher and creator are set to the organization of the current user. 
When creating a collection the owned by should likewise be set to the organization of the current user.

**Comment by woodkri** [comment]
This can be set by adding "ceterms:ownedBy": "<org>" to the template postMessage for framework - unless the ownedBy property is equivalent to publisher or creator, in which case I can add translations instead.

**Comment by mparsons-ce** [comment]
@https://github.com/sedula27
Thanks, I will pass this on to Sneha

**Comment by mparsons-ce** [comment]
@woodkri Sneha found where the postmessage needs to be updated, so she will make the adjustment.
