### ISSUE TITLE
Collections: Collection export not working in Sandbox

### ISSUE THREAD

**Issue by sedula27** [cassproject/cass-editor#1049]
@woodkri 
When trying to export collections in sandbox it takes a long time for records without any competencies, if there are any competencies export is not working at all for both Credential JSON-LD and CSV formats. 
https://dev.cassproject.org/api/ceasn/7106cacd59f10f91cd109ca145de5bb7

**Comment by woodkri** [comment]
Looking into this. How were you able to create a hierarchy in the linked collection? It shouldn't be allowed.

**Comment by woodkri** [comment]
Export of flat collections is working now, it was a server configuration issue. The linked collection still does not export since there is a hierarchy.
