### ISSUE TITLE
SKOS editor inserts non-existent child node

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#105]
I published a new concept scheme ("[TEST] ASN K-20 Education Level Vocabulary") and it looks like the following:

<img width="602" alt="screenshot 2017-12-14 10 12 06" src="https://user-images.githubusercontent.com/2939046/34007736-b8a20c44-e0b7-11e7-8195-f4798ccd0d73.png">

If we look at the jsonld for the "Middle School" node, there is a skos:narrower` node that shouldn't be there. Since this was created without any edits, this can't be an editing artifact...I don't think.

```
{
  "@context": "http://schema.cassproject.org/0.3/skos/",
  "@id": "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.skos.Concept/706a975f-87dc-475a-a122-209c05127e78/1513260466740",
  "@type": "Concept",
  "skos:broader": [
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.skos.Concept/716fefc9-48e8-4b23-a04a-2a2537d193ba"
  ],
  "skos:inScheme": "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.skos.ConceptScheme/0be57ef4-2cae-4336-b0b7-e50c4aa6d449",
  "skos:narrower": [
    "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.skos.Concept/a35a4b64-2181-43fa-a719-5897a5d63ed7"
  ],
  "skos:prefLabel": "Middle School"
}
```

**Comment by Lomilar** [comment]
This will no longer occur, though affected frameworks are still affected.
