### ISSUE TITLE
Collection sandbox export is missing InLanguage

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1050]
Attempted to publish collection: 22-02-03 Collection with concrete competencies.
The collection contains InLanguage but is not included in the export.

![image](https://user-images.githubusercontent.com/58825866/152462916-16820912-12b8-45b7-9e36-702ae9d406c7.png)

[22-02-03 Collection with concrete competencies](https://dev.cassproject.org/api/ceasn/07d333fe2ece8c28cdf5fbca93a9590e)

Also missing ListId
![image](https://user-images.githubusercontent.com/58825866/152468388-2d71b0e7-28c2-4595-afa3-c9918bed01c8.png)

**Comment by woodkri** [comment]
I dropped a comment in #1041, I think the json-ld @type for some of these terms has changed in your contexts so they're no longer compacting as they once were when we translate them. Language is now @type: @id where I believe it once was @type: xsd:language. Are these changes permanent?

**Comment by jeannekitchens** [comment]
@mparsons-ce please answer above question https://github.com/cassproject/cass-editor/issues/1050#issuecomment-1030025933
