### ISSUE TITLE
Sandbox collection: tried to add an ownedBy URI an existing collection and data was not saved. 

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1056]
For the SNHU collection
https://sandbox.credentialengine.org/publisher/collections/?frameworkctid=ce-b14dde45-6d57-4f26-9002-a6e2504d9572
The ownedBy was missing so I added it through the interface. 
There were no errors, but the data didn't save. I tried it a few times but was not successful.

**Comment by woodkri** [comment]
I just added an ownedBy value to the framework through the interface (and then removed it since it's not the actual owner URL). Was the value you entered in a URL beginning with 'http'? I'm wondering if this is an error display issue or a saving issue.

**Comment by mparsons-ce** [comment]
I had been pasting in a full URI with the http.
