### ISSUE TITLE
Sandbox collection export issues

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1057]
For the SNHU collection
https://sandbox.credentialengine.org/publisher/collections/?frameworkctid=ce-b14dde45-6d57-4f26-9002-a6e2504d9572

Export issues
**MajorAlignment is missing in export**
This property exists in the interface. 

The **first competency is not in the correct CTDL JSON-LD format**, and the rest are fine.
https://dev.cassproject.org/api/ceasn/8cc61994476176a85c4d95108c066082

![image](https://user-images.githubusercontent.com/58825866/153515143-f2992943-e23a-4432-8fc9-6f0130d2046c.png)

**Comment by woodkri** [comment]
Patched on sandbox and will be included in the next release.
