### ISSUE TITLE
Concept Scheme Properties Change Needed

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#1092]
The following properties need to be removed from Concept Scheme:  (1) skos:changeNote and (2) skos:historyNote

1. skos:changeNote is only on Concept not Concept Scheme.
2. skos:historyNote is not included with CTDL ASN.

**Comment by sedula27** [comment]
![image](https://user-images.githubusercontent.com/93455942/169314426-0d8d8c07-9e74-4d18-82e6-8b3b1d6dd88e.png)
Change note and History note properties are removed from the concept scheme, And Concepts have change note
