### ISSUE TITLE
At top of concept schemes, collections, competency frameworks need the copy url link

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#1099]
![image](https://user-images.githubusercontent.com/20917206/163466973-9a3619be-124c-439b-a583-9b79260a9bcd.png)

**Comment by gloverkari** [comment]
![image](https://user-images.githubusercontent.com/78623855/230116502-ceddce2b-4a61-4ae8-918a-c1bf7e6af06b.png)

**Comment by gloverkari** [comment]
The reason that the url link isn't showing up is because of a parameter called "user" set equal to "wait". It appears to disable sharing and is set on the iframe link to cass-editor. Is anybody on your end aware of why this might have been set? Removing it should make the link available.

**Comment by jeannekitchens** [comment]
@gloverkari the icon for sharing via URL is not visible on sandbox. Please doublecheck this.  To be consistent, we determined a link icon should be used as is with the search list view.  
![image](https://github.com/cassproject/cass-editor/assets/20917206/7a9f984d-1eb0-4f85-a514-52c60852a73c)

**Comment by gloverkari** [comment]
user=wait allows user to select organization. I'll look into continuing to support this functionality while sharing a link.
