### ISSUE TITLE
Uploads with Errors Result in Infinite Spinner with No Option to Cancel

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#1100]
Since CaSS provides not feedback on uploads other than seeing the spinner icon, really need to have a cancel option.  Otherwise have to close the window and start again. 
![image (14)](https://user-images.githubusercontent.com/20917206/163481130-d269ec88-3f3b-4085-803c-5af198bbf614.png)

**Comment by sedula27** [comment]
@gloverkari ![image](https://user-images.githubusercontent.com/93455942/203121095-2472c4fe-4953-40e9-a1b9-ea57908bef57.png)
I don't see the cancel button or the errors when i am importing this progression model
[progressionmodel.json.txt](https://github.com/cassproject/cass-editor/files/10059087/progressionmodel.json.txt)

**Comment by gloverkari** [comment]
The issue found with the json model is with both Concept Schemes and Progression Models
I have opened a separate ticket to track the problem: https://github.com/cassproject/cass-editor/issues/1243

**Comment by gloverkari** [comment]
Added ability to cancel during JSON file import processing.

**Comment by jeannekitchens** [comment]
@gloverkari this issue certainly impacts all CaSS users.  Any upload that doesn't meet requirements that users will not know exist  because there's no clear validation feedback is something that can't hold up the update. I've moved this card forward because I don't feel it's worth our time and effort to correct this general CaSS issues impacting all customers.
