### ISSUE TITLE
Add Local Subject to Competency

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#1104]
See the Competency mapping sheet. This is missing for the CaSS interface. https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=1383736020

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

ceasn:localSubject | The text string denoting the subject of the competency framework or competency.Example: Algebra\|Materials Science\|Physical Sciences | A pipe-separated \| list of values. Limit 200 characters per subject.
-- | -- | --

</body>
</html>
Multiple
rdf:langString

**Comment by sedula27** [comment]
![image](https://user-images.githubusercontent.com/93455942/169310937-bdf76237-20fd-4ed3-b665-024cc6c70642.png)
Was able to add the local subject property

**Comment by jeannekitchens** [comment]
@sedula27 for each property that is updated, please ensure it exports as well. Thanks!

**Comment by sedula27** [comment]
Tested import and export of local subject, and for an updated property.
