### ISSUE TITLE
Inclusion in CaSS and proper use of ceasn:alignTo and ceasn:alignFrom

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#1109]
Both [ceasn:alignTo](https://purl.org/ctdlasn/terms/alignTo) and [ceasn:alignFrom](https://purl.org/ctdlasn/terms/alignFrom) should be in CaSS. Their definitions should be updated in CTDL to reflect the following:  

1. Both are superproperties and should not be used where a specific subproperty is available; e.g., [ceasn:alignTo](https://purl.org/ctdlasn/terms/alignTo) should not be used where the intention is [ceasn:broadAlignment](https://purl.org/ctdlasn/terms/broadAlignment).  

2. ALSO, [ceasn:broadAlignment](https://purl.org/ctdlasn/terms/broadAlignment) should be defined as a subproperty of [ceasn:alignTo](https://purl.org/ctdlasn/terms/alignTo) and all other existing relationships of that ilk (i.e., competency-to-competency.  competency-to-framework, framework-to-framework, framework-to-competency).  Using Dublin Core 'speak', this allows these the more refined relationships to be "dumbed down" to the superproperty [ceasn:alignTo](https://purl.org/ctdlasn/terms/alignTo) in systems that don't support all the refinements.
 
3. The exact REVERSE is true with [ceasn:alignFrom](https://purl.org/ctdlasn/terms/alignFrom).

**LOCATE THE PROPERTIES IN THE PROPERTY SELECTION MODAL JUST ABOVE ENVIRONMENTAL HAZARD.**

**Comment by jeannekitchens** [comment]
Updated on staging and production Oct 25, 2022
