### ISSUE TITLE
A few 1.5.6 tests failing

### ISSUE THREAD

**Issue by vbhayden** [cassproject/cass-editor#1110]
Morning team,

I'm looking through the editor codebase to work out the Docker stuff for Platform One, very relieved to see that it's a Vue project. 🙏

For the testing, there are a few tests that don't pass due to the `getPluginsFromCuratedList` iteration throwing in `pluginUtil.js`.

Namely:
- `initializeApp()` is never called to trigger the `EcRepository`'s `.init()` call
- The line to set those plugins was using `app/setCuratedPlugins` as the path instead of `app/curatedPlugins`

I have a working version locally which just checks if the curated plugins have been assigned in `pluginUtil.js`, but didn't want to submit a PR without knowing if there was a fix already being worked.

Thanks,
-Trey

**Comment by woodkri** [comment]
We'd be happy to receive a PR! I hadn't seen an error thrown there so we haven't started working on a fix. The app/setCuratedPlugins line should work since there is a store mutation defined called setCuratedPlugins. If initializeApp isn't being called though, that could present a larger problem. Let me know if you're seeing any other issues around that, and if so, how you're running the code/any configurations you're using.

**Comment by vbhayden** [comment]
Mhm np, so I'm on Windows 10 with Node 16.5 LTS.  Cloning and running
```
npm install
npm run test:unit
```
ends with 
```
Test Suites: 1 failed, 6 passed, 7 total
Tests:       5 failed, 61 passed, 66 total
Snapshots:   0 total
Time:        39.524s
Ran all test suites.
```
and each of the failing tests just throws unexpectedly on the same function
```
  ● SideNav › open share assertion modal when button is clicked

    TypeError: this.$store.getters.app/curatedPlugins is not iterable

      251 |         },
      252 |         getPluginsFromCuratedList() {
    > 253 |             for (let p of this.$store.getters['app/curatedPlugins']) {
          |                           ^
      254 |                 this.pluginList.push(this.buildPluginListItemFromCuratedPlugin(p));
      255 |             }
      256 |         },
```

**Comment by vbhayden** [comment]
Oop np, ty!
