### ISSUE TITLE
Selected Server vs. API Location?

### ISSUE THREAD

**Issue by vbhayden** [cassproject/cass-editor#1111]
Morning team,

For the `VUE_APP_SELECTEDSERVER` env variable, it looks like this is where we target the actual CaSS server being used, but there's another declaration below that for
```
var cassApiLocation = "https://dev.rest.api.cassproject.org/";
this.$store.commit('environment/cassApiLocation', cassApiLocation);
```
which is then used for the computed Vue properties like creating a user and whatnot.  That value doesn't seem to be editable or use any env variable to override it, even with the CI yaml defining steps like
```
- export VUE_APP_SELECTEDSERVER=https://t3.api.cassproject.org/api/
```
Are these values intended to represent the same thing?  It doesn't look like there's any way to keep the Vue project from pointing at that hardcoded `dev.rest.api` location.

**Comment by woodkri** [comment]
These are intended to represent two different things, however the cassApiLocation is no longer being used. We had put a login page together using a dev Keycloak instance as SSO which is what that was for. We've gone back to the regular CaSS login page that does not use cassApiLocation to connect to keycloak, though some of the old code is still in the repository.
