### ISSUE TITLE
altCodedNotation property needs to be in CaSS

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#1112]
The [altCodedNotation](https://purl.org/ctdlasn/terms/altCodedNotation) needs to be in CaSS right after [codedNotation](https://purl.org/ctdlasn/terms/codedNotation) in the interface. The correct definition is as follows:

>An alphanumeric notation or ID code identifying this competency in common use among end-users.

with the following comment:

>Unlike the codedNotation property, the value for the altCodedNotation property need not be an official identifier created by the promulgating agency. It must be an identifier in common use among end-users of the competency. This property should be seldom used and only with a clear demonstration of need (i.e., in common use). For example, in the Common Core State Standards (Math) in the U.S., the official codedNotation of "CCSS.Math.Content.1.NBT.C.4" is abbreviated in common use by end-users to the unofficial altCodedNotation of "1.NBT.4".

**Comment by sedula27** [comment]
tested import, export and manually. good to go
