### ISSUE TITLE
ceasn:author needs to be added to CaSS

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#1113]
The [ceasn:author](https://purl.org/ctdlasn/terms/author) property needs to be added to CaSS

Definition: A person or organization chiefly responsible for the intellectual or artistic content of this competency framework or competency.

**Comment by sedula27** [comment]
Not able to import ceasn:author, export works fine

**Comment by sedula27** [comment]
Was able to import and export ceasn:author, we can move this to production, good to go

**Comment by sedula27** [comment]
@gloverkari The export of [ceasn:author](https://purl.org/ctdlasn/terms/author) is not working

**Comment by jeannekitchens** [comment]
@gloverkari Author is still not exporting.  Need to be sure it imports and exports.  Import and export issues go back to June 2022.  

https://sandbox.credentialengine.org/cass-editor/?user=wait&link=true&newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&server=https://dev.cassproject.org/api/&ceasnDataFields=true&show=all&origin=https://sandbox.credentialengine.org&action=import#?user=wait&link=true&newObjectEndpoint=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-&server=https%3A%2F%2Fdev.cassproject.org%2Fapi%2F&ceasnDataFields=true&show=all&origin=https%3A%2F%2Fsandbox.credentialengine.org&action=import?frameworkId=https://sandbox.credentialengineregistry.org/resources/ce-7907223c-78c5-4efd-a231-857f9e6b4a8d

{
"@context": "https://credreg.net/ctdlasn/schema/context/json",
"@graph": [
{
"@id": "https://sandbox.credentialengineregistry.org/resources/ce-7907223c-78c5-4efd-a231-857f9e6b4a8d",
"@type": "ceasn:CompetencyFramework",
"ceasn:creator": [
"https://sandbox.credentialengineregistry.org/resources/ce-a4041983-b1ae-4ad4-a43d-284a5b4b2d73"
],
"ceasn:description": {
"en-us": "Test Framework for Date Created and Date Modified as User Editable Fields"
},
"ceasn:hasTopChild": [],
"ceasn:inLanguage": [
"en-US"
],
"ceasn:name": {
"en-us": "Test Framework for Date Created and Date Modified as User Editable Fields"
},
"ceasn:publisher": [
"https://sandbox.credentialengineregistry.org/resources/ce-a4041983-b1ae-4ad4-a43d-284a5b4b2d73"
],
"ceasn:publisherName": {
"en-us": [
"Credential Engine Administration - Sandbox"
]
},
"ceterms:ctid": "ce-7907223c-78c5-4efd-a231-857f9e6b4a8d"
}
]
}

![image](https://user-images.githubusercontent.com/20917206/211125424-e7e8e832-8b1b-4f6f-ae47-0596fb87e2a0.png)

**Comment by gloverkari** [comment]
Fixed the missing author property on export. 

Commit:
[Add transform for author when exporting as ceasn](https://github.com/cassproject/schema.cassproject.org/commit/566f095b2b0556930c721895faba5bfcbfb2185e)

**Comment by jeannekitchens** [comment]
@gloverkari this is verified on sandbox.
