### ISSUE TITLE
crossSubjectReference should be added to CaSS

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#1115]
Add [crossSubjectReference](https://purl.org/ctdlasn/terms/crossSubjectReference) to CaSS.

The Data Specifications in the spreadsheet say: "A pipe-separated | list of CTIDs for competencies from another competency framework."  Does this mean that CaSS takes the CTIDs and expands them out to full URIs or that the CTID is what's actually in the data?

**Comment by sedula27** [comment]
Tested, good to go
