### ISSUE TITLE
Use https for concept scheme URIs

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#1118]
The publication status URIs and any other concept schemes need to use https:  
![image](https://user-images.githubusercontent.com/20917206/167904510-cde22970-addc-42c2-bec9-aa30f0e3a2d8.png)

**Comment by sedula27** [comment]
![image](https://user-images.githubusercontent.com/93455942/178752004-f0f33ba2-70f3-4a8d-ab55-633da65e4c93.png)
Tested and Good to go
