### ISSUE TITLE
Narrow alignments are not being exported from CaSS

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1121]
@woodkri 
Jeff Gran noted that: 

> College Board entered their AP Computer Science Principles competency framework and alignments to the NICE framework (select high details to see narrow alignment). https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-0cecf7e9-6a86-44f3-963c-a38d0922c0ad. Once approved and published the NICE alignments don't appear in the Finder view.

The alignments do show in CaSS:
![image](https://user-images.githubusercontent.com/58825866/168617040-1440ed02-5d63-4e37-a1fb-8d0ee8472617.png)

However, the alignments are not shown in the export:
https://cass.credentialengine.org/api/ceasn/4ede138c20c2d74b09a8d0b8c614c9cd

![image](https://user-images.githubusercontent.com/58825866/168617441-a275c080-0171-4fe1-9cad-2e8fec365de0.png)

**Comment by gloverkari** [comment]
Which option are you using to export? CASS (JSON-LD), Credential Engine ASN (JSON-LD)?

![image](https://user-images.githubusercontent.com/78623855/172209502-8f3872cb-592f-4a97-9afe-7aca5397eda6.png)

**Comment by mparsons-ce** [comment]
We use: **Credential Engine ASN (JSON-LD)**

**Comment by sedula27** [comment]
![image](https://user-images.githubusercontent.com/93455942/179291407-b58033ad-81fd-4942-9c05-5f9e29e52e27.png)
Able to export Narrow Alignments, Good to go
