### ISSUE TITLE
Configure the UI to show competencies owned by the user, but allow them to toggle and see all.

### ISSUE THREAD

**Issue by sedula27** [cassproject/cass-editor#1135]
@woodkri @gloverkari 
As of now the CASS interface defaults to show all competencies, configure it to show user owned data first and give them the option to see all data.

**Comment by woodkri** [comment]
We'll want to do this as an optional query parameter.

**Comment by gloverkari** [comment]
The url parameter "ownedByMe=true" and "show=mine" now both achieve the same functionality. Setting either of these parameters will default to showing frameworks and competencies owned by the currently logged in user. Unchecking the "Owned By Me" option in the filter options will allow the user to view all frameworks or competencies.

**Comment by gloverkari** [comment]
To use this feature, the url parameters "ownedByMe=true" or "show=mine" need to be set.
It looks like show=mine is set on sandbox, but show=all is set on staging and production.
Updating the credential engine iframe src to use show=mine should turn on the filter by default when a user logs in.

<iframe class="cassEditor" src="https://staging.credentialengine.org/cass-editor/?user=wait&amp;editorRoot=/cass-editor/&amp;server=https://staging.credentialengine.org/api/&amp;ceasnDataFields=true&amp;&amp;newObjectEndpoint=https://staging.credentialengineregistry.org/resources/ce-&amp;show=mine&amp;origin=https://staging.credentialengine.org"></iframe>

**Comment by mparsons-ce** [comment]
Currently show=mine is the default. 
If the current user is CE staff or an external admin (like CaSS staff), it is set back to show=all.
Given that there will be an option to toggle between the two states, I will remove the latter customization.
