### ISSUE TITLE
Retrieve credential frameworks & concept schemes owned by a particular organization

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#115]
With the exception of a person just browsing frameworks and concept schemes, users need to be able to find them based on owner/publisher as well as title.

**Comment by Lomilar** [comment]
Searching should be possible via something like the following:
http://lr-staging.learningtapestry.com/ce-registry/search?fts=ACT

However, the search API does not allow cross domain invocations.

Opening CredentialEngine/CredentialRegistry#187. Pending.

**Comment by Lomilar** [comment]
For showing just the organization's frameworks, works with `show=mine`.

**Comment by Lomilar** [comment]
Superceded by cassproject/CASS#124
