### ISSUE TITLE
Editor "Save and add another" erratically misbehaving

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#1161]
The entry screen for a new competency, there are the two buttons at the bottom: (1) Done, and (2) Save and add another. See below:

<img width="801" alt="SaveAndAdd" src="https://user-images.githubusercontent.com/2939046/177618520-70b2acf8-065d-4902-b6bb-7df7f59d282b.png">

The misbehavior is when you have multiple new competencies at the same level and the "Save and add another" button is used to rapidly move from the creation of one competency to next. That saves a lot of time that would be wasted through multiple key strokes if you clicked "Done" after each entry and then had to click "Add" etc. for the next instance.  So, the "Save and add another" is great! BUT, when you get through with these iterative entries and click "Done", the last entry is there in full. All of those that were ended by clicking "Save and add another" have only the original "New Competency" field prompt. No other information about the entry appears to be present. However, when you open these entries, all of the entered information is present. Only by   closing each of them with "Done" is the full text of the entry displayed.

The frustrating part--it is erratic! I was on the editor most of July 2nd & 3rd with this problem consistently present. Today (July 6th) the problem has disappeared. I nevertheless thought I'd memorialize the problem with this GitHub issue.

**Comment by jeannekitchens** [comment]
@gloverkari what is the status of this?

**Comment by gloverkari** [comment]
The new functionality is as follows:
 For unselected competencies:
 - Single-click selects a single competency without selecting any children
 - Double-click selects a competency and all child competencies (including children's children)

 For selected competencies:
 - Single-click deselects a single competency without deselecting any children
 - Double-click deselects a competency and all child competencies (including children's children)
