### ISSUE TITLE
Need to clear existing competencies from CE CASS Editor 

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#117]
CE would like to clear all competencies from inside their system and restart with only approved competencies.

**Comment by Lomilar** [comment]
Done. @siuc-nate @stuartasutton

**Comment by Lomilar** [comment]
Note: This is without public keys (I don't have that data yet) and without using native registry URLs (The cass-editor needs to support them better) yet.

**Comment by stuartasutton** [comment]
Could someone please send me the json load file?

**Comment by Lomilar** [comment]
Done.

**Comment by Lomilar** [comment]
Imports complete.
