### ISSUE TITLE
Some instances of URI collisions, timestamps needed 

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#118]
In some cases, timestamps are breaking when passing through a RD parser.

The only way we can get the graph to work is remove all timestamps. @Lomilar how do you think we should handle this?

**Comment by Lomilar** [comment]
Me: Check to see what format timestamps are being written to the data as.

**Comment by eddavies** [comment]
2018-02-27T19:56:08.299Z
Looks like ISO 8601 👍
