### ISSUE TITLE
ceasn:dateCreated and ceasn:dateModified Issue

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#1187]
The CTDL ASN JSON export includes the following for the framework and for each competency.
],
"ceasn:dateCreated": "2022-05-24T15:29:32.832Z",
"ceasn:dateModified": "2022-08-15T21:59:08.942Z",
 
However these properties were not actually entered into CaSS.  These should only be in the envelope data not the raw data?  Links are here https://docs.google.com/document/d/17-HtUei3Q8-fR_n9cnB_ruet77wx5XbTmXfQ4SosPBw/edit#heading=h.xys6r4wspnw7

**Comment by stuartasutton** [comment]
Jeanne, these are properties on the resource in the CTDL-ASN and seem to me to be correctly on the resource. When looking at the record in the wild, people don't see an envelope or any of its data.

**Comment by jeannekitchens** [comment]
They're not correctly used.  The date created is the date is was created in CaSS, not the actual date created.  The dateModified is not the date the framework was modified.  It is the date someone logged into CaSS and made a correction.  That belongs in the envelope.  If a date is used, it should be https://credreg.net/ctdlasn/terms#repositoryDate.  Otherwise, we need the dateCreated directly from SHRM, not the date we entered it into CaSS.  We should not make it look as though SHRM modified a framework just because there was a date entry change in CaSS as the actual framework is published and has not been modified.
d



 

https://credreg.net/ctdlasn/terms#dateCreated
https://credreg.net/ctdlasn/terms#dateModified

**Comment by stuartasutton** [comment]
Ah, indeed the CaSS creation date is not accurate. I misinterpreted the issue to mean that these properties are not direcctly on the object.

**Comment by jeannekitchens** [comment]
@sedula27 @gloverkari I do not see that the dateCreated or dateModified has been corrected. 
1. These are CTDL-ASN terms.  They should be seen with the framework UI to added https://credreg.net/ctdlasn/terms#dateCreated and/or add https://credreg.net/ctdlasn/terms#dateModified.

I still see both of these dates in the CaSS export and I don't see either of them with the UI.

**Comment by sedula27** [comment]
@gloverkari For Date Modified and Date Created, time is not required to be entered by user, as of now it won't allow the save of the dates without time.

**Comment by jeannekitchens** [comment]
@gloverkari @sedula27 the[ CaSS/CTDL mapping sheet](https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=0) for Competency Framework shows 
dateCreated= xsd:date
dateModified = xsd:dateTime

ceasn:dateCreated is the date the framework was created not the date it was entered into CaSS. 
ceasn:dateModified is the date the framework was modified outside of CaSS by the creator. e.g., SHRM created their framework in 2017 and modified it in 2021. They would not care about or have the time.  Although CTDL ASN supports including time, it is not required to be entered into CaSS.

**Comment by gloverkari** [comment]
I will default the time to zeros if the user does not enter a time.

**Comment by jeannekitchens** [comment]
@gloverkari please implement your proposal for the display of CaSS dates.  The time still doesn't default to zero.  See related issue https://github.com/cassproject/cass-editor/issues/666

**Comment by jeannekitchens** [comment]
@kari this looks perfect.  It's verified on sandbox.
