### ISSUE TITLE
Importing a competency from another framework intermittently not working

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#1197]
On importing a competency from another framework into the framework being created, there is an intermittent but very frequent issue with the import failing and the application freezing. See the attached PowerPoint with screen captures.
 
[CaSSEditorIssue.pptx](https://github.com/cassproject/cass-editor/files/9577081/CaSSEditorIssue.pptx)

**Comment by sedula27** [comment]
Able to import a competency from another framework, this can be closed @gloverkari

**Comment by jeannekitchens** [comment]
Updated on staging and production Oct 25, 2022.
