### ISSUE TITLE
Framework delete button does not do anything

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#12]
Clicking "delete" while editing the framework name/description does not do anything.

editFramework.js:187 Uncaught TypeError: Cannot read property 'shortId' of null
    at deleteCompetency (editFramework.js:187)
    at HTMLButtonElement.onclick (index.html?user=self&show=mine:176)

**Comment by eddavies** [comment]
Deleting a framework that has existing competencies in other frameworks does not delete the competencies in the other framework. 
Steps to reproduce:
1. create framework 1 with competency 1
2. create framework 2
3. search for competency 1 and add it to framework 2
4. Delete framework 1
5. In framework 2, competency 1 will still exist

**Comment by Lomilar** [comment]
This is true and currently intentional. Should this be different?

**Comment by eddavies** [comment]
Oh probably not. When I read the delete warning message I read it incorrectly, as if it warned that deleting this will delete the competencies in other frameworks, so I thought this was a bug. 

Deleting works, and this being intentional makes more sense then it not.
