### ISSUE TITLE
Create method of querying the cass-editor for the framework and competencies within, in some format/schema.

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#121]
For CE, frameworks should go live when they have been approved by a member of the same organization.

**Comment by kchavas** [comment]
Additional info:

Editor should be able to use the following workflow:
User creates/edits competencies in the editor
The competencies are stored within CASS but not immediately published to the registry or available for use by anyone other than that user's organization
The competencies can be reviewed by the users for that organization and modified as needed
Users for that organization can "approve" frameworks (and possibly individual competenices? It wasn't clear at the time), at which point the data is published to the registry
No framework is published unless it is approved

**Comment by Lomilar** [comment]
Right, all the steps for publishing are currently in...discussion as to how best to accomplish them. I believe the two options are:

1. CASS does all these checks and has a half dozen integration points with the CE stuff.
2. CASS Editor can toss objects out to the parent CE webpage which, I think, already has methods to do all this.

Last I heard, we were investigating 2. @siuc-nate yes?

**Comment by siuc-nate** [comment]
One slight adjustment to the list above - I believe the consensus was that approvals would be at the framework level only, not for individual competencies.

As for validation, we currently generate the [JSON schema](http://json-schema.org/latest/json-schema-validation.html) for validating competencies, but we have been relying on the credential registry's implementation of that (we have a separate validation process for our assistant API).

**Comment by Lomilar** [comment]
To accomplish this, I propose:

Parent page may postMessage to the cass-editor iframe asking to retrieve the currently selected framework in several export forms.
cass-editor postMessages back with the exported form.

This would allow the parent page to retrieve the framework (and competencies) to register, make its own decisions about security and approval and review, then register the framework.

@siuc-nate Does that seem possible and easier than giving us an API to jack into the approvals and review process?

**Comment by Lomilar** [comment]
Discussed on call, go for this method.

**Comment by Lomilar** [comment]
Test using /ce.html, use the following code in the console.

Bind the console.log to the message handler.
```
window.addEventListener("message",console.log,false);
```

Send a message asking for an export.
```
$("iframe")[0].contentWindow.postMessage({action:"export",schema:"ceasn"},window.location.origin);
```

**Comment by Lomilar** [comment]
Complete and in use. #138
