### ISSUE TITLE
CSS does not appear to be getting retrieved correctly

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#122]
CSS does not appear to be getting retrieved correctly. Is there a means by which we can send a reference to the style sheet, or to specific rules, or something like that, that will get around the cross-domain problems?

**Comment by Lomilar** [comment]
We could add another URL parameter that goes and fetches a stylesheet (I believe).

But the better solution is to git pull the cass-editor repo to the local web server. 

That also ensures things don't change/break out from under a production server.

**Comment by Lomilar** [comment]
See updated readme.

**Comment by siuc-nate** [comment]
I updated server to allow CORS to the cas dev/production domains, but it doesn't seem like the request is being made - When debugging locally, I'm not detecting any requests to my local host when I load up the CASS iframe.

I am getting this message in the browser console, however - is there a chance it's related?
![image](https://user-images.githubusercontent.com/21346519/37118165-ea5da1f6-2218-11e8-8954-d1e322f7a490.png)
The indicated line of JS points to somewhere in the jquery code at the top of the cass-editor.js file.

**Comment by siuc-nate** [comment]
Update: I am able to get it to work by passing it as a parameter in the URL. This is probably good enough for now.
