### ISSUE TITLE
Error when importing concept scheme or progression model in json format.

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1243]
Importing a concept scheme or progression in json format results in an error in the console:

Uncaught (in promise) URL does not begin with http. Cannot EcRepository.get

**Comment by gloverkari** [comment]
Implemented fixes to synchronous processing of concepts and progression levels during json import. These fixes are intended to address the timing issue causing the import failures.

**Comment by sedula27** [comment]
@gloverkari I still see the same issue with Json import
![image](https://github.com/cassproject/cass-editor/assets/93455942/039f953b-e377-467f-9807-557ab5f125f9)

**Comment by sedula27** [comment]
[sample json.json](https://github.com/cassproject/cass-editor/files/15487767/sample.json.json)

**Comment by sedula27** [comment]
@miledivovic The error happens before line 881, the sample json file of the concept is attached above. 
![image](https://github.com/cassproject/cass-editor/assets/93455942/6a62aa22-3adc-4328-89f4-4bbd735c37d2)

**Comment by miledivovic** [comment]
@sedula27 This should be fixed on the sandbox now.

**Comment by sedula27** [comment]
Thanks you @miledivovic, I was able to import json files for both concept scheme and progression models without any errors.

**Comment by sedula27** [comment]
Was able to verify that the import is working on Sandbox and production.
