### ISSUE TITLE
Critical: export of some frameworks use a hybrid of the registry and CaSS

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1245]
The export for some frameworks include incorrect ids, like the following:
@id: "https://credentialengineregistry.org/resources/ce-**/data/schema.cassproject.org.0.4.Competency/4030.2.1/1670358363542**",

BSCC competencies
https://cass.credentialengine.org/api/ceasn/4fdd7c125f0ae7d9853f5e1184fb8156

MSDA
https://cass.credentialengine.org/api/ceasn/fb054b48a6869ee92c16fde1768025ff

![image](https://user-images.githubusercontent.com/58825866/206244913-f239a459-6b61-47e8-9dc0-b2f2cc204929.png)

**Comment by gloverkari** [comment]
From Jeanne: (12/7 in slack channel)
  well mystery of the BSCC framework is solved.  It's actually interesting that it uploaded and populated competencies.  https://docs.google.com/spreadsheets/d/1XPqirttuaOBeoOH3RXl0w0gP9xZs86iRimjwWvMxH6I/edit#gid=197467951
We have an issue for allowing external identifiers https://github.com/cassproject/cass-editor/issues/911.
We'll fix the CSVs and re-upload them with CTIDs and ceasn terms header.
[#911 Credential Engine would like to enable the use of an external identifier](https://github.com/cassproject/cass-editor/issues/911)
When importing a framework, the requirement for CTID can be a burden for a user. Instead would like to enable the use of an external identifier.
The external identifier for a framework would have to be unique for the owning organization.  
If a CTID is present, it would take precedence over the external identifier  
OR should the latter be an error? That is one or the other must be provided.  
On import the external id would be used to reference the proper existing framework.  
On import a CTID would be generated (for a new framework).  
Show more
Assignees
[@Lomilar](https://github.com/Lomilar), [@woodkri](https://github.com/woodkri), [@mparsons-ce](https://github.com/mparsons-ce)
Labels
Credential Engine CaSS, Competency Framework, Ticketed, Bulk Upload
<https://github.com/[cassproject/cass-editor](https://github.com/cassproject/cass-editor)|cassproject/cass-editor>cassproject/cass-editor | Aug 25th, 2021 | Added by [GitHub](https://eduworks.slack.com/services/B01UAKUBZ39)


Kari
Interesting. This would be good to discuss at the next meeting. We have had some complications with uploading SKillSync training opportunities using the method proposed in the ticket for id generation. It's still a viable option, but with implications. Thanks for the update.
