### ISSUE TITLE
Diagnose CE iframe

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#125]
CE's iframe isn't loading the user, determine why.

https://credentialengine.org/publisher/competencies

**Comment by Lomilar** [comment]
@siuc-nate Got it. I was incorrect, there were updates.

Still worth adding in the following:

&webSocketOverride=wss://cass.credentialengine.org:8080/ws/custom

**Comment by siuc-nate** [comment]
Thanks.

I have also added the override.
