### ISSUE TITLE
Sharing a link for a framework generates incorrect url

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1250]
Using the "copy link" under Details -> Share in the right panel of a selected framework generates an incorrect url in some cases. This might be limited to use cases with additional query params. 
The url is generated with a question mark in front of "frameworkId" instead of an ampersand when the link needs to include additional parameters. For example:
https://cass.credentialengine.org/cass-editor/?user=wait&editorRoot=/cass-editor/&server=https://cass.credentialengine.org/api/&ceasnDataFields=true&&newObjectEndpoint=https://credentialengineregistry.org/resources/ce-&show=all&origin=https://apps.credentialengine.org#?user=wait&editorRoot=%2Fcass-editor%2F&server=https%3A%2F%2Fcass.credentialengine.org%2Fapi%2F&ceasnDataFields=true&=&newObjectEndpoint=https%3A%2F%2Fcredentialengineregistry.org%2Fresources%2Fce-&show=all&origin=https%3A%2F%2Fapps.credentialengine.org?frameworkId=https://credentialengineregistry.org/resources/ce-32f2c32d-6731-440e-b894-0ccf2099ec15

**Comment by jeannekitchens** [comment]
@gloverkari the very first framework I tried resolves to the import page. https://sandbox.credentialengine.org/cass-editor/?user=wait&link=true&newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&server=https://dev.cassproject.org/api/&ceasnDataFields=true&show=all&origin=https://sandbox.credentialengine.org&action=import?user=wait&link=true&newObjectEndpoint=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-&server=https%3A%2F%2Fdev.cassproject.org%2Fapi%2F&ceasnDataFields=true&show=all&origin=https%3A%2F%2Fsandbox.credentialengine.org&action=import&frameworkId=https://credentialengineregistry.org/resources/ce-76019a27-513b-4fc8-beb7-03ecf60b0a2d
![image](https://github.com/cassproject/cass-editor/assets/20917206/4cf12e5b-7df1-45fc-a843-f14984732314)
![image](https://github.com/cassproject/cass-editor/assets/20917206/ecb2b7f8-1039-448d-8eac-0a1965027243)
