### ISSUE TITLE
Adding Comprised Of property needs to prompt for URL not string 

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1256]
When adding a Comprised Of property to a competency, the modal presents a text box. This needs to be an option for a url.

**Comment by gloverkari** [comment]
Update to the following properties:
ceasn:comprisedOf, ceasn:derivedFrom, ceasn:inferredCompetency, ceasn:isVersionOf
All reference competencies and can be added by url or selection.

**Comment by jeannekitchens** [comment]
@gloverkari this looks to be working on sandbox.
