### ISSUE TITLE
Competencies are incorrectly added when populating the Skill Embodied property. 

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1257]
From Jeanne:
Using the search for competencies to populate "Skill Embodied" is randomly adding competencies that aren't selected, putting them in a random order.

**Comment by gloverkari** [comment]
From Jeanne:
The pattern is the search for three competencies will save the 1st selected and the last selected and will not save the second competency selected.

**Comment by gloverkari** [comment]
This issue affected several properties that referenced urls (Skill Embodied, Knowledge Embodied, Task Embodied, and Ability  Embodied). Multiple updates in succession were causing the properties to be overwritten. Fixed the issue by adding all new referenced url properties together before saving.

**Comment by jeannekitchens** [comment]
@gloverkari this looks to be working on sandbox..
