### ISSUE TITLE
Verifying/correcting properties in competency framework editor

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#126]
We still have a few matters to correct with the input templates in terms of properties. The authoritative source is here https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803.

### Placement of the "General" cluster header

In both competency and concept editors, is it possible to move the "General" category to the top of the frame so that the current top two properties are included in that cluster?

### Competency Framework Editor

1.  It is possible to change the screen label for the `ceasn:author` property from "Author" to "Creator Name" while leaving the underlying `ceasn:author` as the property. this way we'll the person will see "Creator" (URI) and "Creator Name" (text). If so, do so; otherwise let me know.

2.  Remove "Optional" cluster label as well as the two properties in the cluster: `ceasn:codedNotation` and `ceasn:localSubject`.

### Competencies

1. Add "create or select" functionality to "Skill Embodied" property.

2. Remove "Author" and "Alternative Code Notation" properties (Scales cluster)

3. Remove "Optional" cluster label as well as the two properties listed there: "Creator" and "Local Subject".

### Concept Editor

1.  When I open the editor, I am seeing a bunch of css above the header...

```
body { padding-top: 0px; } body { /* border-top: 1px solid #CAD9DB;*/ border-bottom: 1px solid #CAD9DB; } #editFrameworkBack { font-weight: bold; font-size: 1.2rem; cursor: pointer; } #title { font-weight: bold; font-size: 1.6rem; cursor: pointer; /* margin: 0rem;*/ /* margin-left: .5rem;*/ /* line-height: 2rem;*/ } *[draggable="true"] { cursor: move; } #frameworks p a{ font-size: 24px; font-weight: bold; color: #607171; } #frameworks p a mark{ font-size: 24px; font-weight: bold; color: #607171; } #frameworks p span{ font-size: 16px; font-family: Gibson, Tahoma, Arial, sans-serif; } #frameworks p span mark{ font-size: 16px; font-family: Gibson, Tahoma, Arial, sans-serif; } #cassControl #header #search{ font-size: 20px; color: #607171; } .competency { background-image: none; filter: none; padding: .5em 0em .5em .5em; border: 1px solid transparent; border-radius: 4px; } .competency { background-image: none; filter: none; padding: 0em; border: 1px solid transparent; border-radius: 4px; } .competency>span { font-weight: bold; } .competency:hover { border-color: transparent; background-image: none; filter: none; } .competency:hover>span>span { color: #B55130; } .competency small { font-size: .8rem; } .competency small mark{ font-size: .8rem; } .competency>small:active, .competency>span:active { /* background-color: rgba(255, 215, 0, 0.46);*/ } .selected.competency { /* background-color: #F5F5F5; border: 1px solid #aaa; */ border: 1px solid #CAD9DB; background-color: #FCFCFC; } .selected.competency>span>span { color: #B55130; /* color: #45A085;*/ } .competency .collapse { float: left; margin-left: -2em; } .competency .collapse:hover { color: #B55130; cursor: pointer; } .sidebar { background-color: white; border: 1px solid #CAD9DB; width: 33%; margin-top: 3rem; height: calc(100% - 3rem); min-height: 60vh; /* position: fixed; right: 0; float: right; padding-left: 1rem; padding-right: 1rem; margin-top: 1rem; height: 100vh; max-width: 50%; width: 19rem; overflow: hidden; */ } .pageWithSidebar { padding-right: 34%; } #siteNavRow{display:none;} #sidebarExport{ position: fixed; top: 0px; right: 0px; }
```

**Comment by Lomilar** [comment]
Removed CSS from header.

**Comment by stuartasutton** [comment]
@Lomilar, we are still missing the following [spreadsheet properties](https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803) and their Connections category for `Competencies`; they all have `competency` as both domain and range:

>1. `broadAlignment`
>2. `exactAlignment`
>3. `majorAlignment`
>4. `minorAlignment`
>5. `prerequisiteAlignment`

<img width="306" alt="screen shot 2018-03-02 at 5 54 34 am" src="https://user-images.githubusercontent.com/2939046/36902152-53e9cd82-1dde-11e8-903e-e11c87c880a1.png">

**Comment by Lomilar** [comment]
@stuartasutton @jkitchensSIUC The above commit has removed and renamed and rearranged much of the fields in the framework and competency editor panels. The changes can be found in the test CE competency screen.

**Comment by stuartasutton** [comment]
The dateCreated property is a system supplied value and not a user supplied value and marks the creation date which may have nothing to do with the dates of validity.

**Comment by Lomilar** [comment]
Let me attach to this issue: We need to effectively reverse 5fe3161 (matching @stuartasutton's spreadsheet)

**Comment by eddavies** [comment]
Framework: source is replaced by webpage. Is this fine?

Also no changes were made to concepts or concept schemes.

**Comment by eddavies** [comment]
Don't need note and change note under general for concepts.
Made some comments in #214

**Comment by Lomilar** [comment]
Labels should be changed back to what is shown in the spreadsheet.

So, Webpage -> Source is correct.

**Comment by eddavies** [comment]
Every field is accounted for. However, there is no Narrow Alignment for competencies in the ceasn mapping spreadsheet. @Lomilar is this ok?

**Comment by stuartasutton** [comment]
It was just an oversight. Please add. Also, make sure that all of these alignment property labels are singular--Alignment and not Alignments.

**Comment by eddavies** [comment]
All fields in the spreadsheet are accounted for.
