### ISSUE TITLE
Creating or selecting a concept term leads to a blank page

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#127]
While editing a concept, clicking on "create or select..." under concept term sends the user to a blank page. This only occurs while editing a concept.
![blank page concept term](https://user-images.githubusercontent.com/23706850/36687966-e4391c1e-1adf-11e8-9cfe-72eb2786acb6.PNG)

**Comment by eddavies** [comment]
Selecting a concept term doesn't seem to do anything for me. When I go into a concept scheme and select a concept from the list and then click add, I am brought back to the original concept scheme, but zero changes have been made.

**Comment by eddavies** [comment]
Oh I see, it works when adding a concept term to a framework just fine. But the option under a concept scheme does not.

**Comment by Lomilar** [comment]
Adding a concept term to a concept scheme does not appear to work, correct. Checking into it.

**Comment by Lomilar** [comment]
OK to test again.

**Comment by eddavies** [comment]
working now
