### ISSUE TITLE
In view mode, ceasn datafields are not grayed out

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#128]
Changes cannot be made to these fields, but a minor enhancement would be to gray out their fields, just like how the description and name are.

There is a visual error in which I can add concept terms to this framework. These don't save after leaving the framework but appear immediately after adding them.

![concept term added to view mode](https://user-images.githubusercontent.com/23706850/36688358-0af0c02c-1ae1-11e8-944e-92a5eaf5ceb2.PNG)

**Comment by Lomilar** [comment]
How did you get to the edit panel in the first place? The edit button should be vanished.

**Comment by eddavies** [comment]
Was clickable for me

**Comment by Lomilar** [comment]
Scratch that, I see you're not in &view=true, you're in view mode due to permissions.

**Comment by eddavies** [comment]
Ah, my bad on wording

**Comment by eddavies** [comment]
Edit button no longer there
