### ISSUE TITLE
Properties to add to Collections

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1295]
The following properties are missing from Collection:
membershipCondition
collectionType

For details, see: https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=1148066214

**Comment by mparsons-ce** [comment]
@gloverkari I don't think that memberShipCondition is expected to be used in CaSS. The related class: ConditionProfile can have a lot of complexity. 

I added the allowed values for collection type:
ETPL 
GIBill 
IndustryRecognized 
Perkins 
PromiseScholarship 
Quality 
StateApprovedPostsecondary"

**Comment by sedula27** [comment]
@gloverkari 
The values for Collection Types are not in this format https://credreg.net/ctdl/terms/CredentialAlignmentObject/ETPL please use these for respective types
https://credreg.net/ctdl/vocabs/collectionCategory/ETPL
https://credreg.net/ctdl/vocabs/collectionCategory/IndustryRecognized
https://credreg.net/ctdl/vocabs/collectionCategory/GIBill
https://credreg.net/ctdl/vocabs/collectionCategory/Perkins
https://credreg.net/ctdl/vocabs/collectionCategory/PromiseScholarship
https://credreg.net/ctdl/vocabs/collectionCategory/Quality
https://credreg.net/ctdl/vocabs/collectionCategory/StateApprovedPostsecondary

**Comment by gloverkari** [comment]
Good catch - thank you
![image](https://github.com/cassproject/cass-editor/assets/78623855/dbbebb04-eadb-4b1d-afec-8bffd35ade6d)

**Comment by sedula27** [comment]
Verified, correct format is used for the collection types

**Comment by sedula27** [comment]
@gloverkari When I did an export on production(https://cass.credentialengine.org/api/ceasn/23273d09b648a670da5bc3488340d8fe) for the collectiontype 
![image](https://github.com/cassproject/cass-editor/assets/93455942/d12589a2-2c32-442a-bd29-546699fd8f41) and when I did an export for a collection on sandbox(https://dev.cassproject.org/api/ceasn/18cb0a80d54c33547dbdf0b5053fd18e)
![image](https://github.com/cassproject/cass-editor/assets/93455942/e7fbb2d7-dfde-4dcd-bbbd-3f62cf5114c6)

To maintain consistency
 when exported the collectiontype should be similar to the one on production
"ceterms:collectionType": [
"IndustryRecognized"
],

**Comment by sedula27** [comment]
@gloverkari Now the production collection type export shows the cred reg url, can you update the export show just the name like it was on production earlier
_"ceterms:collectionType": [
"IndustryRecognized"
],_

instead of this "ceterms:collectionType": [
"https://credreg.net/ctdl/vocabs/collectionCategory/IndustryRecognized"
],

**Comment by gloverkari** [comment]
I chose to use the url to be consistent with the publicationStatusType. Should both be updated to show type only?

![image](https://github.com/cassproject/cass-editor/assets/78623855/534781fd-524f-4d0e-ae75-eddb596fc978)

**Comment by sedula27** [comment]
It's the _**collection type**_ and just show the type 
"ceterms:collectionType": [
"IndustryRecognized"
],

**Comment by gloverkari** [comment]
I meant that if collectionType shows just the type (instead of the url) then it would be inconsistent with other similar types (such as publicationStatusType).

**Comment by gloverkari** [comment]
Based on discussion during today's meeting, I've updated collectionType to show and export type string only (without url).

**Comment by sedula27** [comment]
@gloverkari  I still have the same issue with saving after clearing the cache
