### ISSUE TITLE
Missing frameworks for Western Governors U. 

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1299]
@gloverkari We noticed some frameworks that are missing in CaSS for Western Governors University. 
The following have been published. I can not find them by CTID or searching.
Can you determine if the record is somewhere in the system but just not being displayed?

**Published and not in CaSS**
Associate of Science, Cybersecurity and Information Assurance
ce-77d9e9ef-2b2c-4adb-b017-88412bce05b9

Cybersecurity and Information Assurance Program Plan
ce-4dc6ad84-72b5-4f8e-90c4-6ea8391ae7cc

Master of Science, Data Analytics (MSDA) Competencies
ce-c6eb6e3b-d637-47ea-96c3-95e3f2d884d9

**`There are also several that have not been published but we still have reference to them being in CaSS at some point.`** 
MSDA 201612 Competencies
ce-fc74254a-c455-492c-af8e-69fe84d8c23c

MSDA 201612 Competencies
ce-542c8f76-c455-4a94-938c-7ab28f532b35

MSDA 201612 Competency
ce-710bdb43-c455-464f-b1e5-64e7071b4d4e

MSDA Competencies
ce-e40e6993-e666-4035-baeb-24565f1f7182

Network and Cyber Defense Foundations Certificate
ce-030f2d1e-6505-4d05-898f-e74b5ccfbf33

Network and Cyber Defense Foundations Certificate
ce-1669a051-a3f1-4e5a-ae97-5e0993ebc318

WGU - Competencies
ce-0fceab23-35dc-423e-bcf5-10b150eb2389

**Comment by gloverkari** [comment]
I am able to directly access two of the three "Published and not in CaSS"
- Associate of Science, Cybersecurity and Information Assurance
- Master of Science, Data Analytics (MSDA) Competencies

but I'm not able to find:
- Cybersecurity and Information Assurance Program Plan

I am also not able to find any of the frameworks under "There are also several that have not been published but we still have reference to them being in CaSS at some point"

I will look into why the two that I can find are not showing up and why the third one is not available at all. 
Where are you seeing the references for the bottom list?

**Comment by mparsons-ce** [comment]
re: bottom list
These are in our database. When a framework gets created in CaSS, we create a record in a related database table. We use this table for local searches, approvals, and publishing. 
Typically if a record gets deleted in CaSS there is a post message process to ensure it also gets deleted in our database. 

![image](https://user-images.githubusercontent.com/58825866/228988922-d781e2db-4d4a-47c9-80e6-9eb60f9d7e3b.png)

**Comment by mparsons-ce** [comment]
@gloverkari 
I re-checked the published frameworks and the following still do not appear in CaSS when editing via the CTID. I was not able to find them by searching either. I also logged in as a WGU user, to see if that is a factor. 

### Published
**Associate of Science, Cybersecurity and Information Assurance**
ce-77d9e9ef-2b2c-4adb-b017-88412bce05b9
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-77d9e9ef-2b2c-4adb-b017-88412bce05b9 
https://credentialengineregistry.org/graph/ce-77d9e9ef-2b2c-4adb-b017-88412bce05b9
Last published: 2022-12-06 20:50:53

**Master of Science, Data Analytics (MSDA) Competencies**
ce-c6eb6e3b-d637-47ea-96c3-95e3f2d884d9
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-c6eb6e3b-d637-47ea-96c3-95e3f2d884d9
https://credentialengineregistry.org/resources/ce-c6eb6e3b-d637-47ea-96c3-95e3f2d884d9

The following frameworks are fine
**MSDA 201612 Competencies**
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-2bdfa1e4-c455-495d-895a-1d297352447f

**Bachelor of Science, Cloud Computing (BSCC) Competencies**
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-32f2c32d-6731-440e-b894-0ccf2099ec15

**Bachelor of Science in Information Technology Degree Program**
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-c0288e3b-ffcb-4ff6-b0ac-9e1187baafcb

### Unpublished
There are several frameworks that are not published, and originated in CaSS but are no longer found. 
There were actually 6 frameworks with the name: "Master of Science, Data Analytics 201612 (MSDA_201612) Competencies" created in a short period (I deleted 4). The latter might imply some issue where a new framework was created with a new CTID each time a save was done, yet none are found now.  
![image](https://user-images.githubusercontent.com/58825866/233154653-ffafb0d3-5106-43b1-a188-8d3bafc1f574.png)

In some cases, the history shows edits on multiple days, and is no longer found.
![image](https://user-images.githubusercontent.com/58825866/233154187-c4cf4154-200d-4558-a2f1-46c9b1349671.png)


### Other
I had removed the following as it was apparently a duplicate.

> Cybersecurity and Information Assurance Program Plan
> ce-4dc6ad84-72b5-4f8e-90c4-6ea8391ae7cc

**Comment by mparsons-ce** [comment]
We need to confirm the process used by Alas. Does she redo an upload? If so, you would think that the CTID would not change.

**Comment by gloverkari** [comment]
Fix for this is addressed in https://github.com/cassproject/cass-editor/issues/1302

**Comment by mparsons-ce** [comment]
Closing this issue, based on belief that the correction for #1302 corrected the issue.
