### ISSUE TITLE
When search results are added, ask if they want to copy or link.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#13]

**Comment by Lomilar** [comment]
If the user wishes to copy the data, copies of the data should be constructed (and new ids generated) for each resource, and the owner of the data should be the user.

If the user wishes to link the data, links should be added to the framework (as is done now) without any additional modifications.

**Comment by miledivovic** [comment]
Implemented in bf2df38

**Comment by Lomilar** [comment]
Feedback in #26.

**Comment by miledivovic** [comment]
Fixed in cb5d3c9.

Tab no longer selects the checkboxes.

**Comment by eddavies** [comment]
There should be a way to cancel using the keyboard as well. There is no way to get rid of the link or copy screen.

**Comment by eddavies** [comment]
If tab highlights select all or add, then spacebar invokes the command of the button. It should not work that way.

**Comment by miledivovic** [comment]
Fixed in 4164f97

Scrolling should also work properly now.

**Comment by eddavies** [comment]
fix verified

**Comment by eddavies** [comment]
Made a note in #26 that a user should be able to deselect all
