### ISSUE TITLE
Extra ceterms:CTID property is being exported with a framework and competencies

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1302]
@gloverkari I was notified of an error publishing a framework.
Master of Science, Data Analytics 201612 (MSDA_201612) Competencies
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-bb06e9f4-5fc3-4b72-9c4f-728dc8f1e86c
This was recently imported. 
I checked the export:
https://cass.credentialengine.org/api/ceasn/10c0b2e009e1f2f48a1c78c432a80b92
I saw that there now a ceterms:CTID property (list of URIs) that appears for both the framework and all of the competencies. 

![image](https://user-images.githubusercontent.com/58825866/234680100-f4446a64-730c-45b1-824f-0c68f0a1bae9.png)

**Comment by jeannekitchens** [comment]
@gloverkari this is a new issue and another blocker.  Please check this out.

**Comment by jeannekitchens** [comment]
That is correct.  The intent is ceterms:ctid.
