### ISSUE TITLE
Make edit section width draggable.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#131]

**Comment by eddavies** [comment]
![too far edit window drag](https://user-images.githubusercontent.com/23706850/36991710-6551c44a-205d-11e8-97bf-e98781fe70ea.PNG)
There should be a limit to how far a user can drag the edit window. A user can drag the edit window into the framework list.

**Comment by eddavies** [comment]
![dragging and windowing](https://user-images.githubusercontent.com/23706850/37481824-f414e02e-283f-11e8-8bc7-3634cdbcb32f.PNG)
Managed to make this occur by dragging the edit panel to max width while the browser window was fullscreen then windowing browser window. This is minor, maxing the browser window or refreshing the page fixes this.

**Comment by eddavies** [comment]
Looks good

**Comment by eddavies** [comment]
![drag window broke again](https://user-images.githubusercontent.com/23706850/37537124-d66a4436-2909-11e8-85b2-f97afce4deae.PNG)
Just ran into this. Steps:
1. In windowed make the browser window as small as possible.
2. Max the window size
3. Open the edit panel
4. Unmax the window size
5. Max the window size again

**Comment by siuc-nate** [comment]
One slight issue that might be related to the above - probably not important, but:
On drag, the bar jumps a little off to the left of the cursor and stays that distance from the cursor as you drag. The cursor ends up roughly aligned with the left edge of the text inside the right panel. Roughly here:
![image](https://user-images.githubusercontent.com/21346519/38102676-8eaa6a00-3349-11e8-9703-501f630cbc12.png)

**Comment by eddavies** [comment]
Fix verified.
