### ISSUE TITLE
Encountered error: TypeError: Cannot read properties of undefined (reading 'ceasn:isChildOf')

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1328]
@gloverkari 
On attempts to publish the following two frameworks, received the error:

> TypeError: Cannot read properties of undefined (reading 'ceasn:isChildOf')

CSC-110 Exam Blueprint
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-805708d6-ce0d-4b53-b28f-23fa621e4472
https://cass.credentialengine.org/api/ceasn/2948ffd56deaa7f1d4bae1cf1831937d

CFR-310 Exam Blueprint
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-72cd1f2d-ebe2-4fcb-a5c7-ca83de66b352
https://cass.credentialengine.org/api/ceasn/e867634d3ffd7fede3cfc809fb733ba1 

Neither frameworks have been updated since 2020.

**Comment by gloverkari** [comment]
Exporting the framework mentioned above as Credential Engine ASN (JSON-LD) on production reproduces the error.
"TypeError: Cannot read properties of undefined (reading 'ceasn:isChildOf')"

I am still unable to reproduce the issue locally or in another instance of CaSS, but I have added several checks to handle an unexpected state of the property ceasn:isChildOf.
I will continue to investigate the difference in this framework and why it causes the error.

**Comment by mparsons-ce** [comment]
@kari 
We are still getting this error for the framework: CSC-110 Exam Blueprint
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-805708d6-ce0d-4b53-b28f-23fa621e4472 
https://cass.credentialengine.org/api/ceasn/2948ffd56deaa7f1d4bae1cf1831937d

TypeError: Cannot read properties of undefined (reading 'ceasn:isChildOf')

**Comment by gloverkari** [comment]
@mparsons-ce Looking into this again.

**Comment by gloverkari** [comment]
@mparsons-ce It looks like both frameworks have references to non-existent child nodes (https://credentialengineregistry.org/resources/ce-f8eab94d-b983-4419-95db-895742357325 and https://credentialengineregistry.org/resources/ce-2386aff0-dcf1-4e75-b282-b29e871ecdef) that are not visible in the UI. 

The 'Credential Engine ASN (JSON-LD)' export fails when it attempts to access properties of the missing child nodes. 
I am putting in a check for this during export to prevent the failure.

**Comment by mparsons-ce** [comment]
@gloverkari 
We are now getting a different error on export of [CSC-110 Exam Blueprint](https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-805708d6-ce0d-4b53-b28f-23fa621e4472)
https://cass.credentialengine.org/api/ceasn/2948ffd56deaa7f1d4bae1cf1831937d

TypeError: Cannot read properties of undefined (reading 'startsWith')

**Comment by mparsons-ce** [comment]
@gloverkari 
We are still getting export errors for both of these two frameworks.
This may have fallen of the radar when the issue was moved to On Production in [Credential Engine Issue Tracking](https://github.com/cassproject/cass-editor/projects/2#card-90000579)

**Comment by mparsons-ce** [comment]
@gloverkari I tried exporting both of these frameworks, and there are no longer any issues. 
Closing.
