### ISSUE TITLE
Replace CTID references when removing duplicates within an upload.

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1336]
Required for #1312 (CaSS Should Not Allow Duplicate competency text with different CTIDs in the same collection or framework)
This issue addresses competency references within a model being uploaded.  If an upload has duplicates (competencies containing identical properties aside from ID and CTID) and the user chooses to upload only one of the duplicates, any references in the model to duplicates not being uploaded will be replaced with references to the duplicate chosen. 

*** Note that this will NOT affect any existing data within the CaSS repository.

**Comment by sedula27** [comment]
Verified in both production and sandbox
