### ISSUE TITLE
If adding property by URL in alignment and url ends in forward slash, then slash is added to beginning of url. 

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1343]
This issue was found while addressing the following ticket: https://github.com/cassproject/cass-editor/issues/827

Setting the url to a value ending in a '/' results in an incorrectly formatted url for the alignment.

![image](https://github.com/cassproject/cass-editor/assets/78623855/4a90bf52-a634-435d-9bbd-c7c49947fe19)

![image](https://github.com/cassproject/cass-editor/assets/78623855/ed15a035-2b52-4b1e-a9a2-f5547cdc1d22)

![image](https://github.com/cassproject/cass-editor/assets/78623855/1792f673-43fd-4d27-9c0b-1c2b32b88f73)

**Comment by gloverkari** [comment]
Implemented a fix to update the url if needed before saving the relation.

**Comment by sedula27** [comment]
Slash is not added to the beginning of the URL, verified and can be closed

**Comment by sedula27** [comment]
Was able to verify this on production as well
