### ISSUE TITLE
Inconsistent behavior when saving publishing status of Concept Schemes

### ISSUE THREAD

**Issue by gloverkari** [cassproject/cass-editor#1346]
From Eduworks/CE Biweekly Meeting:
"On sandbox, concept schemes consistently will not save when publishing status is selected. It takes, at minimum, several changes to the status and continually selecting to save before the error messages clears and it saves!"

**Comment by Lomilar** [comment]
Need to test/repro.

**Comment by Lomilar** [comment]
May be addressed by 1.5.57. Retest.

**Comment by mparsons-ce** [comment]
I just tried updating a concept scheme with publication status. 
I clicked done, and the save has been spinning for 60+ second.
However, I then did a refresh and tried again, this time the record saved immediately

**Comment by sedula27** [comment]
https://github.com/cassproject/cass-editor/issues/1355 and this point out the same issue, refer 1355 for a temporary WorkAround

**Comment by sedula27** [comment]
https://github.com/cassproject/cass-editor/issues/1356 and #1355 point to the same issue, So closing this one
