### ISSUE TITLE
Import to handle Invalid line breaks from copy/paste

### ISSUE THREAD

**Issue by sedula27** [cassproject/cass-editor#1350]
@gloverkari where uploading a csv file which has invalid line breaks after CTID's , can you update the import handle that and remove the (\n) during export.
![image](https://github.com/cassproject/cass-editor/assets/93455942/a81d54e2-2855-47e4-9d80-6b29dd0b6e0c)

This is a sample framework with that [Issue](https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-d6b6d77d-84a4-4ee7-ba12-1cf2a3024456)

And a sample CSV file
[AR CompetencyFramework Bulk Upload  - NCCER Craft_ Plumbing Level 1.csv](https://github.com/cassproject/cass-editor/files/14606688/AR.CompetencyFramework.Bulk.Upload.-.NCCER.Craft_.Plumbing.Level.1.csv)

**Comment by siuc-nate** [comment]
The trailing newline should be stripped out as part of the import, not just removed during export - it isn't valid data and shouldn't be stored in CaSS with the newline present.

**Comment by miledivovic** [comment]
@sedula27 should be fixed in 1.5.71

**Comment by sedula27** [comment]
Was able to verify, this issue can be closed
