### ISSUE TITLE
Unable to create new ProgressionModel, as the editor doesn't recognize that description has been entered (or publication status has been selected)

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#1355]
@Lomilar 
SANDBOX
I created a new progression model.
Clicked Done.
Then got error that description is required, but it exists
![image](https://github.com/cassproject/cass-editor/assets/58825866/8de7c5d4-1a25-412e-80e0-662cb97ce8f3)

I updated the description and tried again.
Now I get an error that language is required, but exists.
![image](https://github.com/cassproject/cass-editor/assets/58825866/8c131835-58ea-45a2-b024-c21470748850)
 
I also got error that Publication Status was required, but it is already selected. 
![image](https://github.com/cassproject/cass-editor/assets/58825866/58d61ccc-5153-485d-bc34-da8b4beba618)

On production a similar error will occur for description. I found that I could just update the latter and then save successfully.

**Comment by Lomilar** [comment]
I was able to create a progression model by selecting a language 'English' vs 'en-us'. There was definitely some weird validation errors going on that required some clicking around. @gloverkari fysa

**Comment by Lomilar** [comment]
hint: Blur validation isn't fully working, may want some sort of timeout based validation.

**Comment by winonadeb** [comment]
Since there is a workaround (click off of the field you edited before saving), is this still a blocker?

**Comment by sedula27** [comment]
Issue with the required fields(Description/Publication Status) highlighted even though they are filled, this is not a consistent issue

**Comment by sedula27** [comment]
Refer #1356, they point to the same issue so closing this one
