### ISSUE TITLE
Import using Paste Text not working

### ISSUE THREAD

**Issue by sedula27** [cassproject/cass-editor#1359]
@Lomilar 

Trying to import a framework into CASS using the paste text feature, I added the framework name and Competency text, after verifying the content in the window and on click of Import, the Status is being updated to Parse Text but no progress after that. I did see the console and was not able to find any errors there.
![image](https://github.com/cassproject/cass-editor/assets/93455942/74b57f0a-e3b5-494f-8da3-bc409ec3c023)

I do see this error on the console after the page loads
main.js:35 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': The provided value is not of type '(record<ByteString, ByteString> or sequence<sequence<ByteString>>)'.
    at _callee$ (main.js:35:32)
    at tryCatch (regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (regeneratorRuntime.js:133:17)
    at Generator.next (regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at editor.js:284:13

**Comment by jeannekitchens** [comment]
@sedula27 which environment?

**Comment by sedula27** [comment]
This is an issue in both Sandbox and Production

**Comment by sedula27** [comment]
Resolved on both sandbox and production
