### ISSUE TITLE
Unable to add a Competency Framework

### ISSUE THREAD

**Issue by sedula27** [cassproject/cass-editor#1360]
@Lomilar 
 I am unable to add a new framework using the editor, it does not save the name and description, and not able to add the competencies either.  
 
 This issue is in both sandbox and production

When the framework is exported it does have the updated Name and description, here is a sample export which has the date but the UI does not display any updated information as shown in the video.

https://sandbox.cass.credentialengine.org/api/ceasn/2031d039a8ded7c4b9958204ae8e859a
 
 

https://github.com/cassproject/cass-editor/assets/93455942/4ac80a8e-f766-45b6-9c00-9af66110b459

**Comment by sedula27** [comment]
This works on production, sandbox still has the same issue

**Comment by Lomilar** [comment]
Sandbox has been updated.

**Comment by sedula27** [comment]
Verified on sandbox and production
