### ISSUE TITLE
Framework's export is missing dateValidFrom and dateValidUntil

### ISSUE THREAD

**Issue by sedula27** [cassproject/cass-editor#1364]
@Lomilar When [this framework ](https://sandbox.credentialengine.org/publisher/competencies/?frameworkctid=ce-c81975a3-c455-46ef-b1e1-a1ec08a4dbad)is exported into json and csv, the CaSS export is missing the ceasn:dateValidFrom property that is available on screen.

https://sandbox.cass.credentialengine.org/api/ceasn/bcbef1698c932467b193c461626886b0
[University Parallel - GUPD (1).csv](https://github.com/user-attachments/files/15887882/University.Parallel.-.GUPD.1.csv)

This issue exists in both sandbox and production.

This is a framework that is missing dateValidUntil in the export https://cass.credentialengine.org/api/ceasn/9d1d7c4f0972a23c3e49e13283f5c6f5

![image](https://github.com/cassproject/cass-editor/assets/20917206/20ab2ae5-3bff-4ccc-a611-71910b76beb3)

**Comment by sedula27** [comment]
Sandbox and production both have 1.5.64, issue seems to resolved on production but **Sandbox is missing the dates when exported**

**Comment by sedula27** [comment]
Export does not include date valid from and date valid until for the frameworks uploaded via import
Framework where I manually added the date
[https://sandbox.cass.credentialengine.org/?user=wait&editorRoot=/&server=https://sandbox.cass[…]n=https://sandbox.credentialengine.org&action=import](https://sandbox.cass.credentialengine.org/?user=wait&editorRoot=/&server=https://sandbox.cass.credentialengine.org/api/&ceasnDataFields=true&&newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&show=mine&origin=https://sandbox.credentialengine.org&action=import#/framework)
Export
https://sandbox.cass.credentialengine.org/api/ceasn/39b23eee5cbc0a2f6e402048bbf91ac4
Framework added via Import
https://sandbox.credentialengine.org/publisher/competencies/?frameworkctid=ce-f90eb8fa-c455-4616-a5b9-435f53e4b2f6
Export:
https://sandbox.cass.credentialengine.org/api/ceasn/8b381044ded476fa5e9a7d066b48816c
Framework:
https://sandbox.credentialengine.org/publisher/competencies/?frameworkctid=ce-c81975a3-c455-46ef-b1e1-a1ec08a4dbad
Export:
https://sandbox.cass.credentialengine.org/api/ceasn/bcbef1698c932467b193c461626886b0 (edited)

**Comment by miledivovic** [comment]
@sedula27 This should be fixed now with CASS 1.5.65 on sandbox

**Comment by sedula27** [comment]
Date Valid From and Date Valid Until are being exported in both sandbox and production
