### ISSUE TITLE
After importing a Progression Model JSON-LD file, the language tag is shown as part of the preferred label

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1367]
Steps to reproduce:
1. Import a Progression Model (this may happen with other types) JSON-LD file into CaSS
2. Review the content
3. Compare that content to what you see if you open that progression model in a separate/new window/instance

Immediately after an import of a JSON-LD file, the language tags are shown as part of the preferred label in the tree view (they are properly split up in the editing modal window).  However, if you leave and reopen this progression model, those language tags are not displayed.  This appears to be a visual bug rather than a data bug.

![image](https://github.com/user-attachments/assets/7f2a65a5-b100-4f2c-bc02-5b523f44ad94)

**Comment by sedula27** [comment]
This can be closed was able to verify the update, language is not shown as part of the name 
![image](https://github.com/user-attachments/assets/dfcaa051-2673-4934-b617-3d0f1bfcb840)

**Comment by miledivovic** [comment]
@sedula27 should be fixed in 1.5.71
