### ISSUE TITLE
Display issues at narrow screen sizes

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1368]
In the screenshot below, there are several display issues due to the narrow width of the page.  Is CaSS intended to support narrower screens?:

![image](https://github.com/user-attachments/assets/6e8596e0-53e4-41d6-871d-da29cdee438f)

**Comment by sedula27** [comment]
Display issues have been corrected, this has been verified on both Sandbox and Production
https://sandbox.credentialengine.org/publisher/progressionmodel/
