### ISSUE TITLE
Display for Progression Model names cuts off at an arbitrary width in search results

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1369]
Unlike other types of search results, the names for progression models appears to have an unnecessary max width associated with it:
![image](https://github.com/user-attachments/assets/04f80dee-0431-475c-a163-c05403bf4ceb)

**Comment by sedula27** [comment]
This issue has been resolved on Sandbox and Production
![image](https://github.com/user-attachments/assets/ec9c1ea4-6bf6-4628-b511-4cc26ae860e7)

**Comment by miledivovic** [comment]
@sedula27 should be fixed in 1.5.71
