### ISSUE TITLE
Competency deletion popup doesn't disappear after clicking confirm

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#137]
Removing a competency causes the prompt to come up, but clicking confirm does not cause the prompt to disappear, but does indeed confirm the deletion of the competency.

**Comment by eddavies** [comment]
![prompt doesn t disappear](https://user-images.githubusercontent.com/23706850/36991588-fe724e48-205c-11e8-8c46-61be57248e71.PNG)

**Comment by Lomilar** [comment]
Wasn't able to repro in an obvious way. Can you give steps?

**Comment by eddavies** [comment]
Only occurs when deleting a top level competency

**Comment by eddavies** [comment]
Ok so, I was able to reproduce only with competencies I have copied from another framework.

**Comment by Lomilar** [comment]
Copied competencies did not belong to the user at the time, remove button should not have shown up. Try to repro now.

**Comment by eddavies** [comment]
Still occurs. So I did these exact steps:
1. create new framework
2. Add existing
3. Select all competencies from the "Big Six" framework and add
4. under one of the competencies click edit
5. Then click on delete.

Just clicking on remove without first clicking on the "edit" button does not cause this issue to occur.

**Comment by eddavies** [comment]
fix verified
