### ISSUE TITLE
Error saving framework when trying to add a link to a progression model

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#1370]
I tried to add a link to this progression model:
https://credentialengineregistry.org/resources/ce-7308f663-c455-4dff-a843-02393f807eb4

To the framework shown below. I get the error shown below, and the data does not save.

Also, when I click the "done" button, it becomes grayed out, but the modal window does not close, meaning I have to refresh the page to get back to the framework view.

![image](https://github.com/user-attachments/assets/fdf90807-eb6c-412a-9ec2-3b7d1c05093b)

**Comment by miledivovic** [comment]
@siuc-nate can you verify if you still run into this error? May have been caused by the production server disk being too full preventing any data from saving.

**Comment by sedula27** [comment]
Was able to save after adding HasProgressionModel
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-78dccffa-f509-47b6-9c63-22f9448cd313
