### ISSUE TITLE
Competency data and framework data are not passed in CTDLASN

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#138]
Currently, it looks like competency framework data are not passed in schema URL parameters for CTDLASN. Appears that competency framework in iframe comes out in vanilla CASS format.

@Lomilar is this intentional?

**Comment by siuc-nate** [comment]
I should clarify that this applies to the data (competencies and framework) that is sent out by the iframe via postMessage when competencies are selected.

**Comment by Lomilar** [comment]
Complete and in use. #121
