### ISSUE TITLE
Framework export label CEASN ---> CTDLASN

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#139]
When exporting a framework, one export option is CDASN.
Should read CTDLASN.

**Comment by eddavies** [comment]
do you mean "Credential Engine ASN"?

**Comment by siuc-nate** [comment]
The current value it looks for is "ceasn" - it should be "ctdlasn".  The former is a prefix used on most of the terms in the schema; the latter is the official shorthand name of the schema itself: http://credreg.net/ctdlasn/terms

**Comment by Lomilar** [comment]
I think I pulled the namespace prefix from here:

http://credreg.net/ctdlasn/terms/

![image](https://user-images.githubusercontent.com/337692/37233377-c1ab371a-23a7-11e8-8de6-75b01d6ec177.png)

**Comment by siuc-nate** [comment]
Has this been taken care of? We'd like to close issues that are fixed.

**Comment by Lomilar** [comment]
There's widespread use of ceasn and ceterms as a namespace prefix across imports, exports, and many other areas. Is there more guidance about when ceasn/ceterms and ctdlasn/ctdlterms should be used?
