### ISSUE TITLE
There should be a cancel button for adding competencies from another framework

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#14]
When adding a competency via search, there is no way to return to the edit screen easily. The only way to immediately get back to the edit screen from the search list is adding a competency.

**Comment by Lomilar** [comment]
Repro'd. Should use back button (need option to enable) on cassproject/cass-viewer to send a 'cancel' message to the parent window.

**Comment by Lomilar** [comment]
Related Note: Back button on the browser or mouse does return to the previous window.

**Comment by eddavies** [comment]
Back button on browser works. For accessibility, the user must use "alt-right left arrow" to do so (might be useful to be in the readme).
