### ISSUE TITLE
Performance/readability hit on large frameworks

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#140]
If you bring up the O*NET framework in the CASS editor, the interface becomes sluggish when hovering/scrolling through the competencies. The text of the competencies also becomes harder to read the deeper into the framework you go:
![image](https://user-images.githubusercontent.com/21346519/37120986-868bd28e-2221-11e8-8604-f580449d443a.png)

I did a bit of digging and this appears to be due to the use of `linear-gradient` for the `background-image` property to create the transparent/layered background effect. I tried using an rgba value for the `background-color` property instead, and it seemed to be much more performant while retaining the transparency/layered effect, so that may be a solution.

However, this does not address the readability issue. I'm open to suggestions here, but one solution might be to use a left (or maybe right?) border (instead of a background effect) on the currently `:hover`ed competency (it's probably fine to keep the background effect for a selected competency).  Using a transparent border by default and a colored left border on hover keeps the text from jumping around.  

Example:
![image](https://user-images.githubusercontent.com/21346519/37121338-6f1127fc-2222-11e8-968f-39d942f52364.png)

Alternatively, it may be better to just darken the currently-hovered/selected competency without darkening any of its parent competencies. 

Any thoughts on this?

**Comment by Lomilar** [comment]
Seems OK. I'm not the authority on how good or bad things look, so getting some more eyes on this.

@otterlove @eddavies Vote away!

**Comment by siuc-nate** [comment]
@jkitchensSIUC and I are reviewing these - we want to move forward with the border-based solution in the second screenshot above.

**Comment by Lomilar** [comment]
@siuc-nate Deployed.
