### ISSUE TITLE
EZ-Framework Paste

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#146]
Need tab delimited import format based on just text lines and tabs.

**Comment by Lomilar** [comment]
Should be when initializing a framework (initial authoring), not editing yet.

**Comment by Lomilar** [comment]
May be desired for appending.

**Comment by Lomilar** [comment]
There are a bunch of easy NLP type things that can be done to augment this (detection of listId, codedNotation) and some questions around how additional information (descriptions, etc) are handled. We can address these as we continue to develop this feature, but wanted to point them out now.

**Comment by jeannekitchens** [comment]
@Lomilar @woodkri is this implemented in the new CaSS version?  We defintely want this with CE CaSS.

**Comment by woodkri** [comment]
Yes, import of competency names by tab/space-delimited text will be included in v2 of the editor.

**Comment by woodkri** [comment]
Included in CaSS 1.3. There's a separate issue open for improvements (parsing out additional fields).
