### ISSUE TITLE
Make draggable detail panel look like it is draggable.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#148]

**Comment by miledivovic** [comment]
Is this referring to the edit panel on the right side that can be dragged left and right?

**Comment by Lomilar** [comment]
Yes, the divider is currently just a dark line. It should be, if possible, turned into a visually grab-friendly line (with the appropriate left-right arrow or left-arrow-to-vertical-line resizable hover mouse cursor)

**Comment by eddavies** [comment]
Edit panel looks draggable
