### ISSUE TITLE
Make sure there's a postmessage event for when frameworks are entered or competencies are selected.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#149]

**Comment by siuc-nate** [comment]
We'd like to make this one a high priority, as it impacts our ability to implement the approval/publishing system we discussed.

Specifically, what I need is a postMessage indicating a selection/view every time the user:
- selects an existing framework
- creates/saves a new framework (when the new framework is initially displayed)
- goes back to the framework search/selection screen

I also need a postMessage indicating a change/update/save when the user:
- saves changes to an existing framework
- any other event that changes/updates the currently-selected framework

These can all be one event type (message?) if that makes more sense on your end, though it would need a flag to indicate when the selection is _also_ a change (which mostly applies to creating a new framework, I guess, as that is a create followed by a view). Two separate event types is also fine, or if it's necessary, one event type for each bullet above.  I'm not partial to any particular approach there.

I need to detect and react to, ultimately, two things:
- A framework has been selected and is now being viewed (this would fetch the approval/publication status and display it on our end)
- A framework has been changed (this would mostly be used to determine when a framework that was previously approved or published is now in need of reapproval/republishing, and display this fact on our end)

**Comment by Lomilar** [comment]
@siuc-nate 

### On Clicked, On Changed, View Changes:
Changes when frameworks or competencies are clicked, changed, or the internal editor view changes are passed to the parent page. The mesasge types are `viewChanged`, `frameworkChanged`, `frameworkClicked`, `competencyChanged`, `competencyClicked`. See the console for additional fields that are passed.

**Comment by Lomilar** [comment]
Done. (and deployed)

**Comment by Lomilar** [comment]
@siuc-nate Above commit should fix that.
