### ISSUE TITLE
Accessibility Issues with adding a competency from another framework

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#15]
1. After clicking search, to search for a competency from another framework, the arrow keys do not highlight the frameworks, making it impossible to select a competency via only keyboard.

2. To mark the checkbox next to a competency, the command is "spacebar" (don't know if this was intended, but "enter" does not work).

3. User has to click tab to browse through each checkmark next to the competency. When searching for a competency in a large framework, it can be tedious to click tab 100 times. The arrow keys should allow the user to browse through this list, especially since with tab, even if the desired competency is the first one among the list, the user has to click tab repeatedly to get to the add button.

**Comment by Lomilar** [comment]
Search is not the same code as is used in the cass-editor, see cassproject/cass-viewer#1

**Comment by miledivovic** [comment]
Added keyboard controls to cass-viewer so this should work now.
Shift + Enter will add the selected competencies.

**Comment by eddavies** [comment]
This is not working initially. When attempting to search competencies tab and the arrow keys cannot select from the list of available frameworks.

Also when coming back from adding competencies form another framework, the user must click on one of the competencies in order for tab and the arrow keys to work (so somebody only using keyboard are forced to refresh the page)

**Comment by eddavies** [comment]
Err just found that you have to click escape in order to browse the list of competencies

**Comment by Lomilar** [comment]
cassproject/cass-viewer#1 deprecated the cass-viewer, so the selector is now the cass-editor (and should have the same keyboard controls).

**Comment by eddavies** [comment]
Other issues have been fixed. But marking the checkboxes with enter or spacebar no longer works.

**Comment by Lomilar** [comment]
Ah, checkboxes are new (#18). Let me see if I can manage this one.

**Comment by Lomilar** [comment]
*Can now check competencies using space bar if in selection mode.

**Comment by Lomilar** [comment]
Should be ready to test. Marking checkboxes is done with space, once marked, enter selects them into the previous framework.

**Comment by eddavies** [comment]
Space and enter work
