### ISSUE TITLE
Add drop zone dashes to competency names when drag starts.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#157]

**Comment by eddavies** [comment]
These look fine, but it's difficult to tell if the competencies are draggable from just looking at the framework, I don't think most people will figure out that they are draggable unless told.

**Comment by Lomilar** [comment]
Are they told in the tutorial?

Hand-grab cursor would also help with this, if the user is allowed to edit the framework.

**Comment by eddavies** [comment]
A hand-grab cursor would be helpful. I didn't see anything on the readme, is there a separate document?

**Comment by eddavies** [comment]
no issues found
