### ISSUE TITLE
Add indent/outdent buttons/keyboard controls.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#158]

**Comment by miledivovic** [comment]
Could I get some more info on this?

**Comment by Lomilar** [comment]
I suppose this would be dependent on being able to reorder competencies as well. Requires #57.

The desired workflow is something like this when creating a framework.
```
One <enter>
<tab>   Two <enter>
Three <enter>
<tab>   Four <enter>
<tab tab>    Five <enter>
```

**Comment by Lomilar** [comment]
tab / shift+tab are taken. This is accomplishable with a minimum of fuss via SHIFT+X, SHIFT+V for now.
