### ISSUE TITLE
Add alignment component.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#159]

**Comment by eddavies** [comment]
Found a bug with aligning competencies. 
Steps:
1. Create a new framework with two competencies.
2. Click on the second competency and add prerequisite alignment
3. In the selection screen, checkmark both competencies
4. Click align with... multiple times (the button goes gray, but every time this is clicked the competency is aligned - it is possible to align the competency this way 100 times).
5. Uncheck the other competency and click align with and this occurs:

![multiple alignments](https://user-images.githubusercontent.com/23706850/38832262-de951aa2-4176-11e8-8edc-4e10614344e7.PNG)

**Comment by eddavies** [comment]
This doesn't seem to occur when more competencies are present and selected

**Comment by Lomilar** [comment]
@eddavies Closing this, it's old and alignment works now. Feel free to re-open.

**Comment by eddavies** [comment]
Confirmed, no longer occurs.
