### ISSUE TITLE
Frameworks refusing to load while searching to add competencies from another framework

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#16]
While trying to add a competency from a framework that I've made, the framework does not load the list of selectable competencies. Other frameworks like "Mosaic" load just fine, but the ones I've made along with the ones Mile has made are not loading.

This does not occur in the basic framework viewer, just while trying to add a competency from an existing framework. 

Stuck on this page:
![stuck loading](https://user-images.githubusercontent.com/23706850/32798117-9b5da220-c928-11e7-85c2-07c0fdc31e46.PNG)

**Comment by Lomilar** [comment]
Investigating. According to the error log there's an A -> B -> A relationship that it can't handle.

**Comment by Lomilar** [comment]
created cassproject/cass-viewer#1 in response to this. We need to begin sharing code. I suggest a branch at first to ensure we don't break anything.

**Comment by Lomilar** [comment]
This issue should be resolved, however, it spawned other issues that have been recorded. OK to test.

**Comment by eddavies** [comment]
The frameworks are now loading. But after clicking search for a competency, the user is brought to the last location where they were searching for a competency to add (the framework they added the last competency from), instead of the list of frameworks.

**Comment by Lomilar** [comment]
@otterlove Is the above behavior (keeping in the same framework when searching repeatedly) OK? It reminds me of file dialogs that do the same thing.

**Comment by otterlove** [comment]
As long as there is an easy way to jump back out to search all frameworks, then assuming a user's most common intent is to work within the same framework is a good one. It's the lesser of two annoyances (clicking back vs. finding your FW again)

**Comment by eddavies** [comment]
Just noticed that if changes were made to the framework in which the user is attempting to use a competency in their framework from, that the changes are not updated. 
So steps to reproduce (assuming two frameworks exist):
1. Access framework 2 and add a competency from framework 1.
2. Make changes to framework 1
3. Access framework 2 again and attempt to add a competency from framework 1
4. This user will see framework 1 as if the changes haven't occurred. However, after going back to the search results and then back into framework 1, then changes are updated.

**Comment by eddavies** [comment]
With new changes, user is now brought their previous search results, making the issue I commented on no longer pertinent.
