### ISSUE TITLE
Possible to delete a framework with the cancel button

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#162]
Clicking the cancel button while editing a framework can lead to framework deletion

Steps to reproduce:
1. create new framework
2. click search
3. open another framework (I used ".Net Web Developer Program")
4. add a competency (I copied instead of linked)
5. Click edit under the framework
6. click cancel
7. A prompt appeared on chrome notifying possible deletion of the framework (I've never seen this one before)
8. Another prompt appeared to confirm or cancel the deletion of the framework

**Comment by Lomilar** [comment]
This spawns from the "on first edit, offer to delete if the user cancels" enhancement.

**Comment by Lomilar** [comment]
Not able to repro. May have been fixed by something. Try again?

**Comment by eddavies** [comment]
Yeah can't repro anymore. closing this.
