### ISSUE TITLE
Competencies: Selecting an existing skill from the suggested list results in kick out of edit.

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#163]
(Duplicated from https://github.com/cassproject/CASS/issues/55)
Steps

Created a new framework
Specified to create a new competency
As I started to type, the system listed (type ahead/autocomplete) existing competencies
I clicked on one of the items in the list
I got kicked out of the edit view
The competency was saved with the item selected, but I lost other data that had been entered.

**Comment by Lomilar** [comment]
That is correct. I put in a warning about what is going to happen when someone clicks on an autocomplete competency.

**Comment by eddavies** [comment]
After clicking ok and creating this new competency, "New Competency" appears in the edit panel.

![after autocomplete of competency](https://user-images.githubusercontent.com/23706850/38276202-199dc2b2-3749-11e8-835a-3d595d2560b3.PNG)

**Comment by eddavies** [comment]
Works most of the time, however, ran into this happening:
<img width="951" alt="worker characeristics" src="https://user-images.githubusercontent.com/23706850/46555386-f58bd900-c897-11e8-81e6-836bb832f1d6.PNG">
I created Worker Characteristics underneath "New Competency" and it never showed up on the right.

**Comment by eddavies** [comment]
In the framework I can no longer create competencies underneath other competencies (may be a separate issue)

**Comment by eddavies** [comment]
Attempting to reproduce above, got it to occur again after adding an autofill competency underneath an existing competency in a new framework:
<img width="955" alt="again" src="https://user-images.githubusercontent.com/23706850/46555608-b1e59f00-c898-11e8-8d68-c603ff098549.PNG">

**Comment by eddavies** [comment]
Previously in the above, "Ensuring computer security" was a child of "New Competency" and then I attempted to make "Occupational Requirements" as a child of "Ensuring computer security"

**Comment by eddavies** [comment]
I managed to get this to occur:
<img width="957" alt="worker characteristics" src="https://user-images.githubusercontent.com/23706850/47879852-e9cffb80-ddde-11e8-83b3-464a430a52a7.PNG">

I believe this is related directly to the specific competency (Worker Characteristics) because every time I try to add it via autocomplete, errors occur.

**Comment by eddavies** [comment]
I can investigate further if you need me to, but this does not occur when adding other competencies via autocomplete.

**Comment by eddavies** [comment]
I found this competency is the "O*NET" framework.

**Comment by woodkri** [comment]
Competencies with invalid ids are no longer be an option for the autocomplete. This should eliminate the problem with some of the O*NET competencies (Worker Characteristics above had an id of "1").

**Comment by eddavies** [comment]
I'm not running into this anymore
