### ISSUE TITLE
Export of Concept keywords as language map is incorrect

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#165]
Duplicated from https://github.com/cassproject/CASS/issues/58

Language maps may not be used, but just in case, noticed that in production the format of ceasn:conceptKeyword is incorrect in an export:

![37689810-51086a88-2c75-11e8-9a59-2192397c4206](https://user-images.githubusercontent.com/23706850/37735454-57bf5710-2d0b-11e8-9615-6bf2c93bdc9d.png)

Instead it should be:

![37689944-02dc2024-2c76-11e8-8754-a2adb9bdeec8](https://user-images.githubusercontent.com/23706850/37735467-64465aba-2d0b-11e8-844a-34c4bae4e776.png)

**Comment by Lomilar** [comment]
According to the JSON-LD playground (I'm using libraries to accomplish the same), the appropriate way of representing arrays of langstrings is as originally shown.

"A language container of arrays, not an array of language containers"

![image](https://user-images.githubusercontent.com/337692/37926884-642b80ba-30ed-11e8-9bec-4e033d69dacc.png)

**Comment by Lomilar** [comment]
This makes a certain kind of sense considering the list of keywords may not have 1-1 translations. Therefore, the lists of keywords may differ for each language, as more or less relevant words are included and taken out.

**Comment by Lomilar** [comment]
@stuartasutton @siuc-nate FYI

**Comment by Lomilar** [comment]
https://github.com/CredentialEngine/CompetencyFrameworks/issues/71#issuecomment-403033575
