### ISSUE TITLE
Editor: Under Rights Holder, the URI Only note appears twice

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#166]
Duplicated from https://github.com/cassproject/CASS/issues/59

![37689987-460ea98e-2c76-11e8-89e6-6d2bc7a7c117](https://user-images.githubusercontent.com/23706850/37735516-88e60096-2d0b-11e8-9ec7-5f5c8b8d96e7.png)

**Comment by Lomilar** [comment]
5444b47b72539c2c3da1287c47c3838e7947dd2d

**Comment by eddavies** [comment]
fix verified
