### ISSUE TITLE
Put sidebar view buttons in top-anchored bar (similar to sidebar edit)

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#169]

**Comment by eddavies** [comment]
All buttons seem to be working except the CSV might be doing something strange.

Clicking on CSV opened three separate excel windows with one of them being completely blank. Does this happen to you?

**Comment by miledivovic** [comment]
When I click on csv it downloads files, doesn't open anything.

**Comment by miledivovic** [comment]
Seems like an issue with excel rather than the cass-editor to me.

**Comment by eddavies** [comment]
Yeah I mean it isn't even a big issue honestly, I just close the blank excel sheet.
