### ISSUE TITLE
When nothing is selected in concept select screen, asks to link or copy.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#173]
Additionally, if nothing is selected in any search screen, it should not ask to link or copy.

**Comment by eddavies** [comment]
A dialog box stating "please select a competency/concept" would be an improvement over the current "add" button turning white. Or if the add button was white from the get go, then marking a competency turns it green.

**Comment by miledivovic** [comment]
Good idea, will add that.

**Comment by eddavies** [comment]
Perfect
