### ISSUE TITLE
Any attempt to shift from edit-mode to view-mode should "Are you sure you want to discard changes?"

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#175]

**Comment by miledivovic** [comment]
How/where is the shift from edit-mode to view-mode triggered?

**Comment by Lomilar** [comment]
If you click on a different competencies in edit mode, it switches to view mode. 

If you click back when in edit mode, it .. well, yeah. loses stuff.

If you click on the framework in edit mode, it switches to view mode.

**Comment by eddavies** [comment]
Works. Only small thing, when clicking on a different competency in edit mode, the prompt appears twice (so ok is needed to be clicked on twice to remove the prompt).

**Comment by miledivovic** [comment]
Woops, accidentally closed it. Pushed a fix for the issue you had @eddavies

**Comment by eddavies** [comment]
The prompt is not appearing at all now for swapping between competencies.

**Comment by eddavies** [comment]
fix verified
