### ISSUE TITLE
Warn if poor characters are detected in any fields.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#176]
Characters like non-breaking spaces, not-detected-here characters, block characters, etc can cause issues.

**Comment by miledivovic** [comment]
Are we able to constrain inputs to alphanumeric only or is that too restrictive?

**Comment by Lomilar** [comment]
That is too restrictive. There are particular placeholder characters in copy and paste errors that get put into text. � for instance.

See:
https://en.wikipedia.org/wiki/Specials_(Unicode_block)

**Comment by eddavies** [comment]
It doesn't notify which fields specifically contain invalid data.

**Comment by eddavies** [comment]
also is there a masterlist of invalid characters?

**Comment by Lomilar** [comment]
New and exciting bad character: �

See CE Production server framework: CCO Service Truck Crane Operator Practical Exam

**Comment by eddavies** [comment]
Entering � now results in a warning while editing. Error message when attempting to save appears correctly as well.
