### ISSUE TITLE
When concurrently editing a framework, structure does not get re-established very well on the 'listening for changes' screen.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#183]

**Comment by Lomilar** [comment]
Only occurs when there is a competency shift+linked in two places in the framework.

**Comment by Lomilar** [comment]
I think this was additionally fixed by some library changes that prevent double-render requests. aa9c154069bcf569db3263edb5d844ab6e0af758 and e33b644c45c3ac68ae64abf4e8b631fb8e97dc98

**Comment by eddavies** [comment]
works much better than before. Only concern which might not be that bad is when two people are editing the same competency and one saves their changes first, then the other is knocked out of edit mode. I can't think of a better way to handle that.

**Comment by eddavies** [comment]
Need to test after #218 changes

**Comment by eddavies** [comment]
@miledivovic I could use some help testing this at some point
