### ISSUE TITLE
Allow reordering of competencies.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#185]
Can be accomplished by reordering the items in framework.competency
Helps address #57

**Comment by Lomilar** [comment]
Thinking: shift+up, shift+down to move things up and down on the keyboard, and move up, move down buttons if edit is available.

**Comment by eddavies** [comment]
The move up and move down buttons don't seem to be doing anything for me,

**Comment by eddavies** [comment]
Works in the framework editor. Does not work in the concept editor

**Comment by eddavies** [comment]
Shift up and shift down should be added to the keyboard shortcuts portion of the read.me

**Comment by Lomilar** [comment]
Newlines weren't put in the right places in the markdown. Updated.

**Comment by eddavies** [comment]
fix verified
