### ISSUE TITLE
Framework export requires framework node to be selected

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#188]
This may only be relevant to the CTDL/ASN use case, but:

If any competency in a framework is selected when the export postMessage is sent, the following error is returned:
```
Individual competencies are not permitted to be represented in CEASN outside of a framework. See https://github.com/CredentialEngine/CompetencyFrameworks/issues/43 for more details.
```
It only works if the framework node is selected. 

It would be nice to have a way to ignore the selection and force an export of the framework instead, perhaps as a parameter of the export postMessage?

Additionally, the schema's name is CTDL-ASN, not CEASN, so the error message itself should be updated (as should the documentation, which is missing "ctdlasn" as an option https://github.com/cassproject/cass-editor/blob/master/README.md#export ).

**Comment by Lomilar** [comment]
Reopen if this doesn't seem to be working.
