### ISSUE TITLE
Importing a framework sends user to an empty browser screen

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#190]
I just attempted to import a CSV for a new framework (the excel sheet should be valid) by clicking browse and finding my file. However, instead of importing or receiving an error message, my chrome tab left the cass-editor to a blank window.

**Comment by Lomilar** [comment]
Changed CSV import to obey some new rules about how IDs work. Try now?

**Comment by eddavies** [comment]
Still running into this issue

**Comment by eddavies** [comment]
Hmm worked with a different csv actually

**Comment by eddavies** [comment]
I'm gonna test this a bit more.

**Comment by eddavies** [comment]
Just found what's causing this. If a user imports the same framework multiple times this occurs. It was occurring because I previously imported the framework I was using in this test.

**Comment by eddavies** [comment]
I'm not running into it either
