### ISSUE TITLE
Move anywhere button/mode for tree

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#193]
Tree should allow someone to move something anywhere else, based on drop zones.

**Comment by Lomilar** [comment]
*not based on drop zones. Related to accessibility (drag and drop is hard sometimes) and for making jumps across huge breadths of large frameworks.

SHIFT+X, SHIFT+V actually solves this.

Closing.

**Comment by stuartasutton** [comment]
Impossible over "huge breadths" if the screen doesn't scroll up and down as you drag. But, up and down arrows are equally bad over such distances moving up and down one node at a time.

**Comment by Lomilar** [comment]
Correct, but you can select a competency, SHIFT+X it to "cut it" (CTRL+X isn't allowed) and then select a target competency node and SHIFT+V "paste it", and it will move. Keyboard shortcuts aren't well spelled out anywhere except for [here](https://github.com/cassproject/cass-editor/#keyboard-shortcuts), however, so maybe we should make that more apparent.
