### ISSUE TITLE
Allow alignment with URLs outside of the system.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#195]

**Comment by eddavies** [comment]
This seems to be working. @Lomilar Should these URIs have link icons or be clickable?

**Comment by eddavies** [comment]
Closing #325 and #357

**Comment by Lomilar** [comment]
We have a process/function right now for finding a name or title on a remote address (in use for Publisher, etc) that we could also use here. Finding the name of the other side of the relation would be useful if it makes sense when you see it. Doing that would also imply the link icon. Clickability -- only via the link icon.

**Comment by Lomilar** [comment]
Reviving this.

**Comment by Lomilar** [comment]
Pretty sure all URLs resolve if they can and display if they can now.
