### ISSUE TITLE
Frameworks: Missing description field

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#197]
The description field appears to have gone missing:
![image](https://user-images.githubusercontent.com/21346519/38519232-c1ad8676-3c04-11e8-8259-43a188ee457b.png)

**Comment by Lomilar** [comment]
I'm having trouble reproducing this on all the sites I know of.

Any errors to go along with it?

**Comment by siuc-nate** [comment]
No errors, the box simply wasn't present - there was a small gap where it should have been, though; maybe that was related?

It seems to be working now, however. Strange.

Closing this for now.
