### ISSUE TITLE
Accessibility.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#2]
Needs to completely operate via keyboard.

**Comment by miledivovic** [comment]
Implemented in 8921487 and d7cbe82

**Comment by eddavies** [comment]
Is there a list of keyboard commands? Arrow keys seems to work, but how do I go back from page to page, or select the search, etc.

**Comment by miledivovic** [comment]
Updated in 3a56305.

Down arrow and up arrow: navigating list of frameworks/competencies
Left arrow and right arrow: expand/contract nested competencies
Enter: Select the current element
Backspace: Go back to list of frameworks
Tab: Switch focus to different elements like search bar or edit buttons.
Escape: Step out of an input field like the search box and go back to navigating the list.

**Comment by otterlove** [comment]
Can the user still edit using the arrows and backspace? Is their navigation functionality disabled when editing a field or textarea?

**Comment by eddavies** [comment]
Existing issues with accessibility:

Unable to create new competencies for a framework right after creating a new framework.
Pressing enter to save changes does not work, have to press spacebar
Unable to select specific competencies in framework edit mode without changing options on the drop down (on the right of the edit screen)

**Comment by miledivovic** [comment]
Fixed in 144d625 and f8ab192

**Comment by eddavies** [comment]
Fixes verified. However, still testing accessibility.

**Comment by Lomilar** [comment]
Please update README.md with keyboard controls.

**Comment by miledivovic** [comment]
README updated in fbbcc5a

**Comment by Lomilar** [comment]
Thanks.
