### ISSUE TITLE
iOS: Date valid from and until always appears invalid

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#202]
As title describes, entering in any date into those fields will not save.

**Comment by eddavies** [comment]
No longer occurs

**Comment by eddavies** [comment]
Sorry didn't see iOS tag on title, may still occur

**Comment by Lomilar** [comment]
Can we repro this on iOS?

**Comment by eddavies** [comment]
<img width="334" alt="selecting" src="https://user-images.githubusercontent.com/23706850/52228773-1d9c4080-2868-11e9-9c4e-e566bd9a8c4d.PNG">
<img width="337" alt="invalid" src="https://user-images.githubusercontent.com/23706850/52228775-1ecd6d80-2868-11e9-899e-053543b7838a.PNG">
<img width="332" alt="close" src="https://user-images.githubusercontent.com/23706850/52228820-3147a700-2868-11e9-83d0-2858422dd191.PNG">

**Comment by eddavies** [comment]
fix verified
