### ISSUE TITLE
Fields that support multiple comma-delimited items should state so in the tooltip.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#204]

**Comment by chinhseah** [comment]
@Lomilar @miledivovic Can I assume tool tips that have plural words like documents, labels, etc. can have multiple items delimited by commas? Is there a validation function that errors when user input commas so I know that field does not allow commas?

**Comment by chinhseah** [comment]
@Lomilar @miledivovic I am thinking for example a current tool tip that says, "Alternate hidden labels for this concept." will be modified to "Alternate hidden labels for this concept. Multiple labels should be separated by commas." Is this what you were thinking tool tip should say?

**Comment by Lomilar** [comment]
Correct.

Talk to @kchavas and @eddavies for wording.

**Comment by chinhseah** [comment]
@kchavas @eddavies 
Let me know if any wording below needs to be changed. 

For Alignments, I got text from [http://credreg.net/ctdlasn/schema](url)


Competency Category: 'The textual label identifying the category of the competency as designated by the promulgating body. Separate each label with commas.'

Derived From: 'A third party version of the entity being referenced that has been modified in meaning through editing, extension, or refinement. Separate each entity with commas. For example, http://example.com/?t=derivedFrom'

Education Level: 'A general statement describing the education or training context. Alternatively, a more specific statement of the location of the audience in terms of its progression through an education or training context. Separate each level with commas.'

In Language: 'The primary language used in or by this competency framework or competency. Separate each language with commas.'

Identifier: 'An alternative URI by which this competency framework or competency is identified. Separate each URI with commas. For example, https://sandbox.credentialengineregistry.org/'

Concept Keyword: 'A word or phrase used by the promulgating agency to refine and differentiate individual competencies contextually. Separate each concept with commas.'

Concept Term: 'A term drawn from a controlled vocabulary used by the promulgating agency to refine and differentiate individual competencies contextually. Separate each term with commas.'

Skill Embodied: 'Cognitive, affective, and psychomotor skills directly or indirectly embodied in this competency. Separate each skill with commas.'

Complexity Level: 'The expected performance level of a learner or professional as defined by a competency. Separate each level with commas.'

Alternative Name: 'Alternative display labels for this concept. Separate each label with commas.'

Change Note: 'Documents fine-grained changes to a concept, for the purposes of administration and maintenance. Separate each change with commas.'

History Note: 'Describes significant changes to the meaning or the form of a concept. Separate each change with commas. For example, http://example.com/?t=idforHistoryNote'

Hidden Label: 'Alternate hidden labels for this concept. Separate each label with commas.'

Note: 'Preferred display label for this concept. Separate each label with commas.'

Notation: 'An alphanumeric notation or ID code as defined by the promulgating body to identify this framework. Separate each notation with commas.'

Creator: 'An entity primarily responsible for making this competency framework or competency. Separate each entity with commas. For example, http://example.com/?t=idforFrameworkOwningorg'

Publisher: 'A URI to an entity responsible for making this competency framework available. Separate each entity with commas. For example, http://example.com/?t=idforFrameworkPublishingorg'

Publisher Name: 'Name of the agent responsible for making this entity available. Separate each name with commas.'

Source: 'The original competency framework which this competency framework is based on or derived from. Separate each original with commas. For example, http://example.com/?t=source'

*Alignment related*

Requires: 'Another competency framework or competency is prerequisite for this. Separate each prerequisite with commas.'

Equivalent To: 'Represents same capability in all aspects to another competency framework or competency. Separate each with commas.'

Broadens: 'Covers all of the relevant concepts in this competency or competency framework as well as relevant concepts not found in this competency or competency framework. Separate each with commas.'

Narrows: 'Covers all of the relevant concepts in the referenced competency framework as well as relevant concepts not found in the referenced competency framework. Separate each with commas.'

Major Alignment: 'Major overlap of relevant concepts between this competency framework and the referenced competency framework. Separate each alignment with commas.'

Minor Alignment: 'Minor overlap of relevant concepts between this competency framework and the referenced competency framework. Separate each alignment with commas.'

Is Enabled By: 'A recommended option that speeds up acquisition of this competency framework or competency. Separate each option with commas.'

Is Related To: 'This competency framework or competency has some degree of overlap with another. Separate each overlap with commas.'

Desires: 'Recommended, assumed, or expected competency framework or competency not essential to acquisition of this. Separate each with commas.'

**Comment by eddavies** [comment]
Make a comment related to this in #214

**Comment by chinhseah** [comment]
@eddavies Is this issue resolved since issue #214 is closed? Thanks.

**Comment by eddavies** [comment]
@chinhseah Yes, thanks for pointing this out. Closing this.
