### ISSUE TITLE
Pressing enter on the keywords input box opens the concept selector.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#205]

**Comment by eddavies** [comment]
fix verified

**Comment by siuc-nate** [comment]
Still getting this issue here.  Steps to reproduce:
1. Edit a framework
2. Highlight a non-textarea text field (like creator)
3. Press enter
4. The concept selector appears

**Comment by Lomilar** [comment]
@miledivovic This occurs when the cass-editor is in an iframe, as the controls are in a form (for reasons I'm not sure of) and the code you wrote that suppresses it doesn't get invoked if there is a cross domain origin, meaning the keypress falls through to the form, which pushes the next button in the form.

I'd recommend either removing the form (not sure what side effects that would have) or figuring out how to suppress form-enter-push-next-button-behavior in HTML.

@siuc-nate This can also likely be mitigated by fixing the cross-domain frame keypress issue.

**Comment by eddavies** [comment]
I'm not running into this issue anymore.
