### ISSUE TITLE
iOS: export/view function is not responsive

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#206]
Clicking on download/view doesn't incur any commands at first. However clicking on CASS JSON after it has already been selected cause a page to open detailing object not found. There should be an error message for exporting on iOS.

**Comment by miledivovic** [comment]
I can reproduce the needing to click twice part, but I don't get any object not found errors. Can you retest?

**Comment by eddavies** [comment]
Not running into the object found error anymore. The clicking twice issue still exists.

**Comment by eddavies** [comment]
@Lomilar will have shortly

**Comment by eddavies** [comment]
The export drop down is shown as normal, however whenever something is selected nothing happens, just the export window collapses:
<img width="336" alt="ios export" src="https://user-images.githubusercontent.com/23706850/52226510-05c1be00-2862-11e9-804e-a0b3d177fa79.PNG">

However, with CaSS RDF QUads, RDF JSON, RDF XML, Turtle, and Table CSV, the user is redirected to a new page in the same tab (no new tab is opened), with the export.

I made a video of this, let me know if you want me to send it to you on slack/email/skype.

**Comment by eddavies** [comment]
After clicking rdf quads:

<img width="340" alt="rdf quads" src="https://user-images.githubusercontent.com/23706850/52227042-52f25f80-2863-11e9-9f22-2feb9e30c337.PNG">

**Comment by woodkri** [comment]
@eddavies I don't have any iOS devices so I can't see if this change helped at all. Can you try out one of the ones you mentioned above that were opening in the same tab and see if this fixed it?

**Comment by eddavies** [comment]
Whatever you did works, the fields are no longer invalid. fix verified
