### ISSUE TITLE
Scrolling down and clicking the "?" causes graphical errors

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#207]
While going though the guided tour on iOS, the framework that is supposed to be spotlighted is just covered by a giant white rectangle.

![tour ios](https://user-images.githubusercontent.com/23706850/38576914-582aae94-3cb4-11e8-829c-c6a827b14177.PNG)

**Comment by eddavies** [comment]
This is not limited to iOS, on iOS the tour works exactly the same as it does on Chrome. What causes this is if the user has previously scrolled down the list of frameworks and then clicked the "?"

**Comment by eddavies** [comment]
Additionally the tour will act as if the user entered the sample framework, but the user is stuck on the master framework list.

**Comment by Lomilar** [comment]
System should probably refresh the page with a flag that starts the tour automagically.

**Comment by eddavies** [comment]
This no longer occurs, however the tutorial stops at the point where it is supposed to open a framework and show the user details there

**Comment by miledivovic** [comment]
That was a quick fix, it should work now.

**Comment by eddavies** [comment]
fix verified
