### ISSUE TITLE
iOS: Alignment buttons are cutoff

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#208]
It is possible to side scroll to see them.
This occurred after I reordered the competencies under one another.

![alignment buttons cutoff](https://user-images.githubusercontent.com/23706850/38577534-13f2fd2e-3cb6-11e8-8f4a-7beab4ccead2.PNG)

**Comment by miledivovic** [comment]
Can't reproduce, might have been fixed with another change.

**Comment by eddavies** [comment]
I'm not sure when this was fixed but this is no longer an issue. Alignments are now positioned underneath the properties section
