### ISSUE TITLE
Add concept schemes as a type of modifiable framework.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#21]

**Comment by Lomilar** [comment]
Informational: CredentialEngine/CompetencyFrameworks#44

**Comment by Lomilar** [comment]
80d368, 8722ad

Outstanding question: What DC and SKOS fields should we be supporting? Currently using title, description, subject, language.

**Comment by Lomilar** [comment]
@stuartasutton

**Comment by Lomilar** [comment]
https://cassproject.github.io/cass-editor/?ceasnDataFields=true&concepts=true

**Comment by stuartasutton** [comment]
I am adding a "SKOS Concept" tab to the google sheet and am adding this property information this AM.

**Comment by Lomilar** [comment]
Do you have namespaces for the properties as well? Are we using dc:creator or schema:creator or ceasn:creator or...

**Comment by stuartasutton** [comment]
For the SKOS tab, I included namespace designation in parens in the 'range' column.

**Comment by Lomilar** [comment]
Functionally, I believe this is done.
