### ISSUE TITLE
Find user friendly IETF language mapping

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#213]

**Comment by Lomilar** [comment]
One use case: Being able to use the "in language" property with words like "english" and having it convert to "en"

**Comment by eddavies** [comment]
This does not occur for additional Languages after clicking the "+" icon

**Comment by eddavies** [comment]
Autofill does not appear for additional languages

**Comment by Lomilar** [comment]
Merged

**Comment by eddavies** [comment]
Autocomplete for multiple languages work! Keeping this issue open in case it is related to #394

**Comment by eddavies** [comment]
Closing this
