### ISSUE TITLE
Add Another button on Edit Competencies

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#218]

**Comment by Lomilar** [comment]
Should be shortcutted, maybe shift+enter.

**Comment by Lomilar** [comment]
Consider, after an add in general, selecting the parent. This means you won't see what you just created.

**Comment by eddavies** [comment]
This button works, but should not exist under the framework's edit panel after creating a new framework.

**Comment by eddavies** [comment]
This button exists in the concept editor but does not add another term/concept

**Comment by eddavies** [comment]
Should not exist in the concept scheme's edit panel (same as the framework)

**Comment by eddavies** [comment]
This is working now, but there is a pretty big delay after clicking the button and the edit panel reopening. Is there a way to not have the edit panel close so it doesn't go from: competency 1 edit panel -> new competency non edited -> new competency edit panel? Instead just: competency 1 edit panel -> new competency edit panel. Or really any other way to prevent the delay, if feels right now like the app is lagging.

**Comment by eddavies** [comment]
Much better now
