### ISSUE TITLE
Import from CASE (with select/checking of frameworks)

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#220]

**Comment by Lomilar** [comment]
CASE endpoint.

https://case.georgiastandards.org/

**Comment by jeff-grann** [comment]
Selecting a framework from that endpoint and importing results in the following error message "No frameworks found."

**Comment by Lomilar** [comment]
Just listing facts and soliciting opinions. @kchavas

- CASE Import doesn't assign user (treats them as public frameworks).
- Technically the frameworks belong to the creators on that CASE server.
- Creators aren't communicated via CASE very well. 
- The URIs are still CASE URIs, so the importing user should not own the frameworks.
- The CASS/CASE adapter should own the frameworks? (so it can update them too?)

**Comment by Lomilar** [comment]
Taking this one step at a time (and seeking to close this issue)

**Comment by eddavies** [comment]
Still running into no frameworks found

**Comment by Lomilar** [comment]
Done.
