### ISSUE TITLE
In production site, upon clicking a different framework, the system returns a selectedFrameworkCtid with the ce- duplicated.

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#222]
Steps:
- login
- open console
- select a framework
- use console to view the Current Framework changed

![image](https://user-images.githubusercontent.com/26332112/38704600-81c8c0e2-3e6c-11e8-98a3-7d414ef4a3cc.png)

as shown above, the selectedFrameworkCtid has ce-ce- then the UUID.
Note, this does not occur in the dev site.

**Comment by Lomilar** [comment]
Should be fixed along with #221 - Deploy when ready.

**Comment by Lomilar** [comment]
Deployed.
