### ISSUE TITLE
Template URI properties don't appear to work

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#223]
I have begun experimenting with the template structure Fritz mentioned some time ago - it seems to work for plain text and date fields (haven't tried the `@owner` property yet), but it doesn't appear to work for URI fields:

![image](https://user-images.githubusercontent.com/21346519/38825970-01efb37a-4174-11e8-8973-569d37c0c629.png)

**Comment by Lomilar** [comment]
Ah, use the schema versions of those fields. schema:creator and schema:publisher

We may not look like it, but we're still CASS under the hood.

**Comment by siuc-nate** [comment]
Ah, that worked.

Thanks.
