### ISSUE TITLE
Split child/parent alignments from narrows/broadens alignments based on if the target is in the framework.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#225]
This is doable, but whether things appear in the broadens/narrows or parent/child buckets won't be up to the user, because the distinguishing feature is a computed feature. So, if I try to broaden something inside my framework, it will get shuttled into a parent slot. Similarly, if I broaden something and then add it to my framework, it will shuttle anything that broadens it into instead being parents of it. Continue discussion here.

**Comment by miledivovic** [comment]
Does this distinction only need to exist visually in the frontend?

**Comment by Lomilar** [comment]
Yes, and only in the ceasnDataFields mode.

**Comment by eddavies** [comment]
@Lomilar Are these broadens and narrows relations specific only to the framework? If someone makes a narrow relationship with a competency of another framework, should the competency in the other framework have a broaden relationship or no?

@miledivovic We need tooltips for child and has child. Also under broaden and narrow we need to specify within the tooltip that making a broaden alignment with another competency within a framework does not actually create that alignment, but makes the competency a child. Or we can remove broaden and narrow alignment capabilities with competencies of the same framework.

**Comment by Lomilar** [comment]
>If someone makes a narrow relationship with a competency of another framework, should the competency in the other framework have a broaden relationship or no?

Not necessarily. If the person owns both frameworks, giving them a prompt to create the inverse relation in the other framework would be nice, but that is the furthest I would go here.

**Comment by eddavies** [comment]
#302 for the tooltips.
Closing this, working as intended unless we change intentions.
