### ISSUE TITLE
UPDATED: ceasn:rights was defined as a single absolute url. It is now defined as a language string

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#227]
@Lomilar 
Definition
![image](https://user-images.githubusercontent.com/26332112/38905075-cc9950d6-4273-11e8-91d7-2fda2c4ad496.png)

Output
![image](https://user-images.githubusercontent.com/26332112/38905098-f8a2f826-4273-11e8-90f1-3addeecf4d82.png)

https://dev.cassproject.org/api/ceasn/schema.cassproject.org.0.3.Framework/a5509302-a60e-44b2-8a1a-73597fc5f9dd/1524008476367

**Comment by cwd-mparsons** [comment]
@Lomilar I have verified the change.
![image](https://user-images.githubusercontent.com/26332112/38951633-ed8d31b8-430e-11e8-9335-bb1d182b1731.png)

**Comment by stuartasutton** [comment]
Well, this is a little messed up. Going back to the original, the ASN used dcterms:rights which has as its range, a dcterms:RightStatement which is a class of literals stating rights. Somehow in the translation to CEASN, this got converted to xsd:anyURI. In the ASN, this is treated as an rdf:langString. It should be that here as well.

**Comment by stuartasutton** [comment]
Sorry guys, but I have changed this from a xsd:anyURI to rdf:langString and not repeated...

**Comment by siuc-nate** [comment]
Language string? Does that imply that the text of usage rights needs to be included in the data?

I believe the use of a URI here was probably borrowed from LRMI, where it was most often used to point to a Creative Commons license.

**Comment by cwd-mparsons** [comment]
@stuartasutton I want to confirm that this is a decided change. If so, we should clear out the existing data in production, and hide the property until the changes are made. 

@Lomilar As indicated in this thread, rights is now a language string. Pending Stuart's response to the latter we will need to take the following actions:
- hide in production (after next step) until updates are made
--Or I can monitor any new published data, and check for use of rights
- Any existing data should probably be set null. 
--I found about 23 documents with this property. I can do the updates and republish the frameworks

**Comment by siuc-nate** [comment]
As @cwd-mparsons reminded me, we do have http://credreg.net/ctdlasn/terms/license to cover the URI for rights (if I'm interpreting that correctly), so this change is probably just a matter of moving any data that currently exists in rights and is a URI over to the license property and republishing it.

**Comment by Lomilar** [comment]
CaSS Team: 

- [ ] To change license to a langstring in cass-editor, 
- [ ] to change translation contexts to and from CTDL-ASN to match, 
- [ ] and to provide a script to remove it from frameworks.

**Comment by Lomilar** [comment]
Thanks, I modified my above post.

**Comment by woodkri** [comment]
@Lomilar I'm working on a node script to remove values in the rights fields from frameworks. If I add the ceasn public key as owner, will that take care of permissioning? As it is, I can only remove the field from public frameworks.

**Comment by Lomilar** [comment]
Adding the CEASN (staging) private key to EcIdentityManager will take care of the permissioning. Nothing additional has to be done with the owner.

**Comment by woodkri** [comment]
Here's a node script to remove data currently in the rights field from frameworks. The ceasn private key will need to be added on line 11.

```
require("cassproject");
EcRemote.async = false;
var repo = new EcRepository();
repo.selectedServer = "https://cass.credentialengine.org/api/";

var m = new EcRemoteIdentityManager();
m.server = repo.selectedServer;

var search = "(*)";
credentialEngine = new EcIdentity();
credentialEngine.ppk = EcPpk.fromPem("private key here");
EcIdentityManager.addIdentity(credentialEngine);

EcFramework.search(repo, search, function (frameworks) {
    for (var i = 0; i < frameworks.length; i++) {
        var fx = frameworks[i];
        if (fx["dc:rights"] || fx["ceasn:rights"]) {
            var rights = fx["dc:rights"] ? "dc:rights" : "ceasn:rights";
            fx[rights] = null;
            console.log(fx.name);
            repo.saveTo(fx, console.log, console.log);
        }
    }
}, function (failure) {
    console.log(failure);
},{size:5000});
```

**Comment by Lomilar** [comment]
Change above script to emit URI.
We have permission to do this.

**Comment by Lomilar** [comment]
```
https://credentialengineregistry.org/resources/ce-31c0f48b-d615-4592-ac9b-7e0ff2a326bd
https://credentialengineregistry.org/resources/ce-bbaadcc2-649a-487b-a3e2-e7d6854b63fe
https://credentialengineregistry.org/resources/ce-3fc0e5b7-9810-442b-9e15-b399c2756e1b
```
