### ISSUE TITLE
Using keyboard only does not allow choosing of concept terms or adding existing competencies

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#228]
As title describes, there is no way to check off specific competencies or concept terms using keyboard commands, unless there is a command that I'm not aware of. (select all does work)

**Comment by miledivovic** [comment]
Up and down arrow keys should work now to select from the list. Enter to checkmark them.

**Comment by eddavies** [comment]
If you click tab once, then the arrow keys no longer work.

**Comment by miledivovic** [comment]
Pressing escape should now correctly allow the arrow keys to work again.

**Comment by eddavies** [comment]
fix verified. We should add these commands to the guide in some way
