### ISSUE TITLE
iOS: Competencies can be cutoff by the mid bar

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#230]
Additionally the Properties section title is cutoff and when scrolling the side menu up, the scroll does not stick and continues to cutoff "Properties"
![competencies cutoff into mid bar](https://user-images.githubusercontent.com/23706850/39022278-9da73e42-43e9-11e8-97d0-c50b863703b4.PNG)

**Comment by miledivovic** [comment]
Are you not able to scroll left and right to view the competencies that are cut off?

**Comment by eddavies** [comment]
fix verified
