### ISSUE TITLE
"tree" list overflows iframe boundaries

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#233]
I suspect it's due to the max-height not accounting for changes in the framework section on top:
![image](https://user-images.githubusercontent.com/21346519/39199374-f0236100-47ae-11e8-9cfe-7039b19bf555.png)
Something like this might be most easily solved with a wrapper div around the framework header and tree div, and playing with css flex rules. Or, since I suspect the widths of the draggable columns are set via javascript, maybe setting the heights with javascript would be easier.

Iframe boundary:
![image](https://user-images.githubusercontent.com/21346519/39199543-56e69894-47af-11e8-81fe-a6173ba2fed4.png)
tree boundary:
![image](https://user-images.githubusercontent.com/21346519/39199573-6b4634b6-47af-11e8-8380-6afc7bbf0a8e.png)

**Comment by eddavies** [comment]
fix verified

**Comment by eddavies** [comment]
Just found an occurrence of this happening again by adding a ton of alignments to a framework with many objects.

**Comment by Lomilar** [comment]
+1 - This happened to me as well, @eddavies 

Recommend resize method at the end of a framework refresh.

**Comment by eddavies** [comment]
fix verified. As a note, adding a ton of alignments makes takes the editor longer to load.
