### ISSUE TITLE
ceasn:repositoryDate is exported as an array, where a string is expected

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#235]
Exported a competency framework for publishing. Received an error
Error reading string. Unexpected token: StartArray. Path '[1].ceasn:repositoryDate'.

ceasn:repositoryDate is defined as a string

![image](https://user-images.githubusercontent.com/26332112/39213009-f81d3e36-47d5-11e8-9e6c-1af84d7066f1.png)

**Comment by Lomilar** [comment]
@siuc-nate @cwd-mparsons Published to Dev.

**Comment by Lomilar** [comment]
No longer in the editor.
