### ISSUE TITLE
Means to retain last page of search results 

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#237]
Scenario
I was publishing each of the frameworks. After publishing a framework, I would go back to the search to select the next one. After the first page, I have to keep specifying to Load All, and scroll to the next item to publish. 
Can the search 'remember' the last page after returning from a framework? Or if a Load All was done, 'remember' the last location in the list? This might suggest that the framework is opened on top of the search results, rather than replacing the results with the edit view.

**Comment by Lomilar** [comment]
TODO:
- Turn on search caching when websocket is connected.
- Invalidate search cache when a new framework comes in via the websocket.

**Comment by Lomilar** [comment]
Retain scroll position and number of frameworks selected.

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor/issues/371 - When complete with this.

**Comment by Lomilar** [comment]
Merged, ready to test.

**Comment by eddavies** [comment]
This is working on cass test. It is even working when searching for competencies to add to a framework.
