### ISSUE TITLE
Members of the credential engine team need to be able to see (search for) all frameworks

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#238]
@Lomilar 
On production, I was going through all of the frameworks and publishing to the registry. I was able to search for and list all the frameworks.
At about 6pm CDT yesterday (April 24, 2018), I lost access to see all frameworks. At one point I saw some test frameworks, and then back to not seeing any frameworks - based on my organization of Credential Engine Administration.
Staff member of credential engine will need access to view all frameworks, in order to publish these to the registry.

**Comment by Lomilar** [comment]
Email is the correct course of action for production support. Responding via email.
