### ISSUE TITLE
Consider "button" like tags (with info) and if there is a way to make those informative and not confusing..

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#243]

**Comment by otterlove** [comment]
@Lomilar I'm not sure of the context for this request?

**Comment by Lomilar** [comment]
This was done "xxx items, created xxx date" already. I think you had some comments to make them look less like buttons, but it warranted further investigation.

**Comment by Lomilar** [comment]
Looking for feedback here. Haven't had any complaints about the tag-like-buttons. Reopen if feedback exists.
