### ISSUE TITLE
Some exported frameworks have incorrect types

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#247]
@Lomilar 
ex: Lift Director Core Written Exam
https://cass.credentialengine.org/api/ceasn/10ef85d2a2a9c616cf02e726eeecf416

![image](https://user-images.githubusercontent.com/26332112/39413889-6580bf7e-4bf6-11e8-80bb-259f91c546f1.png)

I had identified others from April 27th:

- CCO Mobile Crane Operator Written Specialty Exams
- Competency Areas
- Registration Examination for Evoked Potential (EP) Technologists
- Effective Practice Framework
- ExCPT Certified Pharmacy Technician Detailed Test Plan
- CCO Overhead Crane Inspector Comprehensive Examination
- Creating Presence in Your Online Course

However, I checked others on April 29th, and found all of these also had the wrong types.

**Comment by Lomilar** [comment]
This appears to have resolved. An @context was temporarily unavailable. @cwd-mparsons Feel free to check again and close when ready.

**Comment by Lomilar** [comment]
@cwd-mparsons Tested again now, looks fine. Reopen if there's additional follow up.
