### ISSUE TITLE
Everything entered should be selected automatically while in select and edit mode

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#249]
This will make it faster/easier to add competencies to a credential after the user has created a framework in the context of the credential editor.

**Comment by miledivovic** [comment]
@siuc-nate I believe this is already the case, unless I'm misunderstanding the issue.

**Comment by siuc-nate** [comment]
Apologies for the terseness of the initial post - It was entered amidst a flurry of other things.

Anyway, the original intent was:
1. Load up the editor with both selecting competencies and creating/editing competencies enabled
2. Create a framework
3. Create some competencies within the framework
4. The competencies you add should be automatically selected/checked so that all the user has to do is click the "add" button

However, on further review, I think the presence of the "Select All" button negates the need for this.  Ultimately it isn't my call though - this issue originally came from @jkitchensSIUC and she would need to give a yay/nay on the select all button taking care of it.  Jeanne, what do you think?

**Comment by Lomilar** [comment]
@jkitchensSIUC Re-open this if Nate's method (import then hit select all) is insufficient.
