### ISSUE TITLE
Enable triggering the "add" button functionality from the parent window via postMessage

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#250]
This will let the editor's parent page trigger the add functionality so that the "add" button can appear outside of the CASS editor but still function exactly as it does now.

**Comment by miledivovic** [comment]
@siuc-nate Which add button are you referring to specifically?

**Comment by siuc-nate** [comment]
The add button that appears next to the "select all" button when the editor has enabled selecting competencies.  Clicking the button causes the editor to send a postMessage to the parent window containing data for the selected competencies.

**Comment by Lomilar** [comment]
@miledivovic It's the add/select button along with the checkboxes that is shown in response to `select=Add` being passed into the URL parameters.

I would recommend if `select` is added as a URL parameter without any value, that the select functionality is enabled, but the select/add button isn't shown.

**Comment by miledivovic** [comment]
Got it, thanks.

**Comment by eddavies** [comment]
Wasn't working when we tried this @miledivovic

**Comment by miledivovic** [comment]
@siuc-nate Adding `select` as a query parameter without a value will hide the add button, and the message {"message":"select"} will trigger the add functionality.

**Comment by Lomilar** [comment]
Please create a demo page that demonstrates this that @eddavies can access.

**Comment by Lomilar** [comment]
Demo page is now at
demos/add-button.html

**Comment by Lomilar** [comment]
Merged. Ready to test.

**Comment by eddavies** [comment]
This does not seem to be working for me. I have competencies selected, but the add button (demo button) is not doing anything

**Comment by woodkri** [comment]
I added an alert so you don't have to go into the developer tools to see the contents of the postMessage.

**Comment by eddavies** [comment]
This seems to be working. Feel free to reopen if additional issues are found.
