### ISSUE TITLE
In dev environment, the search returns no results, and shows an empty page

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#255]
@Lomilar 
Entered test site, and did a search. 
The search runs, and then a blank page is displayed, with no message, and no search bar.

![image](https://user-images.githubusercontent.com/26332112/39590935-e181d986-4ec7-11e8-97ef-21c59a3c709d.png)

Also, if a framework is selected (from a blind search), and then the back arrow image is clicked to return to the search, a blank page is again shown.

**Comment by eddavies** [comment]
I got search results in firefox, however the search bar is not formatted correctly on firefox.
IE same thing.
![firefox search bar](https://user-images.githubusercontent.com/23706850/39608069-cb251f1e-4ef3-11e8-902b-12f7bbf7fe6c.PNG)

**Comment by Lomilar** [comment]
Seems fine.

**Comment by eddavies** [comment]
Not running into this
