### ISSUE TITLE
Error message when canceling a new framework

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#259]
On create new framework screen:

Please update the confirm cancel message to be non-tech language friendly. 

Current message: This object is new, and has not been saved. Delete it?
New message: Canceling will delete all changes without saving. Are you sure you want to delete without saving?

(We may also want to update the buttons. Okay is fine for the confirmation button but "Cancel" is a confusing term here. 

Maybe the two options should be more descriptive, for example: "Delete without saving" and "Continue editing".)

**Comment by eddavies** [comment]
fix verified
