### ISSUE TITLE
Creating a new competency closes edit options

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#260]
Creating a new competency opens the edit options for a second and then closes. The edit panel should be open with all fields and require the competency to be saved by clicking on the checkmark icon.

**Comment by miledivovic** [comment]
Nevermind, looks like it just occurs some of the time.

**Comment by eddavies** [comment]
This is actually not happening for me anymore. Will close for now.

**Comment by eddavies** [comment]
Ran into this again. Not sure how to reproduce efficiently but occurs once in a while

**Comment by miledivovic** [comment]
I think this will fix it, should be fun trying to reproduce it...

**Comment by Lomilar** [comment]
Yeah, this sometimes happened to me as well. Good luck!

**Comment by eddavies** [comment]
I've created hundreds of competencies and have not been able to reproduce this. If it still happens, it happens way less often.
