### ISSUE TITLE
Need info icon tool tips for alignments

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#262]
Need info icon tool tip descriptions for alignments

**Comment by Lomilar** [comment]
Do you need places to copy tooltips from?

**Comment by miledivovic** [comment]
Yeah that would be great.

**Comment by Lomilar** [comment]
http://credreg.net/ctdlasn/schema -- For the CEASN alignments, look there.

CASS ones can come from SKOS... but it needs to be made user friendly. 
https://www.w3.org/TR/skos-reference/#semantic-relations

Or here. http://devs.cassproject.org/index.html?doc=1U3OQboxlkCgCqyXrdNyr-5fLWtBwaELYN4XXutA9aP8

**Comment by chinhseah** [comment]
Please provide any feedback or comments for text I plan to use:

Requires: "Another competency is prerequisite for this."
Equivalent To: "Represents same capability in all aspects to another competency."
Broadens: "Covers other relevant concepts not found in this competency."
Narrows: "A sub-competency relationship which has relevant concepts in this competency."
Is Enabled By: "A recommended option that speeds up acquisition of this competency."
Is Related To: "This competency has some degree of overlap with another."
Desires: "Recommended, assumed, or expected competency not essential to acquisition of this competency."
![alignments tooltip](https://user-images.githubusercontent.com/15805943/40143253-cf149174-590f-11e8-9248-5fd27accffa0.PNG)

**Comment by miledivovic** [comment]
Are the descriptions not different for ceasn and cass/skos?

**Comment by Lomilar** [comment]
Correct. Find the rdfs:comment for each type of alignment for CTDL here.

http://credreg.net/ctdlasn/schema

**Comment by chinhseah** [comment]
@miledivovic  Yes, they are different. I substitute (or add) to match other tool-tips with "competency framework", "concept" or "scheme".

**Comment by eddavies** [comment]
tooltips are all present. fix verified
