### ISSUE TITLE
Tooltips for new competency info icons when creating a new framework

### ISSUE THREAD

**Issue by kchavas** [cassproject/cass-editor#264]
Fritz or Mile give me a ping on Skype and let's run through these quickly.

**Comment by kchavas** [comment]
@Lomilar Do we use ISO language codes for the _In _Language field? __

**Comment by eddavies** [comment]
Education Level Type is missing a tooltip

**Comment by Lomilar** [comment]
@kchavas Yes. ISO language codes are used.

I'm not sure what this issue is about.

**Comment by eddavies** [comment]
Kevin's suggestion for webpage: The webpage where the original competency framework can be found. The representation of the competency framework in the registry may differ from the original framework.

**Comment by eddavies** [comment]
fix verified
