### ISSUE TITLE
Can duplicate competencies by creating narrow alignments

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#266]
This is the end result:

![narrows bug](https://user-images.githubusercontent.com/23706850/39833701-af05908a-537f-11e8-82b3-385ff97a879c.PNG)

Steps to reproduce: 
1. Create framework with "new competency" parenting "newcompetency1" and "newcompetency2"
2. Create new competency3 under the framework.
3. Create a narrow alignment for competency3 and make it so competency3 narrows all three previous comeptencies.

**Comment by Lomilar** [comment]
A competency can narrow two competencies, and it shows up below both of them (along with all of its children) -- This is intentional and is a common method of showing a graph in a tree.

**Comment by eddavies** [comment]
Ah ok, closing this then
