### ISSUE TITLE
Possible to create alignments with competencies from other frameworks leading to some issues

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#268]
Users can align competencies with other competencies from other frameworks by clicking on the back button when browsing competencies in a framework to align with. This back button should be disabled in this circumstance (unless we want users to be able to do this).
This below image has "A" narrowing a competency from a different framework. A has a list drop down icon but nothing exists underneath it.
![narrowing nothing](https://user-images.githubusercontent.com/23706850/39834327-6f216f6e-5381-11e8-8f66-55f3d20cd3a1.PNG)

**Comment by Lomilar** [comment]
We want users to be able to do this.
