### ISSUE TITLE
Broadening competencies already broadened duplicates competencies

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#269]
![broading bug](https://user-images.githubusercontent.com/23706850/39834525-1d7af58a-5382-11e8-986e-1a7c419ec657.PNG)

This is caused by having A narrowing B. Then clicking B, making a broadening alignment with A. What happens is the alignment duplicates itself and the competency as well.

**Comment by Lomilar** [comment]
+1
We may want to add this to eduworks/ec. EcFramework.addRelation should probably ensure this doesn't happen -- though it could be expensive to figure out.

**Comment by eddavies** [comment]
This no longer occurs, broaden and narrow relationships cannot be made to competencies within the same framework.
