### ISSUE TITLE
URLs that resolve and have a name should be an href with the name as the text of the href.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#270]
ex: http://...../url (<-- blue and underlined) in the creator field should resolve and be Organization Name (<-- blue and underlined)

**Comment by miledivovic** [comment]
Are there properties besides ceterms:name that we would use to substitute for a URL?

**Comment by eddavies** [comment]
ceterms:names seem to populate the field. Does this need to be tested further? I don't know how many examples of this exist.

**Comment by Lomilar** [comment]
`name`, `ceterms:name`, `schema:name`, `title`, and whatever the default display name for Concept Terms are... which I think we already do.

**Comment by eddavies** [comment]
seems to be working
