### ISSUE TITLE
Competencies should flash in green if a change was saved during edit

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#281]
Found during testing #183.  The competency or framework should flash green if a change was saved during edit.

**Comment by miledivovic** [comment]
Just to clarify, this is referring to when a different user saves a change to the framework you're viewing?

**Comment by Lomilar** [comment]
Yes.

**Comment by eddavies** [comment]
So changes do highlight the framework/competency in green when a change is made. However, when a user goes to search for levels or terms in the concept editor, but then returns to the framework without selecting anything, the framework/competency still flashes in green even though no change was actually made. Making an alignment causes the framework title to highlight in green twice.

This also requires additional testing with another person.

**Comment by eddavies** [comment]
Testing with an additional person was successful. The only issue that is super minor, is that when one user makes a change to a competency it closes the edit panel, so if both go to save their changes at the same time, then one user is likely to click on the create new competency icon since the save icon will disappear before the user can notice the difference. (super minor)

**Comment by eddavies** [comment]
fix verified on both accounts
