### ISSUE TITLE
Attempt to reorder competencies fails in Firefox

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#289]
@Lomilar 
Using Firefox, in the test server, I edited a framework, and then tried to drag a competency to a new parent.
I get the following message:
![image](https://user-images.githubusercontent.com/26332112/40446245-2f522d56-5e94-11e8-9042-2a834613cff8.png)

**Comment by eddavies** [comment]
fix verified, but found other issues while using firefox
