### ISSUE TITLE
When adding a competency for the first time, change the name field to an autosuggest that replaces the just-added competency with an existing competency.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#29]

**Comment by miledivovic** [comment]
![capture](https://user-images.githubusercontent.com/14066647/33143322-62a64a62-cf6e-11e7-8731-d8b72bafaf15.PNG)

Is this what you had in mind?

**Comment by Lomilar** [comment]
Yes, wicked.

The use cases around selecting an existing thing are pretty peculiar.

- Should I replace the entire competency with the one I select? (Copy/Link question comes into play)
- Should I just copy the name?
- Should I create an equivalence relationship?

**Comment by eddavies** [comment]
Tested, seems to be working.

**Comment by Lomilar** [comment]
I'd like to see this reuse the id of the item selected and update the relationship it just created (if any) upon selection of an autocorrect entry.

**Comment by Lomilar** [comment]
This popup occurs on any edit of a competency, not just the first edit. It may only make sense on the first edit. Open to discussion.

**Comment by eddavies** [comment]
This functionality does not work when trying to add from the framework head, is this intentional?

**Comment by Lomilar** [comment]
If it happens when you do a normal edit, it's an inversion bug (where something happens exactly when you don't want it to, just a flipped boolean flag)

**Comment by eddavies** [comment]
Indeed it happens when doing a normal edit.

**Comment by miledivovic** [comment]
Pretty sure that doesn't work for the same reason it doesn't work when you try to shift+drag and drop or shift+X to the framework head

**Comment by miledivovic** [comment]
Added in b268ed3 : should only have autocomplete dropdown when you first create a new competency.

**Comment by Lomilar** [comment]
Only seems to search for competencies in this framework.

**Comment by Lomilar** [comment]
Now searches across the server.
