### ISSUE TITLE
Create ability to highlight competencies in a framework from the iframe parent.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#290]
Something that, when it receives a message, will highlight a competency with the @id specified.

**Comment by Lomilar** [comment]
@siuc-nate @cwd-mparsons @stuartasutton

**Comment by Lomilar** [comment]
https://cass.credentialengine.org/cass-editor/index.html?server=https://cass.credentialengine.org/&ceasnDataFields=true&css=https://credentialengine.org/publisher/Style/CassStyles&view=true&frameworkId=https://cass.credentialengine.org/api/custom/data/520df58161933997ff8a59f937f2dcb3

Currently, this is what we got.

**Comment by Lomilar** [comment]
http://explore.dublincore.net/learning_resource/multi-agent-and-semantic-web-systems-rdf-data-structures/ - Inspiration

**Comment by cwd-mparsons** [comment]
@Lomilar In your sample above, the frameworkId ends with: 520df58161933997ff8a59f937f2dcb3.
This identifier is not from the actual framework URI, which is: 
https://credentialengineregistry.org/resources/ce-df57a532-4931-4233-92dd-94ce5ada89ca

I wanted to do some prototyping with displaying a framework, but don't see how to get the correct frameworkId

**Comment by miledivovic** [comment]
{"message":"highlighted", "highlightTarget":"someID"}

**Comment by eddavies** [comment]
Seems to be working
