### ISSUE TITLE
Firefox: possible to make competencies disappear and reappear

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#294]
This is a minor issue, since saving a competency makes them reappear.
Steps:
1. Create new framework
2. Create new competency
3. save the competency then immediately create another competency
Then this occurs:

![new competencies dissapeared](https://user-images.githubusercontent.com/23706850/40853999-ccaa305c-6584-11e8-844c-88057f35cc3f.PNG)

**Comment by chinhseah** [comment]
@eddavies @miledivovic I think I understand issue is that after adding 1st competency and then clicking on "+" (plus sign) to add 2nd competency, listing on left-hand-side of 1st competency "disappeared". Correct?  
So after adding 1st competency, I saw it listed on left-hand-side.
![ce-issue294_1](https://user-images.githubusercontent.com/15805943/40997064-512d8596-68b8-11e8-891d-af7f1ef4420d.JPG)

But only after saving 2nd competency, do I see competencies listed on left-hand-side again.

![ce-issue294_3](https://user-images.githubusercontent.com/15805943/40997136-86290c8e-68b8-11e8-8f62-acaf3eaf23d6.JPG)

**Comment by eddavies** [comment]
The issue i found, was that you could not see either competency framework on the left side after creating two competencies back to back.
so this:
![save1](https://user-images.githubusercontent.com/23706850/41000353-969cee64-68c2-11e8-9073-e502619aa2b7.PNG)
Then creating another competency after it results in this:
![save](https://user-images.githubusercontent.com/23706850/41000368-9f4ff3b2-68c2-11e8-9a13-45152bda2697.PNG)

**Comment by chinhseah** [comment]
@eddavies With recent fixes applied, I tried to re-produce this issue this morning but could not. Could you please try testing out in your Firefox browser and let me know if you still see this issue? Thanks.

**Comment by eddavies** [comment]
I can't seem to make this happen anymore either. Closing this for now.
