### ISSUE TITLE
Firefox: search for concept levels is blank

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#295]
![no conepts appearing](https://user-images.githubusercontent.com/23706850/40854192-7f1363d0-6585-11e8-9092-23579a5148dc.PNG)

**Comment by chinhseah** [comment]
@eddavies I just tried search using Firefox browsers and I got results back (see attached screen capture) so could you please try this search again. Thanks.
![cass-editor-search-concept-level-firefox](https://user-images.githubusercontent.com/15805943/46167182-f5615d00-c249-11e8-87b6-8a64e452022c.PNG)

**Comment by eddavies** [comment]
Bug is no longer occurring.
