### ISSUE TITLE
Keyboard controls need work

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#297]
I'm doing a full test right now utilizing keybaord controls. On http://ctitest.siuccwd.com/competencies, they are barely functional. In a framework I created I cannot use the arrow keys to select the different competencies. Additionally discovered #296.

They are not intuitive either. No user will ever use the keyboard controls since they'd have to learn how to tab select objects and fields in a non-intuitive manner.

**Comment by Lomilar** [comment]
@siuc-nate Have we resolved all the cross domain issues that may be preventing keydown/keyup/keypress from passing into the iframe? I remember this was more prominent on testing than prod.

**Comment by siuc-nate** [comment]
Is there a good place/way to test this?

**Comment by Lomilar** [comment]
@eddavies probably has better repro steps, but...

 - Go to ctitest URL, open Developer Tools.
 - Open framework using mouse click.
 - use arrow keys to attempt to move around, see cross domain errors appear in Developer Tools Console.

**Comment by Lomilar** [comment]
Best way to resolve them: iframe should point at https://ce.../publisher/cass-editor -- Same domain resolves most issues.

https://stackoverflow.com/questions/25995337/listen-for-keydown-events-in-iframe-with-cross-domain explains why cross domain keyboard events aren't allowed.

**Comment by Lomilar** [comment]
All that remains is 
https://github.com/CredentialEngine/CompetencyFrameworks/issues/88
