### ISSUE TITLE
Need tooltips for connections in the concept editor

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#301]

**Comment by miledivovic** [comment]
@stuartasutton Do you know where the definitions for these are listed? Broad Match, Exact Match etc.

**Comment by stuartasutton** [comment]
Yes, the definitions can be found here: http://credreg.net/ctdlasn/terms#properties

If you have the means, there are related figures:

1. broadAlignment
![broad_alignment](https://user-images.githubusercontent.com/2939046/41556431-93995f4a-72ef-11e8-8a06-3fb034f12619.jpg)

2. exactAlignment
![exact_alignment](https://user-images.githubusercontent.com/2939046/41556480-c35601b6-72ef-11e8-8340-4b4482034c8d.jpg)

3. majorAlignment
![major_alignment](https://user-images.githubusercontent.com/2939046/41556525-e7c9e2d8-72ef-11e8-84ed-78f57a2a56d1.jpg)

4. minorAlignment
![minor_alignment](https://user-images.githubusercontent.com/2939046/41556562-072e00e6-72f0-11e8-9825-ac53c31e41a7.jpg)

5. narrowAlignment
![narrow_alignment](https://user-images.githubusercontent.com/2939046/41556607-2559a1d8-72f0-11e8-8572-3917eb5e7715.jpg)

**Comment by stuartasutton** [comment]
@eddavies, note that it is not  "match", but rather "alignment". And, "Alignment" in the labels is singular and not plural.

**Comment by eddavies** [comment]
fix verified

**Comment by stuartasutton** [comment]
@eddavies, my mistake! I somehow through these were competency properties. So, DISREGARD the above. SKOS for concepts does not actually define `broader` and `narrower` other than through rich tradition. So, here are the definitions to use:

**broader:** "A concept that is broader than the concept being described."
**narrower:** "A concept that is narrower than the concept being described."

**Comment by miledivovic** [comment]
Thanks @stuartasutton , are these satisfactory definitions for the concept alignments?

Broad Match: A concept that is broader than the concept being described.
Close Match: Another concept which has major relevance or overlap with this concept.
Exact Match: Represents same capability in all aspects to another concept.
Narrow Match: A concept that is narrower than the concept being described.
Related Match: This concept has some degree of overlap with another concept.

**Comment by stuartasutton** [comment]
@miledivovic, please, let's go with these:

>closeMatch:
A concept in a different concept scheme that is sufficiently equivalent that it can be used interchangeably for this concept.

>exactMatch:
A concept in a different concept scheme that can be used interchangeably for this concept with a high degree of confidence.

>broadMatch:
A concept in a different concept scheme that is hierarchically broader than this concept.

>narrowMatch:
A concept in a different concept scheme that is hierarchically narrower than this concept.

>relatedMatch:
A concept in a different concept scheme that is conceptually related but is neither a hierarchical or equivalence relationships.

**Comment by eddavies** [comment]
fix verified
