### ISSUE TITLE
Popout window persists through pages

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#308]
![persisting window](https://user-images.githubusercontent.com/23706850/41559308-83a0d510-72f8-11e8-8962-99b8a3e54aab.PNG)
To cause this, search and attempt to add existing competencies. When the popout window appears, click on the back button. What should happen is either the window disappears or the back button is disabled when the popout appears.

**Comment by eddavies** [comment]
These options persist through any page you access and are still functional even when editing a separate framework.

**Comment by miledivovic** [comment]
This should be fixed by the same thing as #307

**Comment by eddavies** [comment]
Fix verified
