### ISSUE TITLE
A publisher name that includes a comma, gets split into multiple properties on export

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#309]
In production, we had an error on attempting to publish a framework. 
![image](https://user-images.githubusercontent.com/26332112/41601491-3c4d0a3e-739e-11e8-85b6-609eceb3c2f2.png)

The publisher name was: 

> Illinois CertifiedDomestic Violence Professionals, Inc

On export as Credential Engine ASN (the format for publishing), the publisher is output in the format like keywords: 
![image](https://user-images.githubusercontent.com/26332112/41601597-7e512000-739e-11e8-916c-03a86cf17fc9.png)

If the comma is removed, then the framework is published successfully.

This property needs to be able to handle embedded commas, and not arbitrarily split into separate entries. There seems to be inconsistency in export format, but I added a separate issue to allow for independent handling (#310 ).

**Comment by eddavies** [comment]
@miledivovic So we could do a temporary fix by separating entities with a ";" instead of a comma, but we probably should make some enhancement changes to the ui to allow the addition of entities in all data fields for the long term.

**Comment by eddavies** [comment]
Clicking the "+" sign properly adds an extra field for publisher name, but users should be able to close extra fields they make.

**Comment by eddavies** [comment]
So creating a framework wit multiple publisher names and then deleting it and creating a new framework shows the extra fields under publisher name without having to click on the "+" icon.

**Comment by eddavies** [comment]
This no longer occurs for publisher names. However the tooltip needs to be changed to account for the "+" button. 
Should we make this the defacto way of adding all additional fields?

**Comment by stuartasutton** [comment]
I'd prefer that the "+" button were the defacto way of adding addition instances of a property (including the others notes as "Repeat" on the [spreadsheet](https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803).

**Comment by eddavies** [comment]
Closing this and opening new issue #335
