### ISSUE TITLE
Export of publisher name and keywords is incorrect

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#310]
related to issue #309 
Publishername is defined as list of language strings. If there is one publisher name (and no embedded commas), the output is an array of language objects, consisting of a language and a string:
![image](https://user-images.githubusercontent.com/26332112/41603364-717c3f3c-73a2-11e8-8e60-97b6c8bb69d2.png)

If the publisher name has embedded commas, or for multiple publishers:
**A test publisher, with commas in the name, INC**
Then publisher name is exported as an array of objects consisting of a language string and an array of strings:
![image](https://user-images.githubusercontent.com/26332112/41603549-d31e24da-73a2-11e8-9643-8e4be68c5478.png)

The latter currently fails, as the JSON-LD verification (in the Registry API) is expecting an array of language : string. 
If this is to always be an array of language plus array, then the API will be updated. However, if the latter is true, then a publisher name with a single value should also be exported as an array of language arrays.

**Comment by siuc-nate** [comment]
Per the [implementation document](https://docs.google.com/document/d/1rCEEMD4eKPpVPANsz_zOOPQ70otJzuFEecMUtzynHrc/edit#heading=h.9pkz013ipek0) and the spec, the "ceasn:publisherName" (and any other langstring properties) should be an object at the base level, not an array.  

In other words, it should look like this:
```
"ceasn:publisherName": {
  "en-us": [ "name one", "name two" ]
}
```

**Comment by cwd-mparsons** [comment]
@eddavies @Lomilar 
If there are multiple publisher names, then the export is correct. 
![image](https://user-images.githubusercontent.com/26332112/42848387-eb31838e-89e4-11e8-8069-641b4cbd1ee3.png)

However, if there is only one publisher name, it is incorrect - even if there is only one item, it still must be published as a list:
![image](https://user-images.githubusercontent.com/26332112/42848429-19aa8a3a-89e5-11e8-891c-96db222d4ed5.png)

**Comment by cwd-mparsons** [comment]
The export of the publisher name has now gone back to the original problem, being output as an array of objects!

![image](https://user-images.githubusercontent.com/26332112/43544043-6c1e3dd0-9597-11e8-9724-8a00ae9a2619.png)

**Comment by Lomilar** [comment]
^ This is on production. On Test:

![image](https://user-images.githubusercontent.com/337692/43544381-962ee1de-9587-11e8-8315-cd356a655d7a.png)

![image](https://user-images.githubusercontent.com/337692/43544422-ae69de66-9587-11e8-9e1e-7072f40e0bc4.png)

In ^ -- The publisher name needs to be in an array of one.

**Comment by siuc-nate** [comment]
To avoid confusion, the above is true, but **only** because publisherName is considered multi-value.  Single-value fields like name and description would still just be strings, i.e.

```
{
  "ceasn:name": {
    "en-us": "My name"
  },
  "ceasn:publisherName": {
    "en-us": [ "Name of the publisher" ]
  }
}
```

**Comment by cwd-mparsons** [comment]
@Lomilar What is the status or priority for this fix?
Frameworks with a single values for any of Publisher Name, conceptKeyword, or localSubject will fail.

**Comment by cwd-mparsons** [comment]
Production example:
CCO Service Truck Crane Operator Practical Exam
https://cass.credentialengine.org/api/ceasn/844440e5fba4b5b1f9c78cc1a67d2351

**Comment by Lomilar** [comment]
@cwd-mparsons Reopen if needed.
