### ISSUE TITLE
Conceive method of highlighting competencies via url parameters.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#311]
(that are linked by a credential for instance)

**Comment by Lomilar** [comment]
@siuc-nate @miledivovic @cwd-mparsons

**Comment by Lomilar** [comment]
When using the CASS Editor in view mode, folks would like to be able to have a number of competencies within a framework highlighted for emphasis.

URL Parameter and postMessage form would be ideal.

**Comment by miledivovic** [comment]
For the URL parameter method we can use:
 `?highlightedCompetencies=(EncodedArrayOfCompetencyIDs)`
where
`(EncodedArrayOfCompetencyIDs)`
is equal to
`encodeURIComponent(JSON.stringify(["competencyID", "competencyID"]))`

For the postMessage method we can use the following format: `{"message":"highlightedCompetencies", "competencies":["competencyID", "competencyID"]}`

**Comment by Lomilar** [comment]
@miledivovic:

URL parameters can be multiply defined:

http://foo.bar/index.html?foo=bar&foo=doo is perfectly valid, and the preferred way of encoding arrays in URL form.

Further, curly braces, brackets, etc, in URLs are being waged war on. See [here](https://productforums.google.com/forum/#!topic/chrome/AdUZ6ABikb8).

It's only a matter of time before they go after square brackets.

**Comment by Lomilar** [comment]
@woodkri Can you create a webpage that allows this feature to be tested, in a similar fashion to /demos/add-button.html?

**Comment by siuc-nate** [comment]
Is there a settled syntax for the GET parameters? I tried all of these with no luck (with just one competency for simplicity):

Singular, unencoded
https://cassproject.github.io/cass-editor/index.html?highlightedCompetency=https://sandbox.credentialengineregistry.org/resources/ce-42f4e6f2-f646-4203-a906-b215372ccbeb

Plural, unencoded
https://cassproject.github.io/cass-editor/index.html?highlightedCompetencies=https://sandbox.credentialengineregistry.org/resources/ce-42f4e6f2-f646-4203-a906-b215372ccbeb

Singular, encoded
https://cassproject.github.io/cass-editor/index.html?highlightedCompetency=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-42f4e6f2-f646-4203-a906-b215372ccbeb

Plural, encoded
https://cassproject.github.io/cass-editor/index.html?highlightedCompetencies=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-42f4e6f2-f646-4203-a906-b215372ccbeb

Single, encoded, using the parameters for the test server's CASS iframe
https://cassproject.github.io/cass-editor/index.html?link=true&newObjectEndpoint=https://staging.credentialengineregistry.org/resources/ce-&server=https://dev.cassproject.org/api/&ceasnDataFields=true&origin=http://ctitest.siuccwd.com&css=https://credentialengine.org/publisher/style/cassstyles&highlightedCompetency=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-42f4e6f2-f646-4203-a906-b215372ccbeb

Plural, encoded, using the parameters for the test server's CASS iframe
https://cassproject.github.io/cass-editor/index.html?link=true&newObjectEndpoint=https://staging.credentialengineregistry.org/resources/ce-&server=https://dev.cassproject.org/api/&ceasnDataFields=true&origin=http://ctitest.siuccwd.com&css=https://credentialengine.org/publisher/style/cassstyles&highlightedCompetencies=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-42f4e6f2-f646-4203-a906-b215372ccbeb

**Comment by Lomilar** [comment]
@siuc-nate https://cassproject.github.io/cass-editor/demos/highlight-competencies.html

That will demonstrate it. View the source of that HTML page. I'll also update the readme.md

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor#highlighting-one-or-more-specific-competencies

**Comment by siuc-nate** [comment]
Thanks. I'll pass this along to the person on our team who is implementing it.

**Comment by eddavies** [comment]
This seems to be working. Feel free to reopen if unresolved.
