### ISSUE TITLE
Create method that moves things to CER urls as soon as they touch the cass-editor.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#313]

**Comment by Lomilar** [comment]
Todo: Create diagram that shows initial method chosen per call 11/16/2018.

**Comment by Lomilar** [comment]
Initial method chosen is "The moment of publication" per call Nov 14. OK to proceed.

**Comment by siuc-nate** [comment]
@Lomilar 
Can you verify that this is solved? It appeared to properly align to the old URIs when we uploaded the DQP framework.

**Comment by Lomilar** [comment]
URIs are changed to CER URIs at the moment of publication. Those URIs are derived from:

The base CER endpoint plus the first of these that works...
* The existing CTID if available, extracted from the @id.
* A UUID if available and extractable from the @id.
* The UUID3 hash of the @id.

So yes, things should magically align because of the deterministic nature shown here. We also do all imports without generating new URIs (unless an ID is not provided at all).

**Comment by Lomilar** [comment]
This seems to be operating (except for some ce-ce- repetition).
