### ISSUE TITLE
Export of conceptKeyword is incorrect

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#314]
The format of the export of conceptKeyword is incorrect. This is the same issue as for the publisher name (#310 )
![image](https://user-images.githubusercontent.com/26332112/41693058-238d951e-74c9-11e8-808c-bb36efcd987c.png)
Instead, it should be like:
"ceasn:conceptKeyword":   {
            "en-us": [              "keyword 1",              "keyword 2"            ]
}

**Comment by eddavies** [comment]
Still running into this:
![conceptkeyword](https://user-images.githubusercontent.com/23706850/42465012-a7106962-835f-11e8-974b-c9aa06a36c69.PNG)

**Comment by eddavies** [comment]
fix verified
