### ISSUE TITLE
Add Framework Search Result Tag if the name of the author can be retrieved.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#315]
CredentialEngine/CompetencyFrameworks#63

Limit to CEASN mode for now.

**Comment by siuc-nate** [comment]
Per @stuartasutton in [this post](https://github.com/CredentialEngine/CompetencyFrameworks/issues/63#issuecomment-400092456), this should probably follow this order of preference:

- PublisherName
- Publisher (retrieved)
- Author (retrieved)

**Comment by stuartasutton** [comment]
Agreed.

**Comment by eddavies** [comment]
When searching for additional competencies to copy/link from, these tags do not appear

**Comment by eddavies** [comment]
Publisher name is appearing, but I'm not seeing publisher or creator (uri resolved to a name) when there is no publisher name

**Comment by eddavies** [comment]
I think what happened was that I switched back to the framework view before the uri finished resolving into the name.

**Comment by eddavies** [comment]
Bug fixed. Tags display on test. Closing this, feel free to reopen if any issues concerning this arise.
