### ISSUE TITLE
CTDL-ASN export missing hasTopChild and isTopChildOf properties

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#318]
See https://cass.credentialengine.org/api/ceasn/6693b0935fefead79e0fb23bca670623

There should be both `ceasn:hasTopChild` and `ceasn:isTopChildOf` properties in the framework and competency objects, respectively.

**Comment by miledivovic** [comment]
@Lomilar I'm not seeing any reason why this shouldn't be working https://github.com/cassproject/CASS/blob/master/src/main/resources/c-adapter/ceasn/ceasn.js#L198

**Comment by siuc-nate** [comment]
This is javascript, right? The only thing that jumps to mind would be if the value of `c["ceasn:isChildOf"]` on line 197 is `undefined` instead of `null` when it's checked, which would cause that block to get skipped. But that's a shot in the dark.

**Comment by Lomilar** [comment]
I don't believe this is deployed. Will look into.

**Comment by Lomilar** [comment]
Using @list containers means the JSON-LD processor no longer translates it correctly. Will need to shift to using @list containers in the export.

**Comment by stuartasutton** [comment]
Please note that hasChild is not also present in the json output. The only property providing hierarchical glue that is working is isChildOf.

**Comment by Lomilar** [comment]
@stuartasutton @siuc-nate @cwd-mparsons  You are aware that the export for those properties (and the validation must) now look like:

https://json-ld.org/spec/latest/json-ld/#sets-and-lists

```json
"ceasn:hasTopChild": {
  "@list":[
	"https://credentialengineregistry.org/resources/ce-1dd0d004-7d4c-4ec1-a708-d3cc22263e59",
	"https://credentialengineregistry.org/resources/ce-b1e0eca2-7a19-49e9-8841-fa16ddf8396d",
	"https://credentialengineregistry.org/resources/ce-55e78ee7-5620-4628-9aee-697148918d68",
	"https://credentialengineregistry.org/resources/ce-72d9f26d-2c5d-4e58-9257-21bfdfba7af9",
	"https://credentialengineregistry.org/resources/ce-4e355050-9fb5-4426-a881-8d7742b972f7",
	"https://credentialengineregistry.org/resources/ce-045b8b50-0f7d-40cf-82af-2335a06c9de1",
	"https://credentialengineregistry.org/resources/ce-8d18d1a9-2753-43a5-b1d1-93569bdb5c3e",
	"https://credentialengineregistry.org/resources/ce-45d9ac18-395b-4253-bcaf-3ebdc6c7e613",
	"https://credentialengineregistry.org/resources/ce-4b1d47f5-284a-43c7-8035-796d873773d5",
	"https://credentialengineregistry.org/resources/ce-97a9adc9-5dd0-41eb-aff7-0e56bc5d05c1",
	"https://credentialengineregistry.org/resources/ce-5e67543f-9780-4b3b-8e04-8b5ffd9b6e95",
	"https://credentialengineregistry.org/resources/ce-c8c091d0-9162-40a7-9870-d492b8277d40",
	"https://credentialengineregistry.org/resources/ce-15564e24-4986-48cc-8719-ba9943dd123c",
	"https://credentialengineregistry.org/resources/ce-00fe1232-c635-49f5-85bc-1307060a2b8b",
	"https://credentialengineregistry.org/resources/ce-a7250858-c08f-444b-9f7f-4d980ce6d7e6"
  ]
}
```

**Comment by Lomilar** [comment]
I may be incorrect here. While the above is the recommended expanded form, it seems like JSON-LD doesn't mind a typical array there instead. In fact, it compacts down to just an array and not not a {@list:[]}.

See https://dev.cassproject.org/api/ceasn/schema.cassproject.org.0.3.Framework/d1d3f8a5-9687-4e48-92f9-3b0138be66aa

**Comment by Lomilar** [comment]
Is there any preference on the form? I haven't found a JSON-LD processor that cares either way so far.

**Comment by stuartasutton** [comment]
I think I may be confused. JSON arrays are ordered lists; but, by default, JSON-LD lists are not ordered (to comport with arrays in RDF). To have an array be an ordered list, it needs the @list. I may be missing the point.

**Comment by Lomilar** [comment]
You're not, though based on my experiments I'd restate what you said a bit differently.

JSON-LD lists are ordered, though to comport with arrays in RDF they are treated as unordered. To have a JSON-LD array be treated as ordered by RDF (including JSON-LD processors), it needs the "@container":"@list" defined in the context.

From the JSON-LD Spec:
```
EXAMPLE 51: An ordered collection of values in JSON-LD
{
  ...
  "@id": "http://example.org/people#joebob",
  "foaf:nick": {
    "@list": [ "joe", "bob", "jaybee" ]
  },
  ...
}
```
This describes the use of this array as being ordered, and order is maintained when processing a document. **If every use of a given multi-valued property is a list, this may be abbreviated by setting @container to @list in the context**:

Which we did.

**Comment by Lomilar** [comment]
And to answer your other question, it does appear we get ordered lists. (see the bottom of the list of nquads below)

https://json-ld.org/playground/#startTab=tab-nquads&json-ld=https%3A%2F%2Fdev.cassproject.org%2Fapi%2Fceasn%2Fschema.cassproject.org.0.3.Framework%2Fd1d3f8a5-9687-4e48-92f9-3b0138be66aa

**Comment by siuc-nate** [comment]
My understanding was we were going with the approach shown in example 52 under https://json-ld.org/spec/latest/json-ld/#sets-and-lists

```
{
  "@context": {
    ...
    "nick": {
      "@id": "http://xmlns.com/foaf/0.1/nick",
      "@container": "@list"
    }
  },
  ...
  "@id": "http://example.org/people#joebob",
  "nick": [ "joe", "bob", "jaybee" ],
  ...
}
```
or, for us:
```
{
  "@context": {
    "ceasn:hasChild": {
      "@type": "@id",
      "@container": "@list"
    },
    "ceasn:hasTopChild": {
      "@type": "@id",
      "@container": "@list"
    },
  },
  "ceasn:hasTopChild": [
	"https://credentialengineregistry.org/resources/ce-1dd0d004-7d4c-4ec1-a708-d3cc22263e59",
	"https://credentialengineregistry.org/resources/ce-b1e0eca2-7a19-49e9-8841-fa16ddf8396d",
	"https://credentialengineregistry.org/resources/ce-55e78ee7-5620-4628-9aee-697148918d68",
	"https://credentialengineregistry.org/resources/ce-72d9f26d-2c5d-4e58-9257-21bfdfba7af9",
	"https://credentialengineregistry.org/resources/ce-4e355050-9fb5-4426-a881-8d7742b972f7",
	"https://credentialengineregistry.org/resources/ce-045b8b50-0f7d-40cf-82af-2335a06c9de1",
	"https://credentialengineregistry.org/resources/ce-8d18d1a9-2753-43a5-b1d1-93569bdb5c3e",
	"https://credentialengineregistry.org/resources/ce-45d9ac18-395b-4253-bcaf-3ebdc6c7e613",
	"https://credentialengineregistry.org/resources/ce-4b1d47f5-284a-43c7-8035-796d873773d5",
	"https://credentialengineregistry.org/resources/ce-97a9adc9-5dd0-41eb-aff7-0e56bc5d05c1",
	"https://credentialengineregistry.org/resources/ce-5e67543f-9780-4b3b-8e04-8b5ffd9b6e95",
	"https://credentialengineregistry.org/resources/ce-c8c091d0-9162-40a7-9870-d492b8277d40",
	"https://credentialengineregistry.org/resources/ce-15564e24-4986-48cc-8719-ba9943dd123c",
	"https://credentialengineregistry.org/resources/ce-00fe1232-c635-49f5-85bc-1307060a2b8b",
	"https://credentialengineregistry.org/resources/ce-a7250858-c08f-444b-9f7f-4d980ce6d7e6"
  ]
}
```

**Comment by stuartasutton** [comment]
Yes..

**Comment by Lomilar** [comment]
Sounds right. That's what we are emitting on test.
https://dev.cassproject.org/api/ceasn/schema.cassproject.org.0.3.Framework/d1d3f8a5-9687-4e48-92f9-3b0138be66aa/1530127220192

**Comment by eddavies** [comment]
Seems to be exporting hasTopChild and isTopChildof.
