### ISSUE TITLE
Imports and Registrations.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#32]
Import formats are required for:
- ASN
- MedBiq
- CEASN?

These should be imports, not registrations. (and the difference between the two should be made clear)

Registration formats should be brought in for:
- CASE
- ASN (as exists in the wild)?

**Comment by Lomilar** [comment]
Depends on eduworks/ec#2.

**Comment by Lomilar** [comment]
Also need import for CTDL+ASN.

**Comment by Lomilar** [comment]
0857b166794b7c82599db719296f5aae48bc60a0 and 85a6c05fcca5f1b9ffb6b90ba232ff7a60c53812 brought in MedBiq, ASN import.

**Comment by Lomilar** [comment]
ASN and MedBiq import need to be less lossy.

**Comment by Lomilar** [comment]
@stuartasutton

In light of our conversations, I'm considering the following:

Because (in CASS):
- Registered data is not editable
- Registered data is not owned
- Imported data has different uri/urls
- Imported data is owned

It appears functionally equivalent for:
- Import to be executed by first registering the original data, then copying the framework.

Example:
1. I want to use http://asn.jesandco.org/resources/D10003E9.xml and align credentials to that framework.
1. I register that framework.
1. I associate my credentials with that framework.

Example 2:
1. I want to modify http://asn.jesandco.org/resources/D10003E9.xml for my state, and then align credentials to that framework.
1. I register that framework.
1. I copy that framework.
1. I associate my credentials with the copied framework.

Example 3:
1. I want to create <bespoke framework> for my purpose, and then align credentials to that framework.
1. I import <bespoke framework> from CSV or create it in the editor.
1. I associate my credentials with the copied framework.

Can you find any flaws in this reasoning?

**Comment by stuartasutton** [comment]
Hopefully we can talk this through on today's call...to make sure I am understanding "register", "import" and "own". I want to make sure I understand the exact technical outcome within CASS of "registering"--e.g., is it equivalent technically to a straight cloning (exact, local replica)?

**Comment by stuartasutton** [comment]
...also add a definition of "associate" to the list for definition and discussion.

**Comment by Lomilar** [comment]
For now, to correct terminology: 
Registered -> Carbon Copied or Cloned. This keeps the data unchanged but may involve changing the format and schema.
Import involves more than CCing or Cloning. This includes changing URLs to be internally consistent, changing data, etc.

**Comment by Lomilar** [comment]
Use case:
* I am a state education board who has published a new framework on Computer Science using a system that isn't CE. 
* This framework contains non-CE URLs, non-CE fields and is represented in the wild in a non-CTDL schema. 
* Existing educational resources align with my existing URLs, so I am not permitted to change the URLs, but I would still like to make it discoverable in the CE.
* I would like to use CASS to change the schema and format to a CE compatible format and make this framework discoverable in the CE, without changing any of the data.
* I additionally have credentials that I would like to associate with the canonical URLs.

**Comment by stuartasutton** [comment]
Use case #2:

1. I am a state education board who has published a new framework on Computer Science using a system that isn't CE.
2. This framework contains non-CE URLs, non-CE fields and is represented in the wild in a non-CTDL schema.
3. Existing educational resources align with my existing URLs, so I am not permitted to change the URLs, but I would still like to make it discoverable in the CE.
4. I would like to use CASS to **retain the schema and format and nevertheless** make this framework discoverable in the CE, without changing any of the data.
5. I additionally have credentials that I would like to associate with the canonical URLs.

Policy and technical constraints may determine that case #2 cannot or will not be accommodated in the CER.

**Comment by Lomilar** [comment]
This issue has largely been concluded. Spinning off #184.
