### ISSUE TITLE
Improve guidance of allowed file formats, schemas, and endpoints on "Import Framework" screen

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#320]
The current information is very minimal and not user-friendly.  A typical user is unlikely to know what any of the data means:
![image](https://user-images.githubusercontent.com/21346519/41876068-46678c44-7892-11e8-9c90-483d487608e0.png)

Suggestions:
- Use a single table or display mechanism to indicate the allowed things (currently two tables)
- Add links to the schemas and a brief description/summary of each

**Comment by eddavies** [comment]
fix verified
