### ISSUE TITLE
Enable the user to download a template CSV file for each of the allowed types on the "Import Framework" screen

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#321]
This will help the user provide correct data, and should work similarly to the Bulk Upload tool for credentials.  This would essentially be an export of a blank/empty framework (or, more usefully, one with predetermined sample data for each field).

**Comment by siuc-nate** [comment]
@stuartasutton @jkitchensSIUC @cwd-mparsons We will need to determine which properties are appropriate to include in such a template when it comes to CTDL-ASN, so as not to confuse users.

**Comment by Lomilar** [comment]
Related to #160.

Medbiq and ASN are not spreadsheet based formats.

**Comment by Lomilar** [comment]
See https://credentialengine.org/publisher/BulkUpload for inspiration.

**Comment by eddavies** [comment]
I'm getting stuck on this for the CaSS sample csv with it's relation import:
<img width="917" alt="importing cass samples" src="https://user-images.githubusercontent.com/23706850/46429912-731ae200-c6fc-11e8-84c6-39097ea7bc61.PNG">

**Comment by eddavies** [comment]
Everything else is working

**Comment by eddavies** [comment]
The CaSS sample csv actually imported as I can see it on the framework list. Just the swirl never disappeared during the import process.

**Comment by woodkri** [comment]
I haven't been able to reproduce this.

**Comment by eddavies** [comment]
I cannot reproduce this anymore, may have been fixed by previous import changes
