### ISSUE TITLE
Make prerequisiteAlignment property a field that supports both direct entry of a URI or search.

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#325]
With the competency alignment properties, is it possible to support **both** direct text entry of a resource URI **or** search? While most of the array of "alignment" properties with competencies are for 3rd party assertions, the [prerequisiteAlignment](http://purl.org/ctdlasn/terms/prerequisiteAlignment) can reference a node in the same framework or a different framework. So, instead of just supporting search, we need to **also** provide for direct entry of a URI copied from another node in the same framework.  Also, I remain deeply concerned that search is limited to the CER and many such relationships will be to resources that are not in the Registry; thus, the ability to grab a URI elsewhere and insert it into one of these alignment fields is necessary.

**Comment by Lomilar** [comment]
Agreed.

Should be covered as part of #195

**Comment by stuartasutton** [comment]
Yes, @miledivovic, every alignment property should allow for both search (within registry) and direct entry of a URI (from outside registry).

**Comment by eddavies** [comment]
Closing this, for this is covered in #195.
