### ISSUE TITLE
isChildOf detection throws exception.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#328]
https://credentialengine.org/publisher/competencies

View Framework "CCO Mobile Crane Inspector Specialty Examination"

```
cass-editor.js:98367 Uncaught TypeError: Cannot read property 'shortId' of null
    at renderSidebar (cass-editor.js:98367)
    at afterSaveRender (cass-editor.js:97021)
    at XMLHttpRequest.xhr.onreadystatechange (cass-editor.js:35260)
renderSidebar @ cass-editor.js:98367
afterSaveRender @ cass-editor.js:97021
```

Make sure prereq alignments exist for "Have specific knowledge of cranes and crane types"

**Comment by eddavies** [comment]
This may be related. Was testing alignments and had a slight internet hickup. Refreshed and attempted to make a broaden align
<img width="947" alt="alignment disappeared" src="https://user-images.githubusercontent.com/23706850/42187923-b081640a-7e06-11e8-9589-2543a56e5017.PNG">
ment and the add button did not appear.

**Comment by eddavies** [comment]
attempting to reproduce the above

**Comment by Lomilar** [comment]
Main issue is Fixed. Create issue for new found issue and close?

**Comment by eddavies** [comment]
New issue #339
