### ISSUE TITLE
When a competency is added, it is not selected in the left panel.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#33]

**Comment by miledivovic** [comment]
Fixed in 42a572e

**Comment by eddavies** [comment]
Fix verified. However a minor quality of life change could be that when adding a competency to a large framework, the left panel scrolls down to where the competency is being placed instead of it being off screen if the framework is longer than the browser window.

**Comment by Lomilar** [comment]
Fixed in 2f7a12d.

**Comment by eddavies** [comment]
fix rejected, the window scrolls down to the new competency for less than a second then goes back to the top of the framework like before.

**Comment by Lomilar** [comment]
Repro steps?

**Comment by Lomilar** [comment]
When saving a competency, it pops to the top of the framework.

**Comment by eddavies** [comment]
Ah apparently isn't happening anymore, I might've needed to just restart/refresh things, my bad.

fix verified
