### ISSUE TITLE
Upload of DQP and test of URI swapping

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#333]
@Lomilar, @siuc-nate, & @jkitchensSIUC:

I have uploaded a ceasn competency framework json-ld file to a [DQP folder](https://drive.google.com/drive/folders/1zZCdH6Tvvkojfyn4qfuJHOtE97yTSmBS) for Degree Qualification Framework that has DQP URIs that resolve to data on its own server. This should be our test file for  handling URI swapping and referencing per issue https://github.com/CredentialEngine/CompetencyFrameworks/issues/61. So, when this file is ingested:

1. The DQP URIs are swapped for CER URIs for the CER; and
2. A reference added to each node in the CER version that point back to the original DQP URI on the DQP website using the skos:exactMatch.

**Note:** The DQP file does not have reciprocal CER skos:exactMatch statements. **Consider handing back to DQP their original file with the skos statements to CER added.** Then, if they choose to switch the returned file for their own, applications can see that the DQP data can also be found in the CER.

**Comment by stuartasutton** [comment]
Sorry, didn't add the link to the folder: https://drive.google.com/drive/folders/1zZCdH6Tvvkojfyn4qfuJHOtE97yTSmBS

**Comment by Lomilar** [comment]
Related to #313.

**Comment by siuc-nate** [comment]
Related figure, per @stuartasutton:
![image](https://user-images.githubusercontent.com/21346519/42903936-f2ada0d4-8a98-11e8-963e-9cf80a8d5e93.png)

**Comment by miledivovic** [comment]
@Lomilar Do we need a new import function to handle .jsonld files as well?

**Comment by Lomilar** [comment]
@miledivovic Yes. Would prefer if it is written in http://github.com/eduworks/ec as a library, similar to CSV.

**Comment by Lomilar** [comment]
Thanks, we have code for doing this, needs testing.

**Comment by jeff-grann** [comment]
CE got approved as 3rd party publisher for CSW's [Beta Credentials Framework](http://connectingcredentials.org/wp-content/uploads/2015/05/ConnectingCredentials-4-29-30.pdf). Seems like a good opportunity to test out importing @stuartasutton's mocked-up JSON. 

The owner of the framework also provided this additional guidance on some of the framework properties.
- Name: Beta Credentials Framework
- Description: The Beta Credentials Framework has undergone extensive reviews and field testing in order to revise the framework and ensure its broad utility. An updated and full version of the framework is planned for a January 2019 release.
- Date Valid From: May 2015
- Source Publication Status: Draft

**Comment by woodkri** [comment]
@lomilar I'm not able to import the JSON-LD files. Has that library been written/deployed yet?

**Comment by stuartasutton** [comment]
Jeff, just a couple of notes of clarification. 

1. We need to verify the publisher name and URI for its CER record;
2. This sounds like there will be an updated version this month. Correct? If so, I will want to work closely with folks on that update.

**Comment by Lomilar** [comment]
@stuartasutton
There are some issues with the DQP.jsonld file.

![image](https://user-images.githubusercontent.com/337692/50799928-02530b00-1293-11e9-85c3-509d299f00ed.png)

In the @context, ceasn:name is defined as a language container, which is a different serialization. To fix this, the langstring serialization is required. See below:

![image](https://user-images.githubusercontent.com/337692/50799954-1c8ce900-1293-11e9-8867-2045a2b60dc0.png)

This pattern will need repeating across all "@container":"@language" defined properties in the @context.

**Comment by Lomilar** [comment]
NEVER MIND, I was using the DQP.jsonld from the google drive. Stand by.

**Comment by Lomilar** [comment]
Found some typos, created a pull request.

https://github.com/CredentialEngine/vocabularies/pull/565

@woodkri Above still stands.

**Comment by Lomilar** [comment]
https://cassproject.github.io/cass-editor/?frameworkId=http://degreeprofile.org/dqp

**Comment by stuartasutton** [comment]
If typos were found, were they corrected in github?

**Comment by Lomilar** [comment]
CredentialEngine/vocabularies#565 is a pull request to correct those typos.

**Comment by woodkri** [comment]
@lomilar I'm getting "Object not found or you did not supply sufficient permissions to access the object." when I try to post the file to <endpoint>/data/ctdlasn. Do I need to also post a signaturesheet or something, or is there something else that I'm doing wrong? I was able to get <endpoint>/jsonld to work somewhat on localhost yesterday but not on dev.

**Comment by Lomilar** [comment]
Oh, also, its `/api/ctdlasn` not `/api/data/ctdlasn`.

**Comment by woodkri** [comment]
/api/ctdlasn worked, thanks!

**Comment by Lomilar** [comment]
@eddavies Please work with @woodkri to test import of compatible files from https://github.com/CredentialEngine/vocabularies/

**Comment by woodkri** [comment]
@Lomilar The DQP Framework is the only one that has the .jsonld file extension and the context to be able to import. Should I fix the others and open pull requests? I can also change the import function to try JSON-LD import for .json files but what we have on production chooses the import type based on the file extension.

**Comment by Lomilar** [comment]
I have a PR in to change the rest of the bcsp frameworks. Should I rename them to .jsonld as part of that?

**Comment by stuartasutton** [comment]
What ever works.  Down the road, submission could easily be either .json or .jsonld.

**Comment by woodkri** [comment]
I'll go ahead and make the editor more flexible then.

**Comment by Lomilar** [comment]
Agreed. Expected behavior for .json import is to use the json-ld import if the JSON file has a @context or an @graph in the top level object (if the top level object is an array, treat it as JSON).

**Comment by Lomilar** [comment]
Oh, and if the @context of the top level object is the CTDL-ASN context, should use the CTDL-ASN JSON-LD Import. (POST to /api/ctdlasn)

**Comment by woodkri** [comment]
@eddavies These are ready for testing, other than Connecting Credentials and Connecting Credentials Levels. I opened a pull request to fix a typo in Connecting Credentials, and the Levels one is a concept scheme.
@lomilar We don't have server-side code to import Concept Schemes yet, do we?

**Comment by stuartasutton** [comment]
Typo pull request merged.

**Comment by eddavies** [comment]
@lomilar, the relevant JSON and JSONld files from https://github.com/CredentialEngine/vocabularies/, seem to be importing correctly. Is this safe to close then?

**Comment by eddavies** [comment]
The concept schemes do not import however.

**Comment by siuc-nate** [comment]
We tried importing this to the test server today, and ran into some unusual issues:

Some nodes, seemingly at random, are not editable:
![image](https://user-images.githubusercontent.com/21346519/51864060-4c666400-2308-11e9-80ed-1f31e343c714.png)
![image](https://user-images.githubusercontent.com/21346519/51864071-5720f900-2308-11e9-900e-7905791ae9ce.png)

In edit mode, the letter "h" appears in the language code field:
![image](https://user-images.githubusercontent.com/21346519/51864102-67d16f00-2308-11e9-9a2e-762393c2203e.png)

**Comment by Lomilar** [comment]
@woodkri OK to test again?

**Comment by woodkri** [comment]
@lomilar The language field should now display the framework language (a URL in this case). I haven't fixed the editing issue yet though.

**Comment by woodkri** [comment]
The editing issue is no longer happening for me, though not sure what fixed it. Assigning Eddie for testing.

**Comment by Lomilar** [comment]
Seems OK, now that #449 is fixed.
