### ISSUE TITLE
Make the + icon the defacto way of adding additional entities

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#335]

**Comment by eddavies** [comment]
https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803

**Comment by eddavies** [comment]
Change note's tooltip under a concept scheme needs to be changed.

**Comment by eddavies** [comment]
Alternative Label had a plus but does not have a description in the tooltip for adding additional entities.

**Comment by eddavies** [comment]
On the spreadsheet: **rights** is marked as "repeat" but does not have a "+" icon. **Derived from** is not marked "repeat" but does have the "+" icon.

**Comment by eddavies** [comment]
**Rights** under concept scheme is not marked with repeat in the spreadsheet, but has a "+" icon.

**Comment by eddavies** [comment]
**Notation** under a concept should not have a "+" icon,

**Comment by eddavies** [comment]
**Title** for a concept scheme is marked yes under the repeat column in the spreadsheet. @stuartasutton Does **Title** for a concept scheme require multiple entities?

**Comment by stuartasutton** [comment]
Technically, yes. In fact all properties defined as langString should provide for multiples to enable the same  property in more than one language. We should be able to provide more than one title--e.g., one in English and one in Spanish. That ultimately means that we have to provide the means to set a default language for strings with language tags (e.g., English) with a dropdown option to change that language at will.

**Comment by eddavies** [comment]
If one title contains a comma, it looks as if it is split in two. Is there a different way of separating the titles in view mode?

**Comment by eddavies** [comment]
**Publisher** in a concept scheme should not have a "+" icon

**Comment by eddavies** [comment]
![extra title persisting](https://user-images.githubusercontent.com/23706850/42597089-7e842b2e-850c-11e8-8e5d-74f65a949a3b.PNG)

The added titles to a concept scheme persist through the creation of a new concept.

**Comment by eddavies** [comment]
Could use the AKA commit on concept schemes and concepts

**Comment by eddavies** [comment]
Closing this and creating new issue for concept schemes. #349
