### ISSUE TITLE
Rare occurrence of the alignment add button disappearing 

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#339]
Was testing alignments and had a slight internet hickup. Refreshed and attempted to make a broaden alignment and the add button did not appear.
![image](https://user-images.githubusercontent.com/23706850/42477679-e35bf32e-8386-11e8-93d3-7babf99d4df1.png)

Been unable to reproduce, but keeping it on our radar.

**Comment by Lomilar** [comment]
Could not repro, been 8 months.
