### ISSUE TITLE
Keywords need to comma separate into an array.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#34]

**Comment by miledivovic** [comment]
Fixed in ffae4a8

**Comment by eddavies** [comment]
Fix verified

**Comment by eddavies** [comment]
The keywords are properly displayed in JSON view as separate keywords, however in the edit panel, they are shown exactly as typed (might be better if they had their own line or were put in quotations).
![concept keyword](https://user-images.githubusercontent.com/23706850/33286994-0d46372e-d36c-11e7-91f6-944deb11a5bd.PNG)

**Comment by Lomilar** [comment]
Having them comma separated is OK for input and viewing based on current understanding. Will ask further.
