### ISSUE TITLE
CE Test Server displays multiple framework titles poorly on the bottom footer

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#345]
![framework with multiple titles](https://user-images.githubusercontent.com/23706850/42649639-1060e976-85bf-11e8-9488-e2aaf0d68f8e.PNG)

**Comment by eddavies** [comment]
Here, 6666 7777 888 9999 0000 are extra framework names.

**Comment by Lomilar** [comment]
Nate, Mike: FYSA. Close when you have this represented in your issue tracking software.

**Comment by siuc-nate** [comment]
Where would extra framework names come from? Other non-english languages in the name language map?

**Comment by Lomilar** [comment]
Yes. As of now, frameworks can only have one name per language.

I see that CTITest picks the english name now. Closing.
