### ISSUE TITLE
Date Copyrighted needs clarification

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#347]
Is this field supposed to be just a year? It is not properly saving changes that aren't just a year. 09/22/2017 is not saving, while 2017 is properly saving. There should be an error message if the field is not inputted correctly.

**Comment by stuartasutton** [comment]
Copyright dates are year only (2018).

**Comment by stuartasutton** [comment]
Label should be renamed "Year Copyrighted" as opposed to "Date Copyrighted"

**Comment by eddavies** [comment]
It would be better to give an error if a user plugs in say 7/12/18. Right now it stays green, but when returning to the framework, the input is not saved if it is invalid. So there needs to be an error message.

**Comment by eddavies** [comment]
fix verified

**Comment by eddavies** [comment]
Just realized if you delete all entries in this field, an error is still returned. So if a user accidentally types into the field and deletes their entry they cannot save changes to their framework.

**Comment by eddavies** [comment]
fix verified
