### ISSUE TITLE
Alignments for concepts do not work

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#348]

**Comment by miledivovic** [comment]
@eddavies Please also test competency alignments to make sure there were no unintended bugs introduced there.

**Comment by chinhseah** [comment]
@miledivovic @eddavies Keep in mind this fix doesn't address Firefox issue #294 which is unfortunately still a problem.

**Comment by eddavies** [comment]
"Has child" and "child of" are not appearing for concept connections.

**Comment by stuartasutton** [comment]
Correct.  “broader” and “narrower” handle same concepts in SKOS.

**Comment by chinhseah** [comment]
@eddavies @Lomilar I want to clarify about _"hierarchy of concepts"_ before I make changes. See attached screen capture. If I selected "Chin AA Test Concept" then in Connections "Broad Match:" "Chin A Test Concept" should be listed because it is a "child of" the parent concept? Is that correct? 
![screencapture-localhost-63342-cass-editor-index-html-2018-09-17-11_12_04](https://user-images.githubusercontent.com/15805943/45642422-f71e6a00-ba6c-11e8-9b90-cc59c9b208cb.png)

**Comment by stuartasutton** [comment]
@chinhseah, no, that is not correct. The following mapping properties should **not** be used to map between instances of `skos:Concept` in the same `skosConceptScheme`:

>`broadMatch`
`closeMatch`
`exactMatch`
`narrowMatch`
`relatedMatch`

[SKOS documentation](https://www.w3.org/TR/2009/REC-skos-reference-20090818/#L4160) states:

>"By convention, the SKOS mapping properties are only used to link concepts in different concept schemes."

As a result, these mapping properties play no role whatsoever in defining hierarchies in a `skos:ConceptScheme`.

**Comment by chinhseah** [comment]
Thanks @stuartasutton. I just tested I can add a broad match "2-Comprehending" concept from a different concept scheme (see attached screen capture). @eddavies Please let me know what you mean when you said, "_"Has child" and "child of" are not appearing for concept connections when the hierarchy of concepts are changed._"? Thanks.
![screencapture-localhost-63342-cass-editor-index-html-2018-09-17-13_48_25](https://user-images.githubusercontent.com/15805943/45657707-534eb180-baa0-11e8-9738-ba7f24c6e260.png)

**Comment by stuartasutton** [comment]
Sorry. I didn’t mean to confuse you. With Concept Schemes, hierarchies are established with “broader”/“narrower”. With Competency Frameworks, hierarchies are established with “hasChild”/“isChildOf”.

**Comment by eddavies** [comment]
Has child and childof are no longer visible under connections for concepts on test 👍. 

However, based on what Stuart said above, should we add the broaden and narrow fields under connections for concept schemes to represent concept hierarchy? @Lomilar @stuartasutton would this be correct?

**Comment by Lomilar** [comment]
Makes sense to me.

**Comment by stuartasutton** [comment]
Kind of doesn’t make sense to me since those linkages are easily discerned through the hierarchy in the browser window.

**Comment by chinhseah** [comment]
@Lomilar @eddavies As discussed, I added Broadens (has child) and Narrows (child of) fields under connections. 
![concept broadens](https://user-images.githubusercontent.com/15805943/46095408-4ea98d80-c171-11e8-9569-b0f1d05c1036.PNG)
![concept narrows](https://user-images.githubusercontent.com/15805943/46095409-4ea98d80-c171-11e8-805c-24479228e796.PNG)

**Comment by chinhseah** [comment]
@stuartasutton I just made the change to Broader and Narrower and also the interpretations - see attached screen captures.
![concept narrower](https://user-images.githubusercontent.com/15805943/46105262-7822e300-c18a-11e8-9073-31291912980d.PNG)
![concept broader](https://user-images.githubusercontent.com/15805943/46105261-7822e300-c18a-11e8-93e4-3cd9c7a9a742.PNG)

**Comment by chinhseah** [comment]
@eddavies Changes to display Broader and Narrower are ready for testing.

**Comment by stuartasutton** [comment]
Yes, these are correct! Thanks @chinhseah.

**Comment by eddavies** [comment]
@chinhseah I'm running into an issue where dragging concepts can cause the narrow and broaden relations to not appear.
In the below image A should Narrow B and C. 
Steps on how I got this to occur.
1. Create concept A
2. Create concept B under A (so A narrows B)
3. Create concept C under B (so B narrows C)
4. Drag concept C from under B to be under A.
This should lead to A narrowing B and C, but it is currently bugged where A does not have any Narrow connections. But B and C both broaden A, as intended
<img width="931" alt="as" src="https://user-images.githubusercontent.com/23706850/46307174-0fad7a80-c56b-11e8-890b-dd669ab5e1b0.PNG">

**Comment by chinhseah** [comment]
@eddavies The issue you found with drag-and-drop of concepts and Narrower/Broader Connections not updated should now be fixed so please test again. Thanks.

**Comment by eddavies** [comment]
Narrowing works now 👍

However the broaden relationships disappear for B and C when following the exact steps above:
![c with none](https://user-images.githubusercontent.com/23706850/46495440-46350080-c7ca-11e8-92f0-38baf1d5e5fa.PNG)

**Comment by chinhseah** [comment]
@eddavies Broaden relationship is fixed now.

**Comment by eddavies** [comment]
fix verified
