### ISSUE TITLE
CEASN fields need to allow multiple entries.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#35]

**Comment by Lomilar** [comment]
See multiplicity field at http://credreg.net/ctdlasn/mapping?profileID=registry for guidance.

**Comment by eddavies** [comment]
in language: 👍
competency category: not seeing competency category in a download/view format. Also the competency category did not save properly while adding multiple to a competency.
concept keyword: 👍
alternative coded notation: 👍
author: 👍
creator: 👍

**Comment by eddavies** [comment]
in language: 👍
competency category: 👍
concept keyword: 👍
alternative coded notation: 👍
concept term: still testing
author: 👍
creator: 👍
education level type: still testing
identifier: 👍
local subject: 👍
skill embodied: 👍

**Comment by eddavies** [comment]
for concepts (this is just how it currently works, the documentation did not mention these):
preferred label: 👍
hidden label: 👍
alternative label: 👍
change note: 👍
notation: X
history note: 👍
