### ISSUE TITLE
Framework Name is defined as a single value, but editor allows multiple, as well as export in as a list.

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#351]
In the CASS/ASM mapping spreadsheet:
https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803
Competency Framework name is defined as one per language:
![image](https://user-images.githubusercontent.com/26332112/42901342-f80dd1b4-8a90-11e8-8803-3b637e0db880.png)
The editor allows entering multiple names for a language, and exports as a language map list, rather than a language map.
![image](https://user-images.githubusercontent.com/26332112/42901549-719bc040-8a91-11e8-969a-099329b2f157.png)
The name gets exported as a language map list, and should just be a language map (where only one value can be entered).

![image](https://user-images.githubusercontent.com/26332112/42901749-10dcc21c-8a92-11e8-92d8-ec2d925f5e69.png)

**Comment by miledivovic** [comment]
Coming with #56.

**Comment by miledivovic** [comment]
@cwd-mparsons @Lomilar @stuartasutton To avoid potentially having bad data in the system, fields which are marked as 'one per language' such as Framework Name have been changed back to be singular. Once #56 is finished those fields will allow one name per language as indicated in the spreadsheet.

**Comment by eddavies** [comment]
Closing this for now. Currently, all fields marked "once per language" are singular for the time being. The issue will be tracked in #56 for future changes.
