### ISSUE TITLE
Position "+" at end of entry template and not below it

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#352]
Currently, the "+" symbol for repeating properties is placed below the data entry template as shown here:

<img width="734" alt="screenshot 2018-07-18 12 16 56" src="https://user-images.githubusercontent.com/2939046/42902764-8f207712-8a84-11e8-9ef1-d259ba7bb4e2.png">

The result is that each "+" symbols takes up an entire line of screen real estate. Please place the "+" at to the right of the entry template as illustrated here:

<img width="538" alt="screenshot 2018-07-18 12 20 19" src="https://user-images.githubusercontent.com/2939046/42902900-f935a5aa-8a84-11e8-8f1e-eca585cf6ca9.png">

**Comment by miledivovic** [comment]
Coming with #56.

**Comment by stuartasutton** [comment]
Shouldn't this issue be closed?
