### ISSUE TITLE
Editor not allowing editing of top-level competency

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#353]
Here's a video of me trying.

http://www.screencast.com/t/Duo2zDZY

**Comment by miledivovic** [comment]
This looks to me like its being caused by the same bug as #338.

**Comment by eddavies** [comment]
I'm not running into this on test. @stuartasutton are you still running into this on production?

**Comment by stuartasutton** [comment]
No, this should have been closed long ago.

**Comment by eddavies** [comment]
Thanks, closing
