### ISSUE TITLE
Create options to sort by last modified instead of alphabetically.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#355]

**Comment by stuartasutton** [comment]
@Lomilar, @siuc-nate & @cwd-mparsons:

Just to make sure we are using (and interpreting) the right properties. We need to add a `ceasn:dateModified` with a range of both `ceasn:CompetencyFramework` and `ceasn:Competency". 

Buit, we must understand that a `ceasn:dateModified` on `ceasn:CompetencyFramework` means that some data in the competency framework object has changed. That does **NOT** mean that there have necessarily been any changes in that framework's competencies. Likewise, a `ceasn:dateModified` on `ceasn:Competency` means that there has been a modification to that node and does **NOT** imply that there has been any change to the `ceasn:CompetencyFramework`. In other words, this is not the same notion as version.

**Comment by stuartasutton** [comment]
Definition of `ceasn:dateModified` should also note that equivalence to `schema.org/dateModified` and to `dct:modified`.

**Comment by eddavies** [comment]
This seems to be working. Feel free to reopen if an issue concerning this is found.
