### ISSUE TITLE
Competency alignment search behavior

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#357]
The competency alignment function  for `broadAlignment`, `narrowAlignment` etc. assumes two things inappropriately: 

1. the framework being aligned to exists in the registry; and 
2. the node to be aligned to is in the same competency framework as the competency being aligned from--i.e., an intra-framework alignment. 

As a result of these assumption, when you click to align the current competency node to another, it automatically brings up the current framework for alignment. While it is possible to make such an intra-framework alignment, 98% of alignments will inter-framework alignments--i.e., they have to be found either: (a) in the registry, or (b) outside the registry. If the necessary alignment is to a framework outside the registry, it needs to be possible to **paste a URI into the editor**.  So that means at the least **both** search/select/insert and cut and paste a URI.

**Comment by Lomilar** [comment]
Part of #195.

**Comment by eddavies** [comment]
Closing this, for this is covered in #195.
