### ISSUE TITLE
Event for framework deletion

### ISSUE THREAD

**Issue by miledivovic** [cassproject/cass-editor#358]
There should be an event triggered when a user deletes a framework from the cass-editor, similar to how a FrameworkChanged event is triggered when a framework is updated.

**Comment by eddavies** [comment]
@miledivovic I'm not sure what I'm looking for here, could you clarify? Thanks.

**Comment by Lomilar** [comment]
Look in the F12 log for a FrameworkDeleted message. That is probably as far as you will see without writing a bunch of HTML and JS.

**Comment by eddavies** [comment]
fix verified
