### ISSUE TITLE
Need for "editor profile" functionality for pre-session selection and editor configuration

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#360]
During a single entry/editing session, the person entering data frequently needs to set some defaults (i.e., an editor profile (EP)). Such a profile might include: (1) Default language of resource (inLanguage) and on property values, and (2) default concept schemes for properties like `educationLevelType` and `conceptTerm`. It should be possible to override such defaults for a particular property instance during entry.

Consider further supporting pre-canned EPs that can be created, pre-loaded for selection from a dropdown at the beginning of a session. The ASN Angular editor has such functionality called "Configure" (even including a selection for language translation of the editor interface) and it saves lots and lots of repetitive entry and makes the editor less 'rigid'.

**Comment by Lomilar** [comment]
I'd lean on #365 capabilities at first to autosuggest (when the field is empty) the last entered field, so one could just click, hit enter (or right-arrow enter) and get what they entered last time.

Should the autosuggest not be sufficient, this makes sense.

**Comment by stuartasutton** [comment]
@Lomilar, autosuggest is fine for repetitive entry within a record, the suggested editor profile serves other functions where you are editing/creating a number of records and they all have a property that references a specific controlled vocabulary (inside or outside the registry) and you don't want to have to search and select some of its terms with each record you create. 

Such an editor profile is also useful for prescribing a specific editor profile that people entering data will use in the context of a configurable editor.

**Comment by Lomilar** [comment]
- Default vocabulary to browse for each field where terms can be referenced (maybe as autocomplete or drop down)

 - Configurable settings for preference based options, when we get those.

**Comment by stuartasutton** [comment]
Just an update on this issue regarding an "editor profile". Recently, I did a lot of editing across several days to add data to frameworks that had missing data points--inLanguage being one of them. While the addition of auto-complete for inLanguage is good (even if a bit slow responding), it does not serve the purpose of some sort of session-level "editor profile" that lets someone editing lots of data set overridable defaults like inLanguage. Using the editor over the course of a day to update, means repetitively hitting that property since it is required by every entity.  While functionality such as "editor profile" is not high on the priorities, I hope it does not fall too far out of awareness. It has a significant impact on the utility of the editor.
