### ISSUE TITLE
When should editor cluster headings in editor be present and open

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#361]
There are still a few issues with the editor cluster headings when data is present. I see two problems in view mode (none in edit mode):

1. When any property in a cluster has data, the cluster header should appear along with  those properties with data; and

2. If a cluster has no fields with data, then the cluster should not appear.

Currently, the Rights cluster does not appear even when one or more of its fields have data.

**Comment by stuartasutton** [comment]
Excuse me, my last sentence was the opposite of my intension. It should read "Currently, the Rights cluster is not open even when one or more of its fields have data."

**Comment by stuartasutton** [comment]
Sorry, I meant that the Rights cluster does not open even when one or more of its fields have data.

**Comment by eddavies** [comment]
@stuartasutton do you want the connections section to default to expanded when data is present?

**Comment by stuartasutton** [comment]
@eddavies, I think so. If every other cluster open when there is data, connections should as well since that's the behavior users would expect.

**Comment by eddavies** [comment]
@miledivovic Let's try having connections expand by default.

**Comment by eddavies** [comment]
Fix verified on test
