### ISSUE TITLE
Primary entity of an json-ld @graph should be at the top of the code, not the bottom

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#362]
In the generation of json-ld graphs, the primary entity--e.g., a Competency Framework--is being placed at the bottom of the code output. Is it possible to put the primary entity at the top instead? I know this sounds trivial (since machines don't care), but when a human is reviewing a file, having the primary entity at the top is more convenient. It bothers me enough that I cut and paste that entity at the top every time I download a file for review.

Please :-)?

**Comment by Lomilar** [comment]
Not deployed anywhere yet.

**Comment by eddavies** [comment]
Not deployed yet

**Comment by Lomilar** [comment]
Deployed on dev and production.

**Comment by eddavies** [comment]
fix verified
