### ISSUE TITLE
Missing data in the JSON-LD competency framework export

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#363]
The following properties that contain data in records are not showing up in JSON-LD export data:

### COMPETENCY FRAMEWORK

>audienceLevel
dateCreated
identifier
isVersionOf
conceptTerm
educationLevel
publicationStatusType
publisher
rightsHolder

### COMPETENCY
>isChildOf
dateCreated

**Comment by eddavies** [comment]
+1 these are not showing up on export.

**Comment by eddavies** [comment]
I am seeing identifier and publisher.

**Comment by Lomilar** [comment]
Confirming:

## Framework
conceptTerm does not show up
isVersionOf
educationLevel
validFrom
validUntil
publicationStatusType
rightsHolder
dateCreated

## Competency
dateCreated

**Comment by eddavies** [comment]
Yes!

**Comment by Lomilar** [comment]
@siuc-nate @cwd-mparsons @stuartasutton 

Hey, is ceasn:publicationStatusType supposed to be a multi?

From the validation schema:
```
		"ceasn:publicationStatusType": {
			"$ref": "#/definitions/@id_absolute_multi"
		},
```

**Comment by Lomilar** [comment]
Before translation:
https://dev.cassproject.org/api/data/a2f28878d6d1e19a7c2ebf90f5d93f3a
after translation:
https://dev.cassproject.org/api/ceasn/a2f28878d6d1e19a7c2ebf90f5d93f3a

**Comment by siuc-nate** [comment]
It's probably supposed to be single value. @stuartasutton can you clarify?

**Comment by eddavies** [comment]
On test, all the fields are now showing. Feel free to reopen if there are any specific issues with export fields.
