### ISSUE TITLE
Auto-complete functionality needed on repetitive properties

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#365]
Currently, the Competency Category does not support auto-complete. Some of these literal fields are repeated throughout the entry process for a framework--e.g., "Learning Objective", "Domain" etc. Having auto-complete would be very helpful in this regard.

**Comment by Lomilar** [comment]
Try to trigger browser autocomplete by giving the input a name?

**Comment by miledivovic** [comment]
@stuartasutton I have added autocomplete to competencyCategory, are there other fields that don't currently have autocomplete that should?

**Comment by stuartasutton** [comment]
competencyCategory was the only one I discovered at this time.

**Comment by eddavies** [comment]
The autofill works, but has a side scroll bar when hovering over an autopopulated entry

**Comment by eddavies** [comment]
fix verified, no more unnecessary scrollbar
