### ISSUE TITLE
Ensure 'link' functionality is disabled in the CTDL ASN Profile of the editor.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#370]
Competency frameworks in CTDL-ASN do not permit alternate configurations of identical URLs to exist between frameworks. Please ensure that any situation where competencies would be linked from another framework, that they are in fact copied with a derivedFrom property set.

 * Add competency from other framework search button
 * Competency name autocomplete
Others?

**Comment by Lomilar** [comment]
@stuartasutton @siuc-nate 

Is this first statement I made still true?

eg: Can a competency with a single CTID be shared between two frameworks?

**Comment by jeannekitchens** [comment]
We need to confirm that the reuse of competencies is fully supported. If copying a competency requires a new CTID we need to be sure the https://credreg.net/ctdlasn/terms#derivedFrom property comes along with it.  @woodkri verified the code.  @mparsons-ce is verifying in the CaSS interface.  As long as copying a competency results in the derivedFrom data coming along with it, this is being handled correctly.

**Comment by woodkri** [comment]
Per meeting 4/27/22, link functionality should still be disabled for frameworks in CE CaSS. Only copy should be allowed. Collections still need ability to link.

**Comment by sedula27** [comment]
Tested, Framework has just the copy functionality and the collection has both copy and link
