### ISSUE TITLE
Autocomplete dropdowns don't scroll with the page

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#384]
In both Competency Text and In Language fields, when the autocomplete suggestions pop up the box stays in the same position on the page.

![scroll screenshot](https://user-images.githubusercontent.com/33300923/46490190-569ea880-c7d5-11e8-884f-b53ed4c5df00.png)

**Comment by Lomilar** [comment]
It's not obvious from the above, but commits were submitted to fix this.

**Comment by eddavies** [comment]
Seems to be fixed
