### ISSUE TITLE
If I drag A onto B then B onto A they both disappear.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#39]

**Comment by Lomilar** [comment]
Fixed in 40194e6.

**Comment by eddavies** [comment]
No longer deletes the competency. However, a competency that is a child of another competency cannot be moved under another competency.

editFramework.js:370 Uncaught TypeError: Cannot read property 'relationId' of undefined
    at dropCompetency (editFramework.js:370)
    at HTMLLIElement.ondrop (index.html?user=self&show=mine&ceasnDataFields=true:1)

**Comment by eddavies** [comment]
Also moving a parent competency into one of its children causes issues. In the below screenshot, the B competencies were originally under 1A. Here I attempted to move 1A into 1B and got an error on the console (the error towards the top). Then after making 1C under 1B the framework refreshed and this was the result.
![wonky framework](https://user-images.githubusercontent.com/23706850/33337698-a0a30c38-d428-11e7-885f-9b6b03d4ead3.PNG)

**Comment by Lomilar** [comment]
Was not able to repro either. Based on that error you may have had some old code? Give it another shot with some SHIFT+F5 or CTRL+R action.

**Comment by eddavies** [comment]
yeah was some old code, not running into either issues anymore.
