### ISSUE TITLE
Competency hierarchy messed up post collapse add new

### ISSUE THREAD

**Issue by chinhseah** [cassproject/cass-editor#390]
I found this issue while testing new buttons to collapse all and expand all competencies within a framework. 

When I did not collapse any competency and clicked "+" to add a new competency to existing framework, competency hierarchy was displayed correctly (see screenshot below). 
![add competency to framework](https://user-images.githubusercontent.com/15805943/46832818-e905f580-cd5b-11e8-9243-147b285afe36.PNG)

But after I collapsed a competency hierarchy (Competency 2A shown in screenshot below),
![collapse competency 2a](https://user-images.githubusercontent.com/15805943/46832952-44d07e80-cd5c-11e8-956d-66c781badce8.PNG)

then clicked "+" to add a new new competency to existing framework, competency hierarchy is no longer correctly displayed (below screenshot shows Competency 2AA at same level as Competency 2A).
![add competency to framework post collapse](https://user-images.githubusercontent.com/15805943/46833099-a4c72500-cd5c-11e8-9ec0-00c39051b76a.PNG)

**Comment by eddavies** [comment]
This seems to be working now
