### ISSUE TITLE
Test v1.3.0

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#393]

**Comment by eddavies** [comment]
Dependent on #394

**Comment by eddavies** [comment]
I think we're good for v1.3 @Lomilar .Unless you have any concerns?

**Comment by eddavies** [comment]
Ran into #401 and #402

**Comment by Lomilar** [comment]
#407 is blocking.

**Comment by eddavies** [comment]
#366 was blocking, but is in a state where it would be fine to push.
