### ISSUE TITLE
"None" Field

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#394]
I found this field while editing a framework. I also found this under the Alternative Name for competencies.

id=ui-id-1
<img width="954" alt="none field again" src="https://user-images.githubusercontent.com/23706850/46983602-17eed500-d096-11e8-9f40-c57433b52bc1.PNG">
<img width="946" alt="none underneath label" src="https://user-images.githubusercontent.com/23706850/46983659-61d7bb00-d096-11e8-96e5-9ba40dde53d7.PNG">

**Comment by eddavies** [comment]
<img width="504" alt="more none" src="https://user-images.githubusercontent.com/23706850/46983906-76688300-d097-11e8-8a44-4efacd272b3a.PNG">

**Comment by chinhseah** [comment]
Kamino cloned this issue to [cassproject/CASS](https://github.com/cassproject/CASS/issues/94)

**Comment by chinhseah** [comment]
@eddavies Fix is ready for your testing. Thanks.

**Comment by eddavies** [comment]
fix verified
