### ISSUE TITLE
Alignment usability for competencies 

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#399]
If Broad, Narrow, Exact, Major, Minor, and Prerequisite alignments cannot/should not be made within the same framework (currently they cannot) then we should communicate that somehow to users. 

As of right now, after clicking to add one of these alignments, the user is initially sent to the exact framework they are viewing (this is misleading, perhaps it should default to the framework list). The user may click on a competency within the same framework and click "align with" to proceed. After doing this, nothing happens. 

There should be either an error message when attempting to align competencies of the same framework or perhaps a one line message from hovering over an alignment's tooltip.

**Comment by eddavies** [comment]
On test, the user is now sent to the larger framework list 👍
However, after searching and entering the same framework to create a new alignment with a competency from the same framework, there are some strange things happening.
This is what happened after adding a broaden alignment this way:

<img width="955" alt="alignment weirdness" src="https://user-images.githubusercontent.com/23706850/48435932-65f90600-e732-11e8-9e9f-5819d9a06bf2.PNG">

Previously it was impossible to make alignments to competencies within the same framework.

**Comment by stuartasutton** [comment]
Just a note on future properties. @woodkri, what you describe is the correct behavior for the current set (BroadAlignment, NarrowAlignment, ExactAlignment, MajorAlignment, & MinorAlignment); **but** there will likely be future properties that **do** define relationships between competencies in the same framework. So this is not a universal rule.

**Comment by woodkri** [comment]
Thanks @stuartasutton, that's good to know!

**Comment by eddavies** [comment]
Current set of alignments now cannot be made with competencies from the same framework
