### ISSUE TITLE
User's frameworks only.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#4]
Need flag when logged in as a user to only see their frameworks.

**Comment by miledivovic** [comment]
Implemented in 5a75cc5

**Comment by Lomilar** [comment]
Can you provide production steps so that Eddie can test? (or update the readme.md)

**Comment by miledivovic** [comment]
Testing steps:

1. Add ?user=self&action=add to the end of the url and add a framework through the form.
2. Replace action=add with show=mine in the url and you should see frameworks created by you.

**Comment by eddavies** [comment]
Roger that, thanks

**Comment by eddavies** [comment]
Seems to be working
