### ISSUE TITLE
Importing using opensalt url is getting stuck 

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#401]
When attempting to add a framework from the opensalt example (ims case repository) url, I get stuck on this screen:

![import url case](https://user-images.githubusercontent.com/23706850/47235533-2edf4100-d38e-11e8-85e3-c334f92adc30.PNG)

**Comment by eddavies** [comment]
![console openstalt](https://user-images.githubusercontent.com/23706850/47235746-cfcdfc00-d38e-11e8-82ce-a94264c0a584.PNG)

I'm editing a new framework, completely separate from import and I'm getting these messages on my console.

**Comment by eddavies** [comment]
![image](https://user-images.githubusercontent.com/23706850/47235803-fd1aaa00-d38e-11e8-83dc-d1d56cb728fd.png)

Got this screen randomly while editing a separate framework after not clicking on anything for several seconds.

**Comment by chinhseah** [comment]
@eddavies Not reason for issue you saw but I just wanted to let you know that after waiting for a long time (like over a minute), finally framworks got imported from Opensalt URL.
![opensalt frameworks](https://user-images.githubusercontent.com/15805943/47380742-fbb0f080-d6b2-11e8-9b18-59ba94232d4c.PNG)

**Comment by Lomilar** [comment]
Importing a large framework takes longer than 5 minutes which causes timeouts. Will link issue that threatens to solve this.

**Comment by eddavies** [comment]
The import isn't cancelling when I leave the import screen still.

**Comment by Lomilar** [comment]
Cancel/Back should cancel imports and not eventually switch to a search screen.
Cancel/Back should stop importing frameworks past the current one.

**Comment by eddavies** [comment]
I haven't been able to reproduce this again
