### ISSUE TITLE
Landing page.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#404]
For CE at least, people have three major use cases:
* I want to enter a framework from a PDF or by hand
* I want to import a framework from elsewhere / spreadsheet
* I want to edit a framework or start looking around.

**Comment by woodkri** [comment]
Possible duplicate of #245

**Comment by woodkri** [comment]
@Lomilar Can this be closed with CaSS 1.3?

**Comment by Lomilar** [comment]
Yes.
