### ISSUE TITLE
Feedback: Keys (in editing pane) should not be front and center

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#405]
From a user perspective. Came out of a usability call.

**Comment by stuartasutton** [comment]
Depends on which "users" are the subject?

**Comment by Lomilar** [comment]
Agreed. The concern, I think, came out of the fact that using the editor tool within the context of the Credential Engine, you never have to worry about the CTID, because all our tools navigate internally just fine. When using the competencies in a tool outside of the credential engine, that's when the URI and CTID become useful.

So, perhaps, when viewing the published framework, having URIs and CTIDs would be more useful?

I'm probably missing the fact that identifiers are essential distinguishing features in an editing process in some way.

**Comment by stuartasutton** [comment]
Yes, there is not much direct need in the editing process, but the editing "view" is where people wanting to link to the entity come to grab the link...thus the fact that there are different uses tied to the editor.

**Comment by woodkri** [comment]
This is configurable in CaSS 1.3. Keys are no longer front and center on the default views.
