### ISSUE TITLE
Ability to make certain concept schemes appear only for specific concept scheme selectors.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#406]

**Comment by Lomilar** [comment]
Requires an approach. @stuartasutton This came out of CE User feedback. Is there an obvious way to specialize a concept scheme to a particular field?

**Comment by stuartasutton** [comment]
No; but a particular property can have specific concept schemes declared in its range...i.e., instead of saying it's range is something like skos:Concept, it can require a specific ConceptScheme...or am I missing your meaning?

**Comment by Lomilar** [comment]
It's the right idea but the other way around. EducationLevel can be defined in multiple schemes, so we need a selector that can go out and look at multiple schemes, but it'd be nice if the schemes could identify themselves as being relevant to that ceasn:educationLevel property. Something like skos:indendedFor that has a OWL property for its range

**Comment by stuartasutton** [comment]
That rationale, @Lomilar, cuts both ways. Many concept schemes can be used with multiple properties in multiple schemas. Defining a concept scheme to a single property in a single schema is not an idea that I'd support.

**Comment by Lomilar** [comment]
Being RDF, multiple schemes could be assigned to properties in a many-many. I did not intend to restrict cardinality at all.

If you meant: Restricting schemes to work only on particular properties for which they were intended isn't something you'd support... I'm more curious about the rationale there.

**Comment by Lomilar** [comment]
I've noticed some explicit concept schemes start to be defined in the CTDL. Is there another process going on to help resolve this?

How do concept schemes usually associate themselves as an intended range for rdf:Property?

**Comment by Lomilar** [comment]
Per discussion today,
Closed, we're going to continue to show all concept schemes for each property. Requiring the publisher of a scheme to understand what property their scheme is intended for is a bridge too far. Recommendations may be a better choice here. Re-open if we would like to revisit this.

**Comment by stuartasutton** [comment]
This remains a function of a profile that can be used to format an editor or to validate data. Such a profile can define which value spaces are available for a specific property. A really good editor can be formatted by more than one framework. 

Anyway, I’ve Mentioned this in an issue long ago. So, no, I do not think it is the role of a concept scheme to define the property with which it can be used.
