### ISSUE TITLE
Need keyboard shortcuts to drag/drop competencies or move around hierarchy.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#42]
Recommend cut/copy/paste pattern.

**Comment by miledivovic** [comment]
Added in 2fbb06b.

Keyboard shortcuts are in readme.

**Comment by eddavies** [comment]
Keyboard shortcuts work. Need to retest once #39 is fixed

**Comment by Lomilar** [comment]
CTRL+C and CTRL+X should work differently. CTRL+X should remove the relation and put the stuff into the buffer for CTRL+V. CTRL+C shouldn't remove the relation.

**Comment by miledivovic** [comment]
Should be good to retest.

**Comment by eddavies** [comment]
Using CTRL does not work. The keyboard shortcuts work with SHIFT

**Comment by eddavies** [comment]
Works as intended
