### ISSUE TITLE
Adding concept terms to concept schemes does not work

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#420]
As title describes, clicking the add button does not result in anything when concepts are selected.

**Comment by woodkri** [comment]
@eddavies Is this supposed to have the same behavior as competencies, where a popup asks if you want to copy or link the concepts?

**Comment by Lomilar** [comment]
Pretty sure it is always supposed to copy, never link.

**Comment by eddavies** [comment]
It should work the same way adding a level, or a concept term, or a skill embodied for a competency. Which I believe is copy with no popup.

**Comment by Lomilar** [comment]
@eddavies is correct here. I was thinking about adding a concept to a scheme.

**Comment by woodkri** [comment]
I realized after I asked this that concept term is a field in ceasnDataFields - I was initially looking at selecting and adding concepts in select=Add mode, and wasn't sure what the behavior was supposed to be. It made a lot more sense when I switched over to ceasnDataFields.

**Comment by Lomilar** [comment]
@eddavies Merged @woodkri's change. OK to test.

**Comment by woodkri** [comment]
@eddavies Where is cass test? It's showing up for me at https://cassproject.github.io/cass-editor/?ceasnDataFields=true&concepts=true.

**Comment by eddavies** [comment]
Hmm I can see it now, not sure what happened. Maybe it was a screw up on my end when I was testing this.
