### ISSUE TITLE
Error when publishing learning opportunity with competencies imported from OpenSalt

### ISSUE THREAD

**Issue by jeff-grann** [cassproject/cass-editor#427]
I encountered this "Competency URL is invalid" error message in the test environment when trying to edit a learning opportunity by adding competencies that had been imported from OpenSalt. I have not encountered this error message with competency statements authored in CASS.

![image](https://user-images.githubusercontent.com/7041920/48096636-4c5d3900-e1dd-11e8-8243-9a7abdd274a5.png)

**Comment by Lomilar** [comment]
Worth testing a round trip: From OpenSalt to CaSS to CER and back to Salt (from CaSS?)

If we can find the Connecting Credentials framework, seeing if the URLs align would be A+.

**Comment by Lomilar** [comment]
@jeff-grann Is there a public opensalt instance that has import functionality?

**Comment by jeff-grann** [comment]
Yes, just sent you an email with access info.

**Comment by jkitchensSIUC** [comment]
@Lomilar is this still and issue?

**Comment by siuc-nate** [comment]
Can this be closed?
@Lomilar @woodkri

**Comment by Lomilar** [comment]
This is still an issue.

Todo:

* [ ] Create OpenSalt instance via docker, create framework w/competencies.
* [ ] Import OpenSalt to CaSS
* [ ] Import from CaSS to OpenSalt (via CASE import)
* [ ] Verify data is unchanged.

**Comment by woodkri** [comment]
To do:

- [ ] Remove context from CASE export
