### ISSUE TITLE
Competencies imported into CaSS cannot be viewed by Credential Engine team member

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#428]
related to: #427 
In the latter, the framework that was imported was something like Jeff's import test ACT. 
If I login to the test server as an administrator (i.e. member of Credential Engine Administration) I should be able to view any framework. However I cannot find the framework referenced above. 
It would appear that when a framework is imported, the CE keys need to be "attached".

**Comment by Lomilar** [comment]
This is ready to begin reproducing and exploring with the latest deployment.

**Comment by cwd-mparsons** [comment]
@Lomilar I just did an import of a framework into the test server: 
- Mechatronics-Level 1
- https://sandbox.credentialengineregistry.org/resources/ce-4f484791-aca7-44a0-ba9f-3d4ef6aa4253
- https://dev.cassproject.org/api/ceasn/c09e22d9b7906e98c12619bfbef53148

I imported it under the NOCTI organization.
I then tried to find it using my the administration account and could not.

**Comment by cwd-mparsons** [comment]
@Lomilar I just checked this in the test server. I re-imported the test framework (csv) under the NOCTI organization. I updated the description, and saved. 
I still cannot see this framework when I do a search under the administration organization context. 
This seems to work in production - Nate validated this when doing the json-ld import.

**Comment by Lomilar** [comment]
Everything you said is correct, because the ctitest CASS server is our Development server, and is not configured to be a CE server (it doesn't add the CE Admin Staging private key to all frameworks that are imported, for instance).

This should indeed work in production.

We need CE Staging to model these tests correctly.

**Comment by cwd-mparsons** [comment]
@Lomilar I can test this in our staging server. What is the URL for your staging server? The URLs used for CTI test are: 
root url: 
https://dev.cassproject.org

editor:
https://cassproject.github.io/cass-editor/index.html?user=wait&amp;link=true&amp;newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&amp;server=https://dev.cassproject.org/api/&amp;ceasnDataFields=true&amp;show=mine

**Comment by Lomilar** [comment]
The CE Staging server is not fully configured, and is sitting at staging.credentialengine.org

http://staging.credentialengine.org:8080/cass-editor/index.html?...
