### ISSUE TITLE
Occasionally will receive 404 when using the CaSS viewer

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#434]
In the credential finder site, we have added the use of the CaSS viewer for competency frameworks. We have seen several cases where a 404 error occurs. Following are a list artifacts that result in this error. 
To view, follow the url, on the right side under More Info, click the Assess or Teaches button.
![image](https://user-images.githubusercontent.com/26332112/48509891-e9d8ee00-e817-11e8-84ca-6cd4003d94e8.png)

http://credentialfinder.com/assessment/73/CACP_Application_and_Practicum 
http://credentialfinder.com/assessment/120/CCO_Dedicated_Pile_Driver_Operator_Written_Exam
http://credentialfinder.com/assessment/132/CCO_Mobile_Crane_Operator_Practical_Exam

http://credentialfinder.com/learningopportunity/41/Bachelor_Degree_with_Individualized_Focus_Area_Coursework
http://credentialfinder.com/learningopportunity/70/Certificate_for_Apartment_Maintenance_Technicians_Courses 

http://credentialfinder.com/learningopportunity/22/Bachelor_of_Science_in_Information_Technology_Coursework

**Comment by cwd-mparsons** [comment]
I found that errors appear to be related to the highlightCompetency parameters. I removed most of the latter from the following and the framework would be displayed. 
http://credentialfinder.com/learningopportunity/41/Bachelor_Degree_with_Individualized_Focus_Area_Coursework

We are changing our approach to use the postMessage option. I am guessing the same issue could occur using the latter method. Perhaps the highlight method could catch and ignore 404 errors?

**Comment by Lomilar** [comment]
I believe the 404 errors were alleviated by restarting some services. Reproduce?

**Comment by cwd-mparsons** [comment]
We updated the highlight process to use the postmessage approach.

**Comment by Lomilar** [comment]
&webSocketOverride=wss://cass.credentialengine.org:8080/ws/custom will take care of that.

**Comment by Lomilar** [comment]
Reopen if this issue is still occurring, it seems to have been cleaned up.
