### ISSUE TITLE
Unknown properties in competency editor

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#435]
@Lomilar (who should I assign?), please look at the bottom of the data entry pane in the following image when editing a competency. There are 3 properties there that don't belong (not in schema): "Is Enabled By", "Is Related To" and "Desires".

<img width="1439" alt="error-unknown_properties" src="https://user-images.githubusercontent.com/2939046/48627323-20724e00-e969-11e8-8a18-329c9056f26d.png">

**Comment by Lomilar** [comment]
Repro note: Those additional relations only show up on the first competency you click on (and go to the edit screen)

Clicking on additional competencies removes them as expected.

**Comment by Lomilar** [comment]
Closing then.
