### ISSUE TITLE
Assigning a graph-level URI to competency frameworks

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#436]
For credentials (and related entities) in the CER, individual entities are assigned URI in https://credentialengineregistry.org/resources/[ctid]. They also are assigned a URI at the graph level  in https://credentialengineregistry.org/graphs/[ctid]. 

The same is not true for graphs of competency frameworks and their associated competencies--no graph-level URI assigned. Shouldn't we? Why not?

**Comment by Lomilar** [comment]
A competency framework seems to me to be largely compatible with a @graph. I suppose we could assign a graph level URI, but it would likely just be /graphs/<ctid of framework> -- unless you know of a reason not to do that.

**Comment by stuartasutton** [comment]
Without it, you can't make statements about the graph as a whole...just about its parts. 

The URI is identical to the URI of the graph's primary entity except /graphs/ instead of /resource/

**Comment by siuc-nate** [comment]
We tested this today.  We exported a framework:
https://cass.credentialengine.org/api/ceasn/74ece81cba75046381eb5ec130889435

Note the URI has two issues:
- It uses /graphs/ instead of /graph/ (singular form is correct)
- It uses ce-ce- instead of ce- in the CTID

**Comment by Lomilar** [comment]
Repeated in https://github.com/cassproject/CASS/issues/122

**Comment by woodkri** [comment]
Fixed in dev/CE staging and production.
