### ISSUE TITLE
Arrow keys do not drag the page

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#44]
While using keyboard only:
When browsing frameworks, or competencies, the browser window does not follow what is highlighted by the arrow keys. So a user can select a framework from way below screen that they cannot see.

**Comment by eddavies** [comment]
The arrow keys only drag the page while editing a framework

**Comment by miledivovic** [comment]
Fixed in 4164f97

**Comment by eddavies** [comment]
fix verified
