### ISSUE TITLE
The guided tour prompt should be disabled for the CaSS viewer

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#442]
The CaSS viewer is used on the public credential finder site. Today upon selecting a framework to display in the viewer, I was presented with message noting that I appeared to be a first time user, and would I like a guided tour. 
This feature should be disabled in the viewer. 

I started the tour just to check for any impacts. As shown below, it will attempt to point to how to create a framework. 

![image](https://user-images.githubusercontent.com/26332112/49108521-ff094000-f24d-11e8-9bcb-42fa10e71baa.png)

**Comment by Lomilar** [comment]
For that iframe, is `?view=true` being used?

**Comment by cwd-mparsons** [comment]
@Lomilar 
We are not currently using view=true. A sample URL is:
https://cass.credentialengine.org/cass-editor/index.html?server=https://cass.credentialengine.org/&ceasnDataFields=true&origin=https://credentialengine.org&css=https://credentialengine.org/publisher/Style/CassStyles&frameworkId=https://cass.credentialengine.org/api/data/95cfc7240d596af9cd1c23029aaefc74

We could added the parameter, except I notice that if I add view=true, the splitter is disabled, and cannot resize the sections. I think being unable to size the sections would be a problem. 
As you Jeanne wants to (soon) use a custom view. In the short term, will the use of view=true prevent the tour prompt from being displayed?

**Comment by Lomilar** [comment]
Yes. We can also modify things (turn the splitter back on, remove technical fields) to facilitate view=true being on.

Feel free to put a laundry list here or in a new issue.

**Comment by Lomilar** [comment]
No longer being used.
