### ISSUE TITLE
Split bar is not working in view mode

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#444]

**Comment by eddavies** [comment]
@woodkri what is the split bar referring to?

**Comment by woodkri** [comment]
@eddavies It's the vertical bar in the middle of the page that you can drag to one side or another to resize the different parts of the page. It was locked in on CTDL-ASN view mode, wouldn't move.

**Comment by eddavies** [comment]
Ah, thank you

**Comment by eddavies** [comment]
The bar seems to be working now in view mode

**Comment by Lomilar** [comment]
@cwd-mparsons
