### ISSUE TITLE
CASE import with a lot of frameworks a) doesn't retrieve them all, and b) doesn't have a scroll bar.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#445]
Here's a registry with lots of frameworks in it.
https://caseregistry.imsglobal.org

**Comment by woodkri** [comment]
@Lomilar I see all 100 frameworks detected. Is the issue that not all 100 can be imported, or are they not all showing up as options to import for you?

**Comment by Lomilar** [comment]
There are more than 100 frameworks in that registry, but our list is limited to 100.

**Comment by woodkri** [comment]
Ah ok. I saw 2 per state at the link so thought there were just 100 there.

**Comment by Lomilar** [comment]
Thanks. Sorry, round numbers are incredibly infrequent, thought I was seeing an error.
