### ISSUE TITLE
Remove intro.min.js, find alternative.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#448]
Licensing issues.

**Comment by woodkri** [comment]
Maybe [hopscotch](http://linkedin.github.io/hopscotch/)? It's licensed under Apache 2.0.

**Comment by woodkri** [comment]
@eddavies - I changed the plugin we're using for the tour when someone new tries out the CaSS Editor. It should look a little different than the old one but function the same way.

**Comment by Lomilar** [comment]
Seems to work fine.
