### ISSUE TITLE
Enable CTDL-ASN export for a single competency.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#449]
https://github.com/cassproject/CASS/issues/82 - Source
https://github.com/cassproject/CASS/commit/a0270d76ef58740841334e62987b08fd23132f69 - Server side commit to enable individual competency export.

Please enable the export for a single CTDL-ASN competency.

**Comment by woodkri** [comment]
@lomilar This seems to be working for competencies with a https://credentialengineregistry.org URL. Competencies with other URLs are exporting an entire framework, not always the same one that is being viewed in the CaSS Editor (if the competency exists in more than one framework). Should the export be restricted to competencies having CER ids?

**Comment by Lomilar** [comment]
>Should the export be restricted to competencies having CER ids?

No. There's probably a mistake in there somewhere.

**Comment by Lomilar** [comment]
Done.

**Comment by Lomilar** [comment]
cassproject/cass@2ed5dd028ba430e4e76d849920c5bcd2c9d143f5
