### ISSUE TITLE
HTML markup appearing in some frameworks

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#45]
Below are screenshots of some text that probably shouldn't exist in the frameworks. 
First image : Georgia Performance Standards - Social Studies - 2008
![strange characters](https://user-images.githubusercontent.com/23706850/33148175-9b7c6b3a-cf7f-11e7-9939-d8a68e8ecb93.PNG)

Second/Third image: Mathematic Standards
![strangecharacters1](https://user-images.githubusercontent.com/23706850/33148395-934543e6-cf80-11e7-8e83-d4202ba8d665.PNG)
![strange characters2](https://user-images.githubusercontent.com/23706850/33148396-94a74234-cf80-11e7-81e5-06ffcc39b7ed.PNG)

**Comment by Lomilar** [comment]
This is by design and comes from other standards. See opensalt/opensalt#193, CredentialEngine/CompetencyFrameworks#40.
