### ISSUE TITLE
Attempt to resolve URIs in properties and fetch labels/turn things into href. 

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#452]
Similar to ceasn:creator, this should be attempted for all URIs that return useful JSON-LD data.

skos:prefLabel in a @graph is one use case.

**Comment by woodkri** [comment]
@lomilar I've added a few things here from URLs I've seen in the editor that could be resolved. I'll keep an eye out for others to add but this could possibly be closed.

**Comment by Lomilar** [comment]
OK to close. Deploying what's in here so far as part of 1.0.6.
