### ISSUE TITLE
The Credential Engine ASN Export of a competency framework is missing coded notation and Competency Category

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#455]
@Lomilar 
As an example, look at: Building Operator Certification (BOC) Level II Training Certificate of Completion Competencies. 
![image](https://user-images.githubusercontent.com/26332112/51266366-b41fc500-1980-11e9-98fb-a14189915bf5.png)
Upon export, the Coded Notation (ex. BOC 201) and Competency Category (ex. Learning Outcome/Competency) are missing for a competency.

**Comment by Lomilar** [comment]
@eddavies Please retest. This was fixed during a call 1/16.

**Comment by eddavies** [comment]
This is working on test.
