### ISSUE TITLE
Load number filters occasionally do not work

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#456]
Today (working on 2 machines in 2 different browsers), the filters for titles displayed--Load 100 | Load 1000 | Load All--intermittently do not work and the person is stuck with the default. I first noticed this intermittent problem right after we went to v.1.0.

**Comment by eddavies** [comment]
This is no longer occurring for me with the latest commit. Closing this (along with #460), feel free to reopen if this still occurs after the next update to production.
