### ISSUE TITLE
Display error message for attempting to save additional entities with no language tag

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#458]
Currently, after adding an additional entity (ex: a 2nd description) that requires another language to be inputted, the extra entity will not save. (note: Is this intended behavior?)
However, when attempting to save the addition, there should be an error message, or the language field should highlight in red to inform the user that they have to fill the language field in.

**Comment by woodkri** [comment]
Entity should now save even if there is no language present.

**Comment by eddavies** [comment]
Now these fields save, and use the default en-US when saved. Seems like a good solution to me.
