### ISSUE TITLE
Intermittent failure to save edited data

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#459]
Since enabling v.1.0, the editor **intermittently** fails to save edited data. I can see no editing patterns that makes this happen. It's really bad since discovering that it occasionally fails to save means a person editing has to double check with every save since they can't be confident that the work was saved. Yesterday, I was in an editing session and had to save edits to a competency 4 times...5th time saved.

**Comment by Lomilar** [comment]
We need to watch the server and browser log and reproduce this to see what's going on. Could be an issue with the proxy, could be with the repository.

**Comment by woodkri** [comment]
Reproduction: In production, when you add a complexity level to a competency, it doesn't save the first time. Second time it does.
Timing issue or something else?

**Comment by stuartasutton** [comment]
@woodkri, complexity level is not the only place where this occurs. It happens intermittently regardless of the property.

**Comment by woodkri** [comment]
Right, we just need to be able to reproduce the issue in order to diagnose it. This was happening pretty consistently with complexity level yesterday, so it gives us a place to start from.

**Comment by Lomilar** [comment]
We have one positive reproduction of this (#545) in the last month. Any other evidence?

**Comment by Lomilar** [comment]
The double save thing doesn't appear to be happening on production as of today.

**Comment by eddavies** [comment]
I haven't run into this myself, but I haven't been testing on production.

**Comment by Lomilar** [comment]
We believe we have this mitigated, as it was an IIS issue. Reopen if it occurs again / regularly.
