### ISSUE TITLE
Search for framework fails when certain characters are used in title

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#46]
I created a stub framework titled "[Test] Certified Environmental, Safety & Health Trainer (CET)". If I search for any terms in the title, I am successful--e.g., "Test", "Certified Environmental", etc. But if I search on "[Test]" I go into an infinite "Loading Frameworks".

**Comment by stuartasutton** [comment]
That's no problem as long as the result of a search for "[Test]" doesn't fail to retrieve even though a search for "[" fails.

**Comment by Lomilar** [comment]
It does eventually return, that query seems to particularly break the search engine (it took over a minute for results for me).
