### ISSUE TITLE
Load no. links intermittently do not function

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#460]
Since enabling v.1.0, the "Load" links **intermittently** do not work. Yesterday, I could not get off the default "100" for an entire editing session...thus no browsing available past 100. This happened to me on both my iMac and my MacBook with both Chrome and Firefox.

**Comment by eddavies** [comment]
This is no longer occurring for me with the latest commit. Closing this (along with #456), feel free to reopen if this still occurs after the next update to production.

**Comment by stuartasutton** [comment]
Was this fix on production? I'm still stuck with default number.

**Comment by stuartasutton** [comment]
Thanks!
