### ISSUE TITLE
Competency multiple comments have disappeared

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#461]
I don't know whether this change appeared with the publishing of 1.0, but where a Competency has multiple comments, only the first now appears in the hierarchical display. This was not the case before. Some of these comments are quite significant. An example (from among many) are the "Building Operator Certification (BOC)..."

**Comment by Lomilar** [comment]
This does not seem to be an issue on production any longer for competencies or frameworks. Tested.
