### ISSUE TITLE
CSS Inheritance from parent page

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#467]
When adding a concept or competency relation to a competency or framework, a new iframe pops up to select the one(s) the user wants. That page should inherit styles from the parent page when available.

**Comment by eddavies** [comment]
I believe #472 may be occurring as a result of this change.

**Comment by woodkri** [comment]
@eddavies Did you notice any other issues when testing this one?

**Comment by eddavies** [comment]
I did not. Closing this
