### ISSUE TITLE
Handling of special characters may be breaking the search

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#470]
Last week I created this framework:
https://cass.credentialengine.org/cass-editor/index.html?editorRoot=/cass-editor/&server=https://cass.credentialengine.org/&ceasnDataFields=true&webSocketOverride=wss://cass.credentialengine.org:8080/ws/custom&newObjectEndpoint=https://credentialengineregistry.org/resources/ce-&show=mine&origin=https://credentialengine.org&css=https://credentialengine.org/publisher/Style/CassStyles&frameworkId=https://credentialengineregistry.org/resources/ce-e447aacc-8829-4485-857d-84de452693ce

Which is showing a bunch of triple question marks (???) in place of special characters that would've been copy-pasted out of the PDF where this data originated.  
![image](https://user-images.githubusercontent.com/21346519/51756225-20d44700-2086-11e9-8823-d1a08c3b123c.png)

I was able to publish this data to the registry, but it replaced the first two question marks with a jquery callback:
https://credentialengineregistry.org/graph/ce-e447aacc-8829-4485-857d-84de452693ce

![image](https://user-images.githubusercontent.com/21346519/51756191-10bc6780-2086-11e9-8d0a-3ce1d74f6d99.png)

I am unable to find the original framework in the CASS page on production.
![image](https://user-images.githubusercontent.com/21346519/51756272-38133480-2086-11e9-949f-65f8ffd5c7f3.png)

This may be related to https://github.com/cassproject/cass-editor/issues/468 or it may have something to do with the handling of special characters.

In the PDF for the source data, the ??? are showing for long dashes and smart quotes (single and double flavored)
http://connectingcredentials.org/wp-content/uploads/2015/05/ConnectingCredentials-4-29-30.pdf
![image](https://user-images.githubusercontent.com/21346519/51756379-7f012a00-2086-11e9-9006-e7acf7bf8269.png)
![image](https://user-images.githubusercontent.com/21346519/51756387-84f70b00-2086-11e9-9a18-ad224b85e191.png)

**Comment by Lomilar** [comment]
This has to do with the character set we use to read files. We should be sure that those characters are UTF-8 and that we're reading files with a UTF-8 encoding.

**Comment by woodkri** [comment]
@lomilar The file reader uses UTF-8 encoding to read files. The special characters are coming from copying/pasting text into the editor. I tried copy/pasting the same text and it displays properly for me in the editor but about half of the exports replace the special characters with other symbols. Should validation be done when saving things in the editor, or translation when exporting?

**Comment by Lomilar** [comment]
We should probably do a full pass to make sure everything goes in and comes out as UTF-8. I don't think we need to validate as long as we don't mess up anywhere.

https://github.com/cassproject/CASS/issues/123 has a checklist that can be added to.

**Comment by woodkri** [comment]
More odd behavior here - When I import the DQP framework the apostrophes in the framework description show up in the editor as apostrophes, but when I move away from the framework and come back they then appear as a question mark symbol.

**Comment by woodkri** [comment]
Actually I think this may be related to https://github.com/CredentialEngine/CompetencyFrameworks/issues/87.

I imported the DQP framework with the language updated from a URL to "en-US" and when I backed out of it and reentered, the URL is showing up again so it seems to be from a previous import. On the plus side, this version displays and exports the apostrophes correctly.

**Comment by Lomilar** [comment]
All my testing here seems to work. To be deployed in 1.0.6.
