### ISSUE TITLE
Moving existing during editing of nodes in competency and concept editors

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#473]
Currently, while editing **either** a competency framework or a concept scheme in the editors, competencies and concepts are reorder (changed position) by dragging and dropping the node being moved onto the folder where you want the node to be repositioned--even if the move is within the same folder. When the drop into the folder is done, the editor automatically puts the node at the bottom of the list of children for that folder. If you want to change the positioning of the node amongst the children, you have to use the same procedure of dragging and dropping to the parent of (frequently) all of the child nodes to get them correctly ordered. So, if there are 10 child nodes, each has to be dragged and dropped on the parent to rearrange the order. If you make a mistake, you can't just drag the problem node to the correct position and drop it, you have to redo (frequently) all 10 moves. PAINFULLy slow if moving any number of nodes; and REALLY PAINFULLY slow if the size of the array of sibling nodes to be reordered is large.

The editor should support the following node move behaviors:

1. Like now, when a competency/concept node is moved to a different folder by dragging and hovering over a destination node, the moved node should be dropped at the bottom of the array of children nodes for that folder; AND
2. When a node is repositioned in its original array of siblings or moved to an exact position in an array of siblings in a different folder, it should allow the node being moved to be dropped in the exact new position.  

The second behavior means that the person editing doesn't have to rely on the first behavior to handle every reordering.

**Comment by Lomilar** [comment]
The arrow up and arrow down buttons should be able to be used to reorder without having to drag/drop all the time.

![image](https://user-images.githubusercontent.com/337692/51872138-44f58980-230d-11e9-8547-fcd015335704.png)

**Comment by Lomilar** [comment]
But you are correct, there is no 'move to top' or any such. Would that be useful?

**Comment by stuartasutton** [comment]
Yuo...my mistake.
