### ISSUE TITLE
Langstring encoded ceasn:competencyCategory is not displayed correctly.

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#474]
I just tried reimporting the framework from here: https://github.com/CredentialEngine/vocabularies/blob/master/Competency-Frameworks/ConnectingCredentials.json

And while the source data was corrected to have ceasn:competencyCategory data:
```
{
      "@id": "https://credentialengineregistry.org/resources/ce-8b7e549f-d73c-426d-9102-00e7fdb18ab2",
      "@type": "ceasn:Competency",
      "ceasn:competencyCategory": {"en-US": "Competency"},
      "ceasn:competencyText": {"en-US": "Demonstrates comprehensive, specialized, systematic state-of-the-art knowledge in a discipline or profession and contributes to innovation or the expansion of knowledge."},
      "ceasn:complexityLevel": "https://credentialengineregistry.org/resources/ce-0edf49cc-8c07-42f8-b253-1ef8d39b47b4",
      "ceasn:inLanguage": "en-US",
      "ceasn:isChildOf": "https://credentialengineregistry.org/resources/ce-57d2272f-74c8-4cb4-96d6-01331b592c0d",
      "ceasn:isPartOf": "https://credentialengineregistry.org/resources/ce-c62c336f-a76d-4d7f-a777-367e7cc72d17",
      "ceterms:ctid": "ce-8b7e549f-d73c-426d-9102-00e7fdb18ab2",
      "ceasn:shouldIndex": "true"
},
```

The data does not show in the CASS interface or in the export:
![image](https://user-images.githubusercontent.com/21346519/51848715-b6204700-22e3-11e9-9fdf-e6319c9f4045.png)

**Comment by siuc-nate** [comment]
Note: This framework correctly exports both competencyCategory and listID: https://cass.credentialengine.org/api/ceasn/ece964c0debab0d4c3693a8925e711c7

So the issue may be with the import - perhaps because the URIs were reused?  Note that we did try deleting the framework and then importing it again as well, with no luck.

**Comment by Lomilar** [comment]
In the import translation context, we didn't have competencyCategory marked down as a langstring.

It has been now been marked as a langstring in the import.

Performing the import on our test server, the competencyCategory still doesn't appear in the editor, but it does appear in the export now.

https://dev.cassproject.org/api/ceasn/ba13a98298ab5fea4188f4bd3dacdc66

**Comment by siuc-nate** [comment]
Thanks.

We reimported the data and as you specified, it does show in the export (and was successfully published to the registry) - though the interface still needs to be fixed.
https://credentialengineregistry.org/graph/ce-c62c336f-a76d-4d7f-a777-367e7cc72d17

**Comment by Lomilar** [comment]
Switched this issue to address the non-displaying langstring.

**Comment by stuartasutton** [comment]
Not an issue in the source code.

**Comment by eddavies** [comment]
I reimported the framework on the test server and competency category appeared correctly in the editor and in the export.
