### ISSUE TITLE
Imported competencies appear out of order in the editor

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#479]
Yesterday when we were (re-) importing the beta connecting credentials framework ( https://github.com/CredentialEngine/vocabularies/blob/master/Competency-Frameworks/ConnectingCredentials.json ), we noticed two issues regarding the order of nodes:

1. The nodes would appear out of order in the editor interface, giving the impression that they were not imported correctly (they were within the correct layer of the hierarchy however).  
2. When exported, nodes would appear in the order they appeared in the JSON-LD document (that is to say that the physical ordering of the nodes themselves, rather than their URIs in the relevant hasChild list, seemed to affect what showed up in the export.

The second one can be worked around by having the interface that displays the data enforce the hasChild order (it is identified as a `@list` property in the `@context`), but the first problem was baffling.

**Comment by woodkri** [comment]
I've been looking into this. Right now with the CTDL-ASN JSON-LD import, competencies are ordered within the CaSS Editor based on the order of nodes in the JSON-LD document (while respecting hierarchies). We can change the order competencies are added to follow the hasChild and hasTopChild lists instead, but I noticed that some frameworks (BCSP-ASP for one) also have listIds on the competencies that don't match the order in those lists. What is the preferred behavior @siuc-nate ?

**Comment by stuartasutton** [comment]
@woodkri, can you point me to an example where the listID's aren't consistent with @list ordering? Thanks in advance.

**Comment by stuartasutton** [comment]
@woodkri, @siuc-nate, I'd like to also to check whether the example was entered by hand through the editor or otherwise imported... is this possible to determine?

**Comment by woodkri** [comment]
@stuartasutton I noticed it here: https://github.com/CredentialEngine/vocabularies/blob/master/Competency-Frameworks/bcsp-asp.json.

**Comment by stuartasutton** [comment]
@woodkri:

Yes, the nodes were significantly out of order. I updated the file on github:

https://github.com/CredentialEngine/vocabularies/blob/master/Competency-Frameworks/bcsp-asp.json

The organization has 7 others in github and I'll work on those. The only reliable way is to walk through comparing it with the source and reordering accordingly

Let me know if there are sequencing problems still with this one.

**Comment by siuc-nate** [comment]
I think the larger question, from the developer perspective, is if there _is_ a conflict (in the future), what aspect of the data should be considered authoritative? The order of items in the `@list` array, or the order produced by processing `ceasn:listID`?

**Comment by stuartasutton** [comment]
The @list is ABSOLUTELY the authority...and the advice is that when you enter data, the order in which you enter and display it in the editor is the order in which it will be enforced. If the person creating  (or editing) a framework misses the node with listID "d" and then adds it, it is incumbent on them to move it to the position between "c" and and "e".

**Comment by stuartasutton** [comment]
Is there any way this fix can be pushed to production? The production edit's version of the Beta Credentials Framework remains out of sync even though the same data in the Credential Finder is in correct order. We cannot do any editing on the production editor involving moving nodes if what we see is not what we get.

**Comment by siuc-nate** [comment]
The order is seemingly completely random:
![image](https://user-images.githubusercontent.com/21346519/52666427-e36c1800-2ed3-11e9-9301-c9a9c104c184.png)

**Comment by siuc-nate** [comment]
See also #127

**Comment by woodkri** [comment]
@siuc-nate The order in the Editor was originally based on the order the nodes appeared in the import file rather than the hasChild lists. That's why they appear as they do in the Editor. I have a fix in, it just needs to be tested and deployed.

**Comment by stuartasutton** [comment]
@woodkri any idea how long it might take to wrap this up and get it deployed to the production editor?

**Comment by Lomilar** [comment]
cassproject/cass@5cf43ee038d1f40fa91dd2852286af685ff6e12f

**Comment by Lomilar** [comment]
Will be doing testing today, can deploy tomorrow.

**Comment by Lomilar** [comment]
Tested. To be included as part of 1.0.6.
