### ISSUE TITLE
Editable frameworks (or public frameworks) should be indicated by an "Editable" tag or a "Public" tag in the search.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#483]

**Comment by Lomilar** [comment]
Repeat for concept schemes.

**Comment by eddavies** [comment]
This seems to be popping up correctly for frameworks and concept schemes. @Lomilar should we have a tag for the opposite, like a "view only" tag?

**Comment by Lomilar** [comment]
I don't think so.

Feel free to toss this to usability if you feel strongly about it.
