### ISSUE TITLE
Should have a toggle that makes a framework public or private.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#484]

**Comment by Lomilar** [comment]
Frameworks should default to private.

**Comment by Lomilar** [comment]
@cwd-mparsons This may impact searching for CaSS data by id.

**Comment by woodkri** [comment]
This is ready for testing. I've added a couple of new parameters to cassEditorTestShell.html, so you can put the editor in concept mode, and/or default new frameworks to private when testing with a login. We had discussed a URL parameter for setting the default to public or private, so there is now a private=true parameter to set the default to private in addition to the ability to set individual frameworks within the editor.

As of now, imports are not being set to private by default. We can discuss if that's something we want to add, though I'm not sure how well it would work with different users being able to import the same ids.

**Comment by Lomilar** [comment]
#501 #502 - Related issues.

**Comment by Lomilar** [comment]
Import should be clear, for now, that the frameworks that are imported are public.

**Comment by eddavies** [comment]
For concepts, whenever I make a concept scheme private, I can never find it again, even though I'm the one who made it private.

**Comment by woodkri** [comment]
@eddavies Are you logged in or are you using user=self? If the latter, it might not be preserving your user. You can test with a login here: https://cassproject.github.io/cass-editor/cassEditorTestShell.html

**Comment by eddavies** [comment]
Ah. I was testing with user=self. Will test with the login.

**Comment by eddavies** [comment]
The concept scheme is indeed appearing using the Test Shell.

@woodkri Will this login be implemented on the ce site in some way? Because this issue still exists on ctitest.

**Comment by woodkri** [comment]
Ctitest does use a login so the user should persist.

There was a versioning issue that came up on ctitest that may have been causing this problem there. Do you still have concept schemes disappearing on ctitest now? There's one I just created and made private that's showing up in the search for me.

**Comment by eddavies** [comment]
Concepts scheme no longer disappearing on ctitest. Verified
