### ISSUE TITLE
CTDL-ASN JSON-LD import error/failure

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#485]
If the post request fails, it shows an error message and sends the user to a blank page. Instead, it should return the user to the import section after displaying the error in an alert (to be consistent with other import error messages).

**Comment by woodkri** [comment]
Discovered this on a local deployment. I don't think it's one Eddie will be able to test so assigning Fritz.

**Comment by Lomilar** [comment]
Seems to work fine to me.

Non-CTDL-ASN JSON-LD still doesn't import, but I believe this is known.
