### ISSUE TITLE
Made a new framework and added a new competency which didn't save

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#486]
<img width="960" alt="no new competency" src="https://user-images.githubusercontent.com/23706850/52085334-1a980c00-2559-11e9-8a04-c153369a64be.PNG">

First time this happened to me on ctitest.

**Comment by eddavies** [comment]
<img width="345" alt="f-12" src="https://user-images.githubusercontent.com/23706850/52085421-529f4f00-2559-11e9-841d-0cbb0f24df19.PNG">

**Comment by eddavies** [comment]
I can create additional competencies, but the back key to return to the framework list is not working.

**Comment by eddavies** [comment]
Could this be related to #459?

**Comment by eddavies** [comment]
Had this occur with a concept scheme today, not sure if related.

<img width="960" alt="concept scheme save" src="https://user-images.githubusercontent.com/23706850/52152607-c873eb00-262b-11e9-99f2-2db5ccf4409e.PNG">

**Comment by Lomilar** [comment]
Hm. We need reproduction steps here to proceed.

**Comment by siuc-nate** [comment]
Can this be closed?
@Lomilar @woodkri

**Comment by Lomilar** [comment]
OK to close. @woodkri Close when ready.
