### ISSUE TITLE
Should use getDisplayString() over direct array/"@value"

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#488]
viewFramework:626 should instead use Thing.getDisplayStringFrom(displayCompetency["skos:prefLabel"])

and everywhere else "@value" is referred to.

**Comment by woodkri** [comment]
I was planning to do this as part of code cleanup once some of these issues are out of the way. I discovered that function after I had already written most of the langstring code so @value is all over the place. Let me know if it's causing any functionality problems and I can bump it up in the priority queue if so!

**Comment by Lomilar** [comment]
No problem. It is causing some null pointer exceptions in some edge cases (like when competencies or frameworks don't have names).
