### ISSUE TITLE
Langstrings when initially created take on an index instead of a language.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#493]
Repro:

Go to a framework.
Create another name/title.
Give the title en-US, put something in there.
Save
Go edit the framework again.
1?

Or:
Go to a framework
Create another name/title
Give the title fr
Add title un francais.
Save
Go edit the framework again.
2?

**Comment by woodkri** [comment]
@Lomilar I was not able to replicate this issue using the steps above, but I did find a similar issue with multiples in fields that were not originally saved as langstrings and have fixed that. Please let me know if that solves the issue you were having or if it's still occurring.

**Comment by Lomilar** [comment]
Here's my repro. Am I doing something weird?

https://drive.google.com/file/d/10U-seXEpwyBw70wrEzDXTJ5jXLHF_3bm/view?usp=sharing

**Comment by woodkri** [comment]
@lomilar When I do exactly what you do in the video, the language always saves the first time. I've tried different browsers and a Linux VM and same thing. Is it possible whatever plugin is showing up in the input box on your screen is modifying the values in some way?

**Comment by Lomilar** [comment]
You're correct, it's related to the Grammarly plugin.
