### ISSUE TITLE
Share/Unshare a competency framework with a contact.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#498]
Should be able to share a competency framework with a contact, if said contact exists within the Identity Manager.

Sharing should be invisible unless contacts exist, and should not show up in CTDL-ASN mode.

**Comment by woodkri** [comment]
@Lomilar is this covered by sharing and user management capabilities in CaSS 1.3, or does this issue need to remain open?

**Comment by Lomilar** [comment]
Yes.
