### ISSUE TITLE
Support all CE-ASN data fields.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#5]

**Comment by miledivovic** [comment]
Implemented in d6b3c84.

Testing Steps:
1. Add ?ceasnDataFields=true to the url
2. The edit panel should have additional fields.

**Comment by eddavies** [comment]
Works. Is there anything additional to test with this except for, these extra fields are visible and editable?

**Comment by Lomilar** [comment]
Added to ce.html view.

Review:

- During view, most data fields have no label, making it unclear what they are.
- Concept Scheme should be disabled while the Concept Scheme Viewer/Selector isn't available. (it needs to select from controlled vocabularies or do search/autocomplete).
- What is required, recommended, and optional should be denoted.
- Missing weight.

**Comment by Lomilar** [comment]
- Fields, if empty, should not fill in the data field. see: https://dev.cassproject.org/api/data/schema.cassproject.org.0.3.Competency/5953ce05-ca7c-4584-9272-1510722275f9

**Comment by otterlove** [comment]
If I understand the issue, these values (circled in red) could be confusing as more obscure fields are displayed?
![ce-issue5-screen1](https://user-images.githubusercontent.com/3535069/32857858-309b31a6-c9fe-11e7-98e6-90aadc8f2ccf.png)

If so, I suggest making the labels visible, setting the "display" to "inline", set the "p" margins to zero and make them bold. Like so: 
![ce-issue5-screen2](https://user-images.githubusercontent.com/3535069/32857910-6397d988-c9fe-11e7-8135-53135e1c19ec.png)
Ultimately, putting the data in a table would make it flow better, but that might be messy with the existing structure.

**Comment by eddavies** [comment]
In this screenshot the highlighted field is the small "date created" in the bottom right. I cannot see what I'm entering unless I click the "page-down" button, which not all computer's keyboards have. If I tab past that field the browser window scrolls down, but then it becomes impossible to fill out the "date created" field with full vision unless the browser's window size is changed.
![date created cutoff](https://user-images.githubusercontent.com/23706850/33448661-7115e9b0-d5bb-11e7-8d8e-930c7d9ed55d.PNG)

**Comment by miledivovic** [comment]
Fixed in f522d17

**Comment by eddavies** [comment]
Works, but now the date field entries cannot be navigated through.

**Comment by eddavies** [comment]
Typing still works for these fields.

**Comment by Lomilar** [comment]
New fields: Concept Term and Education Level term -- Uses Concepts from schemes. Should take you to concept editor automatically when '...' is hit.

**Comment by eddavies** [comment]
works and saves, but found problems #73, #74, #75
