### ISSUE TITLE
Defaulting to en-US and editor's behavior

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#50]
It appears as though the editor defaults to "en-US" for language of both the framework and properties regardless of what someone enters. While not illustrated here, if the `inLanguage` property in both the `Competency` and `CompetencyFramework` templates are empty and if the user enters a language (e.g. "en-US"), the data outputs both:

```
"ceasn:inLanguage": [
      "en-US",
      "en-US"
    ],
```
 Setting a default makes sense --why should someone repetitively re-enter the language code; but, it should probably **show up in the entry template** where it can be accepted or over-written in cases where the English default is not correct (e.g., in the manner of the "New Competency" text with the name property (a separate conversation since it is a pain to continually have to remove the "New Competency" text where there is no name)).

So, below you see what happens when the user intentionally thinks he or she has left the `inLanguage` tag empty only to discover in the output that it's magically not empty:

<img width="1294" alt="screenshot 2017-11-25 09 25 44" src="https://user-images.githubusercontent.com/2939046/33232888-bf66636c-d1c2-11e7-809c-f5bd60813498.png">

```
[
  {
    "ceasn:name": {
      "en-us": "[Test] Language tags"
    },
    "ceasn:hasChild": [],
    "ceasn:inLanguage": "en-US",
    "@type": "ceasn:CompetencyFramework",
    "ceasn:ctid": "ce-9e9497cf-d32f-331e-96ae-265c6a879bec",
    "@id": "https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/e7ae0458-90b2-4002-badb-719a6894d7d5/1511630572838",
    "@context": "http://credreg.net/ctdlasn/schema/context/json?releaseID=20170929",
    "ceasn:description": {
      "en-us": "Testing defults and editor behavior with language tags."
    }
  }
]
```

**Comment by Lomilar** [comment]
inLanguage is a required field [for the registry profile](http://credreg.net/ctdlasn/mapping?profileID=registry) requirements, so we are populating it if it is missing.

We can omit this behavior but it'll fail to register.

**Comment by Lomilar** [comment]
The duplication of the field should be fixed as well.

**Comment by stuartasutton** [comment]
I've no problem with including the en-US default...although the editor should ultimately allow the data creator to set the default for a session/record to whatever language is appropriate. My problem is that it's currently always English with no way for the person creating the data to override the default. Eliminating the duplicate is good; but, you should nevertheless see the default language code ("en-US") in the field so the naive creator doesn't waste time and can override.

**Comment by Lomilar** [comment]
We now allow the framework creator to define it once in the framework and it becomes the default with any new or edited competency. Same behavior with author/creator.

**Comment by Lomilar** [comment]
Note: Not yet deployed to cass.credentialengine.org

**Comment by Lomilar** [comment]
Now deployed.
