### ISSUE TITLE
When adding competencies from another framework, private flag shows up.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#501]
Private flag should probably be moved to the editing side of the screen (right side) and maybe only in the edit window.

May also show up in view=true mode.

Adding a tag to the framework display (next to Editable) that is (Private) would be a good indicator that the framework is private.

**Comment by Lomilar** [comment]
Related to #500

**Comment by eddavies** [comment]
This is no longer occurring. Closing this, but found a possible related issue in #519.
