### ISSUE TITLE
New competencies that are nested (not at the top level) in a private framework don't seem to be made un-private when private is unchecked.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#502]
Repro:
* Create a private framework
* Create a new competency
* Create a new child competency
* Uncheck private
* Check the URI of the new child competency to see if it is private
Expected:
Is not private, returns fine.
Actual: 
Is not private, returns fine.

BUT

* Create a private framework
* Create a new competency
* Add a child competency from another framework (that I do not own)
* Add a child competency to the competency from another framework
* Uncheck private
* Check the URI of the newest child competency to see if it is private
Expected:
Is not private, returns fine.
Actual: 
Is private, does not return.

**Comment by Lomilar** [comment]
Related to #500

**Comment by woodkri** [comment]
Having trouble reproducing this. Is the issue when there are two children of the new competency, or a child and grand-child? I'm also assuming that this is with the "copy" option of copy or link? Both ways are working for me but I'll keep trying to replicate the issue.

**Comment by Lomilar** [comment]
This is with the link option, where I don't own one of the children, but I do own that child's child.

**Comment by woodkri** [comment]
Also - was this in the test shell or a different environment?

@Lomilar

**Comment by woodkri** [comment]
Ah, I did notice a problem with linking earlier so this may be fixed by https://github.com/cassproject/cass-editor/commit/f708bb7c3834732dc9011d1915ed5aa5ebf09834

**Comment by Lomilar** [comment]
This was on dev.

**Comment by Lomilar** [comment]
This is fixed from my perspective.
