### ISSUE TITLE
Can't drag and drop!

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#503]
Below is an editor image with nodes entered at the wrong level. No matter what I do to drag Task 10 over Task 9 to put it at the right level, it simply doesn't do it.

<img width="538" alt="screenshot 2019-03-04 10 29 58" src="https://user-images.githubusercontent.com/2939046/53754457-da35f180-3e68-11e9-9eba-569a6f21a29e.png">

Competency Framework: Surgical Technologists Certifying Examination

**Comment by Lomilar** [comment]
Is this still occurring? We fixed this instance during a call and were not able to reproduce.

**Comment by Lomilar** [comment]
Reopen if this is still happening, @stuartasutton
