### ISSUE TITLE
CTDL-ASN Import detection does not work with additional whitespace

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#504]
If `ceasn:competency   ` (see whitespace) is used in the type field, the detector to see if it is a CTDL-ASN import fails back to normal CSV.

**Comment by Lomilar** [comment]
There's a broader question of: If something doesn't go through the analysis quite correctly, do we display the error message that was generated in ruling it out (CTDL-ASN CSV vs CaSS / other format CSV)

**Comment by eddavies** [comment]
I believe this has been working for a while. Feel free to reopen there is still an issue with this.
