### ISSUE TITLE
Find functionality / enhancement delta between Competency Editor and Concept Scheme Editor

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#506]
For instance, arrow up and down, keyboard, drag and drop, etc.

**Comment by woodkri** [comment]
Candidate for closure. I think I've found most of the differences between the two editors. If we find additional ones we can open up new issues.

@Lomilar

**Comment by stuartasutton** [comment]
@woodkri, is this documented somewhere?

**Comment by woodkri** [comment]
@stuartasutton I've been creating new issues and commits as I find things, and linking to this issue.

**Comment by Lomilar** [comment]
Please re-open if there is additional follow-up required.
