### ISSUE TITLE
Import for SKOS kicks the concepts out of order.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#507]

**Comment by eddavies** [comment]
Tried testing using the default example provided on the the import screen, but encountered this error:

![error importing](https://user-images.githubusercontent.com/23706850/54382168-afa81d80-464c-11e9-8456-4246b34aa7dc.PNG)

**Comment by eddavies** [comment]
I get the same error when attempting to import a framework via JSON-LD.

**Comment by eddavies** [comment]
@woodkri is there a separate way of importing concept schemes to test this if the JSON-LD isn't working?

**Comment by eddavies** [comment]
I attempted to import the json-ld you gave me the other day @woodkri , but then it resulted in this:

![unknown](https://user-images.githubusercontent.com/23706850/54775147-8ea27800-4bca-11e9-8bf6-6ebd33bc15a2.PNG)

Did not kick me out of the editor, but doesn't seem like it imported correctly.

**Comment by woodkri** [comment]
@eddavies It looks like you're trying to import the concept scheme into the competency editor. Can you try  [here](http://ctitest.siuccwd.com/conceptscheme)? I'll create a new issue for importing the wrong type though, it should probably throw an error rather than try to import in that case.

**Comment by eddavies** [comment]
Oh my bad I was spaced out apparently.

**Comment by eddavies** [comment]
Still, will make a new issue related to that.

**Comment by eddavies** [comment]
Okay, this seems to be importing correctly in the concept scheme editor.
