### ISSUE TITLE
CTDL-ASN spreadsheet import should support all properties.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#509]

**Comment by woodkri** [comment]
Pull request in. Is this supposed to be able to handle other alignments as well?

**Comment by Lomilar** [comment]
See comments on PR. Up to you whether this should move forward as-is.

**Comment by woodkri** [comment]
I did think to myself - this would be a lot easier if we could just use the translation we use for JSON-LD. I have no idea how to accomplish that (compact, expand, etc) in that file though so I just continued the pattern that was there. Is it rs2 that it's written in?

**Comment by Lomilar** [comment]
Its in JS, it's the JSON-LD expand then compact during the import JS.
src/main/resources/c-adapter/ceasn/ceasn.js:639-643

**Comment by woodkri** [comment]
Oh I should have been more clear with my question, I meant the $get and $put and such in the java file. I now realize it's ST-JS. I'll do some more research into ST-JS and see if I can figure out how to make this work.

**Comment by woodkri** [comment]
Assigning @Lomilar for testing since this is in a branch of EC.

**Comment by Lomilar** [comment]
@siuc-nate @cwd-mparsons Would you like to test this using the data you have, or ship the data over and have us test?

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @siuc-nate @Lomilar use the DOL Industry Competency Models for this.  This is a usability issue.  A single, not two, CSV upload that allows for all properties needs to be available to all users.

**Comment by siuc-nate** [comment]
I had previously made some progress getting the DOL models into a suitable format for import. I was planning to target JSON-LD, but if it makes more sense to go the CSV route, I can do that.

@Lomilar if I use the isChildOf and isTopChildOf properties, will CASS auto-assign the inverse (hasChild/hasTopChild)?  Otherwise, how should I encode multiple values into a single cell?

**Comment by woodkri** [comment]
@siuc-nate For competency frameworks, the file should include isChildOf and isTopChildOf and the inverses will be assigned. You can download an example on the competency import page of the editor.

There's a small issue that came up with the translation contexts that we need to address before this can be tested though.

**Comment by stuartasutton** [comment]
Nate, you had done a normalized spreadsheet for one of the frameworks. I
did some color coding in that spreadsheet to define what parts of some of
the current literals in the sheet are actually  listIDs and
competencyCategories.

**Comment by siuc-nate** [comment]
Thanks @woodkri 

@stuartasutton Do you have a link to that spreadsheet?

**Comment by stuartasutton** [comment]
Yes, it is your "normalized" sheet at https://docs.google.com/spreadsheets/d/1UUKbrwXV4K64Mk7QM04_UrWev-G1jLFW-m7YSFR46-g/edit#gid=0

**Comment by siuc-nate** [comment]
Ah, yes, that makes sense - that sheet is still a work in progress, so I hadn't gotten to the stage of breaking those out.  It looks like we're thinking the same thing in terms of what pieces of the rawText column will end up in which fields, though.  Thanks.

**Comment by stuartasutton** [comment]
@siuc-nate, due to your review of the set that revealed two general patterns, we need to determine whether this normalized breakdown analysis nevertheless holds across the industry dataset. I suspect that it does hold.

**Comment by stuartasutton** [comment]
@siuc-nate, due to your review of the set that revealed two general patterns, we need to determine whether this normalized breakdown analysis nevertheless holds across the industry dataset. I suspect that it does hold.

**Comment by woodkri** [comment]
This can now be tested.

**Comment by Lomilar** [comment]
Q: Which are supported?
Everything in http://schema.cassproject.org/0.3/ceasn2cass

**Comment by Lomilar** [comment]
Q: How is multi value handled?
Comma Delimiting? Checking into this. @woodkri

**Comment by woodkri** [comment]
Multi value is only in place for concepts at the moment, but I will go ahead and add that for competencies as well. The best way I was able to get multiple values in a field to work was like this: "['entry 1', 'entry2']" (including all quotations). Just commas didn't work as delimiters since the fields are separated by commas.

**Comment by cwd-mparsons** [comment]
Could pipes (|) be used instead:
this is, entry 1 | this is entry, 2 | etc

It would be preferred to not have to use the quotations.

**Comment by woodkri** [comment]
Yes, I'll switch it over to use pipes. For example:
entry 1|entry 2

**Comment by Lomilar** [comment]
OK to test, need test document. Any current use cases?

**Comment by siuc-nate** [comment]
Steps to test:
1. Create a framework in CASS with a value for every property.
2. Create ~3 competencies, where at least one of the competencies has a value for all properties.
3. Export the framework as CTDL-ASN in CSV format
4. Purge the framework from CASS
5. Import the exported data
6. Validate that everything works

**Comment by siuc-nate** [comment]
Has this been tested?

**Comment by woodkri** [comment]
Marked working by QA.
