### ISSUE TITLE
Remove empty properties from jsonld data

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#51]
Currently, the BCSP json data at issue #47 contains properties with empty values; e.g., 

>`"http://schema.cassproject.org/0.3/level": [],`

>`"ceasn:name": {
      "en-us": ""
    },`

In the jsonld encoding, where there is no value, there should be no property.

**Comment by Lomilar** [comment]
Should be remedied for now. https://cass.credentialengine.org/api/ceasn/schema.cassproject.org.0.3.Framework/2714b9d9-0a08-4222-af88-58f4d6758f69/1511630182476

**Comment by Lomilar** [comment]
This now happens more aggressively.
