### ISSUE TITLE
Resource is not available encountered while searching for a concept scheme from a competency

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#512]
On the CTItest server:
http://ctitest.siuccwd.com/competencies
- selected and edited a competency framework
- selected to search for a concept term
- briefly was presented with message "requested resource is not available"

![image](https://user-images.githubusercontent.com/26332112/54215039-3c1fd800-44b5-11e9-965d-57c52b44475d.png)

**Comment by Lomilar** [comment]
You managed to hit that server during an upgrade. Give it another shot.
