### ISSUE TITLE
Concept Scheme Export as SKOS (Json-LD) requires some changes

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#513]
Per the Cass - ASN mapping spreadsheet:
https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1140243756

The inLanguage for both ConceptScheme and Concept should be a list of strings (currently a single string).
The creator for ConceptScheme should be a list of strings (currently single).
ConceptKeyword is supposed to be many per language. Instead of:
"ceasn:conceptKeyword": {
          "en-us": "Credential Engine"
        },
should be: 
"ceasn:conceptKeyword": {
          "en-us": ["Credential Engine", "second keyword"]
        },

The ChangeNote property (for both ConceptScheme and Concept) is output as:
        "http://www.w3.org/2004/02/skos/core#changeNote2": {
          "@value": "A change note",
          "@language": "en-us"
        },
and should be a language map list (many per language)
        "changeNote": {
          "en-us": ["A change note", "another note"]
        },
The historyNote property should be a list of strings, and is being output as: 
        "skos:historyNote": {
          "@value": "http://credentialengine.org",
          "@language": "en-us"
        }
The properties: skos:altLabel, skos:hiddenLabel, and skos:note, are being output as JSON-LD language strings:
        "skos:altLabel": {
          "@value": "Home dog",
          "@language": "en-us"
        },
rather than CTDL language map lists (many per language)
        "skos:altLabel": {
          "en-us": ["alt label one", "alt label 2"],
          "fr": ["Le label Un"]
        },

**Comment by woodkri** [comment]
@cwd-mparsons I'm working on getting the arrays in the right places and changing historyNote into a list of URLs rather than langstrings.

I believe the other changes will need to be made to CE's context here: http://credreg.net/ctdlasn/schema/context/json. The skos:changeNote field is defined there as a URL rather than a langstring. These fields are not defined in the context at all, so they're not translating properly: skos:altLabel, skos:hiddenLabel, skos:note, skos:historyNote, skos:notation.

**Comment by stuartasutton** [comment]
@cwd-mparsons, in response to @woodkri note above, it is perhaps declared because skos:changeNote field is declared there as a URL  because of how @siuc-nate is using it for tracking CTDL term history. We need to talk this through.

**Comment by siuc-nate** [comment]
FYI: Yesterday I updated credreg.net to output skos:changeHistory instead of skos:changeNote (the value is still a URI).

**Comment by woodkri** [comment]
Is that meant to be skos:historyNote? I don't think skos concepts have a changeHistory property.

**Comment by siuc-nate** [comment]
skos:changeHistory was based on some emails back and forth between @stuartasutton and myself - however, it does look like skos doesn't have that property (or any property that is meant to be a URI that points to history data, as far as I can tell.  Confusingly it does have both changeNote and historyNote, both of which appear to be langstrings).

Stuart, should that be meta:changeHistory instead of skos:changeHistory?

**Comment by stuartasutton** [comment]
Use meta:changeHistory. The note properties in SKOS are all intentionally langString.

**Comment by siuc-nate** [comment]
@stuartasutton related question - what should our context file point to as the URI for cs as used in our history data (e.g. http://credreg.net/ctdl/termhistory/orgType/Collaborative/json )? We uncovered in today's meeting that the definition for this is missing.

**Comment by Lomilar** [comment]
@woodkri Action to be taken here to make sure we jibe with the discussion.

- [ ] CE SKOS Profile should publish meta:changeHistory
- [ ] CE to update Spreadsheet with skos properties if there is reason to be a langstring or URL for changeNote or historyNote.
- [ ] skos:historyNote to be added to CE @context for SKOS if CE observes its use.

**Comment by Lomilar** [comment]
@stuartasutton Should skos:historyNote in the spreadsheet be a URL or a langstring? How would an individual use historyNote?

**Comment by stuartasutton** [comment]
Nate, not sure what you are asking at https://github.com/cassproject/cass-editor/issues/513#issuecomment-474992115

**Comment by stuartasutton** [comment]
A email message from a while back (2005) from Alistair Miles:

One way to think about historyNote vs. changeNote is that a history note documents a change to a concept for public consumption and a changeNote documents a change to the  thesaurus management system usually for non-public consumption.

For example the thesaurus management system may automatically create change notes when an editor checks in a change to a concept or group of concepts in the thesaurus.  This might look like:

>`<skos:changeNote xml:lang='en'>`Checked in 2005-08-03T13:30:00-04:00 by userX. Check in comment: completed changes to all concepts relating to pears.`</skos:changeNote>`

But the history note might read:

>`<skos:historyNote xml:lang='en'>`Pears were previously listed as a narrower term under vegetables instead of fruits.`</skos:historyNote>`

**Comment by siuc-nate** [comment]
@stuartasutton 
>Nate, not sure what you are asking at #513 (comment)

Our history JSON data uses a "cs" prefix, but this prefix isn't defined anywhere in our context.  Where should it point to?

**Comment by stuartasutton** [comment]
http://vocab.org/changeset/schema#

You might as well add the other change properties from the vocabulary that we are currently not using.

**Comment by siuc-nate** [comment]
Thanks.

I have updated the context to point to http://vocab.org/changeset/schema#.

**Comment by Lomilar** [comment]
Are we at a spot to close this?

**Comment by woodkri** [comment]
I have a pull request for the schema change on our end. skos:historyNote still needs to be resolved - either added to CTDL context or removed from our export if it's not going to be used. If it's a langstring I'll need to update that too since I have it defined as a URI per the spreadsheet.

**Comment by siuc-nate** [comment]
So if I understand correctly:

- skos:changeHistory (which will be changed to meta:changeHistory in the next credreg update) is a URI
- skos:historyNote is a langString, and is missing from the CTDL context (this will also be added in the next update)
- skos:changeNote is a langString, and is present in the CTDL context

Correct?

**Comment by woodkri** [comment]
skos:historyNote is defined as a URI in the spreadsheet so that's how we have it in the editor. I can change it if it should be a langstring instead.

My understanding is that other than that, those points are all correct.

**Comment by cwd-mparsons** [comment]
@woodkri Yes, I just updated the spreadsheet to change historyNote to a langstring, one per language.

**Comment by cwd-mparsons** [comment]
Testing the export and noticed that the editor does not have source:

![image](https://user-images.githubusercontent.com/26332112/54789636-228f3680-4c01-11e9-895c-9c2db80a5b70.png)

**Comment by woodkri** [comment]
Got it, I'll change historyNote to a langstring, one per language.

I noticed yesterday that source was added to the spreadsheet for concept schemes, I just need to know which section of the editor it should appear in and I'll add it.

The lists such as inLanguage will be updated with the next deployment of CaSS to dev. That fix is in, it's just not live on the dev server/ctitest yet.

**Comment by stuartasutton** [comment]
It should be in the top ("general"?) section.

**Comment by woodkri** [comment]
I think the only thing remaining for the export is skos:historyNote, which Nate mentioned above will be added in the next update to the context. Does this issue need to address anything else or are we at a point we can close it out?

**Comment by siuc-nate** [comment]
Per our 4-3-2019 meeting:
This issue has been taken care of and has been tested.  @cwd-mparsons will reopen this issue if further testing proves a need to do so.
