### ISSUE TITLE
ExactAlignment is being exported as a single string, needs to be a list

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#515]
In the CaSS-ASN mapping spreadsheet, exactAlignment is defined as a repeating URI.
https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803

![image](https://user-images.githubusercontent.com/26332112/54309261-c5aad500-459d-11e9-9792-089d1b62fcd4.png)
On export of a competency with a single exact alignment, it is a single string. If there are multiple URIs, they are properly exported as a list

![image](https://user-images.githubusercontent.com/26332112/54309403-128eab80-459e-11e9-98a1-4b8fb915416b.png)

Also, how can an exactAlignment be removed from a competency! See: Certified Chef de Cuisine.

**Comment by stuartasutton** [comment]
@cwd-mparsons, that is correct, it can have from 1-n exactAlignments. 

Unlike, hasChild and isChildOf, other relationships (connections) are not autogenerated and can simply be deleted via the editor. I looked at Certified Chef de Cuisine and don't  understand your question--I see no exactAlignment (but did not walk through lo0o0king at every node).

**Comment by cwd-mparsons** [comment]
@stuartasutton. I talked to Fritz regarding not being able to delete the exact alignments. He noted that an issue occurs when the URIs for exact alignment are http and the site is https. The issue results in the remove icons (X) not being displayed.  

![image](https://user-images.githubusercontent.com/26332112/54366156-2853ad80-463e-11e9-98a3-070701222bda.png)

**Comment by eddavies** [comment]
Verified on test. Creating new issue concerning the missing "x" for deleting matches.
