### ISSUE TITLE
Searching for data fields that open the concept scheme editor causes panel overlap issues

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#520]
Searching for a concept term to add to a concept scheme:

![was searching for concepts within concept schemes](https://user-images.githubusercontent.com/23706850/54380597-162b3c80-4649-11e9-99f9-f0e32d6f89de.PNG)

On ctitest:

![concept scheme editing](https://user-images.githubusercontent.com/23706850/54380840-a23d6400-4649-11e9-8222-80475c974b23.PNG)

Heading appears twice when creating/editing a concept scheme.

![search weirdness](https://user-images.githubusercontent.com/23706850/54380850-a7021800-4649-11e9-8b11-75df49c8d365.PNG)

**Comment by woodkri** [comment]
The first part should be fixed by https://github.com/cassproject/cass-editor/commit/a20e0d234e40750702eefe7f40d7369d6a52cff8.

The second brings up a bigger question - should users be able to edit concepts within the competency/framework editor? This was necessary when CE didn't have a concept scheme interface but may not make sense anymore.

**Comment by Lomilar** [comment]
Leave it to an URL configuration option. There are reasons either way.

**Comment by woodkri** [comment]
URL configuration in place.

I would be in favor of keeping the two headings in Eddie's photo above, to show how many levels in the user is - they're linking to a concept that they're editing before linking to another concept or competency at that point. I can remove display of one of the headers though if that's preferred.

**Comment by eddavies** [comment]
Bug fix, verified

@Lomilar do we want the workflow of attempting to add a concept term to a framework, and being able to create a new concept scheme from that desire to be disabled? Because with the url parameter you cannot edit concept schemes while search for levels, or terms to be added.

**Comment by Lomilar** [comment]
That is correct. The URL parameter limiting the edit of schemes (correctly?) implies there is another screen for editing concept schemes. This is true in the CE use case, for instance.

**Comment by eddavies** [comment]
Okay thanks. This has been fixed, closing
