### ISSUE TITLE
Add button not present when looking for concept related data fields to add to framework

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#521]
![add button gone](https://user-images.githubusercontent.com/23706850/54381789-d6b21f80-464b-11e9-81c3-bd7cd6ae9a7d.PNG)

**Comment by eddavies** [comment]
Not entirely sure how this happened, but there has been some weird issues with searching for concept terms, levels, etc. such as, #520

**Comment by woodkri** [comment]
@eddavies Do you have any steps to reproduce this?

**Comment by eddavies** [comment]
Have not been able to reproduce, this may have been fixed alongside #519 or something similar.
