### ISSUE TITLE
Can a post message be added to the end of an import to notify the publisher of a successful upload

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#522]
@Lomilar 
Currently information about a framework in CaSS is sent to the publisher whenever a user saves a framework or competency. 
However, if a framework is uploaded and never edited, the publisher will not have a record of the framework. 
We would like to have a post message added at the end of a successful import to notify the publisher of the existence of a new framework.

**Comment by Lomilar** [comment]
OK.

**Comment by woodkri** [comment]
Looks like most of the imports already had this, the message is "importFinished". I added one for JSON-LD imports as well.

**Comment by eddavies** [comment]
Verified on test server.

**Comment by tejaswidaruvuri** [comment]
@Lomilar I am working on the import to notify the publisher on a successful upload, I am using the "Import finished" to listen to the messages. When the "Framework is changed" I get back the CTID, Framework name etc., 
![image](https://user-images.githubusercontent.com/27224483/56304280-6a6f8380-6103-11e9-8cd2-cccde64e7b5f.png)

But for the Import Finished the only thing I get back is the Framework URI
![image](https://user-images.githubusercontent.com/27224483/56304373-9a1e8b80-6103-11e9-82f9-2cb8849228c7.png)

I need the framework name, CTID and orgCTID to be populated. Can you please make changes and let me know.

**Comment by woodkri** [comment]
@tejaswidaruvuri This is changed on ctitest. It will be changed on production with our next deployment.

**Comment by tejaswidaruvuri** [comment]
![image](https://user-images.githubusercontent.com/27224483/56427652-45554f00-6282-11e9-9d55-cab24bef3d58.png)
@woodkri Earlier after the import it used to show Import finished an event and show nothing in it. Now it is not changing from the status "View Changed" it is not considering the import being successfully updated.

**Comment by woodkri** [comment]
@tejaswidaruvuri My apologies, I had a misnamed variable in the message for the JSON-LD import.

From the console messages you're seeing though, it looks like you might be having a mixed content issue since your local server is https and one of the files used in translation is http.

If my change to the variable name doesn't fix this, we would need to address the mixed content issue. Ctitest is not loaded over https so you should be able to see the import finished messages there.

**Comment by eddavies** [comment]
Are we clear to close this issue? I see the changes in the post message now. Is there anything else we're missing here?

**Comment by woodkri** [comment]
@tejaswidaruvuri Are we providing enough information in the post messages now?

**Comment by tejaswidaruvuri** [comment]
@woodkri I am sorry I didn't respond to your reply, I was on vacation for the past two weeks. It is working now. I just tested it. Thank you.
![image](https://user-images.githubusercontent.com/27224483/57256543-7e304a80-701c-11e9-8407-53e9ffa6a0bc.png)
