### ISSUE TITLE
complexityLevel for beta Connecting credential disappeared

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#523]
With the beta Credentials Framework  of competencies, the display of the complexityLevel property value as expressed in the separate concept scheme of levels has disappeared from the tree display. It was there before and now it is gone.

**Comment by Lomilar** [comment]
I've experienced this as well, but am currently unable to reproduce it. Recent attempts show the complexity level. I think some aspect of editing removes it.

**Comment by woodkri** [comment]
Possibly related - I was toggling a framework public/private several times and the connections disappeared. I may or may not have navigated to a competency while the framework was in edit mode. Framework and competencies are using newObjectEndpoint. Still need to nail down steps for reproduction but grabbed a couple of screenshots.

![connections disappeared](https://user-images.githubusercontent.com/33300923/55038644-eccec100-4ff7-11e9-9466-692597a8556d.PNG)
![connections disappeared2](https://user-images.githubusercontent.com/33300923/55038645-eccec100-4ff7-11e9-84ff-2caa5b591d20.PNG)

**Comment by woodkri** [comment]
Complexity level is not showing up in the selector iframe.

**Comment by woodkri** [comment]
If a competency has a complexity level, the field is now visible on the righthand side within the competency selector.

**Comment by stuartasutton** [comment]
Over the weekend (2019-04-21/22), I entered a very large competency framework into ctitest and encountered this problem again. Occasionally, the complexityLevel field is not present; but, if you go ahead and fill in what you can, save and re-enter the record, competencyLevel will be present. When it occurs, that save/re-enter behavior is consistent.

**Comment by woodkri** [comment]
@stuartasutton Thanks for letting us know this is still an issue. The field was not present when editing a competency or when viewing one? Was this a framework that you imported and then edited, or created from scratch?

**Comment by stuartasutton** [comment]
When entering a new framework. It's in editing. The input template just disappears.

**Comment by woodkri** [comment]
Repro: Add new competency. Type in a relation URI in the complexity level field. Hit enter. Right side is still in edit mode but all editable fields have disappeared except for Competency Text, Comment, and Connections panel.

**Comment by eddavies** [comment]
This seems to be working with this fix. Feel free to reopen if this happens again.
