### ISSUE TITLE
Privacy changes are changing ids on ctitest

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#524]
Displayed id becomes https://sandbox.credentialengineregistry.org/resources and ctid: resources. Ctid appears to be correct in the console, and id is something like https://sandbox.credentialengineregistry.org/resources/1552933010416

**Comment by eddavies** [comment]
This seems to be working now. However, changing privacy of frameworks on ctitest can cause the editor to freeze, especially with big frameworks.

**Comment by Lomilar** [comment]
Optimization of this will occur with eduworks/ec#22

**Comment by Lomilar** [comment]
Just to check, are we using the asynchronous modes of functions to do encryption? They are much much much faster.

**Comment by woodkri** [comment]
I have the synchronous versions in there now, I'll look into using the Ec async helper to speed this up.

**Comment by eddavies** [comment]
The duplication is no longer occurring but running into an error where competencies are disappearing. Below is a screenshot of where I created a new framework then copied over 160 competencies from an existing framework then attempted to make the framework private:

![added private](https://user-images.githubusercontent.com/23706850/55745798-eaec0100-59ec-11e9-8a69-740d21e84cd2.PNG)

Additional console errors:

![console of private](https://user-images.githubusercontent.com/23706850/55745800-ed4e5b00-59ec-11e9-99af-9fbe659ae9e6.PNG)

**Comment by woodkri** [comment]
@eddavies I created a new issue for that since it's probably going to involve some bigger changes. Can you do some privacy testing on data that doesn't have any symbols and let me know if you find any other issues?

**Comment by eddavies** [comment]
Don't seem to be finding any. Will open a new issue if some are found.

**Comment by Lomilar** [comment]
Fixes for special symbols are on their way.
