### ISSUE TITLE
Subcompetencies not indented in tree

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#525]
![tree not indented](https://user-images.githubusercontent.com/33300923/54558737-d93aaf00-4994-11e9-976b-a462e2e03040.PNG)

Might be an isolated incident, I haven't noticed it anywhere else. These competencies are 6 levels deep and look like they were linked from another framework.

**Comment by woodkri** [comment]
The problem above is the opposite of what I thought it was. Computational Thinking Practices is a top-level competency in the framework so it should be all the way to the left.

To reproduce: Add a level to a competency that has another competency after it in the tree. The second competency is then indented to the same degree as the level. If you collapse the competency which has the level, the competencies go back to where they should be.

In the screenshot, New Competency should be at the same indentation as something new.

![Level indentation](https://user-images.githubusercontent.com/33300923/56608793-97c3a200-65d9-11e9-8b8a-75bf5ddbcf71.PNG)

**Comment by eddavies** [comment]
Subcompetencies seem to be indented correctly now.
