### ISSUE TITLE
Concept preferred label is showing autocomplete error on change

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#526]
![concept name autocomplete](https://user-images.githubusercontent.com/33300923/54562959-70f0cb00-499e-11e9-85a2-738621457144.PNG)

**Comment by woodkri** [comment]
Since a concept can only be part of one concept scheme, autocomplete is not enabled for concepts.

**Comment by eddavies** [comment]
autocomplete verified to be disabled.
