### ISSUE TITLE
Order of concepts in a concept scheme vary from user to user and time period

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#527]
We noticed that the order of concepts in a concept scheme vary from time to time. 
first time
![image](https://user-images.githubusercontent.com/26332112/54632091-532d6f80-4a4b-11e9-8626-5d3de54ae080.png)

next time
![image](https://user-images.githubusercontent.com/26332112/54632072-4872da80-4a4b-11e9-9a8e-5df9f2dac53c.png)

While on a webinar, another user reported seeing a different order than I see. 

On export, the order in the JSON-LD reflects the order seen in the list.

**Comment by woodkri** [comment]
A fix for this is coming with the next deployment.
#507

**Comment by cwd-mparsons** [comment]
Great, I will close this issue.
