### ISSUE TITLE
Checking/unchecking private on ctitest doesn't work the first time

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#528]
Looks like it checks and then unchecks. Will work the 2nd or third time. Possibly a race condition somewhere?

**Comment by woodkri** [comment]
Replicated on dev by adding url parameter newObjectEndpoint. Problem is occurring somewhere in repo.saveTo - when the encryption/decryption works, the server preview and response have the correct type. When it doesn't, the server returns the previous type. Status code of 200 in both cases.

**Comment by woodkri** [comment]
Fixed with update to EC: https://github.com/cassproject/cass-editor/commit/0996c1a1212105319a21b9955b9a67b0b6a4cf22

**Comment by eddavies** [comment]
Working for frameworks.

Working for concept schemes (except #536).

Verified
