### ISSUE TITLE
CEASN fields not updated properly after saving in edit panel

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#53]
Previously saved entries for Alternative Code Notation, Author, Creator, and Weight disappear in the edit panel after attempting to re-edit/make changes. (In below image, each field had an entry saved while initially editing, but here they are blank)
![ce fields](https://user-images.githubusercontent.com/23706850/33286545-89290a12-d36a-11e7-90d2-594caf8025a0.PNG)

They still however show up in JSON view, so they are being saved.
![json view](https://user-images.githubusercontent.com/23706850/33286527-748eebbc-d36a-11e7-9321-e4da479ce725.PNG)

**Comment by Lomilar** [comment]
Updated the writing of fields to the correct locations, but didn't update the reading of those fields. My bad.

**Comment by Lomilar** [comment]
Rewrote how properties are read and saved.

**Comment by eddavies** [comment]
All fields in framework editor are saved properly
