### ISSUE TITLE
Concepts should not have relations field

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#531]
Connections other than skos:broader and skos:narrower are currently being added as relations rather than skos:x.

**Comment by stuartasutton** [comment]
@woodkri, perhaps this text from an email to @siuc-nate and @cwd-mparsons will help (ignore it if not :-)

> Guys, sorry if this response is a bit pedantic, but skos has a property called ckos:related that in the world of thesauri construction is for pointing to a term that is semantically related but not in a broader/narrower sense. It has a super property of skos:semanticRelation. There is a property skos:relatedMatch that has super properties skos:mappingRelation AND skos:related. skos:relatedMatch is for pointing to a concept in some other concept scheme that is not just "related", but a close match in terms of identity. The skos:related is for general use for pointing to something that would be considered significantly "related"--e.g., "U.S. Civil War" might be skos:related "Abraham Lincoln" but would certainly not  be considered skos:relatedMatch (i.e., they certainly don't share an identity).
>
>Truth be told, our schema should have both. In fact, our context file for concept schemes should include ALL of the skos:properties even though our tool implementation might not (yet).

Hope this helps.

**Comment by Lomilar** [comment]
Hey Stuart,

The relations field being referred to here is the same relations that we use in competency frameworks. http://schema.cassproject.org/0.3/Relation -- Very obviously doesn't belong in skos.

**Comment by eddavies** [comment]
Verified on test. Feel free to reopen if this still occurs for whatever reason.
