### ISSUE TITLE
CSV Import Error

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#532]
Currently unable to import a csv file. I tried the sample csv file from the import page, and a framework Kevin and I made in the sandbox.cassproject.org.  We did not try to import a relation file.

Clicked on Browse, found the file and did not make any changes in the confirmation window, just clicked on import so and so items. 

This led to: In the console, there are a bunch of "failed to save competency" errors before being sent to the google home page.

**Comment by eddavies** [comment]
CSV import is working again!

In the workflow that Kevin and I used to create a framework in one instance, then export, then import our framework into CaSS (separate instance), there is a big problem in that the export did not export a relations file. So after importing the framework we made, there is no hierarchy of competencies. There should be a way to export a relations file or provide a similar solution.

**Comment by woodkri** [comment]
@eddavies Can you point me towards the framework you tried to export? I got a relations file for the one I tried on dev.

**Comment by eddavies** [comment]
@woodkri it's possible that the one I exported was using too old of a version of CaSS. It was Eduworks QA Manager Framework from sandbox.cassproject.org

**Comment by woodkri** [comment]
Ah I tried that one and got a little popup from chrome at the top of the page that said the page was trying to download multiple files. I had to click to allow it, and then the relations file was downloaded as well.

**Comment by Lomilar** [comment]
^ What Kristin said is often the problem.

**Comment by eddavies** [comment]
Ah I see it now, thanks for the heads up. I think we can close this issue then.
