### ISSUE TITLE
Publishing error in updating a competency framework

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#533]
I upodated the name of the Connecting Credentials Framework and saved the edits--the approval worked, and then the following on attempting to republish:

<img width="1216" alt="Screenshot 2019-03-26 14 21 12" src="https://user-images.githubusercontent.com/2939046/55034537-dbbf8900-4fd2-11e9-943c-ca28ea1c2a75.png">

**Comment by cwd-mparsons** [comment]
@Lomilar 
The competency framework description is supposed to be a langstring, one value only. 
It has been changed to be a list of lang string
Current export: 
![image](https://user-images.githubusercontent.com/26332112/55035419-efc0b600-4fe5-11e9-8445-18ed1e902b48.png)

Previous value 
https://credentialengineregistry.org/resources/ce-c62c336f-a76d-4d7f-a777-367e7cc72d17 
![image](https://user-images.githubusercontent.com/26332112/55035475-0f57de80-4fe6-11e9-8fe6-007b0777ec69.png)

**Comment by Lomilar** [comment]
In https://cass.credentialengine.org/api/data/ba13a98298ab5fea4188f4bd3dacdc66

Description has two langstrings, one is en-us and the other is en-US.

The check whether there is only one string for each language should probably be case insensitive. I expect that it currently is not.

**Comment by cwd-mparsons** [comment]
I removed the extra lang string. Now the description gets exported as expected. 
@stuartasutton I tried to publish the framework and received errors that creator and dateCreated were missing. I had recently added edits for the latter. I was able to manually add the creator and for now disabled the check for date created. I was then able to publish the Beta framework. 
I created a separate issue for the missing dateCreated: #534.

**Comment by siuc-nate** [comment]
Can this be closed?

**Comment by stuartasutton** [comment]
Before closing, I have a question. I see no reason that the description could not be present in more than one language; e.g., a Canadian framework that has the description in English and French as the law requires.

**Comment by cwd-mparsons** [comment]
@stuartasutton the description is still a language map. The issue was it was being exported as a language map list, like used for say keywords.
