### ISSUE TITLE
In the export, Date created is missing from older frameworks and concept schemes

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#534]
I tried to publish the Beta framework and got errors on missing creator and dateCreated. 
I could manually update the creator, but cannot update dateCreated (as would be expected).

With newer frameworks and concept schemes, the date created is present in the exports. 
Can the date created be systematically populated?
Also, could the creator be populated if missing? I am not sure if the latter is available behind the scenes.

**Comment by Lomilar** [comment]
- [ ] Batch process to update everything without a created date to have a created date.
- [ ] When an object is edited that doesn't have a created date, extract the created date from the @id if possible (won't be possible with newObjectEndpoint specified objects) or use Date.now().

**Comment by woodkri** [comment]
Here's the script to add schema:dateCreated to concept schemes and concepts that don't already have it. I've run it on dev already but someone will need to add CE's private key to run on production. It can be run with node from any machine (it doesn't need to be run from the server).

`require("cassproject");
EcRemote.async = false;
var repo = new EcRepository();
repo.selectedServer = "https://cass.credentialengine.org/api/";

var m = new EcRemoteIdentityManager();
m.server = repo.selectedServer;

var search = "(*)";
credentialEngine = new EcIdentity();
credentialEngine.ppk = EcPpk.fromPem("private key here");
EcIdentityManager.addIdentity(credentialEngine);

EcConceptScheme.search(repo, search, function (cs) {
    for (var i = 0; i < cs.length; i++) {
        var c = cs[i];
        if (c["schema:dateCreated"] == null || c["schema:dateCreated"] === undefined) {
        var date = new Date().toISOString();
        c["schema:dateCreated"] = date;
        repo.saveTo(c, console.log, console.log);
    }
    }
}, function (failure) {
    console.log(failure);
},{size:5000});

EcConcept.search(repo, search, function (cs) {
    for (var i = 0; i < cs.length; i++) {
        var c = cs[i];
        if (c["schema:dateCreated"] == null || c["schema:dateCreated"] === undefined) {
        var date = new Date().toISOString();
        c["schema:dateCreated"] = date;
        repo.saveTo(c, console.log, console.log);
    }
    }
}, function (failure) {
    console.log(failure);
},{size:5000});`

**Comment by cwd-mparsons** [comment]
@woodkri I may need a little more instruction. 
By node, do you mean node.js? I have no experience with the latter. Is this script to be saved as .js, and then run under a context like node.js or some other tool? A quick search reveals:

> Getting Started with NodeJS
> This guide assumes you have installed and configured NodeJS/NPM.

So I would first start with the latter configuration?

**Comment by woodkri** [comment]
@cwd-mparsons That's correct, I mean node.js. The script would be saved as .js, and run in a console window with `node fileName.js`. You would need to first install node.js and within the folder that the file you want to run is located, you'd run `npm install cassproject` to install the CaSS package.

If it's easier I can run the script, I just don't have the key for production.

**Comment by woodkri** [comment]
Both check boxes above are done.

@lomilar This won't be an easy one for Eddie to test so I'll leave it to you close it out if it's resolved.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @woodkri is this completed so we can take it off the open items list tomorrow>\?

**Comment by woodkri** [comment]
@jkitchensSIUC It's been completed but still needs to undergo testing before we close the issue. I don't believe there's any discussion needed during our meeting tomorrow though.

**Comment by cwd-mparsons** [comment]
@woodkri I imported a concept scheme and then exported it. The property name is incorrect: http://purl.org/ctdlasn/terms/dateCreated and should be ceasn:dateCreated. Note that if a concept scheme is created in CaSS and then exported, the correct property is present. 
NOTE: In the import file, I included:
"ceasn:dateCreated": "2019-04-09"

![image](https://user-images.githubusercontent.com/26332112/55837310-9b89fb80-5ae6-11e9-8363-e3221e1c84bd.png)

**Comment by woodkri** [comment]
The translation from ceasn:dateCreated to schema:dateCreated was missing in the import context. A fix is coming with the next update to our schema.

**Comment by cwd-mparsons** [comment]
I can change the created date to use schema:dateCreated. The downloadable template didn't have dateCreated, so I was not sure which format to use.

**Comment by Lomilar** [comment]
The schema has been deployed.

**Comment by cwd-mparsons** [comment]
@woodkri 
I republished two older frameworks today. The dateCreated was set to today in the export. 
Per the earlier post from April 9, 2019, shouldn't the dateCreated have been set to at most 2019-04-09 for existing frameworks?


![image](https://user-images.githubusercontent.com/26332112/58841854-4cb59980-8631-11e9-88ff-dc3575605940.png)


I checked another framework. I didn't update this today, yet on export, the created date and modifed date are today (ctid: ce-ca7bb1ab-1000-4e23-91b2-54f46ddbc1d0):
![image](https://user-images.githubusercontent.com/26332112/58842104-4b38a100-8632-11e9-8a5a-689cc02d5161.png)

**Comment by woodkri** [comment]
Apologies, it looks like I ran this script for concept schemes and concepts but not frameworks and competencies. I will run it for frameworks and competencies as well.

We also should add the date created as part of the import process.

**Comment by woodkri** [comment]
https://github.com/cassproject/cass-editor/issues/548#issuecomment-500540318

**Comment by woodkri** [comment]
dateCreated can be added to CTDL and Case imports that don't already have that field when it's defined in the template. For example:

EcFramework.template["schema:dateCreated"] = ""

**Comment by siuc-nate** [comment]
What is the status of this?

**Comment by woodkri** [comment]
@Lomilar Did you add dateCreated to the templates as part of #548?

**Comment by Lomilar** [comment]
Yes, that has now been done.

**Comment by woodkri** [comment]
This worked for me server-side with a CASE import. I don't see the dateCreated or inLanguage fields in the templates client-side though. I believe that adding them to the "template" postMessage sent to the CaSS iframe is the last piece missing here.

**Comment by siuc-nate** [comment]
Has this been fixed?

**Comment by woodkri** [comment]
@siuc-nate For the dateCreated and inLanguage fields to be added for client side imports, they need to be added to the "template" postMessage that CE sends to CaSS.

**Comment by jeannekitchens** [comment]
@siuc-nate is following up on this.

**Comment by siuc-nate** [comment]
In Language is set by default for frameworks already, and is not a property that users can add for competencies.

I have checked in the template change for inLanguage, it should make its way to the servers as part of the normal update processes.

**Comment by jeannekitchens** [comment]
On production as of March 16th. Closing this issue.
