### ISSUE TITLE
Newly created frameworks don't show up in the framework list unless the page is refreshed

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#535]
If you create a new framework then click on the back button to return to the framework list, your newly created framework will not appear, unless the page is refreshed. Perhaps the back button should cause a refresh?

**Comment by Lomilar** [comment]
Needs to be informed by https://github.com/cassproject/cass-editor/issues/487, which caused this.

**Comment by eddavies** [comment]
Sometimes editing the framework name doesn't update after clicking back:

![origin name](https://user-images.githubusercontent.com/23706850/56605935-098bf380-65ba-11e9-895a-5e82004dd1ae.PNG)

![name on list](https://user-images.githubusercontent.com/23706850/56605938-0abd2080-65ba-11e9-9caf-0357cae18bfd.PNG)


Additionally:

Nothing actually broke in this test, the framework list was populated and all my changes were saved, but if you change the name of a framework and quickly click the back button to return to the framework list, you can get this error on ctitest (not always reproducible, seems to happen when the framework name takes an extra second to change and get highlighted in green):

![weird error message](https://user-images.githubusercontent.com/23706850/56605680-85397080-65b9-11e9-88ba-81f4806fafd8.PNG)

**Comment by woodkri** [comment]
I disabled the back button until the save is finished so hopefully that fixes the second issue! If not, I'm not sure what else we can do since it's a CE error message.

**Comment by eddavies** [comment]
My framework saved instantly, and was able to see it, but I did get that CE error message. Not sure if we can do anything about it then? If not, we can probably close this issue.

**Comment by eddavies** [comment]
Deleting a framework or concept scheme does not update the list immediately after deletion and requires a refresh.

**Comment by woodkri** [comment]
I realized the code I just committed will probably not change things. They're deleting on my end though - is this happening for any framework that you delete, or just brand new ones you created, etc? Which URL are you seeing this at?

**Comment by eddavies** [comment]
I'm no longer running into this and am unable to reproduce the issue. Will reopen if I manage to cause this to happen again.
