### ISSUE TITLE
Possible to duplicate concepts when making a concept scheme private

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#536]
I imported the example concept scheme and went to make it private on ctitest. Below you can see that several concepts have been duplicated after I made the scheme private:

![duplicates but fix themselves](https://user-images.githubusercontent.com/23706850/55104246-43cfa700-5087-11e9-9d44-c8a9ab90e7bb.PNG)

**Comment by eddavies** [comment]
This doesn't happen every time and apparently when it does, entering back into the concept scheme fixes it.

**Comment by eddavies** [comment]
I just tried to import the same concept scheme and this happened just after the import finished:

![imported scheme](https://user-images.githubusercontent.com/23706850/55744907-ec1c2e80-59ea-11e9-9941-8fa7cdc9ca4e.PNG)

The concepts are not appearing and the Keys header is cutoff.

**Comment by eddavies** [comment]
![import scheme console](https://user-images.githubusercontent.com/23706850/55745455-1de1c500-59ec-11e9-9368-5d6c47b84357.PNG)

**Comment by woodkri** [comment]
#540

**Comment by woodkri** [comment]
Looks like the concept scheme was not encrypted but the concepts were - that might have been a holdover from prior testing. They're all public now and I can see all of the concepts. I tried reimporting too and had no issues.

**Comment by eddavies** [comment]
works now. closing this
