### ISSUE TITLE
Concept Matches cannot be deleted

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#537]
The "x" to delete matches for concepts does not exist. 

![missing x](https://user-images.githubusercontent.com/23706850/55107803-6d8ccc00-508f-11e9-9937-c9a1105d5933.PNG)

**Comment by eddavies** [comment]
#515

**Comment by eddavies** [comment]
This seems to be working now. Found a separate issue with matching however, closing this and opening a new one.

**Comment by cwd-mparsons** [comment]
@woodkri Reopening this issue. There is no delete (X) options for related matches etc. 
![image](https://user-images.githubusercontent.com/26332112/55512005-9d0b7d80-5627-11e9-8a52-7ac64ff415c2.png)

This occurs on both ctitest and production.

**Comment by woodkri** [comment]
@cwd-mparsons They're showing up for me:

![conceptsDelete](https://user-images.githubusercontent.com/33300923/55585007-a82bdf80-56f3-11e9-84d4-27435a69c1a9.PNG)

What browser are you using, and are there any unusual messages in the console that might help me diagnose the issue? A hard refresh might fix it too, if you haven't already tried that.

**Comment by cwd-mparsons** [comment]
I get the same scenario with Chrome and Firefox.

However, I see that while the X does NOT appear when I  edit a concept, it does appear when viewing the concept. That is, if I just click the concept on the left, and do not click the edit button, an X is shown and is clickable. 
Is that the intent? It would seem confusing if data can be updated (or deleted) without explicitly editing an item.

**Comment by woodkri** [comment]
You're right, and it's that way for competencies too. I'll flip those from viewMode to editMode.

**Comment by eddavies** [comment]
These have been correctly swapped with the new commit. Feel free to reopen if problems still occur.
