### ISSUE TITLE
Error saving matches to concepts

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#538]
If you create say a close match, then go to create an exact match, you will be brought to the last location of where you created the close match, and if you add the same matches from that page, the matches will not save in the editor. Additionally, sometimes even exiting that concept scheme and entering into another to add concepts causes this to happen. Trying to reproduce this more consistently.

Also, users should be brought to the list of concept schemes by default.

**Comment by woodkri** [comment]
You're saying you can't save the same concept in two different connection fields, right? I think that is expected behavior. To clarify though - if you're adding a connection and go to a different scheme to add a different concept, that concept doesn't always save either? That part is a bug if so.

I'll look into taking the user to the list of concept schemes each time.

**Comment by eddavies** [comment]
Okay after further testing, something strange is going on I think. However it's not the issue I described before, cause some of it is intended behavior.

Below I made an exact match to a concept named 3 in a separate concept scheme and it duplicated my concept 1 on the list:

![matching](https://user-images.githubusercontent.com/23706850/55115979-10027a80-50a3-11e9-9804-6454baa8d016.PNG)

Here I created a concept scheme with concept "2", and made an exact match to "new concept" and this happened:

![matche duplicate](https://user-images.githubusercontent.com/23706850/55116020-36281a80-50a3-11e9-8b62-f9ff850fce31.PNG)

**Comment by eddavies** [comment]
I can't seem to add matches anymore:

![match add not there](https://user-images.githubusercontent.com/23706850/55745979-6baafd00-59ed-11e9-9e96-5d6b651749a8.PNG)

No add button present.

This concept scheme is not being shown:

![concept scheme not appearing](https://user-images.githubusercontent.com/23706850/55746063-a2811300-59ed-11e9-95fd-8d893ee29583.PNG)

**Comment by eddavies** [comment]
Just attempted to repro in a new incognito window and this did not happen. Not sure what happened before.

**Comment by woodkri** [comment]
Haven't been able to replicate the first scenario yet. If it happens again, let me know what the steps were to reproduce.

The second photo is happening because the framework title is so long. Fixing that one now.

**Comment by eddavies** [comment]
Fix verified
