### ISSUE TITLE
Error on download of competency framework

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#539]
I am getting the following error when trying to download the Beta Connecting Credentials Framework as Credential Engine ASN (JSON-LD):

>TypeError: null has no such function "toLowerCase"

**Comment by Lomilar** [comment]
Had some old code stuck in there. Should be working OK now.

https://cass.credentialengine.org/api/ceasn/ba13a98298ab5fea4188f4bd3dacdc66

**Comment by stuartasutton** [comment]
Working!
