### ISSUE TITLE
A Signature is Expired is still occuring

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#541]
There is a closed issue regarding the error: "A Signature is Expired"
https://github.com/Eduworks/ec/issues/15

Stuart reported this issue today. 
An end user will not know, or need to know to check the clock time on the local computer with internet time. 
This process should be updated to be more forgiving, and not put the onus on the user to make corrections.

**Comment by Lomilar** [comment]
A remedy to this is to use EcRepository.autodetectEndpoint (which hits ping, which sets the time offset that changes the signature generation) -- But autodetectEndpoint is not used when the server URL is known. We need a method for doing this in eduworks/ec::EcRepository that doesn't autodetect.

**Comment by cwd-mparsons** [comment]
For history purposes, added the following comments from recent emails.
From Stuart Sutton: 

> I am still getting an expired signature on ctitest. 

Reply from Fritz:
>Good news is that it was the same problem as before, bad news is that what we did previously to keep the server from doing this again didn't seem to want to run on an automatic schedule, and we're also attacking this at the editor level.

**Comment by Lomilar** [comment]
Has not been re-reported in one month. Candidate for closeout.
