### ISSUE TITLE
RelatedMatch is being exported as a object, or list of objects, and should be a list of strings

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#543]
Created a concept, and then added a relatedMatch URI. On export, relatedMatch is an object and should be a list of strings like narrowMatch. 
A single relatedMatch:
![image](https://user-images.githubusercontent.com/26332112/55511533-7567e580-5626-11e9-802e-da3daf9e8118.png)

Two relatedMatches:
![image](https://user-images.githubusercontent.com/26332112/55511794-0f2f9280-5627-11e9-8ee5-cd7b5c1b943d.png)

From mapping spreadsheet:
![image](https://user-images.githubusercontent.com/26332112/55511655-bf50cb80-5626-11e9-8330-9c53071ec920.png)

**Comment by woodkri** [comment]
@cwd-mparsons I think this is because skos:relatedMatch isn't in your context. If it's added in, it should export the same as skos:narrowMatch.

**Comment by cwd-mparsons** [comment]
@siuc-nate Please add relatedMatch to the context. Thanks

**Comment by siuc-nate** [comment]
Done
