### ISSUE TITLE
No option to add or select a Broader or Narrower concept

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#544]
In concept editor, for the Broader and Narrower properties, there is no a capability to add or search for a concept URI.

![image](https://user-images.githubusercontent.com/26332112/55512522-faec9500-5628-11e9-97e3-c876a02759ff.png)

**Comment by stuartasutton** [comment]
Yes, @cwd-mparsons, that is correct since both properties are autogenerated and uneditable except by moving nodes around or actually adding a broader or narrower node to the concept being edited. They remain empty if a node does not have any broader or narrower concepts.

**Comment by cwd-mparsons** [comment]
Thanks Stuart, closing the issue.
