### ISSUE TITLE
CTDL-ASN Export should have better message when item can't be accessed

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#546]
If you make a framework private and someone tries to access the URL, the message says: 'Object not found or you did not supply sufficient permissions to access the object.' The CTDL-ASN version of the URL says: 'TypeError: null has no such function "toLowerCase"'. Message should probably be the same as the CaSS one.

**Comment by woodkri** [comment]
Ready for testing after next deployment to dev.

**Comment by Lomilar** [comment]
Deployment scheduled for 4/15

**Comment by eddavies** [comment]
The message is correct now.
Not sure if this is directly related but:
I went to export one of my frameworks I made private via CE ASN JSON-LD and got this error. Shouldn't it export properly without an error if it's my owned framework?

**Comment by woodkri** [comment]
At the moment you cannot export private frameworks or concept schemes. I could see an argument either way for being able to export. On the one hand it would be nice to be able to share your framework with someone else if you want to. On the other hand, if you're choosing to encrypt your frameworks, it's probably for a reason and maybe we shouldn't open up the possibility of someone else being able to view it.

**Comment by Lomilar** [comment]
When we get the transformation libraries from CaSS to CTDL-ASN into the common javascript (and take it out of the server side), the capability to download a CTDL-ASN file for an encrypted framework will be available.

It may be a good idea to gray out / notify the user that while the framework is encrypted, some export options may not be available.

**Comment by eddavies** [comment]
Option correctly greys out. Closing this.
