### ISSUE TITLE
Encryption of UTF8 characters

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#547]
Our encryption process doesn't perform UTF8 encoding. This is causing problems with private frameworks if there are any symbols in the data being encrypted (see #524). Need to find a way to preserve this data.

**Comment by Lomilar** [comment]
Fixes for special characters are on their way.

**Comment by woodkri** [comment]
This is working for me now. Assigning Eddie for further testing.

**Comment by eddavies** [comment]
This seems to be working. Will reopen if this issue arises again.
