### ISSUE TITLE
Highlight name text when new competency/concept created

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#549]
This already happens for frameworks and concept schemes.

**Comment by eddavies** [comment]
Working for concepts and competencies now. Verified

**Comment by eddavies** [comment]
Related to #564 

This is actually a big issue, in that attempting to make changes to any field sends the user back to the competency text, or title field. Even when attempting to create a long competency name, the field highlights the name and deletes it if more text is added.

**Comment by woodkri** [comment]
Repro: Create framework. Add new competency. Save and add another. As soon as the button reappears, save and add another again. This happens for the newest competency.

**Comment by eddavies** [comment]
Reproduced by clicking the save and create another button twice in a row.

**Comment by eddavies** [comment]
This is no longer occurring. Fix verified.
