### ISSUE TITLE
Competency editor has no up/down arrows

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#550]
@woodkri, the concept scheme editor at https://cass.credentialengine.org/skos.html seems to lack up/down arrows to move concepts...or am I not in the right place.

**Comment by woodkri** [comment]
@stuartasutton I haven't been to that particular page before, but you're right that we still need to add up/down arrows for concepts. They can be moved by dragging/dropping for now, but arrows are coming soon as well.

**Comment by stuartasutton** [comment]
@woodkri, the only drag and drop I can detect when reordering siblings is to carefully drag all the nodes to the parent folder and drop. Tedious once...and pray you don't have to add anything because you can be faced with dragging/dropping the same nodes all over again.

Is there no way to drag a node and drop it in the right position as opposed to over the parent folder? My angular JS [ASN competency editor](http://rdf.tools/t/asn/#/home) allows me to drag nodes and drop them in position.

**Comment by woodkri** [comment]
@stuartasutton You're right, that's the only drag and drop we have. Up and down arrows are now present for concept schemes though so you won't need to drag/drop to the parent concept.

**Comment by stuartasutton** [comment]
Thanks...someday drag to the correct position and drop....

**Comment by eddavies** [comment]
The up and down arrows are present and functional. I think we can close this issue. We can create a new issue in the future concerning more drag and drop functionality.
