### ISSUE TITLE
Concept scheme import ignored ceterms:ctid for concept, gives error if @id is a URI

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#551]
I have been importing concept schemes from credReg.net. I noticed that the imported concepts don't have ctids, and the id is a purl. On export, the CTID does appear, and the proper registry URL is generated. However, we need to see the CTID and proper URL within the CaSS editor. I tried adding ceterms:ctid to a few of the concepts, but it was ignored. 
I tried to add an @id like the following but received an error on upload.
"@id": "https://credentialengineregistry.org/resources/ce-e09db6e8-1000-768d-a018-cf08cf44cef9"

![image](https://user-images.githubusercontent.com/26332112/55838744-12c18e80-5aeb-11e9-9882-3d60c62820d6.png)

Sample using cetermsAgentServiceType
https://gist.github.com/cwd-mparsons/f13d9cff58ca3d599045a09652cdf419

**Comment by woodkri** [comment]
@cwd-mparsons What error message are you getting when trying to import the sample? I just imported it on ctitest and didn't get any error messages. I'm wondering if the error is something we've since fixed on test but haven't pushed to production yet.

We have not been changing ids on json-ld import, for concepts or for competencies. I'll have to look into what it would take to do that.

**Comment by cwd-mparsons** [comment]
I just tried the import on the test server and didn't get an error on the @id property.
As shown in the below image, the ctid from the json file is imported, but not as ceterms:ctid. 
It is reasonable for the import process to create the ctid and an @id for the registry target based on the current environment. The issue is that the latter are present in the export but in the interface - for concepts, the CTID is blank and the @id is a purl url.

![image](https://user-images.githubusercontent.com/26332112/55897627-85337c80-5b86-11e9-9cc7-40bff80f99c6.png)

**Comment by Lomilar** [comment]
@stuartasutton Please confirm the following.

Canonical IDs, currently, are intended to be maintained during the import process. This allows folks like CASE to see their familiar URIs when editing competencies, frameworks, and concepts (which CASE does have) and to maintain that linking with external data.

When data is published to the registry, all @ids, as well as links to data are switched to registry URLs and the references to the canonical URLs are kept in exactMatch and the like. This needs to be done as well when linking to concepts, that is, in places like ceasn:conceptTerm, ceasn:complexityLevel, etc.

We can drag #313 back up, but this was the currently agreed upon method.

Related: #514

**Comment by Lomilar** [comment]
Pending #568

**Comment by woodkri** [comment]
CTID is now calculated and credential registry URLs are displayed alongside canonical URLs in the editor.
