### ISSUE TITLE
Concept scheme of External Input exports with extra purl Uris in skos:hasTopConcept

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#552]
Added concept scheme of External Input. 
Manually added the concepts. After publish, viewed the registry document and saw that the hasTopConcepts had the registry Uris and a set of purl based Uris. I have not seen this for other concept schemes. 
CaSS export
https://cass.credentialengine.org/api/custom/ceasn/758816ba7f2f6e2c3ef07fcbbfde7bc1
Registry
https://credentialengineregistry.org/graph/ce-4a0b0394-7077-c5b9-af1f-6c588e723508
hasTopConcept
![image](https://user-images.githubusercontent.com/26332112/55842487-69ce6000-5af9-11e9-9a7e-b04bb0b827e6.png)

**Comment by woodkri** [comment]
@cwd-mparsons Was this scheme imported first, before you manually added concepts? The purl urls are the ones that appear when importing one of these schemes.

**Comment by cwd-mparsons** [comment]
I think I probably imported all the concepts, and then, since there was the issue with the concept Ctids, and @id, I deleted the concepts and manually re-added them.

**Comment by woodkri** [comment]
Trying to replicate this.

@cwd-mparsons Do you remember if you deleted the concepts by clicking the trash can button within the editor, or some other way? When I import one of these schemes and then delete one of the purl id concepts by clicking the trash can, the concept is removed from the skos:hasTopConcept list. If a concept is deleted through the console, I think the id would have to be manually removed from the hasTopConcept list.
