### ISSUE TITLE
Bad characters in CASS

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#553]
From the team:
Fritz provided an approach for finding characters:

https://docs.google.com/document/d/1izrtGrbC09sKCFYUdU1_T61U--0AyL-KNJ5U1odcdWM/edit#heading=h.fdpbhgyjg48x

Search for broken characters (e.g., punctuation (e.g., “,”, unicode, copyright), make correction re-approve, and re-publish.

https://cass.credentialengine.org/api/data?q=@type:Framework&size=5000
CTRL+F for �
CTRL+F for ? (Lots of false positives)

https://cass.credentialengine.org/api/data?q=@type:Competency&size=10000
CTRL+F for �
A search for the competency name or a partial name in quotes will result in the framework.

![image](https://user-images.githubusercontent.com/21346519/55903321-042eb200-5b93-11e9-80f2-3282ece34c1d.png)
![image](https://user-images.githubusercontent.com/21346519/55903344-0ee94700-5b93-11e9-837b-32a612cf564b.png)

@cwd-mparsons @woodkri 
The issue is we are having trouble finding the remaining competencies in CaSS. The URL has a schema.eduworks domain. 
![image](https://user-images.githubusercontent.com/26332112/55907014-3e03b680-5b9b-11e9-906d-4c2ad19252d0.png)

**Comment by stuartasutton** [comment]
OK, so we search, find and correct them all. What about going forward when a new batch get's entered. If we have a means of identifying them, can't they be caught at the point of entry?

**Comment by Lomilar** [comment]
We have the ability to detect the "bad character" symbol, but question marks aren't going to be possible.

**Comment by siuc-nate** [comment]
I see them a lot in place of apostrophes (I think it's a byproduct of some mechanism for protecting against faulty strings or string injection attacks or something, I don't recall specifically).  I would start there though - look for question marks with a non-whitespace character on both sides (or maybe just question marks immediately followed by a non-whitespace character, aside from maybe a quote/double quote).

That should catch a lot of them.

My two cents anyway.

**Comment by woodkri** [comment]
Next steps: Run script to remove orphans, then do the search for question marks and see what is left.

**Comment by Lomilar** [comment]
Also remove imported frameworks that have no owner (pre-case-permissioning-import-fix)

**Comment by woodkri** [comment]
Orphan competencies have been removed and it cut down the number of question marks by a lot. I see 8 now.

**Comment by woodkri** [comment]
Path forward: put together URLs with name.keyword sorted in ascending and descending order so we can get at all of the competencies. Search for ?s so we can find and fix.

**Comment by woodkri** [comment]
Example URL that works:
https://cass.credentialengine.org/api/data?q=@type:Competency&size=5000&sort=%5B%7B%22name.keyword%22%3A%7B%22order%22%3A%22asc%22%2C%22unmapped_type%22%3A%22long%22%2C%22missing%22%3A%22_first%22%7D%7D%5D

I put together a list of competencies with question marks, attached here. I searched frameworks as well but they were all part of URLs, so valid uses. The competencies can be found in the editor by searching for part or all of the name in quotes.

[question marks.txt](https://github.com/cassproject/cass-editor/files/3286885/question.marks.txt)

**Comment by Lomilar** [comment]
Certified Fiber Optics Installer (FOI) needs republishing.
Data work is done.

**Comment by cwd-mparsons** [comment]
Republished Certified Fiber Optics Installer (FOI) .
