### ISSUE TITLE
Inter-framework alignment properties still don't support direct entry

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#554]
There have been a number of currently closed issues that touch directly on the fact that the inter-framework properties for competencies require three behaviors:

1.  Direct entry of the URI of the related competency;
2. Search for a related competency known to be in the CER; and
3. Search for a related competency anywhere out there in the wild.

We only support no. 2.  

There have been related issues closed: #195, #325, #357.

The properties of concern are:

>narrowAlignment
exactAlignment
majorAlignment
minorAlighment
prerequisiteAlignment

**Comment by woodkri** [comment]
Per meeting 4/10, + icon should be changed. Right now the icon gives the impression that it would be used to add a second alignment.

**Comment by woodkri** [comment]
I'm searching for good Font Awesome icons to use in place of the plus sign to indicate the user can add an alignment by typing it in. The pencil to me implies edit, which might be misleading if some alignments have already been made. The keyboard might be a more user-friendly option. Anyone have any thoughts or suggestions?

![pencil-alt-solid](https://user-images.githubusercontent.com/33300923/56044101-7b3b8600-5d0c-11e9-802d-d6ff43e8f810.png)

![keyboard-regular](https://user-images.githubusercontent.com/33300923/56044005-4c251480-5d0c-11e9-8d98-a25254bffc4b.png)

**Comment by siuc-nate** [comment]
Maybe the link symbol that I believe you currently use with competencies? Perhaps combined with the existing plus symbol in the corner or something.  Just a thought.

**Comment by woodkri** [comment]
Right now this is what we have - a search icon with a plus inside, and a regular plus sign. A link symbol might make more sense than the plus. The search icon also links to another competency though (just by searching rather than typing), so I'm not sure if that would be any more clear to the user.

![current](https://user-images.githubusercontent.com/33300923/56047660-ea68a880-5d13-11e9-8f8b-e1783dbeb768.PNG)

**Comment by stuartasutton** [comment]
@woodkri, the keyboard icon might actually work...is would suggest typing something in. Why don't we give it a whirl...

**Comment by woodkri** [comment]
This is what it looks like with the keyboard:

![mockup](https://user-images.githubusercontent.com/33300923/56053483-33275e00-5d22-11e9-97df-a610e10542ec.PNG)

**Comment by stuartasutton** [comment]
That actually works for me. Why don't we go with it and see how others respond.

**Comment by stuartasutton** [comment]
However, don't we also need the + for addition of more than one entry?

**Comment by woodkri** [comment]
You can add new entries by clicking the same button - the search icon for additional competencies within the system, or the keyboard for additional URIs.

**Comment by stuartasutton** [comment]
Thanks, @woodkri

**Comment by eddavies** [comment]
Seems to be working besides the enter key functionality, tracked in #561 . Feel free to reopen if other concerns arise.
