### ISSUE TITLE
After entering several concepts in a row, (sometimes) the save buttons get hidden

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#556]
I was entering several concepts. After about 9, the save buttons were barely visible. I was able to click. After save, the button was completely hidden:
![image](https://user-images.githubusercontent.com/26332112/56061958-8b655c80-5d30-11e9-9aa8-f62898211859.png)

If the getting started banner is dismissed, the save buttons are visible again. 

Update:
I encountered the same problem later, even after previously dismissing the getting started banner.

**Comment by eddavies** [comment]
Haven't run into this on ctitest after the commit. Feel free to reopen if this happens again.
