### ISSUE TITLE
Ability to type or copy/paste a URL when adding concepts

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#557]
Complexity level, concept term, etc. In addition to the existing search.

**Comment by eddavies** [comment]
For whatever reason everytime I attempt to paste a url into the complexity level, or level fields it pastes the url in the competency/framework title field.

**Comment by stuartasutton** [comment]
This may be related. I was unable to get complexityLevel to save. It cut n' pasted OK, but no save.

**Comment by woodkri** [comment]
@stuartasutton Did you click on the keyboard or check mark icon to the right after you copy/pasted? Depending on when and where you tried this, the icon might have changed as I'm trying to make it more obvious that these need to be saved individually.

**Comment by stuartasutton** [comment]
Got it!

**Comment by woodkri** [comment]
@eddavies Is this good to close now that #549 is fixed?

**Comment by eddavies** [comment]
Yes!
