### ISSUE TITLE
Encoding error in CTDL-ASN export

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#558]
Workkeys applied math on production when exporting CTDL-ASN seems to partially encode 1/2 and 1/4 in the names.

**Comment by woodkri** [comment]
https://github.com/cassproject/CASS/issues/123

This is the same issue we were having before, where the CaSS export displays symbols correctly but it appears that the CTDL-ASN export is interpreting UTF-8 characters as Windows-1252 or ISO 8859-1.

**Comment by siuc-nate** [comment]
Found another example of this:
Vincennes TSAP Biology Competencies has several competencies with special characters that don't get encoded correctly in the export. For example:
→ becomes â
![image](https://user-images.githubusercontent.com/21346519/58575924-bf291280-8208-11e9-9e45-e815b62f07ed.png)

**Comment by woodkri** [comment]
I was just coming here to capture the same thing - a lot of the apostrophes are showing up incorrectly as well. Another example is Darwinâs from CE export. It shows up properly as an apostrophe in the CaSS export.

**Comment by woodkri** [comment]
Patched on production. Will be released with the next release.

**Comment by Lomilar** [comment]
Added info to install QA and installation post-install to look at and possibly address this.

**Comment by Lomilar** [comment]
Forcing the default charset to UTF-8 likely makes sense here, as it is the de-facto file encoding of the web.

**Comment by Lomilar** [comment]
https://cass.credentialengine.org/api/ceasn/666e652f5054058a5e536fabd0e66c7e

**Comment by woodkri** [comment]
@lomilar Has EW been released? I'm thinking this fix hasn't actually been deployed yet since CaSS's pom has ew version 5.15.1.

**Comment by Lomilar** [comment]
Good catch.

**Comment by siuc-nate** [comment]
Has this issue been fixed?

**Comment by woodkri** [comment]
The fix still needs to be deployed.

**Comment by siuc-nate** [comment]
Has this fix been deployed?

**Comment by woodkri** [comment]
Yes this has been deployed. Here's your example from Vincennes TSAP Biology Competencies above: https://cass.credentialengine.org/api/ceasn/333bc4515f2d192e016e08ab87bf493e

**Comment by siuc-nate** [comment]
Can this issue be closed?

**Comment by Lomilar** [comment]
OK to close. @woodkri Close when ready.
