### ISSUE TITLE
I18N string editor.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#56]
LanguageStrings exist in this data, where, for instance, name may be represented as an object 

```json
{
  "en-US":"Apple",
  "zh":"苹果"
}
```

The text editor fields should be able to store, view, construct and edit such an object, fallback and use the correct language for I18N purposes.

**Comment by Lomilar** [comment]
This needs to respect plurality of things as well.

**Comment by miledivovic** [comment]
@stuartasutton @Lomilar @cwd-mparsons Thoughts on this UI?
![screen shot 2018-07-18 at 12 32 16 pm](https://user-images.githubusercontent.com/14066647/42903456-bde8d43e-8a86-11e8-8a4f-3bc005c126ff.png)

**Comment by stuartasutton** [comment]
Yup.

**Comment by Lomilar** [comment]
cassproject/cass#81 -- The work to do on the repository side.

Storing langstrings in the repository (internally) requires explicit object definitions of the langstring in an array.

I don't think we're going to enforce "@container":"@language" at the schema level.

This also enables support for existing methods .getName() and .getDescription(), both of which should be used.

```json
{
   "@context":"http://schema.cassproject.org/0.3",
   "@id":"https://credentialengineregistry.org/resources/ce-76019a27-513b-4fc8-beb7-03ecf60b0a2d",
...
   "@type":"Framework",
...
   "name":[
      {
         "@language":"en-US",
         "@value":"\"Big Six\" Leadership Competencies."
      },
      {
         "@language":"en",
         "@value":"Another name for \"Big Six\" Leadership Competencies"
      }
   ]
...
}

**Comment by Lomilar** [comment]
OK to proceed.

**Comment by woodkri** [comment]
@Lomilar Is the format of these supposed to be like your July 24th comment? I'm setting the name field of an EcFramework object to name:[{@language:"en",@value:"Name1"}] and the framework saves as "name":["Name1"].
I had also tried name:[{en:"Name1"}] and it wouldn't save at all.

**Comment by eddavies** [comment]
looks good, additional errors will be posted as new issues
