### ISSUE TITLE
Keyboard icon should change to save icon for second click

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#561]
Right now it's not intuitive that you have to click the keyboard again after typing in a URL to save it.

**Comment by woodkri** [comment]
Maybe also a save when you press enter?

**Comment by eddavies** [comment]
Verified on test shell.

**Comment by eddavies** [comment]
Enter does not work after making an edit to a pasted url. 

Steps to reproduce:
1. Go to create a new match and paste in a url
2. Click on the field and make an edit to the url by typing
3. Click enter, and nothing will happen

**Comment by woodkri** [comment]
@eddavies You pasted in a URL and just added additional text to the end of it? I found that if I edit the beginning (so it's htt://... for example), it won't work since it's not a valid URL. I was able to save by hitting enter after editing other parts of the pasted URL though.

**Comment by eddavies** [comment]
I'm not running into this anymore, the enter key is working. But now I can still save strange urls like these after pasting: 

"tps://sandbox.credentialengineregistry.org/"
"https://sandbox.credentialengineregistry"

**Comment by eddavies** [comment]
I did what you mentioned before, I was being a dumb user, and it shouldn't have worked, just needed an error message. Using it now, I can make any edits to a pasted url and it works ("https://s" works).

**Comment by woodkri** [comment]
I looked into this further and all you need to be considered a URL is at least one letter plus a colon. I was able to save something like "a:" since that is not considered invalid. I'm not sure why the htt:// pattern was not saving previously but it is now. You still wouldn't be able to save something like http//something or www.somethingelse.com, and there is a warning in place for these invalid URLs.

We could add some further validation but I'm not sure if we should. Any thoughts @Lomilar @eddavies ?

**Comment by eddavies** [comment]
I think we can close this. It may be nice in the future to have additional validation, but I think for now we can leave these errors up to the user in them typing slightly incorrect urls. This isn't breaking anything else.
