### ISSUE TITLE
On attempt to approve a framework, getting: Object not found or you did not supply sufficient permissions to access the object.

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#563]
In the **ctitest environment**, any attempt to approve a framework results in:
_**Object not found or you did not supply sufficient permissions to access the object.**_

We don't get this error in production. 

The current process (which has not changed) is:
- get the URL to be used for getting the framework from CaSS:
https://dev.cassproject.org/api/ceasn/schema.cassproject.org.0.3.Framework/https://sandbox.credentialengineregistry.org/resources/
- append the CTID (ce-4e06cda5-057d-440a-b162-3fabe8f7e16d)
- resulting in 
https://dev.cassproject.org/api/ceasn/schema.cassproject.org.0.3.Framework/https://sandbox.credentialengineregistry.org/resources/ce-4e06cda5-057d-440a-b162-3fabe8f7e16d
- issue a Get

We are consistently getting the message:
Object not found or you did not supply sufficient permissions to access the object.

These frameworks can be exported. Has something changed in what should be sent to the CaSS get request?

**Comment by woodkri** [comment]
Fritz would know the history better than me, but as far as I know the URL for the get request uses an MD5 hash of the framework's id. An example from ctitest: https://dev.cassproject.org/api/ceasn/be6f37d7e3e61a4bb3f05db7721cd10a where be6f37d7e3e61a4bb3f05db7721cd10a is the MD5 hash of https://sandbox.credentialengineregistry.org/resources/ce-b588ade1-b7bf-457d-be49-45de3cea63ca. Including the Framework type in the middle (https://dev.cassproject.org/api/ceasn/schema.cassproject.org.0.3.Framework/be6f37d7e3e61a4bb3f05db7721cd10a) works too.

I got an error message when trying to use the pattern you have above on production as well (https://cass.credentialengine.org/api/ceasn/schema.cassproject.org.0.3.Framework/<registry framework id>). Do your get requests on production follow a different pattern?

**Comment by cwd-mparsons** [comment]
For production we use:
https://cass.credentialengine.org/api/ceasn/?id=https://credentialengineregistry.org/resources/--CTID--

**Comment by woodkri** [comment]
Understood. The same pattern would work in the test environment (https://dev.cassproject.org/api/ceasn/?id=https://sandbox.credentialengineregistry.org/resources/ce-4e06cda5-057d-440a-b162-3fabe8f7e16d), though as you noted you would need the entire framework id for non-sandbox URLs. With the JSON-LD imports, CASE, etc. you may start seeing this issue more on production as well.
