### ISSUE TITLE
Property labeled "Level" in Competencies should be renamed

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#565]
I recall this issue before and I thought we have fixed it. In the competency editor, there is a field labeled "Level".  The Complexity Level is the only level. So, the field labeled "Level" should be removed.

**Comment by Lomilar** [comment]
That refers to the education level. It was relabeled in a UI pass at some point.

**Comment by stuartasutton** [comment]
Hmmm. Then I think it needs to be relabeled "Education Level"...

**Comment by eddavies** [comment]
Verified on test server.
