### ISSUE TITLE
Where a non-registry URL was entered for a competency framework, it is exported as exactAlignment and should be as source

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#567]
@woodkri Stuart may have talked to you about this, but I didn't see an existing issue here. 
As an example, on the test server, see: Science - Georgia Standards of Excellence.
![image](https://user-images.githubusercontent.com/26332112/56688225-c86d0f80-669d-11e9-8034-93de3e1c7f61.png)
The framework URL is:
https://case.georgiastandards.org/ims/case/v1p0/CFDocuments/27a08dc6-416e-11e7-ba71-02bd89fdd987

On export, the @Id is set to the registry URL, and the case.georgiastandards.org URL is output in the cesan:exactAlignment property. The latter is not a valid property for competencyFramework. 
Instead, the URL should be output in ceasn:source. 
![image](https://user-images.githubusercontent.com/26332112/56688581-b344b080-669e-11e9-8b42-67d63f708c86.png)

@stuartasutton 
 A user can also enter Source Frameworks. So, to confirm, the original URL should be merged with any entered source frameworks.

**Comment by eddavies** [comment]
In CE ASN JSON-LD export, the framework url is now appearing under source instead of exactAlignment. Closing this, feel free to reopen if this is still an issue for whatever reason.
