### ISSUE TITLE
Should we be seeing registry URLs in the CE CaSS Editor for imported data (say, from CASE)

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#568]
@stuartasutton @jkitchensSIUC 

There is also a previous issue where @cwd-mparsons brought this up.

And for the JSON-LD imports (Concept Schemes)

**Comment by Lomilar** [comment]
TODO: Link relevant issues.

**Comment by woodkri** [comment]
Related: #551 #514 #313

**Comment by Lomilar** [comment]
For the CTDL-ASN Profile, every object should also show its registry URL (if newObjectEndpoint is set) in the list, next to the canonical URL and the CTID. (probably between them)

Additionally, the CTID should be calculated from the UUID3 of the @id, not always pulled from the URL. See #551 image for an example.

@stuartasutton -- Included for relevance.

**Comment by woodkri** [comment]
@Lomilar For competencies, is the UUID3 supposed to be derived from the competency id or the combination of the framework and competency ids? I see it both ways in different places in the code.

**Comment by Lomilar** [comment]
The conversion to CTDL-ASN is a special use case, as the practices employed for CE require that competencies be part of only one framework (I believe this is still true). So, when converting to CTDL-ASN, we use a UUID of the framework + competency ID to ensure that any standards that don't follow this rule don't have the same CTID when converted into CTDL-ASN.

So, the framework + competency id -> uuid3 thing should only be true for converting to CTDL-ASN.

**Comment by woodkri** [comment]
Got it. One of the places I saw just the competency id being used was in the CTDL-ASN JSON-LD export, so I'll fix that function.

**Comment by woodkri** [comment]
Assigning @Lomilar for testing/review

**Comment by Lomilar** [comment]
I don't think I explained things correctly.

1. If there is a GUID already in the @id, use the GUID. (the CTID is embedded in the @id most of the time).
2. If not, and we're converting to CTDL-ASN, mashup the framework ID and the competency ID then UUID3.
3. In cases where we're doing something other than converting to CTDL-ASN, come back... It should be just a straight UUID3 of the @id, but that may not always be the best choice.

I think there is a gap still where people can reuse @ids that have a GUID.

This should revert 1327235. Not sure about e6b347a.

**Comment by woodkri** [comment]
Can you help me understand how what I did is different? All I did in 1327235 was add the framework id/competency id mashup. The framework id was being passed into the function but never used.

**Comment by Lomilar** [comment]
You're right, uri is being modified that UUID3s, not the input uuid.

Cleaned a little bit and trimmed versions.

**Comment by woodkri** [comment]
I made the same changes to the code in the editor.

**Comment by Lomilar** [comment]
Thanks. This work should *not* be replicated to the CEASN profile of SKOS, as I don't think SKOS objects can share taxons.

@siuc-nate @cwd-mparsons Are any frameworks published to the CR that don't have UUID/GUIDs in their canonical URLs that you are aware of?

**Comment by stuartasutton** [comment]
This conversation makes me nervous. Can I see an example of input and output?

**Comment by woodkri** [comment]
Sure, here are a few examples of what it currently looks like on ctitest. If there's already a uuid in the id, that's what is used. If there is not (such as a purl id), then a UUID3 is calculated from the id and the registry URL and CTID are displayed based on that.

![open salt](https://user-images.githubusercontent.com/33300923/59198991-ef56a680-8b62-11e9-89e4-7e43c8f20a41.PNG)
![generated uuid for framework](https://user-images.githubusercontent.com/33300923/59198994-f2519700-8b62-11e9-8206-b6ab394fd440.PNG)
![generated uuid for competency](https://user-images.githubusercontent.com/33300923/59198998-f41b5a80-8b62-11e9-82fb-e8cd8cf3d22e.PNG)



![regular concept scheme uuid](https://user-images.githubusercontent.com/33300923/59199012-f8477800-8b62-11e9-8e4c-f64a34195cb4.PNG)
![generated uuid for concept scheme](https://user-images.githubusercontent.com/33300923/59199019-fb426880-8b62-11e9-8f7b-1cc2822bc5ad.PNG)
![generated uuid for concept](https://user-images.githubusercontent.com/33300923/59199026-fda4c280-8b62-11e9-81f4-d4d56a9a256d.PNG)

**Comment by woodkri** [comment]
Change labels: Canonical URL and Credential Registry URL

**Comment by Lomilar** [comment]
Explain what canonical means in the info icon.

**Comment by Lomilar** [comment]
Close this when done.

**Comment by Lomilar** [comment]
Evaluate/Close #551 when done.
