### ISSUE TITLE
Remove (but do not delete) button

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#569]
I just realized that the buttons with this tooltip do two different things depending on whether you're viewing or editing the competency. When viewing it removes the competency from the framework, while when editing it just unlinks the competency (removes the relations). It seems like the behavior should be to remove the competency from the framework in both cases. Is there a use case I'm missing with regards to clicking a button to unlink? If we have both options it needs to be clear what the behavior is for each.

This has implications for concepts as well (#506), currently unlinking is the only option.

@Lomilar

**Comment by stuartasutton** [comment]
I'd appreciate an explanation of the rationale.

**Comment by Lomilar** [comment]
Hopefully I'm not misinterpreting this...

The remove button shouldn't be visible when in view mode -- but I'm assuming you're talking about the minus button in the top right corner, and not like a relation remove button.

@stuartasutton The remove button removes the competency from a framework without deleting it, so that it may be used in another framework.

**Comment by woodkri** [comment]
Yes I'm referring to the minus button but there's a minus button when you're viewing a competency (removes it from the framework), and a minus button when you're editing a competency (unlinks by removing the relations but the competency is still part of the framework). Both have a tooltip that says Remove (but do not delete) but the functionality is different.

To me it would make more sense to only have the remove button, and as you mention only in the edit pane. I'm not sure if there's a reason to be able to unlink competencies/concepts that I'm missing though.

**Comment by Lomilar** [comment]
oh. There is. If you own the framework but not the competencies in it (because you're reusing them from elsewhere), you need to be able to remove the competency.

**Comment by woodkri** [comment]
Right, which is what the remove button does. The unlink button just removes relations but keeps the competency in the framework and that's the one I don't understand the use for.

Good point about needing to remove without editing though.

**Comment by Lomilar** [comment]
Ah. I think the unlink button was there because dragging a competency onto a framework to return it to the top level (not a child of anything) wasn't intuitive. It might need to be better named, like: "Move to top level." @otterlove

**Comment by woodkri** [comment]
Ah that makes sense. It definitely does need to be renamed since it currently has the same tooltip as the remove button. A different icon might be a good idea too since the minus doesn't seem very intuitive outside of a developer mindset.

**Comment by eddavies** [comment]
Tooltip is there, but are we changing the minus icon? I think people would figure the red button in the right would be used to remove the competency. 

I do think the tooltip is a little confusing "Remove (but do not delete)." I think the tooltip should say something along the lines of "Remove from this framework (but does not delete object from original location)" or something along those lines, since I'm sure if users will instinctively understand the difference between removing and deleting.

**Comment by woodkri** [comment]
@eddavies We could change that tooltip too. The one I changed is the one that you can see when you're editing - it doesn't actually remove the competency but it moves it to the top level in the framework. I changed that icon because the minus didn't make sense to me for that. Now it's an up arrow but please feel free to make other suggestions if there's something else you think would be better.

**Comment by eddavies** [comment]
Ah I see that now, was looking at the wrong thing. I think that's a great change.

**Comment by eddavies** [comment]
But I am confused as why there is the remove button for new competencies you have created and not just linked ones.

**Comment by woodkri** [comment]
@eddavies If you remove a new competency from your framework, it still resides on the server even though it's not attached to any frameworks. To remove it from the system completely you would need to click the trash can instead of the remove button.

**Comment by eddavies** [comment]
Okay understood, thank you for the clarification. Verified, tooltip looks good.
