### ISSUE TITLE
Private frameworks show up in search but concept schemes do not

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#571]
#506

They show up in the general search but not if you search for a keyword.

**Comment by Lomilar** [comment]
Ah. EcEncryptedValue.encryptObject copies the name field from the data its encrypting to the encrypted data. Concept Schemes don't use the name field, so this doesn't happen, the ... dc:title? skos:something? of the concept scheme would have to be copied to the same field in the encrypted object by hand.

**Comment by woodkri** [comment]
Very helpful, thanks!

**Comment by eddavies** [comment]
While testing this I ran into a bug:

1. Create a new concept scheme
2. Change the title
3. Make the scheme private
4. Click save.
5. This happens:

![1](https://user-images.githubusercontent.com/23706850/57247953-0cdda100-6ff6-11e9-93fa-c4f9dd4b23fe.PNG)

The concept scheme never saves and I can't seem to find it in the list of concept schemes.

**Comment by Lomilar** [comment]
I've seen this several times as well.

**Comment by woodkri** [comment]
Hm. So when I added the private framework feature, the save methods were not reencrypting objects so I had to do that manually everywhere we saved something. Now that they're being reencrypted in the library methods, the regular CaSS editor page (with versioned ids) still works but ctitest is reencrypting objects I've already manually encrypted so there's a double layer of encryption. If it were just setting encryptOnSave back to true upon save it wouldn't be as hard to work around but it's save, get, search, etc.

I think I could take out the manual reencryption if I add the object's short id to the encryptOnSaveMap. We would lose the names for concepts and concept schemes again though so they wouldn't appear in the search. @lomilar Would it be ok to add a check for dcterms:title and skos:prefLabel to the encryptValue library method (and if they exist in the original, add to the encrypted object) or is that a bad idea?

**Comment by Lomilar** [comment]
Seems fine to me to include that in encryptValue.

**Comment by woodkri** [comment]
Pull request opened in EC.

@eddavies Private concept schemes won't show up in the search yet. With your repro steps above you should now see the framework name change on the left, and if you scroll all the way to the bottom of the list on the search page (until it stops adding more concept schemes) you should be able to see your scheme there. Concepts and subconcepts should now be encrypting properly on both ctitest and the regular cass editor, as well as frameworks and competencies.

**Comment by Lomilar** [comment]
Merged. Will be available on release 1.2.8 to be deployed on May 10.

**Comment by eddavies** [comment]
Verified
