### ISSUE TITLE
Autocomplete for Concepts

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#574]
Should users be able to add concepts they don't own to their concept scheme like they can for competencies? Since relations are managed at the individual concept level they wouldn't be able to add sub-concepts to those, or move them around in the hierarchy. There are a few options I can think of - 1. Don't allow users to add concepts they don't own, 2. Allow them to copy concepts they don't own but not link them, 3. Allow them to link concepts, hide the editing buttons in the right pane (add subconcept, move up and down, add alignments), and add a way to remove the concept from the scheme without deleting it.

Also applicable to #572.

#506

**Comment by stuartasutton** [comment]
@woodkri, I've a question about adding a concept or a competency that to a framework or concept scheme that the organization doesn't "own"...actually have more than one question. we should probably plan on going over this on one of our Wednesday calls. 

I see no functionality in the editors to add a competency or a concept from a framework or concept scheme owned by someone else. Wouldn't that mean that at the point of adding concept or competency that a search would be opened to locate the concept/competency and to add it? If that is enabled and I'm missing it, I'd like to see it in action and what the resulting json-ld looks like.

**Comment by woodkri** [comment]
@stuartasutton The functionality does exist for competencies, though they have to be on the same server. There are a couple of different ways to do this - one is via the autocomplete functionality when you create a new competency and start typing in the name. You can select a competency that already exists on your server from the dropdown that appears, and it will replace the competency you just created. The json-ld for that competency doesn't change, but the framework does. That competency is added to the framework's competency list, and if it's a subcompetency, that relation is added to the framework's relation list as well.

The other way is by clicking the magnifying glass icon right above the keys section:
![copy or link](https://user-images.githubusercontent.com/33300923/57149188-27ffa500-6d99-11e9-8309-106b1714150e.PNG)
That will allow you to search for other competencies on the server and you have the option to either pull in the competencies as they already exist (no change to the competencies' json-ld, just the framework as above), or copy them over with new URLs that connect back to the originals in the derivedFrom field. With the latter, you're able to make edits because you now own that copy of the competency.

I believe Credential Engine uses the show=mine URL parameter, so that the framework search only displays frameworks that the user or organization owns. The points I brought up may be less relevant for your purposes, since with that parameter in place your users wouldn't be able to find competencies that they don't own. Though now that I'm thinking about it, we need to add an identity check in for the autocomplete and I'll create a new issue for that. I'm happy to talk about this further on one of our calls too!

**Comment by stuartasutton** [comment]
Yes, lets talk about it on a call. I'll miss the calls this coming week and the next, but after that. I'l also curious as to how the provenance of such a concept is handles...i.e., does it indicate that is it derived from the foreign concept/competency and how?

**Comment by Lomilar** [comment]
Probably not a good idea here. Concept schemes use a "two object" model (ask me about it if need be), meaning relations between concepts are part of each concept. This prevents them from being shared between concept schemes, so linking/reuse is not an intended capability for concept schemes. Copy w/derivedFrom is quite alright.

**Comment by woodkri** [comment]
Got it. Do we still want to have autocomplete functionality for concepts (just copy instead of link) or scrap it? It could get confusing if the behavior is different between concepts and competencies, though it wouldn't be that hard to add if it would be useful to people.

**Comment by Lomilar** [comment]
I'm currently of the opinion that a concept scheme probably doesn't have nearly as many reasons to support reuse, but am open to discussion.

**Comment by stuartasutton** [comment]
Concept Schemes (AKA SKOS) already have a well defined mechanism for reuse; see https://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#secextension

**Comment by stuartasutton** [comment]
Fritz, it has nothing to do with 2 entity- 3 entity

**Comment by Lomilar** [comment]
From an RDF statement perspective, you're completely correct, but the statement:

"ex1:cats skos:inScheme ex2:catScheme."

from that example is a statement being made in a subsequent context. RDF has the ability to extend objects that were not initially defined here, whereas object based systems that have permissioning would error on that statement, saying "You can't make statements about ex1:cats, because ex1:cats was (as an example) defined by a different party and you can't change it".

"ex2:catScheme owl:imports ex1:cats" would be fine, however... That's why, natively, CaSS defines narrows but not broadens, requires but not isRequiredBy -- We had to wrestle with the notion of "Who is permitted to make this relation?"

Does SKOS allow the reuse just a part of a concept scheme in another scheme?

**Comment by stuartasutton** [comment]
Note that the SKOS example doesn't "change" anything...doesn't extend anything... "ex1:cats skos:inScheme ex2:catScheme" simply uses it.   It simply references what is "over there" being included "here". If there is a change...e.g., extension...then you have a derivative, not a copy and should use a new URI.

**Comment by woodkri** [comment]
Closing as won't do.
