### ISSUE TITLE
Framework that forks and merges loses children

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#576]
https://cassproject.github.io/cass-editor/?frameworkId=https://dev.cassproject.org/api/data/schema.cassproject.org.0.3.Framework/fb4490e2-7322-46c3-a099-bc159371e942

E is a child of D, D is a child of C and B, but E doesn't show as a child of D on the B branch.

**Comment by woodkri** [comment]
Screenshot of bug for Eddie's reference:

![fork and merge](https://user-images.githubusercontent.com/33300923/57476161-fb99cc00-7263-11e9-92ab-7beb80f553b1.PNG)

E is missing from the first D node.

**Comment by Lomilar** [comment]
Validated from my viewpoint.

**Comment by eddavies** [comment]
This seems to be fixed.
