### ISSUE TITLE
Upon attempting to publish/export some frameworks, get TypeError: Cannot read property "ceasn:hasChild" from undefined

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#577]
We tried to republish:
- Ivy Tech TSAP Secondary Education Biology Competencies
- Vincennes TSAP Biology Competencies 

We get the error:
TypeError: Cannot read property "ceasn:hasChild" from undefined

**Comment by Lomilar** [comment]
Patched in CE Production.
