### ISSUE TITLE
CaSS environment on staging getting server error of: File or directory not found

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#579]
Upon starting the CaSS editor in the staging server, we are getting the error: 
File or directory not found
http://staging.credentialengine.org/publisher/Competencies

There are no specific references as the cause of the latter error. The following errors can be seen in the console:
- VM104:1 POST http://staging.credentialengine.org/cass/sky/repo/search 404 (Not Found)
- WebSocket connection to 'ws://staging.credentialengine.org/cass/ws/custom' failed: Error during WebSocket handshake: Unexpected response code: 404

This was working previously.

**Comment by woodkri** [comment]
Have you checked to see if elasticsearch is still running? My first guess is that maybe it went down. If not that, I'd check tomcat and apache as well to make sure they're still up.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons check elasticsearch and update the comment here ahead of our CASS meeting today.

**Comment by cwd-mparsons** [comment]
Elastic is running. The finder search (uses elastic) is working. 
I noticed the version of elastic is 6.6.1, versus 5.6 on production.

**Comment by Lomilar** [comment]
I think this was resolved yesterday. Please reopen if necessary.
