### ISSUE TITLE
No (apparent) means to return to frameworks browse

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#58]
Once you have selected a framework and entered edit mode, there is no apparent way to exit that mode and return to frameworks browse list.

**Comment by Lomilar** [comment]
Depending on which edit mode... Are you seeing this?

![image](https://user-images.githubusercontent.com/337692/33389051-8cb335e0-d4e6-11e7-86cf-7219f3ccd77f.png)

or this?

![image](https://user-images.githubusercontent.com/337692/33389156-cec4bc4c-d4e6-11e7-8128-843ee287fb32.png)

**Comment by stuartasutton** [comment]
Hmmm. Can't believe it was that obvious :-)

**Comment by Lomilar** [comment]
Cheers. :-)
