### ISSUE TITLE
Set in language for new concepts

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#580]

**Comment by woodkri** [comment]
From attempting to replicate, I think the issue is that the inLanguage field wasn't being automatically populated when editing an existing concept rather than when creating a new one. This is the same behavior as competencies.

1. Do we want a language to be added where none exists when items are edited?
2. @cwd-mparsons Do you run into this problem when creating a new concept?

**Comment by cwd-mparsons** [comment]
@woodkri -
1. Yes - add a language where none exists when items are edited
2. Yes. I just created a new concept  in production, and saved it. A language was not added.

**Comment by woodkri** [comment]
Ah, I realize now what's happening here. I added the code to set the language for a new concept as part of addressing the functionality delta between frameworks and concept schemes. That change has not yet been pushed to production.

**Comment by woodkri** [comment]
Now that we've deployed to production, the language field should be populating on creation of a new concept. I've also added code to add a language when editing a concept if it doesn't have one.

**Comment by eddavies** [comment]
The language field is populating correctly with the creation of new concepts.

@woodkri This may be very minor, but if you import a new concept scheme without designating a language in the CSV/JSON file, the concept scheme does not populate the language field at all. But after quickly clicking edit and save, the concept scheme auto populates the language with en-US. Would it be at all beneficial to make it so imported concept schemes without a language field designated in the file, auto populates? If not, we can close this issue.

**Comment by woodkri** [comment]
@eddavies I had the same thought! Adding the language to imports is part of issue #548.

**Comment by eddavies** [comment]
Ok I see, awesome. Closing this issue then.
