### ISSUE TITLE
Get 500 error on attempt to import a concept scheme into the staging server. 

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#581]
Exported the Agent Sector concept scheme from production, and then attempted to import to the staging server. 
[AgentSector_staging190603.zip](https://github.com/cassproject/cass-editor/files/3249492/AgentSector_staging190603.zip)

I receive a message that the input file may be invalid. In the console, there is a '500' status with the following details:
![image](https://user-images.githubusercontent.com/26332112/58835014-64cdee80-861a-11e9-9a81-04ea0642e77c.png)

I am able to import the concept scheme into the test server without issues.
I also noticed that the staging concept scheme import only allows JSON-LD, whereas the test server also has an option for CTDL-ASN formatted CSV.

**Comment by woodkri** [comment]
@cwd-mparsons Do you know which version of CaSS is on the staging server? It may just be that it has an older version than the test server.

I'm working on adding a csv import for concept schemes but it's not quite ready to use yet.

**Comment by cwd-mparsons** [comment]
@woodkri I checked: C:\Program Files\Apache Software Foundation\tomcat\apache-tomcat-8.5.12\webapps\ROOT\cass-editor, and see that all of the files have a date of 4/19/2019.

**Comment by woodkri** [comment]
My guess is that's all that's happening here, there's just a slightly older version of CaSS on the staging server. We were having a problem for a while where CTDL-ASN jsonld files that we exported from one server weren't importing properly into another (https://github.com/cassproject/CASS/issues/137).

**Comment by cwd-mparsons** [comment]
@woodkri @Lomilar 
I updated the staging server to version 1.2.9, and I still get an error trying to import the AgentSector concept scheme (assuming all worked correctly when I did the update).

**Comment by woodkri** [comment]
@cwd-mparsons I created an account on staging - username kristinwood. Can you add me to an organization so I can get into the editor?

I see a localhost:8080 in the console messages you posted so it looks like the correct server isn't being registered somewhere.

**Comment by cwd-mparsons** [comment]
I added you to Credential Engine. You will have to log out and back in.

**Comment by woodkri** [comment]
Thanks! It looks like repo.selectedServer has not been set on the server side. @Lomilar Is this usually done in the config file or elsewhere?

**Comment by cwd-mparsons** [comment]
Fritz applied a fix, and I verified that I could import a concept scheme.
