### ISSUE TITLE
Credential Engine ASN Export in staging is incorrect

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#585]
I tried publish a framework in the staging environment. It failed as it could not find the @type of ceasn:CompetencyFramework was not found. I did an export from CaSS and found that the data is very wonky:

![image](https://user-images.githubusercontent.com/26332112/59474020-b4769c00-8e0a-11e9-9de9-a4534e2f182b.png)

**Comment by Lomilar** [comment]
This is likely the long tail of the switch to HTTPS biting us. 

Namespaces in https://credreg.net/ctdlasn/schema/context/json
need to match namespaces in http://schema.cassproject.org/0.3/cass2ceasn and in other places.

**Comment by woodkri** [comment]
@Lomilar This translates correctly if I change the ceasn namespace to https. Will it cause other problems if we change the namespaces for ceasn, ceterms, cass, etc. to https in the schema files, or should I go ahead and do that?

Also, should the context of the CTDL ASN export be updated to https or should it remain as http for now, to match other frameworks in the registry?

**Comment by Lomilar** [comment]
Yes, it will cause other problems, but we have to address those problems as well. This is a forced change that we can't back away from.

And the context should be updated to https, but this has already been done.

**Comment by woodkri** [comment]
This should be fixed on production now.

**Comment by woodkri** [comment]
This should be fixed, reopen if problems are still occurring.
