### ISSUE TITLE
CASS editor appears to hang or crash

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#586]
On going to https://credentialengine.org/publisher/Competencies and selecting an organization, the editor appears to hang indefinitely:
![image](https://user-images.githubusercontent.com/21346519/59620373-496ee300-90f2-11e9-96d0-9fbf729d21d3.png)

@cwd-mparsons found that [site.js](https://cass.credentialengine.org/Scripts/site.js) and other files are throwing 404 errors when going directly to https://cass.credentialengine.org/
![image](https://user-images.githubusercontent.com/21346519/59620321-27756080-90f2-11e9-92d2-44a0e67f9d0e.png)

Did something change over the weekend?

**Comment by woodkri** [comment]
CaSS is back up on production. There were around 200 hanging processes on Tomcat but a restart has us up and running again.

We will need to figure out a way to address hanging processes so this doesn't occur again.

**Comment by Lomilar** [comment]
This coincided with the switch from http to https, and could have been caused by that. Need to go look at production and see if any threads are hanging.

**Comment by Lomilar** [comment]
No threads were hanging upon this most recent check. OK.
