### ISSUE TITLE
Editor displays empty block for empty-string listIDs and codedNotations

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#587]
The editor attempts to display empty listIDs and/or codedNotations (I suspect because the value is an empty string rather than null/undefined?).

listID (red), codedNotation (blue):
![image](https://user-images.githubusercontent.com/21346519/59780584-db582680-927f-11e9-873e-2daf2cb43680.png)
![image](https://user-images.githubusercontent.com/21346519/59781013-9c76a080-9280-11e9-88cb-4d7cf7a1b20f.png)

**Comment by eddavies** [comment]
Not running into this anymore.
