### ISSUE TITLE
CTDL-ASN export is missing most fields

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#590]
When I do an export (on production CASS) of any of the frameworks in CTDL-ASN format, I get data that looks like this:
![image](https://user-images.githubusercontent.com/21346519/59926165-572cad00-93ff-11e9-9d3d-18159eaee69b.png)

Most of the fields are missing (name, description, competencyText, hasChild, isChildOf, etc.).

Is this due to the https/context issue?

**Comment by woodkri** [comment]
Yes, that's due to the https issue. We strip the framework export of non-Credential Engine fields, and the function that does that looks for the ceasn and ceterms prefixes. Once those are resolving again, the rest of the fields will appear in the export.

**Comment by stuartasutton** [comment]
Any sense of timing on when a full CTDL-ASN export will be enabled? We have an absolute deadline of today to export the set of cybersecurity frameworks needed by the JDX project.

**Comment by cwd-mparsons** [comment]
I see that the export/publish works on the test server, so it seems promising.

**Comment by woodkri** [comment]
This should be working on production again.

**Comment by woodkri** [comment]
I believe this is fixed, re-open if any problems are still occurring.
