### ISSUE TITLE
URIs for CTDL Concept Schemes

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#591]
https://credreg.net/ctdl/terms#conceptschemes

When testing the import of these concept schemes again, we noticed that the URIs for concept schemes (ex: https://purl.org/ctdl/terms/AgentSector) don't match the URIs of the concepts in those schemes (https://purl.org/ctdl/vocabs/agentSector/PrivateForProfit).

We had added ceterms into our context for concept schemes, which means the ids are now being imported as ceterms:AgentSector and the like rather than as the purl URLs.

Should these concept schemes have vocabs URIs rather than terms?

**Comment by siuc-nate** [comment]
The concept schemes use the /terms/ URIs; the concepts use the /vocabs/____/ URIs.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @cassproject-org @cwd-mparsons is this a high priority issue?

**Comment by stuartasutton** [comment]
I am uncertain whether there is a problem I am not seeing (quite possible), but there is no rule that the URI namespace of a concept scheme and its concepts need to be the same.

**Comment by woodkri** [comment]
The problem here isn't necessarily that the URI namespaces aren't the same, it's that the Concept Scheme ids are compacting to ceterms:AgentSector (as an example) on import rather than https://purl.org/ctdl/terms/AgentSector since ceterms is part of the context. It's causing problems since it doesn't begin with http. This isn't happening with the concepts because vocabs is not part of the context.

**Comment by siuc-nate** [comment]
Do you have some example JSON-LD that shows the problem?

**Comment by woodkri** [comment]
@siuc-nate All of the ceterms concept schemes (https://credreg.net/ctdl/terms#conceptschemes) have this issue. If you try to reimport one of them, the id is compacted to something like "ceterms:AgentSector" instead of "https://purl.org/ctdl/terms/AgentSector" since ceterms is part of the context. This causes problems since it doesn't begin with http.

**Comment by woodkri** [comment]
Confirmed these are staying as is. To do: Add a check to the import process to see if the id was compacted. If so, re-expand.

**Comment by gloverkari** [comment]
Leave as is. The compacted version is being used by CE code. See Nate for details. @siuc-nate
