### ISSUE TITLE
Getting an export based on @id

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#592]
Is it possible to get an export of a framework based on the `@id` of that framework (or its CTID, or some other identifier other than CASS's internal GUID)?

Currently an export URL looks like this:
```
https://cass.credentialengine.org/api/data/f0ce7a571348d22644b57f40fea58dff
```
But we don't keep track of that internal GUID anywhere.  We could do that, but if CASS already has a means of getting that same export via CTID, `@id`, or some other identifier already in the schema, that would be preferred.

**Comment by Lomilar** [comment]
That segment, `f0ce7a571348d22644b57f40fea58dff` is the md5 of the @id. `https://credentialengineregistry.org/resources/ce-d82041d6-0165-4116-9463-18be163628a1`

Also, `https://cass.credentialengine.org/api/data/?q=@id:"https://credentialengineregistry.org/resources/ce-d82041d6-0165-4116-9463-18be163628a1"`

Or, for something where it has a CTID in the ID:  `https://cass.credentialengine.org/api/data/?q=@id:"ce-d82041d6-0165-4116-9463-18be163628a1"` -- Though this will not work for resources that originate outside the CE ecosystem (eg, from CASE).

**Comment by cwd-mparsons** [comment]
Thanks, we have this covered now.
