### ISSUE TITLE
Unable to create concept matches via the search icon

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#593]
![matches not working](https://user-images.githubusercontent.com/23706850/61315075-d8831f80-a7b2-11e9-8ddd-c9814059eaa6.PNG)

Tried to create an exact match, but nothing happens when I click on the search (plus) icon.

**Comment by woodkri** [comment]
Oops, there was a typo that didn't affect anything on cassproject.github.io but did on CE pages. Should be working now.

**Comment by eddavies** [comment]
Okay this is working now, thank you.
