### ISSUE TITLE
For quoted search terms, highlight only the entire search term.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#594]
![image](https://user-images.githubusercontent.com/337692/61406028-ea86c000-a88f-11e9-82c6-3dfd6ddf1b6f.png)

**Comment by woodkri** [comment]
I also noticed that the first and last word of the search term weren't being highlighted. Should be fixed now.

**Comment by eddavies** [comment]
I'm not seeing anything highlighted anymore when searching for a term with quotations.

**Comment by woodkri** [comment]
Hmm. In the search bar I put "deep knowledge becomes more of a focus" and this is what I got when I opened up the Norm Webb framework:

![text highlighting](https://user-images.githubusercontent.com/33300923/63536125-eda14b80-c4e0-11e9-83cf-1c1483e9dc9d.PNG)

Are you getting highlighting when you search for a phrase without quotations, just not with? What browser are you using? @eddavies

**Comment by eddavies** [comment]
Oh I'm seeing highlights now. I don't however if I search up some single words like "and" but I guess it's not considered a term necessarily? Not like there is a use case for searching up "the"

**Comment by eddavies** [comment]
Just after testing a few words, I search up "deep" and saw highlights, but then searched up "health" and got none.

**Comment by woodkri** [comment]
I think what's happening here is that words that are in the framework name or description are highlighted on the search page (health is in a ton of framework names), whereas words that appear in competencies are highlighted when you click to go into the framework. This kind of makes sense to me but there's probably a way to pass the search term down to the competency level if you think they should be highlighted there as well.

**Comment by woodkri** [comment]
This was from the old interface.
