### ISSUE TITLE
Framework export contains bad data

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#595]
A number of frameworks (approximately 40 at time of posting) have competencies (totalling nearly 200) that are being exported with a non-existent broad alignment (and a few narrow alignments) to a non-existent entity:
![image](https://user-images.githubusercontent.com/21346519/61749238-dea36e00-ad67-11e9-916c-80ff4ab46de0.png)
![image](https://user-images.githubusercontent.com/21346519/61749175-b87dce00-ad67-11e9-8468-8c433539c1ba.png)

Some of these include the DOL frameworks that were recently uploaded, and other frameworks.

This is resulting in faulty data and a lot of flagged resources in our bad link checker.

The total issues list can be found here:
https://docs.google.com/spreadsheets/d/1gMvhYd008dlsjJYHhgZ6pdVq4W1UMYDd/edit#gid=634463157

**Comment by siuc-nate** [comment]
Additionally:
https://cass.credentialengine.org/api/ceasn/5cb30a4357cd113acbf90c19c0efa35c
![image](https://user-images.githubusercontent.com/21346519/61749731-119a3180-ad69-11e9-85ac-c77491dbde78.png)
![image](https://user-images.githubusercontent.com/21346519/61749752-1e1e8a00-ad69-11e9-990e-625b85e9f24b.png)

**Comment by Lomilar** [comment]
There seems to be an issue with the import being used, where null/empty is not being filtered correctly. This relation was found.
https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Relation/f1a09dc2-a32a-4450-a014-06a252fb67fc

Note that its target is empty. That is likely getting hashed and processed to become a URL by the ceasn export.

1) Import should not import csv cells that are "" or whitespace.
2) Export should ignore relations that are null or empty strings.

**Comment by woodkri** [comment]
Were these frameworks CSV imports? We do have a check for empty strings, so whitespace is probably the issue if so.

**Comment by siuc-nate** [comment]
What's the timeline for fixing this?

**Comment by siuc-nate** [comment]
Does this issue only affect CSV imports?

**Comment by Lomilar** [comment]
This is patched on CE Production.

**Comment by Lomilar** [comment]
In addition, no imports or exports should import or export blank "" or null or empty data.

**Comment by woodkri** [comment]
Ex: ceasn:comment field here with empty data https://cass.credentialengine.org/api/ceasn/e531d992ae4ca69f24a82086166e113b

The import part (for CTDL-ASN CSVs) has been addressed above but not the export.

**Comment by siuc-nate** [comment]
Has this issue been fixed?

**Comment by siuc-nate** [comment]
Can this issue be closed?
@Lomilar @woodkri

**Comment by Lomilar** [comment]
OK to close. @woodkri Close when ready.
