### ISSUE TITLE
On export, framework contains an exact alignment that is not shown in CaSS

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#596]
While testing I noticed the following:
Framework: CCO Mobile Crane Inspector Specialty Examination , 
Competency: Pre-Inspection Survey

In CaSS there is no exact alignment data for the above competency. 
On export of the framework:
https://cass.credentialengine.org/api/custom/ceasn/653e88faefeba037eb3b66aba8dbddc3

There is an exactAlignment proper that points to a CaSS url
![image](https://user-images.githubusercontent.com/26332112/62082076-9ed20000-b219-11e9-91ff-0b57927342c4.png)

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/34651602-2c35-411f-b03f-da039d3411fb/1564100917440

**Comment by woodkri** [comment]
All the competencies at the Domain category in that framework have cass.credentialengine.org ids for some reason. Since that's not the same as the registry URL, an exact alignment to the canonical id is created on export.

That behavior is expected as far as the export goes, but I'm wondering how the competencies ended up with those ids in the first place. Do you know how they got into the system (manually added, CSV import, etc.)?

**Comment by Lomilar** [comment]
This was likely a result of some of the earliest editing of frameworks, back before we had objects being generated with URLs as if they were in production. My guess is that some competencies were created with those cass.credentialengine.org URLs, and this is applying the rule that canonical URLs should be exactAlignments of the published competency. Also, the competency it links to is a CaSS competency, not a CTDL-ASN competency.

So, that's how it got there. Next is to decide whether it is OK, and what we should do with it.

**Comment by Lomilar** [comment]
* [ ] Create script to move cass.credentialengine.org @ids to registry URIs and update references to the new URIs.
* [ ] Need to produce a list of frameworks that are affected.

**Comment by woodkri** [comment]
Script is still TBD but here's the framework list:

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/541e493a-15c5-418d-9394-61c857cc1157
transformed: https://credentialengineregistry.org/resources/ce-541e493a-15c5-418d-9394-61c857cc1157

https://credentialengineregistry.org/resources/ce-a1e7b863-aa0c-42e4-a598-a8229a208943

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/23943f01-38ed-443d-a932-d2d0c61febc6
transformed: https://credentialengineregistry.org/resources/ce-23943f01-38ed-443d-a932-d2d0c61febc6

https://credentialengineregistry.org/resources/ce-b0f16f1d-4612-4f54-bb63-11b8584eb8d5

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/015ac948-65b0-481c-8480-47f13a08359d
transformed: https://credentialengineregistry.org/resources/ce-015ac948-65b0-481c-8480-47f13a08359d

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/8a705a02-ab53-4df4-868c-820ecb06fc23
transformed: https://credentialengineregistry.org/resources/ce-8a705a02-ab53-4df4-868c-820ecb06fc23

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/23943f01-38ed-443d-a932-d2d0c61febc6
transformed: https://credentialengineregistry.org/resources/ce-23943f01-38ed-443d-a932-d2d0c61febc6

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/015ac948-65b0-481c-8480-47f13a08359d
transformed: https://credentialengineregistry.org/resources/ce-015ac948-65b0-481c-8480-47f13a08359d

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/8dfd3c9f-f557-4636-b07c-7d831f078679
transformed: https://credentialengineregistry.org/resources/ce-8dfd3c9f-f557-4636-b07c-7d831f078679

https://credentialengineregistry.org/resources/ce-7eacee3f-2c55-4fe7-bf5f-247e793b4e75

https://credentialengineregistry.org/resources/ce-3e21c72d-22cb-4df6-9cf7-3f00e31e3eab

https://credentialengineregistry.org/resources/ce-8b933f8a-80d8-488c-8202-4943d1c58ed9

https://credentialengineregistry.org/resources/ce-0fc9ba4a-bc7d-4a62-a9bd-42c64f19084c

**Comment by woodkri** [comment]
URLs have been changed and references updated. There were two cass.credentialengine.org Frameworks that appear in the list up above in 2 versions. I was able to remove one of the versions but there's still a version of these two that I can't seem to delete:

https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/23943f01-38ed-443d-a932-d2d0c61febc6/1533243977454
https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/015ac948-65b0-481c-8480-47f13a08359d/1533250612756

If you go to one of the URLs it doesn't seem to exist (maybe it's getting by shortId which has been deleted?), but the search is finding it somehow. Both are instances of the "cm" framework which looks like it was an early test of a handful of O*NET competencies. Neither was published.

**Comment by Lomilar** [comment]
Are we ready to handover to @cwd-mparsons @siuc-nate ?

**Comment by woodkri** [comment]
With the exception of still needing to delete those two extra frameworks, yes. Is there a way to delete a version of an object or does the delete always fall back to the short id?

**Comment by Lomilar** [comment]
No, there isn't. We try to promote the permanence of web data, so links to specific versions are never deleted. The server can be taken offline or database modified, of course, if this is absolutely required.

**Comment by woodkri** [comment]
Hm I guess we would need to figure out why the versioned object is coming up in the search when the shortId has been deleted then, for these two but not for others.

**Comment by Lomilar** [comment]
Agreed.

**Comment by woodkri** [comment]
Not sure what is and isn't relevant information here, so just noting the differences I've found. When you just search the repo, these frameworks are not found. When you do an EcFramework.search or a repo.search with @type:"Framework", they are found. With skyrepoDebug turned on, those two have different output for the gets/fetches:

```
2019-11-12 08:29:44,830 [CruncherDebug.java:30] DEBUG <Failed to find schema.cassproject.org.0.3.Framework/ba7aa067-6033-442c-8da7-b6f5e7642d2b/ -- trying degraded form from search index. (String)>
2019-11-12 08:29:44,830 [CruncherDebug.java:30] DEBUG <Fetching from schema.cassproject.org.0.3.framework : schema.cassproject.org.0.3.Framework / ba7aa067-6033-442c-8da7-b6f5e7642d2b /  (String)>
2019-11-12 08:29:44,830 [CruncherDebug.java:30] DEBUG <Get:http://localhost:9200/schema.cassproject.org.0.3.framework/schema.cassproject.org.0.3.Framework/ba7aa067-6033-442c-8da7-b6f5e7642d2b (String)>
2019-11-12 08:29:44,830 [CruncherDebug.java:30] DEBUG <Failed to find schema.cassproject.org.0.3.Framework/42061ccb-fc44-4f27-9b19-619d0ede1cc0/ -- trying degraded form from search index. (String)>
2019-11-12 08:29:44,831 [CruncherDebug.java:30] DEBUG <Fetching from schema.cassproject.org.0.3.framework : schema.cassproject.org.0.3.Framework / 42061ccb-fc44-4f27-9b19-619d0ede1cc0 /  (String)>
2019-11-12 08:29:44,831 [CruncherDebug.java:30] DEBUG <Get:http://localhost:9200/schema.cassproject.org.0.3.framework/schema.cassproject.org.0.3.Framework/42061ccb-fc44-4f27-9b19-619d0ede1cc0 (String)>
```


The rest of the Gets are all to /permanent/permanent/id. In addition, the format of the ids are a bit different for these two than the others:

```
2019-11-12 08:29:44,818 [CruncherDebug.java:30] DEBUG <Get:http://localhost:9200/permanent/permanent/471bca3704243f891542c418da4b8096. (String)>
2019-11-12 08:29:44,818 [CruncherDebug.java:30] DEBUG <Get:http://localhost:9200/permanent/permanent/ba7aa067-6033-442c-8da7-b6f5e7642d2b. (String)>
2019-11-12 08:29:44,818 [CruncherDebug.java:30] DEBUG <Get:http://localhost:9200/permanent/permanent/576fb3236cbc51be69140de4d4d68619. (String)>
2019-11-12 08:29:44,818 [CruncherDebug.java:30] DEBUG <Get:http://localhost:9200/permanent/permanent/5f222229316a2533170e2322f1822c7c. (String)>
2019-11-12 08:29:44,818 [CruncherDebug.java:30] DEBUG <Fetching from permanent : schema.cassproject.org.0.3.Framework / 42061ccb-fc44-4f27-9b19-619d0ede1cc0 /  (String)>
2019-11-12 08:29:44,819 [CruncherDebug.java:30] DEBUG <Get:http://localhost:9200/permanent/permanent/42061ccb-fc44-4f27-9b19-619d0ede1cc0. (String)>
```


Data in elasticsearch for one of them:

```
{"_index":"schema.cassproject.org.0.3.framework","_type":"schema.cassproject.org.0.3.Framework","_id":"ba7aa067-6033-442c-8da7-b6f5e7642d2b","_version":1533250613119,"found":true,"_source":{"@context":"http://schema.cassproject.org/0.3","@id":"https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Framework/015ac948-65b0-481c-8480-47f13a08359d/1533250612756","@owner":["-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj9hH5RuzbVjF88J0jEme\r\nzBLG80e4WXfOB1elROAY/0vHh4vV1WjobmhqDeUO5A1jQG9UZAgFBBlFqXgskknM\r\nQ6gizcsxBDMRSAkQMGRdX2ex0qwBwXRDNqbT5NuMrYa2M+u2nSdJ1FNi20Sbui4R\r\n6lenUYIZS89IFd7KpuRhPJa69n++wwXAURtGVjLnYIklNy2sxNENqVLAhkOwJuPq\r\nxmNkjzZ6v5m2PRgcyq22o5uwLgE0RT/LSmYz39UsCvSxw31FrE1xlKEuwr37/+ih\r\natatDL/HOqcPXi2ifFO+qwY7RM5JkvpZU0PHLwMLv1f+2Is3UTiN0OXLBtfUQaZF\r\ncQIDAQAB\r\n-----END PUBLIC KEY-----","-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz8dtLf5k+kMgykrX5QV5ro70UAu8KR7IVhh3EWMxKZrkLo2bKhalCss+wM0ueIbIs3LvAfiG1p5u8cqql9bEcMyM8KUEC1q8hAVOjI9EmmWkghhCoHx1hS5L94xBlZEdLsA/q7xQqjNXtxnwKh16lLCZQh6utX5gZeApRbUet3vLE/3/q1ZUjo3TPwxPBU4Vr4z23a2vIm65ee/sp0Z/fl5w3+bzQ0sc/LD4aoW4Rk4xkrNVgTjtgr8f5QajfUyFjXCfZIiRSOVrjicbrPyQqb6R0uO+1uB6we4Kmyb3XnjSGWD734bgcP7sHPq/kxCe5yWTwQ7lrYxNepmYYjjauwIDAQAB-----END PUBLIC KEY-----"],"@signature":["tt9AQ8BGCjzasQ9CLv5Q6oVTAxeXtesBgYKqvqklhzMVnqXXbyw2XoLmW8DN67nVXTfeyPgE9Kmc+j8NN3rSUduVj08ZsNdARayLphh6zxMX/wnTCub/MVdc+8MeRJF5A1X2xl5+N8Z2MLwguh7ANGA39jsctb9w+lGIs9KTt3Cg8iY0ODa3OKmt6Pvz3xg6uJqQak/cRfNXB8Qsv/sfFGC5MLpaNCUs6CKO5sou52j9kW8gnYBQsdNySl2nPm0eIE/UTfi6HUSvsTbU1IW4W6ypkYgFiM/Jm02OwRFq/5dejSD1wDb0o7ZkgsvjutHjkZP2ALDM0PIkLNcnUt9z5g=="],"@type":"Framework","ceasn:publisherName":"National Center for O*NET Development","ceasn:repositoryDate":"2018-08-02T22:55:40.206Z","competency":["https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/b30767a6-f668-4ac3-830e-d8685174d635","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/d0fd91f5-421f-41e1-87c1-27d49ab18a85","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/697d8459-be61-49a8-9056-b39ec9e0dc52","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/ffbf5156-f0cd-42f3-a5d2-e046a8aeada4","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/858f1658-78bc-4724-81da-114ebde56c8a","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/3d676f51-3c69-40f6-976f-e8485d366381","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/18aa193c-b748-4298-8b1c-9e391478ea5a","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/c2c3869e-7e7f-49e6-82c2-d768d31443e0","https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.Competency/f7e113eb-5491-458a-9f64-764087768cc7"],"description":"","name":"cm","relation":[],"sameAs":"https://credentialengineregistry.org/resources/ce-2abf6ed3-0b26-4a60-9608-e7e310729ae9","schema:creator":"https://credentialengineregistry.org/resources/ce-dade72f7-c183-4070-9022-b9f65510e17b","schema:publisher":"https://credentialengineregistry.org/resources/ce-dade72f7-c183-4070-9022-b9f65510e17b"}}
```

I'm not sure how the @id translates to the _id here. I believe normally it's the md5 hash of the id but this one is a different format.

**Comment by woodkri** [comment]
"cm" frameworks have been removed. I believe that's all that remained for this issue.

**Comment by mparsons-ce** [comment]
Thank you
