### ISSUE TITLE
Remove ceasn:inLanguage from Competency consideration.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#597]
Derivative of https://github.com/CredentialEngine/vocabularies/issues/604
We need to do a bit of an impact analysis.

Things I am aware of:

* [x] Remove inLanguage from competency editor.
* [x] Remove inLanguage from competencies in the CEASN import.
* [x] Remove inLanguage from being auto-assigned to competencies when created, edited, or imported.

**Comment by woodkri** [comment]
- [ ] All of Fritz's bullet points, substituting concept for competency.
- [ ] Remove translation between skos:inLanguage and ceasn:inLanguage
- [ ] schema:inLanguage is used for both frameworks and competencies, so that would be a bit less straightforward. May have to tackle that in the exports themselves.
- [ ] Remove existing data by script?
- [ ] Remove autocompletes attached to competency and concept inLanguage fields

Will update if/as I think of more.

**Comment by siuc-nate** [comment]
Has there been any progress on this?

**Comment by woodkri** [comment]
Nothing yet, do we have the green light to go ahead? The original issue is tagged as Consideration so I didn't want to start down that path if you all weren't ready for it yet.

**Comment by siuc-nate** [comment]
It makes sense to me to remove ceasn:inLanguage from Competencies where it already exists.

**Comment by siuc-nate** [comment]
Has this been taken care of?

**Comment by woodkri** [comment]
Not yet, I'm waiting to run a script until the changes are on production.

**Comment by siuc-nate** [comment]
This change is scheduled to happen by the end of the month. Will your work be ready by then?

**Comment by woodkri** [comment]
Just finished running the script. It's now assigned for testing.

**Comment by Lomilar** [comment]
@woodkri Can you post the script (remove public/private keys)? Looking to figure out how to test this.

**Comment by woodkri** [comment]
Sure, I did this in three parts. Server is set to production and search is "(*)".
```
EcConcept.search(repo, search, function (cs) {
    var count = 0;
    for (var i = 0; i < cs.length; i++) {
        var c = cs[i];
        if (c["skos:inLanguage"] != null) {
            delete c["skos:inLanguage"];
            repo.saveTo(c, function() {
            	console.log("success!");
            }, console.log);
            count++;
        }
    }
    console.log(count);
}, function (failure) {
    console.log(failure);
},{size:10000});
```

```
EcCompetency.search(repo, search, function (comp) {
    var count = 0;
    for (var i = 0; i < comp.length; i++) {
        var c = comp[i];
        if (c["schema:inLanguage"] != null) {
            delete c["schema:inLanguage"];
            repo.saveTo(c, console.log, console.log);
            count++;
        }
        if (c["ceasn:inLanguage"] != null) {
            delete c["ceasn:inLanguage"];
            repo.saveTo(c, console.log, console.log);
            count++;
        }
    }
    console.log(count);
}, function (failure) {
    console.log(failure);
},{size:500, start:9500, sort:'[{"name.keyword": {"order": "asc", "unmapped_type":"long", "missing" : "_first"}}]'});
```

I did the competencies in chunks (500) so as not to overwhelm the server, and sorted asc and desc. Apparently the number of competencies has gone beyond 20,000 though now, so I wasn't able to reach them all that way since elasticsearch cuts it off at 10,000 records.

I did the rest by framework, also a handful at a time:
```
EcFramework.search(repo, search, function (f) {
    console.log(f.length);
    for (var i = 255; i < f.length; i++) {
        var c = f[i];
        if (c != null && c.competency != null) {
            for (var j = 0; j < c.competency.length; j++) {
                EcCompetency.get(c.competency[j], function(comp) {
                    if (comp["schema:inLanguage"] != null) {
                        delete comp["schema:inLanguage"];
                        repo.saveTo(comp, console.log, console.log);
                    }
                    if (comp["ceasn:inLanguage"] != null) {
                        delete comp["ceasn:inLanguage"];
                        repo.saveTo(comp, console.log, console.log);
                    }
                }, console.log);
            }
        }
    }
}, function (failure) {
    console.log(failure);
},{size:5000});
```
