### ISSUE TITLE
Issues related to lookahead/autocomplete.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#598]
* [x] When typing quickly, lookahead should wait 1 second before searching. (avg person types 200 characters per minute, may want to lower to 800ms or 600ms)
* [x] Remove symbols from search string before doing lookahead / autocomplete. This is causing errors that flood the server.

**Comment by Lomilar** [comment]
For the first one, using a var timerHandle = setTimeout() before beginning the search, then cancelTimeout(timerHandle) on every keypress before re-setting the setTimeout() should take care of it.

**Comment by Lomilar** [comment]
The errors related to the second item can fill up a hard drive rather quickly.

**Comment by Lomilar** [comment]
1749ebfc18b80aa2c3e585eb1be857b0dacd3f4f
607fc8ccdad6edce2afb4bf3545f90495175da29

**Comment by Lomilar** [comment]
This is kinda only working intermittently. Updating the source means the list pops on the next character. Maybe use the approach here:

https://api.jqueryui.com/autocomplete/ - Under source -> `Function: The third variation, a callback, provides the most flexibility .....`

Also, EcCompetency.search returns a list of competencies, don't need to re-fetch them from the db/cache. (line 1542)

**Comment by woodkri** [comment]
I hadn't noticed that option for source before. It seems to work much better! This also allows us to use the built-in delay option when setting the autocomplete versus setting a timeout.

**Comment by eddavies** [comment]
Working, verified.
