### ISSUE TITLE
Cancel button on "Add a new Framework" screen

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#6]
This cancel button doesn't do anything. Would be nice if it redirected to the framework list view:
![cancel button](https://user-images.githubusercontent.com/23706850/32515652-a864ec1c-c3b5-11e7-88f9-830a65354f2c.PNG)

**Comment by Lomilar** [comment]
Should go 'back', whether that be back in the parent iframe (via a iframe message) or back to the previous page.

**Comment by miledivovic** [comment]
Fixed in d828fa6.
Cancel button now returns the user to the list of frameworks.

**Comment by eddavies** [comment]
Fix verified
