### ISSUE TITLE
A competency in framework: Beta Connecting Credentials Framework, has a CTID different from registry URL

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#600]
In the Beta framework, there is an issue with competency:
>Demonstrates the ability to build consensus and apply negotiating practices in a group or interactive environment.

The CTID is different than that used in the Credential Registry URL:
![image](https://user-images.githubusercontent.com/26332112/62586639-07595680-b884-11e9-984e-66c4231328ab.png)

If the just competency is exported:
![image](https://user-images.githubusercontent.com/26332112/62586567-bea19d80-b883-11e9-9039-51aafa227394.png)

When the framework is exported/published a different (third) CTID is output:
![image](https://user-images.githubusercontent.com/26332112/62586703-4e474c00-b884-11e9-8613-22453ca54f64.png)

The publish process uses the target registry domain plus CTID, not the @Id from CaSS. In the registry, the following is invalid:
https://credentialengineregistry.org/resources/ce-f644304e-151c-4074-9372-7679adctc3c9

But this URL works (using the third CTID - ce-b1b44...)
https://credentialengineregistry.org/resources/ce-b1b442ea-0c91-38f5-9587-46d64e624549

This is the only instance that I have found with this inconsistency. It was found while running a link checker. 
Can this be manually fixed, or does the competency have to deleted and re-added. 
NOTE: the Beta framework was imported from a file in Github. The CTID is correct in the latter file. 
https://github.com/CredentialEngine/vocabularies/blob/master/Competency-Frameworks/ConnectingCredentials.json
![image](https://user-images.githubusercontent.com/26332112/62587021-adf22700-b885-11e9-9673-d80e83849dbd.png)

**Comment by woodkri** [comment]
This competency's id and ctid contain a 't', which our regex doesn't recognize as part of a valid UUID so we generate a new one. It's my understanding that valid UUIDs have letters in the range [a-f] and [A-F].

**Comment by cwd-mparsons** [comment]
Ahh , thanks Kristin.
@siuc-nate 
Can the correct be made in the Github source, and re-imported?
https://github.com/CredentialEngine/vocabularies/blob/master/Competency-Frameworks/ConnectingCredentials.json

If updates have been made in CaSS since the latest import, then it could be exported, changed and re-imported.

**Comment by woodkri** [comment]
This looks like it was corrected in the registry and republished. Does anything else need to be addressed here or can the issue be closed?

**Comment by woodkri** [comment]
Closing, reopen if needed.
