### ISSUE TITLE
Cleaning up some "Connections" cluster (embodied) properties.

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#603]
1.  I have updated  the CaSS [mapping spreadsheet](https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803) to reflect the addition of two [new properties](https://github.com/CredentialEngine/vocabularies/issues/618#issue-482023667) (knowledgeEmbodied and taskEmbodied) to the "Connections" cluster of the competency framework editor.

2. The editor currently has [ceasn:skillEmbodied](https://purl.org/ctdlasn/terms/skillEmbodied) in the "Tagging" cluster. It should be moved to the "Connections" cluster and its range changed to xsd:anyURI. Currently, it's range is skos:Concept due to an error on my part. 

3. We also added a [ceasn:abilityEmbodied](https://purl.org/ctdlasn/terms/abilityEmbodied) a few months back, but its existence apparently didn't get telegraphed to CaSS. It, too, should be in the "Connections" cluster.

4. In terms of behavior, these all should trigger a competency search defaulting to the framework being described--i.e., pointing to nodes in the current graph being created. However, as far as CTDL-ASN is concerned, the range could be a competency anywhere.

**Comment by Lomilar** [comment]
Works.
