### ISSUE TITLE
Ctitest drop down menu needs a close button

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#605]
If the browser window is not in fullscreen, the drop down menu in the top right cannot be closed:

![top bar menu](https://user-images.githubusercontent.com/23706850/63535324-094b2880-c4c6-11e9-968f-35cecc007e17.PNG)

![cant close this smaller menu](https://user-images.githubusercontent.com/23706850/63534563-50d0b500-c4c4-11e9-8169-adf2f289a0de.PNG)

**Comment by cwd-mparsons** [comment]
@eddavies Thanks for the observation. 
This has been corrected on the test server.

**Comment by eddavies** [comment]
Verified on test server, closing.
