### ISSUE TITLE
In chrome, on hover over a sidebarToolbar button, detail slider disappears

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#606]
Chrome Version 76.0.3809.132, just started noticing it.
Not happening on Firefox.

![blank detail slider](https://user-images.githubusercontent.com/33300923/64451691-b1f6ac00-d0b2-11e9-9903-6a89b1f6f951.PNG)

Sometimes a weird split when trying to export too.
![split in screen](https://user-images.githubusercontent.com/33300923/64451702-b8852380-d0b2-11e9-8940-298af44126e5.PNG)

**Comment by woodkri** [comment]
Top picture also happening with some Copy URL to the clipboard buttons.

**Comment by woodkri** [comment]
Temporary fix by disabling the LayoutNG flag here: chrome://flags/. There's an open issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1001083

**Comment by Lomilar** [comment]
This may be related to some hover actions for buttons and the like. Only seems to happen when hovering a button or input. Does stripping those out of the CSS help at all? Could also be somewhat related to cursor change.

**Comment by woodkri** [comment]
No longer occurring with Chrome Version 77.0.3865.75.

**Comment by Lomilar** [comment]
Update message to let people know to update their version of Chrome.

**Comment by woodkri** [comment]
@lomilar Done.
