### ISSUE TITLE
Editor permits multiple copies of a dragged/dropped node

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#607]
I was working on the *Certified Construction Manager (CCM) Exam Outline of Competencies* to correct some formatting errors. I needed to drag and drop a set of nodes to place them under the correct parent. When I tried to drag and drop, the editor appeared to do nothing--no update in the left-hand panel. So, I tried again and again...3 times. Still no apparent action. So I went back to the TOC and open the framework again. The editor had actually executed the action...three times. See the `ceasn:isChildOf` property in the JSON-LD snippet below. There is no way from the editor to delete the duplicates since trying to select any one of the duplicates with the same URI selects them all. I did not want to delete all and reenter the node because I did not want to lose the existing URI.

In essence, part of the editor wasn't working (i.e., updating the left-hand result after edit), while another part of the editor continued to execute the move action. Obviously, the left-hand panel should have updated; but, the editor should not allow repeat drags and drops of the same node. 

```
{
   "@id": "https://credentialengineregistry.org/resources/ce-dec0f70e-370d-4ee5-89cd-e6125d9ab725",
   "@type": "ceasn:Competency",
   "ceasn:competencyText": {
      "en-us": "Agency"
   },
   "ceasn:dateCreated": "2019-06-04T17:48:26.303Z",
   "ceasn:dateModified": "2019-09-06T20:24:30.309Z",
   "ceasn:inLanguage": [
       "en-US"
   ],
   "ceasn:isChildOf": [
      "https://credentialengineregistry.org/resources/ce-8c7790d2-cb82-4441-a4aa-3b1e6d5c1520",
      "https://credentialengineregistry.org/resources/ce-8c7790d2-cb82-4441-a4aa-3b1e6d5c1520",
      "https://credentialengineregistry.org/resources/ce-8c7790d2-cb82-4441-a4aa-3b1e6d5c1520"
            ],
   "ceasn:isPartOf": "https://credentialengineregistry.org/resources/ce-6e0530c7-9495-4d4c-b030-cb196871b3f8",
   "ceasn:listID": "1",
   "ceterms:ctid": "ce-dec0f70e-370d-4ee5-89cd-e6125d9ab725"
}
```

**Comment by Lomilar** [comment]
Repro is likely something along the lines of:

1. Find a way to make the server non-responsive but things are queued up. 
1. Do some actions.
1. Things broke.

**Comment by Lomilar** [comment]
Solution here so far is to make the server more responsive (SSD? :-)
