### ISSUE TITLE
Require notification on delete of a competency

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#608]
We had recent issues, where:
- competencies had been aligned to an assessment
- the assessment was published with alignments
- some competencies were deleted
- the assessment now references non-existent competencies

Currently on delete of a competency, the only message is a framework changed, that includes nulls for the current competency. 
We need a message type of **competency deleted** that includes the CTID or ID.
We can then delete any alignments and handle notifications.

**Comment by Lomilar** [comment]
The only data we will have at this point is the internal CaSS ID. We can send that as part of a deleted event.
