### ISSUE TITLE
Confirmation prompt appearing incorrectly for adding Concept Terms and Education Level Types

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#609]
After attempting to add a concept term to a framework via the "add a relation with a URI" option:

![the prompt](https://user-images.githubusercontent.com/23706850/64810149-acd0ab80-d54f-11e9-9d57-64bbfad49f59.PNG)

This only happens when a concept term and/or education level is saving at the same time as a different field is highlighted in green.

The prompt appears three times in a row. Clicking cancel causes the editor to freeze for a few seconds and update slowly.

**Comment by woodkri** [comment]
Applies when adding other types of relations too (competency alignments, etc)

**Comment by woodkri** [comment]
This was from the old interface.
