### ISSUE TITLE
Could the ConceptScheme HasTopChild property be generated from IsTopChildOf property

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#612]
I started working on formatting a CSV for importing a concept scheme. For concept schemes with 10, 50, or hundreds of concepts, formatting the HasTopConcept will be very tedious. 

![image](https://user-images.githubusercontent.com/26332112/65532617-c2d05b80-dec1-11e9-9f96-b904583f164d.png)

Instead, couldn't HasTopConcept just be generated from topConceptOf?

It looks like the competency framework import doesn't (based on the sample) have a HasTopChild property.

**Comment by siuc-nate** [comment]
The schema defines these as inverse of each other, so it should be possible to generate the data as @cwd-mparsons suggests.

**Comment by stuartasutton** [comment]
Yes, use of an auto inverse here would be good.
