### ISSUE TITLE
A CTID must be unique. Need to resolve scenario where a framework is imported with existing CTID and different canonical URI

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#615]
Last week an issue was encountered where an O*Net framework was imported with an existing CTID but different canonical URI.
This scenario led to issues like:
- difficult to find the new framework in the search
- confusion with storing a reference in the publisher as CTID already existed
- could not initially approve or publish due to the problem with two records in CaSS

We eventually had to delete the existing (first) framework. We could then approve and  publish the newer framework.

**Comment by mparsons-ce** [comment]
This may have been addressed. I see that there are non-registry URIs in the publisher CaSS database table. 
Closing for now.
