### ISSUE TITLE
Framework Name in postMessage after import

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#618]
viewChanged and importFinished messages after import finishes don't include framework name. Framework needs to be cast as EcFramework for getName() to work.

**Comment by woodkri** [comment]
Part of https://github.com/cassproject/cass-editor/commit/ed9577f590dc8dca31de6cfbc2673da5d6c4f426

**Comment by siuc-nate** [comment]
Has this been fixed?
@Lomilar @woodkri

**Comment by Lomilar** [comment]
OK to close. @woodkri Close when ready.
