### ISSUE TITLE
Add ceasn:competencyLabel to interface

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#619]

**Comment by woodkri** [comment]
On left panel:
- If we have both label and name, put label where name currently is and name where description currently is.
- If we have only name, put it where name currently is and description beneath.

**Comment by siuc-nate** [comment]
We updated CTDL-ASN today to include ceasn:competencyLabel.  It now appears in the CTDL-ASN context file: http://credreg.net/ctdlasn/schema/context/json

**Comment by woodkri** [comment]
Great! The export looks good on test:

```
"ceasn:competencyLabel": {
    "en-us": "Process"
},

**Comment by Lomilar** [comment]
* [ ] Deploy on staging, test.

**Comment by siuc-nate** [comment]
Can this issue be closed?

**Comment by Lomilar** [comment]
OK to close. @woodkri Close when ready.
