### ISSUE TITLE
CE, disable/vanish levels and shared behavior.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#62]

**Comment by Lomilar** [comment]
This was done somewhere.

**Comment by eddavies** [comment]
Unable to add levels when ceasnDatafields=true, as intended. Levels already existing in a framework are editable as competencies and are downloaded/viewed as competencies. I don't think that this is an issue since I haven't noticed any weird issues arising from editing as a level or competency.

**Comment by Lomilar** [comment]
This is probably okay for now.
