### ISSUE TITLE
Outputting nodes without data

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#623]
In the competency framework at https://credentialengineregistry.org/graph/ce-02a8adbd-3da9-487c-8f11-3d97cfd7aedb, we are outputting a property that contains no data...

```
"ceasn:comment": {
    "en-us": [
       ""
     ]
},
```

This should not happen.

**Comment by woodkri** [comment]
This was fixed with #595 but is happening again on production (version 1.2.23). Not happening on staging or test so we may just need an update.

**Comment by siuc-nate** [comment]
Has this been fixed with the latest version?
@Lomilar @woodkri

**Comment by woodkri** [comment]
The CaSS export of the framework above is no longer outputting the empty comment field.

https://cass.credentialengine.org/api/ceasn/029cd6bfe8fb7595c0771c483b39f1de

Some frameworks that are published do have an empty field in them. They would need to be re-exported and republished to remove it.

**Comment by woodkri** [comment]
Closing as a duplicate of #595
