### ISSUE TITLE
SSL issues on staging server

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#624]
Background
We used LetsEncrypt to add SSL to the staging server. 
CaSS would fail - due to running non-SSL under SSL site. 
Fritz tried to export the certificate created by LetsEncrypt, but could not as a hidden/unknown password was created during the process. 

**Actions**
Could a separate SSL  be created for CaSS, and then installed?

If not, then we may need to explore other clients for letsencrypt:
https://letsencrypt.org/docs/client-options/

**Comment by siuc-nate** [comment]
This has been solved.
