### ISSUE TITLE
Implications for changes to the URLs and domains used by the credential engine site

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#625]
@Lomilar @woodkri @kchavas 
The CredentialEngine.org site is based on Wordpress. Due to issues with configuration and a preference to host the site on a Linux VM, we are going to move the latter to a new Linux VM. 
We are going to change the **pattern** of the publishing and account sites to use:
**https://credentialengine.net** as the base domain name. 
The following is a link to the planning document, and on a separate tab, a list of current and planned new domain names:
https://docs.google.com/spreadsheets/d/1UpKIOUNySKl65CRyX9kUNhavg2iYCtoHKQdZfPEf5kI/edit#gid=1953189131
for example, from
https://credentialengine.org/publisher 
to 
https://credentialengine.net/publisher 

We will continue to use cass.credentialengine.org. 
We want to ensure that CaSS has enough notice should any configuration changes be necessary.

**Comment by Lomilar** [comment]
This should not impact us.

It would also be prudent to detach CaSS from the main server at some point and put it on a Linux VM as well. That way we can decouple our use of elasticsearch, etc.

**Comment by jeannekitchens** [comment]
@cwd-mparsons the URL changes were made awhile back.  I'm closing this.
