### ISSUE TITLE
On staging get error that publisher must be provided, one is shown in interface, but not in export

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#626]
Environment: **Staging**
Framework:  **Parts, Tools, and Equipment.**
The interface shows data entered for creator, publisher name and publisher URI
![image](https://user-images.githubusercontent.com/26332112/68343355-331def80-00b2-11ea-9a98-14c1c63fdcac.png)

None of these three properties exist in the export:
![image](https://user-images.githubusercontent.com/26332112/68343557-acb5dd80-00b2-11ea-9f9d-edac81f2f803.png)

**Comment by woodkri** [comment]
When I search for the framework, I get a version that doesn't have any of that information (@id: "http://staging.credentialengine.org:8080/api/data/schema.cassproject.org.0.3.Framework/0a849142-f051-442e-b98b-fbb42e845d11/1560367303235").

Strangely, if I search by creator (go to Aircraft Dispatcher Written Exam and click on the search icon next to Navy COOL in the Creator field), then I get a version of the "Parts, Tools, and Equipment." framework that does have those fields populated (@id: "http://staging.credentialengine.org:8080/api/data/schema.cassproject.org.0.3.Framework/0a849142-f051-442e-b98b-fbb42e845d11/1573079045385"). I can view everything in the editor and the console there, but if I try to export I get yet another version of the data, with fields missing ("http://staging.credentialengine.org:8080/api/data/schema.cassproject.org.0.3.Framework/0a849142-f051-442e-b98b-fbb42e845d11/1560367303235").

Something odd is happening with versioning here. Further investigation needed.

**Comment by mparsons-ce** [comment]
@woodkri 
Quick update. I just tried a few exports on sandbox and production and the publisher does appear in the export. 
However on staging the publisher is not part of the export.

**Comment by woodkri** [comment]
I restarted tomcat on staging and it should be displaying publisher in the export now. The translations were cached from my testing the publisher export issue yesterday.

**Comment by mparsons-ce** [comment]
Great, yes, now the publisher appears in the export - closing.
