### ISSUE TITLE
On attempt to export/publish some older frameworks get a TypeError on splice

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#627]
I was republishing the competency frameworks to fix the date formatting issue. 
Several frameworks failed to publish/export. 
If edit one of the frameworks (**Connecting Learning Theories to Your Teaching Strategies**), and then do a CE ASN JSON-LD export, I get the following error:
TypeError: f["schema:publisher"].splice is not a function

If I just edit, and save without making changes, I can publish without any errors. 

I left the above referenced framework as a reference, and fixed all of the other issue.

**Comment by woodkri** [comment]
This should be fixed with commit https://github.com/cassproject/CASS/commit/84b97d114d96331528a05360b1656ec1e43339a1, hasn't been deployed to production yet.

**Comment by cwd-mparsons** [comment]
Thanks. 
I will fix and republish the referenced framework.

**Comment by siuc-nate** [comment]
Has this been solved?
