### ISSUE TITLE
On publish/export of older ConceptSchemes get TypeError on IndexOf

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#628]
I was checking production concept schemes and found several cases, where upon export, the following message is displayed:
TypeError: cs["ceterms:ctid"].indexOf is not a function

Examples include:
- scoringMethod
- Residency
- Organization Type

**Comment by Lomilar** [comment]
Merged.

**Comment by woodkri** [comment]
Does the server cache the context and is there a way to force a refresh? I had to do a hard refresh to see the change client side but I suspect the server is still using the old translation.

**Comment by woodkri** [comment]
There's no more error and these appear to be exporting properly now. Candidate for closure @Lomilar
