### ISSUE TITLE
Pre-populate language tags in editor for ceasnDataTypes.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#63]

**Comment by Lomilar** [comment]
If the language is changed from the framework, default language should be pulled from the framework. Default lang for framework could just be en-us or come from the browser.

**Comment by Lomilar** [comment]
Also autosuggest ISO codes.

**Comment by eddavies** [comment]
For new competencies, the language, creator and author are taken from the framework. However changing the language or plugging in the language after a competency has been created does not update from the framework (is this intentional?)

**Comment by eddavies** [comment]
Ah I see, opening edit will populate the fields for the competency to what is on the framework unless this was previously changed for just the competency.

**Comment by Lomilar** [comment]
This is intentional.

Correct. They are used as defaults.
