### ISSUE TITLE
Setting up Sandbox.credentialengine.org. Should this use the dev instance of CaSS

### ISSUE THREAD

**Issue by cwd-mparsons** [cassproject/cass-editor#632]
We are setting a new sandbox/test environment at https://sandbox.credentialengine.org/publisher. 
We are planning to stop using ctitest.siuccwd.com soon.
The sandbox site will share the same server as for staging. 
Should we continue to use the dev instance of CaSS? Then we wouldn't have to be concerned with maintaining two versions of CaSS on this server. 
I used LetsEncrypt to set up SSL. Will there be any configuration changes necessary?

Currently in our test environment, we have the following for CaSS related urls:

    <add key="cassGetUrl" value="https://dev.cassproject.org/api/ceasn/schema.cassproject.org.0.3.Framework/https://sandbox.credentialengineregistry.org/resources/ce-{0}"/>
    <add key="cassEditorUrl" value="https://cassproject.github.io/cass-editor/index.html?user=wait&amp;link=true&amp;newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&amp;server=https://dev.cassproject.org/api/&amp;ceasnDataFields=true&amp;show=mine"/>
    <add key="conceptSchemeEditorUrl" value="https://cassproject.github.io/cass-editor/index.html?user=wait&amp;link=true&amp;newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&amp;server=https://dev.cassproject.org/api/&amp;ceasnDataFields=true&amp;show=mine&amp;concepts=true"/>
    <add key="cassResourceViewerUrl" value="https://cassproject.github.io/cass-editor/index.html?server=https://dev.cassproject.org/api/&amp;ceasnDataFields=true&amp;origin=http://ctitest.siuccwd.com&amp;css=https://credentialengine.org/publisher/Style/CassStyles&amp;frameworkId=https://dev.cassproject.org/api/data/{0}"/>
    <add key="cassExportUrl" value="https://dev.cassproject.org/api/ceasn/{0}"/>

Will the latter need any changes?

**Comment by cwd-mparsons** [comment]
BTW, the databases for the sandbox server were restored from the test environments, so all existing login info will be the same.

**Comment by cwd-mparsons** [comment]
When starting CaSS from sandbox, I don't see Credential Engine as an option. 
So do the private keys for CE have to be resent/established?
Would that be the case for all other orgs that had established 'keys' on the soon-to-be obsolete ctitest server?

**Comment by mparsons-ce** [comment]
This has been addressed successfully.
