### ISSUE TITLE
Missing data for 3 ACT frameworks

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#633]
The following frameworks have 0 items and show as having been edited months ago.  They should have data:
- ACT College and Career Readiness Standards
- ACT Holistic Framework - Acting Honestly
- ACT Holistic Framework - Getting Along With Others V2.0

**Comment by Lomilar** [comment]
These all came from the ACT framework server at https://frameworks.act.org -- We have re-imported them and they seem OK now.
