### ISSUE TITLE
Need different success for Case imports

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#634]
We currently search for the CASE endpoint after importing, but we've found some import URIs that don't match the endpoint so there's no way to tell if your import was successful. Examples here: https://frameworks-staging.act.org/ims/case/v1p0/CFDocuments

After import, displays "No frameworks found" even when import was successful.

**Comment by mparsons-ce** [comment]
@brandonopened 
Copied from https://github.com/CredentialEngine/credentialPublisher/issues/14

https://credentialengineregistry.org/resources/ce-f6e25e8a-6a93-11e8-98be-0242ac120003

Hi, I have loaded a CASE framework into the competency manager and am unable to:

Exporot a full CF Package.. just document or items? https://cass.credentialengine.org/api/ims/case/v1p0/CFDocuments/97c398d5e09d30b00f8bf9e8786fcc0c

Retrieve the derivative framework URL: https://credentialengineregistry.org/resources/ce-f6e25e8a-6a93-11e8-98be-0242ac120003 . (this should show the full CASE CF Package referenced at frameworks.act.org/uri/f6e25e8a-6a93-11e8-98be-0242ac120003

If this is a CASS bug I should file instead, please let me know.

**Comment by jeannekitchens** [comment]
@woodkri @mparsons-ce is this an open issue?

**Comment by woodkri** [comment]
The original issue was completed.

Regarding the add on from January, we do now export CFPackages instead of CFDocument when exporting the framework in CASE format. I believe the derivative framework URL won't resolve until the framework has been published to the registry.
