### ISSUE TITLE
Help text / titles / bubbles

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#64]
Add help text in a bunch of different forms to navigate some of the more quirky features of the app.

**Comment by Lomilar** [comment]
Could be a tour (see tour in rdf.tools)

**Comment by miledivovic** [comment]
Need some feedback on what things should be highlighted / explained in this tour.

**Comment by miledivovic** [comment]
Labels of the fields in the edit panel now show a tooltip when hovered over, need to find descriptions of the skos fields still.
