### ISSUE TITLE
Issue - getting java error:java.security.spec.InvalidKeySpecException on attempt to export frameworks

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#640]
The following error occurs on attempt to export a framework
java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence

**Comment by mparsons-ce** [comment]
NOTE: this issue only occurs on production, staging and sandbox are OK.

**Comment by Lomilar** [comment]
@woodkri This is an issue when we do a redeployment in Tomcat without restarting Tomcat. Some libraries freak out, and their name is BouncyCastle.
@mparsons-ce Restarting the Tomcat service will resolve this issue.

**Comment by mparsons-ce** [comment]
Thanks, did the restart and now can publish frameworks.
