### ISSUE TITLE
Credential Engine is moving to a different server, and the publisher domain will change to apps.credentialengine.org/publisher - implications for CaSS

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#645]
The publisher site will be moving to apps.credentialengine.org/publisher. 
The production CaSS implementation uses http://Cass.CredentialEngine.org.
@Lomilar 
We don't think that these changes will impact CaSS or require any changes but just want to confirm one way or the other.

The current SSL certificate expires on Nov. 11, 2020.
![image](https://user-images.githubusercontent.com/58825866/73869538-0d6ac880-4810-11ea-9f24-7f7917504a06.png)

We are using Let's Encrypt for the apps site. We could switch the CaSS SSL to the latter in November or now? If we switch now, will you have to do an export and then import into tomcat?

**Comment by Lomilar** [comment]
The ask here is to move CASS to something like apps.credentialengine.org/cass?

Being linked data, this would normally be a huge issue, but given we use CER urls for everything, it may be less of a problem than expected.

- [ ] Determine if there is data in CE CaSS with cass.credentialengine.org domain name

**Comment by woodkri** [comment]
I searched for up to 5000 records, and got 5000 results, mostly relations.

**Comment by Lomilar** [comment]
OK. There are probably performance impacts to changing the domain name, but those are likely the worst offenses we will have to deal with. I'd recommend a soft transition: Set up apps.credentialengine.org/cass, test things, don't take down the previous one until it works, then take down the previous and test some more.

**Comment by mparsons-ce** [comment]
@Lomilar No  There is not a plan to change the CaSS related domain. We just want to determine of there will be any impact. 
The second part is when to change the SSL certificate to be under Let's Encrypt

**Comment by Lomilar** [comment]
Oh oh, that makes things much easier.

No. There should not be an impact, changing the originating domain for the publisher (and not the CaSS system). Neither should the SSL certificate change have an effect.

... most of the time. Some very old versions of Java don't have the LetsEncrypt certificate authority (I forget who it is) in their certificate store. I'd categorize this under legacy support if anything.
