### ISSUE TITLE
On staging attempted to import file with nine frameworks and site would not respond

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#649]
I attempted to upload the attached file on staging. 
CaSS would recognize the file contained 9 frameworks and the number of competencies. 
I clicked the file to start import. 
While there is often a 'pause' before the import spinner would show, nothing happens. 
In chrome, after some time, a message would display indicating the app is not responding. 

I also tried a file with three frameworks that worked last week. I had the same issue of no response. 

[Vincennes University file with 9 frameworks_times out_staging.xlsx](https://github.com/cassproject/cass-editor/files/4372153/Vincennes.University.file.with.9.frameworks_times.out_staging.xlsx)

**Comment by woodkri** [comment]
It looks like the file isn't formatted correctly. When I open it up in Google Sheets, I can see the ctid in 3 different columns for 3 different frameworks, and the header fields for one framework at the end of the previous framework (@type, ceasn:creator, etc...).

![vincennes screenshot](https://user-images.githubusercontent.com/33300923/77430278-4b687f80-6db1-11ea-9524-641b8ec808d9.PNG)

Can you send me the other file that used to work and isn't anymore? I can take a look.

**Comment by mparsons-ce** [comment]
@woodkri Thanks. After merging I just deleted the rows where I saw an @variable and didn't notice that the line had wrapped (i.e. had header properties on the previous row). 
I removed the extra stuff and was able to successfully to an import.
