### ISSUE TITLE
Data issue with publication status in older records.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#650]
No action to take in cass editor.

The following frameworks need to be updated to represent the correct publication status:

[https://cass.credentialengine.org/api/data/?q=%22http://credreg.net/ctdlasn/vocab/publicationStatus/%22](https://cass.credentialengine.org/api/data/?q=%22http://credreg.net/ctdlasn/vocab/publicationStatus/%22)

**Comment by mparsons-ce** [comment]
The @id for the DQP entry doesn't have a registry URI
"@id": "http://degreeprofile.org/dqp",

_Competency frameworks_
**Done**

- Bachelor of Science in Information Technology (Coursework Competencies)
- Certified Information Systems Security Professional (CISSP) Exam  Competencies 
- Building Operator Certification (BOC)  Level I Training Certificate of Completion Competencies
- Building Operator Certification (BOC) Level II Training Certificate of Completion Competencies
- American Board of Genetic Counseling (ABGC) Detailed Content Outline
- WorkKeys Graphic Literacy
- WorkKeys Workplace Documents

**Not published, fixed the publication status**
- Degree Qualification Profile
- Surgical Technologist Certifying Examination
- Surgical Tech Job Standards - General Surgery

**Org api issue (fixed status, will probably be unpublishing)**
Association of Boards of Certification (ABC) - to be removed

- Professional Operator Wastewater Treatment Need-to-Know Criteria
- Water Distribution Operator Class I Need-to-Know Criteria
- Water Distribution Operator Class II Need-to-Know Criteria

_Concept Schemes_
**Done**

- Agent Sector
- Action Status
- Agent Service Type
- Assessment Method
- Audience
- Cost Type

 NO CTID FOUND for ConceptScheme Name: ISTE Competency Glossary, id: https://cass.credentialengine.org/api/data/schema.cassproject.org.0.3.skos.ConceptScheme/902b2e93-6ad7-4cb1-a4ed-7da889b7fc51/1554919381853
