### ISSUE TITLE
Need to be able to pre-filter the search based on property values

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#653]
@woodkri @Lomilar 
We have a need to be able to embed the concept scheme search via CASS into our bulk upload page and have it only show specific concept schemes based on those concept schemes having a particular ceasn:conceptTerm value.  This filtering would need to be transparent to the user.

**Comment by woodkri** [comment]
You can display schemes with a particular conceptTerm value by adding to the URL parameters:
filter=ceasn\:conceptTerm:"http://termIdHere"

Will that work for your purposes?

**Comment by siuc-nate** [comment]
Possibly - I'm not sure how far along into the relevant implementation we are (@mparsons-ce has been handling it).  

Is there a way to do it in real-time (ie via postMessage) so that the editor doesn't have to be reloaded when the filter is changed?
