### ISSUE TITLE
typeError on attenpt to download frameworks as CTDL-ASN

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#657]
I tried downloading as Credential Engine CTDL-ASN the O*Net Basic Skills competency framework (https://www.onetcenter.org/ctdlasn/resources/ce-07c25fd1-9119-11e8-b852-782bcb5df6ac) and get the following error:

TypeError: d.isAny is not a function

**Comment by woodkri** [comment]
Was this on production? It's working for me on both production and staging: https://cass.credentialengine.org/api/ceasn/70d27b782c062d1280b240890141dcf6
https://staging.credentialengine.org/api/ceasn/70d27b782c062d1280b240890141dcf6

**Comment by stuartasutton** [comment]
It was https://apps.credentialengine.org/publisher/Competencies

**Comment by woodkri** [comment]
Are you still getting that error? It's exporting fine for me.

**Comment by stuartasutton** [comment]
Seems to have cured itself.

**Comment by woodkri** [comment]
In that case I'll close the issue. Feel free to reopen if it happens again!
