### ISSUE TITLE
The publisher, creator, and publication status properties are being wiped on edit by a different user

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#658]
re: **NHA Certified Electronic Health Record Specialist (CEHRS)**
The latter was created by Scarlett after selecting NHA as the organization - so the default values for publisher, creator and publisher name were added.
I later selected to edit the framework using the direct link of: 
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-4f9285d7-2c9f-49dc-b563-cd54776f7c11

In the display view (before clicking the edit button), the publisher, creator and publish status are blank. If I edit the record, the properties are indeed blank. I added the properties and successfully published the record. 

I then logged in as Connie Sears (from NHA). The CEHRS framework doesn't show in the search - even though it was created under the NHA organization - originally. 
I (Connie) then went to the organization summary page and clicked the link to directly edit the framework. 
Again the 3 mentioned properties **were blank** (again before even editing the framework).
I added the three properties and was able to save. 
Now the framework does show in her search. 

Next I went back to my user and did a direct edit of the framework - **the properties did display properly.** 

Unfortunately I could not recreate the condition with any of the other NHA frameworks - that is I did a direct edit of several and in no case where the properties wiped out.

**Comment by woodkri** [comment]
Looking through the version history for the framework, it looks like the publisher and creator weren't being wiped out, they just weren't being added in the first place. Interestingly, there was no owner of the object until version 153 (latest version is 155). My guess is that there was a problem with either sending or receiving the post messages for identity and template when the framework was initially created.

That doesn't explain further editing though, I'm not sure what happened when you attempted to add the properties, save and publish as yourself.

**Comment by mparsons-ce** [comment]
this could be related to #825

**Comment by mparsons-ce** [comment]
As this scenario could not be recreated, it is being closed.
