### ISSUE TITLE
Attempt to publish: Education Design Lab 21st Century Skills results in a type error

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#660]
@woodkri @Lomilar 
Attempted to publish framework: Education Design Lab 21st Century Skills 
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b

We get an error. Following is the message displayed attempting to export.
![image](https://user-images.githubusercontent.com/58825866/86291635-e349e680-bbb4-11ea-81cd-5f901be6d7c7.png)

**Comment by woodkri** [comment]
It looks like somehow a couple of relations got deleted from the repository but not removed from the framework: https://credentialengineregistry.org/resources/ce-02d39179-120c-4e0a-baf9-99d3baeb610a and https://credentialengineregistry.org/resources/ce-9c2d9eb3-ccc0-40b4-994d-7a759d2740af

I will add some null/undefined checks to the export code, but in the shorter term it's probably better to just remove those relations from the framework. Let me know if you want me to go ahead and do that.

**Comment by mparsons-ce** [comment]
I could not find either of the referenced ctids in the published framework - in order to know from where to delete them.
How can I find these?

**Comment by woodkri** [comment]
Turns out there was another issue here related to a duplicate variable name when there's a schema:identifier field on the object. I've pushed a fix for this, it will be part of the next release.

**Comment by mparsons-ce** [comment]
@woodkri So we will not be able to publish this until the next release?
If so, when is the next release date?

**Comment by woodkri** [comment]
Not with the ceasn:identifier fields included on the competencies. The same identifier appears to be used for several of the competencies, I can't see what's at the other end of the URL though.

Is there an urgent need to publish the framework with the identifier fields? We don't have a schedule for releases so I don't know for sure when the next release date will be.

**Comment by mparsons-ce** [comment]
Scarlett didn't add the identifiers and doesn't think that the partner would know to add an identifier. 
http://frameworks-staging.act.org/uri/d83efde8-99a6-11e8-8c6e-0f5268d15f8c

She did do some alignment to O*Net competencies. Given that the identifiers refer to act.org, it seems like some related activity added the identifier.

**Comment by mparsons-ce** [comment]
I removed all of the Identifier properties, and then was able to publish the framework.
