### ISSUE TITLE
Unable to delete some 'test' frameworks in production

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#665]
@woodkri I have been trying to remove some 'test' frameworks from production, with some issues.
For the following, I tried to delete them but they refuse to be put down. 
![image](https://user-images.githubusercontent.com/58825866/91065529-3610af00-e5f6-11ea-9fc4-ea3f8444f435.png)

I renamed them DELETE-ME - cm # so I could be sure which ones didn't work. The original name was just 'cm'. I was able to delete one. For others, the delete would appear to work, and I would be sent back to the search. The framework would still show but with the name reverted back to 'cm'.

I had a similar problem with these two:
![image](https://user-images.githubusercontent.com/58825866/91066019-c9e27b00-e5f6-11ea-82b1-5d0156abebde.png)

Could you please purge these from production.

**Comment by woodkri** [comment]
I've deleted the framework with credentialregistry ids. The two cm frameworks with cass.credentialengine.org ids came up in #596 and I haven't figured out how to remove them from the search results yet.

**Comment by mparsons-ce** [comment]
Thanks Kristin.

**Comment by woodkri** [comment]
@mparsons-ce The 'cm' frameworks have now been removed as well.

**Comment by mparsons-ce** [comment]
Thank you.
