### ISSUE TITLE
At crosswalk end, handle finish - return to framework if possible

### ISSUE THREAD

**Issue by AleitaT** [cassproject/cass-editor#669]
When crosswalking it makes sense to return to the framework you saved to when finished

- [x] add in processing icon on saving.
- [x] If only one of the frameworks was editable - on successfully save return to that framework with all properties showing to ensure relationships are showing 
- [x] If both frameworks were editable return to the framework list view sorted by last modified 

@woodkri , this was discussed with Scarlett so I'm putting it here.

**Comment by woodkri** [comment]
Marked working by QA. Included in release 1.3.14 and later.
