### ISSUE TITLE
Concept Scheme editor in production shows no schemes

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#684]
@woodkri 
There should be a lot of concept schemes in production;
https://apps.credentialengine.org/publisher/conceptscheme

On search none appear. 
I created a simple concept scheme, saved it and returned to the search - the new scheme is not shown.

The URL used by the editor is the following:
https://cass.credentialengine.org/cass-editor/?user=wait&amp;editorRoot=/cass-editor/&amp;server=https://cass.credentialengine.org/&amp;ceasnDataFields=true&amp;webSocketOverride=wss://cass.credentialengine.org:8080/ws/custom&amp;newObjectEndpoint=https://credentialengineregistry.org/resources/ce-&amp;show=mine&amp;concepts=true

The competency framework editor is working as expected. The editor URL is:
https://cass.credentialengine.org/cass-editor/?user=wait&amp;editorRoot=/cass-editor/&amp;server=https://cass.credentialengine.org/&amp;ceasnDataFields=true&amp;webSocketOverride=wss://cass.credentialengine.org:8080/ws/custom&amp;newObjectEndpoint=https://credentialengineregistry.org/resources/ce-&amp;show=mine

The same issue occurs in the staging environment:
https://staging.credentialengine.org/cass-editor/?user=wait&amp;editorRoot=/cass-editor/&amp;server=https://staging.credentialengine.org/api/&amp;ceasnDataFields=true&amp;webSocketOverride=wss://staging.credentialengine.org:8443/ws/custom&amp;newObjectEndpoint=https://staging.credentialengineregistry.org/resources/ce-&amp;show=mine&amp;concepts=true

**Comment by woodkri** [comment]
I'm investigating this, it's possible there's a problem with whitespace in the identities and/or templates again. In the meantime, you can view the concept schemes by removing show=mine from the URL.

**Comment by woodkri** [comment]
I think you all had removed whitespace from all the identities you were passing to CaSS at one point, but there's whitespace embedded in the @owners listed in the templates you're passing us. I think this is breaking the search when the ownership is restricted with show=mine.

**Comment by mparsons-ce** [comment]
@woodkri 
Note that the Concept search does work in the sandbox using the new version of CaSS. 

@siuc-nate 
Nate,
As noted by Kristin, there is an issue with whitespace. This does sound familiar. 
Did you have to do some fix for this before? 
Both ConceptSchemes and Framesworks call the same method to get the owners, yet frameworks is OK, and ConceptSchemes fail.

**Comment by woodkri** [comment]
The frameworks search does return some frameworks but I don't think it shows all of them with show=mine. With the admin account selected, I see show=all in the iframe URL instead of show=mine. The concept scheme one does have show=mine with the admin account selected though.

**Comment by siuc-nate** [comment]
I think I had added something to remove whitespace from the keys that get generated in the accounts system - I'm pretty sure they're stored without it in the database, but if they aren't, then there must be something either in the C# that reads from it or in the javascript that talks to CaSS that removes it.

**Comment by woodkri** [comment]
Turns out Chrome made a change that broke our newline replacements. Putting in a workaround now and we'll be updating libraries and builds. In the meantime, it should still work on Firefox.

**Comment by woodkri** [comment]
We've addressed the javascript engine change. You should see concept schemes with show=mine again, and the "show only mine" button should work again.

**Comment by mparsons-ce** [comment]
I have noticed inconsistencies with getting post messages for concept schemes. 
We have a number of listeners setup:

```
		addMessageListener("", function(data){
			console.log("Received Message from CaSS", data);
		});

		//User selects Concept Scheme or search view
		addMessageListener("viewChanged", viewChanged);
		addMessageListener("competencyChanged", dataChanged);
		addMessageListener("conceptChanged", dataChanged);
		addMessageListener("frameworkChanged", dataChanged);
```
I have not been getting any of the dataChanged events in the sandbox. I sometimes see this error:
![image](https://user-images.githubusercontent.com/58825866/92795539-127b9180-f376-11ea-9465-28a7b77cae9f.png)

**Comment by woodkri** [comment]
Is this on sandbox or staging? It looks like your screenshot is from the new version of the editor, so not production.

Are you getting messages for frameworks and competencies, but not concept schemes and concepts? Or none of them?

**Comment by woodkri** [comment]
If this is on staging, it may be because the websocket connection fails due to an expired certificate:

`WebSocket connection to 'wss://staging.credentialengine.org:8443/ws/custom' failed: Error in connection establishment: net::ERR_CERT_DATE_INVALID`

**Comment by woodkri** [comment]
@mparsons-ce Is this still an issue?

**Comment by mparsons-ce** [comment]
Closing as fixed (SSL update)
