### ISSUE TITLE
Allow user to omit @id in CTDL-ASN spreadsheet upload

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#691]
If they provide a ctid but no @id, we can assign the id based on that.

**Comment by mparsons-ce** [comment]
Can we also include that the HasChild, HasTopChild, etc also handle just CTID?
The destination credential registry domain would be the same for all contents of an upload.

**Comment by woodkri** [comment]
Coming in the next release, you can use CTIDs in place of the full id for the CTDL-ASN CSV import. The @id field is still required but can be the shorter CTID and we'll turn it into a full id. Relation fields as well.

**Comment by woodkri** [comment]
Included in 1.3.14 and later.
