### ISSUE TITLE
Hide or disable 'Add property' button if there are no more properties to add

### ISSUE THREAD

**Issue by AleitaT** [cassproject/cass-editor#697]
Right now on at least the create framework workflow, if the user clicks 'add a property' after adding a name and description (the only available properties) the add property section displays with no properties, which is confusing. 

- At a minimum, there should be a message displayed when there are no more available properties when arriving on this section of the edit framework/competency workflow.
- Ideally, the 'add property' button is disabled and a hover message is available that indicates that no more properties are available to add. 

<img width="913" alt="Screen Shot 2020-10-13 at 6 09 52 AM" src="https://user-images.githubusercontent.com/12263415/95865296-5d911780-0d1b-11eb-82fb-e3e02f47255a.png">

**Comment by woodkri** [comment]
QA marked this as working.
