### ISSUE TITLE
Deleting framework name removes framework name  input when creating a new framework

### ISSUE THREAD

**Issue by AleitaT** [cassproject/cass-editor#698]
Steps to reproduce 
- go to framework list page
- click create new framework
- delete framework name 
- if the property input doesn't disappear, click to add a new property and it should cause the bug 
<img width="971" alt="Screen Shot 2020-10-13 at 7 06 05 AM" src="https://user-images.githubusercontent.com/12263415/95871521-98e31480-0d22-11eb-8b3b-99a8bc064bfc.png">

**Comment by woodkri** [comment]
@AleitaT  I'm having trouble reproducing this. If I click the x to delete the framework name I get "This property is required. It cannot be removed." If I just remove the text from the input, I see "Framework Name is required. Please enter a value." Clicking to add a new property doesn't do anything.

Do you happen to remember what configuration you were using? I'm wondering if there's one somewhere that doesn't have framework name marked as a required field.

**Comment by AleitaT** [comment]
Unable to reproduce.
