### ISSUE TITLE
Adding top level competencies from other frameworks is bugged

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#7]
Steps to reproduce:
1. Create a new framework
2. Edit the created framework (should be empty)
3. Add a top level competency via search
4. Add a competency from any framework
5. Click add

The add button does not work, this error appeared on the console:
editFramework.js:67 Uncaught TypeError: Cannot read property 'shortId' of null
    at appendCompetencies (editFramework.js:67)
    at cappend (server.js:88)

Additionally this bug can cause the editor to freeze as depicted in this screenshot:

![clicking add can freeze the editor](https://user-images.githubusercontent.com/23706850/32516229-7d367946-c3b7-11e7-8b1f-fb4580ec4174.PNG)

**Comment by miledivovic** [comment]
Fixed in f8eb3d4

**Comment by eddavies** [comment]
Fix verified

**Comment by Lomilar** [comment]
This change caused a huge performance degradation in loading large frameworks.
![image](https://user-images.githubusercontent.com/337692/32808060-c553788e-c946-11e7-87bf-726599dcb930.png)

What was this seeking to fix?

**Comment by Lomilar** [comment]
Could not repro after above commit (and reverting part of @f8eb3d4) -- Please retest.

**Comment by eddavies** [comment]
Able to add top level competencies from another framework
