### ISSUE TITLE
404 Error when attempting to search for competencies to add to new framework

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#70]
Just created a new framework. Went to search for competencies to add from the framework head and got this error:
![404](https://user-images.githubusercontent.com/23706850/33451266-5394fa22-d5c3-11e7-9740-87fc800ead1b.PNG)
Happens with or without ceasnDataFields. Cannot search at all anymore

**Comment by Lomilar** [comment]
Duplicate of #69 (with a poor regression fix) -- Fix in 69 should address this.

**Comment by eddavies** [comment]
Fix Verified
