### ISSUE TITLE
In export of O*Net framework hasChild is now an object containing @list

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#705]
I noticed errors publishing from CaSS for some frameworks. 
I checked the O*Net Cross-functional skills.
The competency  hasChild is now an object containing @list where it used to be a list of URIs
![image](https://user-images.githubusercontent.com/58825866/95929240-1fcad800-0d89-11eb-928f-8f25bbc7792c.png)

Same error for Surgical Technologist Certifying Examination
https://cass.credentialengine.org/api/ceasn/72679bb98ef93926374e361ce78c468f

**Comment by woodkri** [comment]
We haven't made any changes to this. Has the ctdlasn context changed to remove '@container: "@list"', and if so is the change permanent? We'll need to change our translation if so.

**Comment by siuc-nate** [comment]
This was a bug on our end, I think it was related to [when we merged the context files](https://github.com/CredentialEngine/Schema-Development/issues/689). It should be fixed now.
