### ISSUE TITLE
Date Created on CE Production

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#733]
Missing dateCreated fields were set by script in June of 2019. Some of those frameworks already had a dateModified, so now the frameworks have a created date that is later than the modified date. Created date should be before or equal to modified date.

**Comment by woodkri** [comment]
Script has been run to convert any dateCreated fields that were later than dateModified to the value of dateModified.

**Comment by mparsons-ce** [comment]
Thanks
