### ISSUE TITLE
Keyboard controls cease to work after using "alt-left arrow" from searching for a concept term

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#75]
Using alt-left to go back/cancel the search makes it so tab does not select any of the fields within the framework, only the url and browser specific buttons.

**Comment by eddavies** [comment]
So I missed some steps here.
1. Edit a framework and search for a concept term
2. Access a concept scheme and attempt to edit the scheme
3. Search to add a concept term to the concept scheme
4. user is brought to a blank page
5. using alt-left will make keyboard commands no longer work

**Comment by miledivovic** [comment]
Fixed in a6215e5.

Please do a full re-test of keyboard shortcuts, a bunch of stuff changed and could have broken.

**Comment by eddavies** [comment]
Fix verified. Doing full re-test of keyboard shortcuts will post findings as new issues.
