### ISSUE TITLE
Improve encryption/decryption performance via Async crypto methods.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#768]
src/components/framework/Share.vue:758,770

Sync versions of encryption and decryption are discouraged, as it doesn't take advantage of native hardware to perform that crypto. Recommend use of EcEncryptedValue.toEncryptedValueAsync().

Searching across the project, use of the synchronized method is typical. Recommend use of async across the app.

**Comment by Lomilar** [comment]
Noticing significant vue/ui hooks updating as timestamps are being updated during encryption. This is now the performance blocker for encrypting large frameworks.

**Comment by Lomilar** [comment]
I think the above performance hit is forcing UI updates... may need some way to keep the UI updates from going all the way out to the DOM.

**Comment by woodkri** [comment]
Included in 1.3.15
