### ISSUE TITLE
Need concept export of entire scheme and graph.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#77]

**Comment by Lomilar** [comment]
@stuartasutton Is this of use to you if it is still outputting disjoint graphs (URIs dont match)? Should this wait until the long/short ID stuff is taken care of?

**Comment by stuartasutton** [comment]
Do we have any sense on how long before the long/short issue is tackled?

**Comment by Lomilar** [comment]
Not at the moment. It's probably one of the first things on the list for CASS 0.4 (2018) though. Issue chain is as follows:

cassproject/cass-editor#80
cassproject/CASS#34
eduworks/ew#9

**Comment by woodkri** [comment]
@lomilar I opened a pull request for schema.cassproject.org as there are a couple of fields that I missed in the initial translation. There are a few other skos fields that don't translate properly but I believe it's because they're either not listed or defined as @id rather than a langstring in CTDL-ASN's context (http://credreg.net/ctdlasn/schema/context/json).

**Comment by Lomilar** [comment]
https://dev.cassproject.org/api/ceasn/b99ad43eb6b533b5c09e43d680ad33b4 (Export of the Connecting Credentials) has an ID fetch error, probably needs a null check.

**Comment by woodkri** [comment]
Linked to an issue in the wrong repository - https://github.com/cassproject/CASS/commit/c4f28dfb0c53fdafd7c2ad69a6857ec3333158fd adds null checks to the export. The Connecting Credentials that was linked was an old version of that concept scheme, I accidentally deleted it so I don't know if that commit would fix that particular issue or not. I'm not finding any other frameworks with the same issue. The imported Connecting Credentials Levels exports fine here: https://dev.cassproject.org/api/ceasn/9a794e243b56c1f37d27bdbf874ad5c8

**Comment by Lomilar** [comment]
Should the context for the CE Profile of SKOS export use "http://credreg.net/ctdlasn/schema/context/json" or "http://credreg.net/ctdl/schema/context/json"?

Which does the publisher expect?

**Comment by siuc-nate** [comment]
Use http://credreg.net/ctdlasn/schema/context/json
