### ISSUE TITLE
Add industryType and occupationType to CTDL-ASN competency frameworks

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#788]
Including:

- [ ] Configuration
- [ ] Import translation
- [ ] Export translation

These will be an array of strings that the publishing process will transform.

**Comment by jeannekitchens** [comment]
@mparsons-ce @siuc-nate add a property for CaSS so the existing API can expand the codes (i.e., the API will identify the name and description for NAICS and SOC codes).  @mparsons-ce provide @woodkri what you want in the export.

**Comment by mparsons-ce** [comment]
Suggested properties:
- SOCList or ONETList?
- NaicsList

**Comment by woodkri** [comment]
https://www.bls.gov/soc/

**Comment by woodkri** [comment]
Which heading do you want these under? We have "General", "Tagging", "Connections", "Context", "Rights", "Keys" in your configuration currently. And do you want these to show up under low, moderate, or high detail?

Any preference on the order they show up in the list of properties?

**Comment by woodkri** [comment]
Per https://github.com/CredentialEngine/Schema-Development/issues/757:
Add socList and naicsList to Competency as well, along with cipList.

I have the same questions for Competency as for Framework - which heading, which detail level, and which order?

We're preparing for our next release, do you want these to be included in that?

@mparsons-ce @jeannekitchens

**Comment by mparsons-ce** [comment]
@woodkri 
re: Which heading do you want these under? 
I would suggest general.
@jeannekitchens @siuc-nate ???

re: release
Sure, please do include these changes.

**Comment by mparsons-ce** [comment]
@woodkri 
I was able to add a list of SOC to the CyberSecurity collection. 
![image](https://user-images.githubusercontent.com/58825866/111700744-d4b96300-8807-11eb-92b9-6341b4d6b6ce.png)


However, on export the socList property is not included:
https://dev.cassproject.org/api/ceasn/369952bf505a99fabdda57119e007f68

**Comment by woodkri** [comment]
My apologies, I don't think we've deployed the new 1.4 release to the dev.cassproject.org server yet. The front end reflects the 1.4 code but the export takes place server side.

This should be working on staging since I did deploy 1.4 there.

**Comment by woodkri** [comment]
Closing as verified in 1.4.0.
