### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window' in Chrome Incognito

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#793]
I was logged into the sandbox using Chrome incognito. Whenever I go the CaSS page, I get the following message. 

![image](https://user-images.githubusercontent.com/58825866/108562358-58de0080-72c5-11eb-9792-8d7787359574.png)

This is for a user I just created recently for Western Gov. 
I then tried my regular admin user and get the same message.

**Comment by woodkri** [comment]
Is this causing any problems within the application, or just sending an error message to the console?

**Comment by mparsons-ce** [comment]
I could not continue with the app after receiving the latter message.

**Comment by woodkri** [comment]
In 1,4.0.
