### ISSUE TITLE
Searching for a framework bug

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#8]
The framework Mosaic keeps opening after attempting to search for a different framework.

Steps to reproduce:
1. Open https://cassproject.github.io/cass-editor/
2. Click on search and type in "Mikael" (or anything) (The framework Mosaic gets highlighted in gray after typing into the search box)
3. Click enter to search
4. Mosaic will open instead of the search (but clicking back will open the correct search results)

**Comment by Lomilar** [comment]
@miledivovic Related to the competency selection / keyboard shortcuts?

**Comment by miledivovic** [comment]
Fixed in 4a03314

**Comment by eddavies** [comment]
Fix verified
