### ISSUE TITLE
Consider returning @id without the version...

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#80]
For systems that don't resolve URLs via HTTP requests, the @id including version differing from most references causes issues.

**Comment by Lomilar** [comment]
cassproject/cass#34

**Comment by Lomilar** [comment]
@stuartasutton @siuc-nate

This is being accomplished via a feature that allows the cass-editor to create, modify and manage frameworks that "aren't hosted on CASS" -- what we've been calling 'registered' objects -- their @ids point at some canonical location or can even be URIs. Versioning is disabled (really made invisible) on such objects.

The code has been committed for this and is undergoing pretty extensive testing, because how we think about objects (they are located at their @id) is no longer true, meaning we have to track @ids as well as the repository they are homed at -- in all the code, import, etc. We want to make sure it works before deploying it.

Just wanted to let you know it is on the way.

**Comment by Lomilar** [comment]
46614d73d9bc4c5c7076762654ca3820f051c631

**Comment by siuc-nate** [comment]
How does searching work with data that isn't in CASS?

**Comment by siuc-nate** [comment]
I would worry about the performance impact and code maintenance (ie maintaining code that hits multiple third-party search APIs) and third-party API search query quotas and so on for data that isn't in CASS somewhere. If the point of CASS is to be an index/repository, then that is exactly what it should be.

I think that having the data in CASS (for technical/search reasons) and just maintaining external `@id`s is probably okay - though it does mean you could never resolve that data in CASS if there is no CASS URI for it, right?

Why not just issue everything resolvable in CASS a URI/`@id` that points to CASS and leverage the schema:sameAs property for all of the foreign URIs? This would allow CASS to have a CASS URI that always resolves to the CASS representation of a record (along with all of the data transformation benefits that brings) while also maintaining a link (literally) to the same data in other systems (i.e., the Credential Registry _and_ the actual data owner's website, etc.).

Then everything in CASS would have a CASS URI and the problem is greatly simplified, no? What is the point of schema:sameAs if not for this exact use case?

My two cents, anyway.

**Comment by Lomilar** [comment]
We can store objects where the @id is held elsewhere. We could also spider links and register remote data locally (making it searchable). Nothing in CASS _has_ to have a CASS URI (any longer, with the changes in #80)

But the claim that CASS is a search index is (was?) only secondary to it being a repository. It was intended to "search the data it stores", but requirements are starting to turn that into "store data it searches".

**Comment by siuc-nate** [comment]
I had thought there was supposed to be a 1:1 correlation between "data stored" and "data searched" - perhaps I was mistaken.

**Comment by Lomilar** [comment]
Right. If other systems want to put all their data into CASS and update everything when it changes, we're more than happy to act as a search index for that data.

When the requirements move towards harvesting/spidering other repositories, that's when things start to get more complicated.

Are we talking about the former or latter?

**Comment by siuc-nate** [comment]
I'm probably just misunderstanding what you mean by "harvesting" - to me that means the storing and searching data inside CASS.  I'm not sure what you mean by "spidering".

**Comment by Lomilar** [comment]
A harvest is a method where one takes a known endpoint and extracts all data from it, for instance, the CE Registry. [OAI-PMH](https://www.openarchives.org/pmh/) was a method for harvesting metadata repositories, so called "Digital Libraries".

A spider is taking, traditionally a website, but also a linked data document, and following all those links, reading the documents at the end of those links and adding any new links found in the new documents to the list of links to follow... Branching out or 'walking' the web like a spider does.

Both of them have currency problems, in that they have no means of being notified when data changes. This means that not only do endpoints and protocols need to be followed, but re-harvests or re-spidering needs to happen on a regular schedule. This is considered the worst of the models.

In contrast, a search engine publish/subscriber model requires any data repositories or sources to post new data (or links to new data) to the search engine after every create or update. This can have currency problems if the search engine goes down for a period of time. Webhooks and Websockets fulfill this space, as do registered publish-endpoints.

To remedy the currency problems for both, some sort of RSS-like feed for updates can be walked by a search engine, that way the repository only needs to publish to its own RSS feed, and the search engine can read that RSS feed. Other protocols for this can be used, like AMQP, XMPP, even ancient protocols like email or timestamp batching via FTP.

CredentialEngine/CredentialRegistry#152 is asking for such a method from the CER, in hopes of avoiding harvest-based methods.

**Comment by siuc-nate** [comment]
That explains the miscommunication - I was talking about where the data ends up, you seem to have been talking about how it got there.

In any event, the `@id` thing was just a suggestion - but if you did use non-CASS `@id`s for stuff in CASS, what URI would you use to resolve the CASS representation of that data?

**Comment by Lomilar** [comment]
Right. Yeah, actually indexing the data isn't an issue if it gets into our system somehow, then we can talk about implementing enhanced search and discovery.

There are two major ways to get data that does not call CASS home:
```
<cass-endpoint>/data/?q=@id:<id>
or a more proprietary method:
<cass-endpoint>/data/<md5 of @id>
```

**Comment by Lomilar** [comment]
@siuc-nate Has this been clarified sufficiently?

**Comment by siuc-nate** [comment]
I think so. Thanks.
