### ISSUE TITLE
Web server received an invalid response while acting as a gateway or proxy server.

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#817]
@woodkri @Lomilar 
In production, we are receiving the following error trying to access CaSS:
`502 - Web server received an invalid response while acting as a gateway or proxy server.`

**Comment by woodkri** [comment]
@mparsons-ce Have any IIS or other settings changed recently? I'm seeing the 502 on the old editor but the new editor comes up and searches fail with a 404.

**Comment by mparsons-ce** [comment]
@woodkri @siuc-nate 
I have not made any changes. Nate has been doing testing for elastic 7.x but I would think that would have no impact on CaSS.

**Comment by woodkri** [comment]
I'm logged in, I'm trying to comb through log files and figure out what's going on.

**Comment by woodkri** [comment]
I did a bit more sleuthing and it appears there may be an SSL certificate error of some kind. In the IIS log files, I can see the 502s have a winhttp status code of 12175. From https://docs.microsoft.com/en-us/windows/win32/winhttp/error-messages:

ERROR_WINHTTP_SECURE_FAILURE

12175

One or more errors were found in the Secure Sockets Layer (SSL) certificate sent by the server. To determine what type of error was encountered, check for a WINHTTP_CALLBACK_STATUS_SECURE_FAILURE notification in a status callback function. For more information, see WINHTTP_STATUS_CALLBACK.

**Comment by mparsons-ce** [comment]
Fritz noted the the cert for tomcat was out of date. He exported a new one and updated Tomcat. 
Can now access CaSS.
