### ISSUE TITLE
Hiding large amounts of framework data on scroll makes it hard to see the first competency

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#826]
When the framework node has a lot of data (in terms of vertical space in the editor), and that data is hidden on scroll, this can cause the first competency to be pushed too far off-screen, making it hard or impossible to see data in the first competency.  The first screenshot shows the framework.  The second screenshot shows what the user sees after scrolling one notch on the scroll wheel:

![image](https://user-images.githubusercontent.com/21346519/116270359-9edf9680-a744-11eb-95e9-ece08dc27699.png)
![image](https://user-images.githubusercontent.com/21346519/116270418-aef77600-a744-11eb-9f5c-2c3ca5295b94.png)

**Comment by siuc-nate** [comment]
Any progress on this? We ran into it again today. I was completely unable to see or access the first couple of competencies in a framework because:
1. The framework's description was so long that it was taller than the screen, meaning I wasn't able to see those competencies while scrolled to the top, and
2. Scrolling down at all caused the framework section to be compacted at the top but positioned such that the first few competencies were completely hidden underneath it

It seems like adding some margin/padding (based on the height of the compacted framework) to the framework hierarchy would solve this, along with perhaps not compacting the framework until its visible height was less than or equal to its intended compacted height (essentially only making it "sticky" past a certain point).

Ultimately I had to open the dev tools and delete the framework's description div just to be able to see the competency I wanted to edit.
![image](https://user-images.githubusercontent.com/21346519/121246546-e9395480-c866-11eb-9be0-e15731b12afc.png)

**Comment by jeannekitchens** [comment]
@woodkri is this issue being fixed this sprint?  We're finding that no matter the quantity of information, this is a problem.

**Comment by woodkri** [comment]
We are working on this issue as part of the current sprint.

**Comment by AleitaT** [comment]
This ticket will require some additional design changes.  I'm thinking about an interim solution to hold you over while we work on that Jeanne. I'll posts updates as soon as I have them.

**Comment by siuc-nate** [comment]
A quick solution would be to give this div some top margin when the framework is in compacted mode. That reveals the first competency here:
![image](https://user-images.githubusercontent.com/21346519/121381119-0c1d4480-c90b-11eb-8337-3372f53a8ca6.png)

**Comment by AleitaT** [comment]
This works for me for now, on scroll adding top margin.  Also resolving some unwanted scroll effect that was appearing behind top level framework object.  Will let you all know when mockups are prepared for these screen improvements.

**Comment by siuc-nate** [comment]
Padding instead of margin would probably also work, if that's easier - I know margins can sometimes do weird things you don't want.

**Comment by woodkri** [comment]
Accepted in meeting 9/22
