### ISSUE TITLE
Leading whitespace character not removed on save

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#828]
When I add/edit a competency text, the editor will remove trailing spaces, but not leading spaces or line breaks on save:
![image](https://user-images.githubusercontent.com/21346519/116271846-fd594480-a745-11eb-96a7-3a6531fe54bc.png)

**Comment by woodkri** [comment]
This was in our last sprint and has gone through QA. The fix is up on the master branch and the github deployment and will be part of the next release.

**Comment by mparsons-ce** [comment]
verified
