### ISSUE TITLE
ceasn:minorAlignment does not appear to be getting published

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#829]
While updating the Horizontal Industry Framework, we noticed that one of the competencies had a Minor Alignment.  This alignment data did not appear in the published data, but the other alignments did:
![image](https://user-images.githubusercontent.com/21346519/116272918-ef57f380-a746-11eb-8d57-432e889a9681.png)

Note: We have removed the alignments for now, pending a fix for the normal URLs being turned into registry resource URLs.

**Comment by woodkri** [comment]
Reviewed in meeting 1/5.
