### ISSUE TITLE
Keyboard control concerns

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#83]
For https://cass.credentialengine.org/editor.html:

1. Using the arrow keys to browse frameworks makes the browser page scroll down, making it so it's impossible to view what framework a user is selecting if scrolling down the list.

2. Using tab to select elements is annoying since there are several elements at the bottom of the web page.

3. When framework search is opened via "searching' for competencies or concept terms, the user has to tab to select the search field and click "esc" in order to select from the list of frameworks.

**Comment by miledivovic** [comment]
The scrolling issue should be fixed.

**Comment by eddavies** [comment]
Can't test until pushed to cass.credentialengine.org/editor.html

**Comment by Lomilar** [comment]
This has been published.

**Comment by eddavies** [comment]
Still testing, but so far, using tab is annoying since the user has to tab through the bottom web page elements which sends the user scrolled down to the bottom of the screen, making it difficult to scroll back up to what you're working on

**Comment by eddavies** [comment]
Regression test still needed (will get to it).

**Comment by eddavies** [comment]
Closing this issue. Will post additional findings as new issues
