### ISSUE TITLE
Limit Group Name Length to 60 Characters

### ISSUE THREAD

**Issue by AleitaT** [cassproject/cass-editor#833]
Group Descriptions allow for long descriptions of groups.  For usability and best practice enforcement I am suggesting we limit the character length of group names to 60 characters.

**Comment by Lomilar** [comment]
What's the usability and best practice reasoning? 

Wouldn't use of CSS ellipsis + title remove the need for this from a display perspective? I just imagine there are groups with names longer than 60 characters.

**Comment by AleitaT** [comment]
Right now group name lengths have no bound so you can end up with (image attached).
<img width="1552" alt="Screen Shot 2021-05-03 at 9 21 10 AM" src="https://user-images.githubusercontent.com/12263415/116903180-e8baf780-abf0-11eb-8385-9af123f3f682.png">

Enforcing short names would encourage users to create names that are more friendly to group navigation, inputting longer descriptions in the description box. Best practice would be using a name that is succinct and easy to understand in the given context of the available interface.
