### ISSUE TITLE
Quick Filters not working as expected

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#835]
When logged in as a user (not an admin), I click the "Owned By Me" filter and nothing happens - no search is performed.  I click into the search/keywords bar and press enter, and nothing happens (I can't force a blind search for all of "my" stuff).
![image](https://user-images.githubusercontent.com/21346519/117199620-03879a80-adb0-11eb-8784-33449f4f9413.png)

Clicking instead on "Not Owned By Me" does trigger a search, but it returns zero results (and this user definitely does not own all of the frameworks).
![image](https://user-images.githubusercontent.com/21346519/117199636-08e4e500-adb0-11eb-9038-0c7edb76a7c8.png)

**Comment by woodkri** [comment]
@siuc-nate When not logged in as an admin, you guys have show=mine in the iframe parameters, correct? If so, the interface would already only be showing things that you own. If you clicked 'owned by me' the results wouldn't change, and if you clicked 'not owned by me' it would try to search for things that you own AND don't own.

We should probably hide those filter options if show=mine.

**Comment by siuc-nate** [comment]
It would make sense to either make the filter do something so it doesn't "feel" broken, or hide it, yes.

Also, it seems that the user can't force the search to be re-performed by pressing enter while the keywords box is focused (regardless of whether or not there is anything typed into it). Is that intentional?  It only responds to the initial press of enter.

**Comment by woodkri** [comment]
Can you provide more detail on the issue with pressing enter? I tried a few search terms without un-focusing the search bar and it re-searched each time I hit enter.

**Comment by siuc-nate** [comment]
If you try to do the same search twice, it doesn't respond to subsequent presses of enter.  For example:
1. Open CaSS
2. Type `test` into the search bar
3. Press enter
4. A search is performed
5. Press enter again
6. Nothing happens

**Comment by mparsons-ce** [comment]
@siuc-nate   verified.
