### ISSUE TITLE
File Upload UI does not respond visually

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#839]
Hovering the mouse over the dotted area for the "Import from file" UI doesn't lead to any effects/colors/response/etc. from the UI, nor does the mouse cursor change to indicate that that whole area can be interacted with.  The only button-like element is the "Process Files" button in the center. The user's eyes are naturally drawn to this button, but it is both grayed out and presents a "disabled" cursor when hovered over. This can lead to the perception that the file upload functionality is not currently available. If the user clicks on the disabled button, the click event bubbles up to the import area and the user is prompted to select a file - for a seemingly disabled button.  

Ideally, the entire dotted area should react when hovered over.  Suggestions include:
- Change the background color slightly
- Change the mouse cursor to "pointer"

Those same (or similar/appropriate) effects should also happen when the upload box is focused via tab.

I would also suggest hiding the "Process Files" button entirely until it is ready to be clicked.

**Comment by woodkri** [comment]
Looked at in meeting 1/19.
