### ISSUE TITLE
Clicking "Done" after uploading a framework directs the user to the CaSS starting page

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#840]
I imported a framework, and clicked "Done" (the button with the house icon on the second or third screen after importing), and was taken to the page in the screenshot below.

The user should be directed back to the search, rather than seeing a page like this, which provides information about creating a user, groups, configuration, etc., that is outside of credential engine.  The user should never see this page in CE cass.

![image](https://user-images.githubusercontent.com/21346519/117205270-076aeb00-adb7-11eb-8652-b985f48af737.png)

**Comment by mparsons-ce** [comment]
verified.
