### ISSUE TITLE
Make iframe height match contents to remove scrollbar.

### ISSUE THREAD

**Issue by otterlove** [cassproject/cass-editor#85]
The extra scrollbar is awkward. Having the page behave more like a traditional search result page would be much better. Large numbers of search results are better handled via pagination or lazy loading.

Suggest making the iframe height adjust to fit it's contents. Something like the solution here: https://stackoverflow.com/questions/819416/adjust-width-height-of-iframe-to-fit-with-content-in-it

**Comment by Lomilar** [comment]
Requires #86

**Comment by Lomilar** [comment]
I suggest https://github.com/house9/jquery-iframe-auto-height on client webpages.
