### ISSUE TITLE
Error on import in sandbox

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#853]
I tried to import a small test framework, and the javascript crashed somewhere (I didn't have the console open at the time to catch it happening).  Opening the console afterwards did show some evidence though.  The spinner in the UI gets left in a permanent spinning state when this occurs.
![image](https://user-images.githubusercontent.com/21346519/119044396-c0b4ed80-b97f-11eb-9e85-afd33719f761.png)

I had logged in as an admin and selected the CE account.  @mparsons-ce could this be related to the recent update to the admin keys?

**Comment by woodkri** [comment]
We've addressed the error you're seeing in the console in our libraries but it's not updated in the interface yet. I will make sure that gets updated.

Something in the import process is erroring before that though. I'm happy to take a look at the file if you want to send it over.

**Comment by siuc-nate** [comment]
In case this thread gets checked later - I sent the data to Kristin and she will check it over at the next available opportunity.

**Comment by jeannekitchens** [comment]
@woodkri Nate had emailed you the file.  Any status on this?

**Comment by woodkri** [comment]
@jeannekitchens I was out on Friday but I'm hoping to have some time to look it over this afternoon.

**Comment by woodkri** [comment]
@jeannekitchens I had a chance to look over the file and have just sent some feedback by email.

**Comment by jeannekitchens** [comment]
The updates on sandbox fixed the workflow for sending an error message back.  @siuc-nate check this on sandbox.

**Comment by mparsons-ce** [comment]
@siuc-nate Kristin demo'd the fix for me.
Let me know if you want to verify this separately, otherwise we can close it.

**Comment by siuc-nate** [comment]
We can close it.
