### ISSUE TITLE
Elasticsearch weighting seems to be off

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#856]
Shouldn't framework name matches get a much higher boost?  For example, why isn't the "Food and Beverage" framework the first result here?:
![image](https://user-images.githubusercontent.com/21346519/119377296-92d2f000-bc82-11eb-818b-9087b2eb5831.png)

**Comment by jeannekitchens** [comment]
CaSS searches the whole object.  Have to use the filters to narrow.  There's no weighting used for titles or descriptions.
