### ISSUE TITLE
Unable to publish/export the O*Net technology skills framework in production

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#859]
It's back!
I have been trying to export the O*Net technology skills framework in production. 
I timed the process twice. I stopped the export after getting no response after 35 minutes.

**Comment by mparsons-ce** [comment]
That does sound much better.

**Comment by woodkri** [comment]
@mparsons-ce Give this another try with the new server updates - it just took ~2 minutes to export here.

**Comment by mparsons-ce** [comment]
Closing as running fine on production.
