### ISSUE TITLE
Paginate search results.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#86]
10 or 20 per go, with a "load more" and "load 1000 more".

**Comment by eddavies** [comment]
Works, but perhaps adding a way to show fewer results would be a minor improvement? Would be neat if there was a way to view say 50, 100, 150, or all.

**Comment by Lomilar** [comment]
I thought so too, at first, but then I thought the following:

When people get results, they tend not to be looking for an exact number, so they want either 'more' or 'all' of the results.

**Comment by eddavies** [comment]
I imagine the list is going to be upwards of 5000 (or at least a very high number) in the future, if that's the case, then showing say 50 100 or 150 is useless; that people are really going to just search for what they want. However, if a user clicks on show all, there is no way of taking that back without closing their web browser completely and reopening. Going into a framework and then back still loads all of the results. 

I'm not sure if this would happen, but for someone with a slower pc who loaded all and is having timing issues, they would be stuck. Do you see this as being a possible issue in the future, or would something like this not happen? I mean currently I'm having zero issues, just theorizing at the moment.

**Comment by eddavies** [comment]
So what I'm saying is perhaps adding a show fewer option could be helpful.

**Comment by Lomilar** [comment]
Actions like "show all" can't be taken back very easily without reloading the page. If it brings a machine to its knees, no button will likely be able to recover it without reloading or closing the tab.

Show less wouldn't be useful, I guess. One could also just hit "show 100 results" instead of "show less".

I'm not against a "show 1000 results" though, for "lots but maybe not all, if there are a ton".

**Comment by eddavies** [comment]
You're right, show fewer is not useful if load 100 lowers the amount of results a user can view. This function is working, closing the issue.
