### ISSUE TITLE
CaSS/Credential Engine Instructions

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#864]
@woodkri I thought the instructions were changed to use an information link on the right top corner of the various views for each tool rather than having instrutions only on the left menu and an information link only with the crosswalk.  We see links on the left rail and the instruction link on the right only on on the crosswalk interface.
![image](https://user-images.githubusercontent.com/20917206/121076905-ce45e200-c78b-11eb-9035-1a3e4a470dd4.png)
![image](https://user-images.githubusercontent.com/20917206/121076975-e453a280-c78b-11eb-8f48-a4e868f8663b.png)

**Comment by woodkri** [comment]
@jeannekitchens Is this on production? I haven't yet been given the go-ahead to update CaSS on production to the version with the changes in documentation links. Last time we spoke about it you guys wanted to do some testing on staging before I updated production.

**Comment by jeannekitchens** [comment]
No.  It's not on production.  The screenshots I pasted above are from production.  The help link is better on the right side rather than being documentation links in the left menu:

1. The info button adjacent to the right-panel for crosswalking instructions and with upload, would be better as "?Help" to be consistent, instead of "Info".
2. When in the My Directories section, the Help is not linked directly to the related Directories section of the guide.

Is the intruction related links and the drop-down with the +New all that impacts a production update?

**Comment by woodkri** [comment]
Right, I was asking if those screenshots were from production. The changes to the instruction links and the dropdown with +New are part of the release that is currently on staging but not yet on production. I can update production whenever your team is ready.

**Comment by jeannekitchens** [comment]
..also, using one named new window for each link would be good so a new window doesn't open for every help link.  The feedback I provided is minor, doesn't hold up updating production but let me check with Mike and Nate and I'll let you know.

**Comment by jeannekitchens** [comment]
@woodkri the directories are also not on production so it's directories, +new, and help?.  For the directories, I only see an option to add a new framework not an existing framework.  I would want to be able to put frameworks I create in my folder not just created them in my folder.  Also, I think Nate already provided this but I selected the new drop down to add a framework to my directory and I really don't want ot create one so I cancel and and even though I entered nothing I see
![image](https://user-images.githubusercontent.com/20917206/121085687-0bfc3800-c797-11eb-94c3-0cee0cab645c.png)
and
![image](https://user-images.githubusercontent.com/20917206/121085780-23d3bc00-c797-11eb-8ca2-afba677043ed.png)

**Comment by woodkri** [comment]
Correct, directories are included in this release as well as industryType, occupationType, and instructionalProgramType. There are some bug fixes as well.

You can put existing frameworks in a directory by searching for the framework from the main page and single clicking on it. A panel will open on the right side of the screen with options to move the framework into a directory.

**Comment by jeannekitchens** [comment]
Ohhhh...that's kind of buried.  The bugs are all ticketed?  Let's wait until we meet and get a more concrete look at where things are with all of the related bugs.  I'm putting this on the running topics.  I'll also invite Scarlett who is putting together instructions and needs to base them on the updates.
