### ISSUE TITLE
I can copy frameworks into directory I did not connect

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#865]
I do not have admin access in the CaSS sandbox so I cannot edit any frameworks I did not create, or I'm not directly added to the account for the org that is publishing.  The directory I created is Jeanne's directory.

![image](https://user-images.githubusercontent.com/20917206/121101272-5ccc5a80-c7b0-11eb-9999-13390d672933.png)

I also see directories created by others and no settings to create private directories.  Is the intent that all directories, alway have to be viewable to anyone with a login? 

Even, if I can see and look at what's in another's directory, I should not be able to put frameworks in other's directories.

**Comment by woodkri** [comment]
The directories you see there are ones that were created by a user who wasn't logged in so they have no owner. That means anyone can edit them. On your staging and production sites, there should always be an owner so you'd only see your own directories as options to move frameworks into.

I believe you guys use show=mine in the URL parameters for users who don't have admin accounts. In that case, the user wouldn't see directories owned by someone else in their search results either.

**Comment by jeannekitchens** [comment]
On production every directory has an owner and only the owner add or remove items.
