### ISSUE TITLE
Using "Edit Multiple" with "Concept Term" results in duplicate references

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#866]
This was on production CaSS.

Steps to reproduce:
1. Select 2 or more competencies in a framework
2. Use the "Edit Multiple" feature to add a "Concept Term"
3. Select any concept to use as the "Concept Term"
4. Each competency will have duplicate references that seem to be equal to the number of competencies that were selected (e.g. if you select 7 competencies, each competency will end up with 7 references to the same competency for Concept Term)

Note also: When we were doing this, the process errored out (error visible in the console but the visual just left the spinner on the screen) during the stage where the references are applied, so only four or so of the duplicate references were added to each of the 7 or so competencies we had selected.  After that, the references weren't visible in the UI until I:
1. Opened a competency via its edit button
2. Closed the competency (using the "X" button, not the "done" button)
3. Opened the same competency again via its edit button
4. Now the multiple references appear in the edit window
5. Remove duplicate references
6. Click "done"
7. Now the reference appears in the main UI

Based on the timing (and the reference to "MultiEdit"), I believe this is the error that occurred (when the spinner stayed on screen):
![image](https://user-images.githubusercontent.com/21346519/121243471-5d71f900-c863-11eb-96d3-109dffd95c76.png)

**Comment by woodkri** [comment]
This was fixed but isn't on production yet. It should be working on dev/sandbox.

**Comment by mparsons-ce** [comment]
@siuc-nate Kristin demo'd the fix for me. 
You can verify this or close.

**Comment by siuc-nate** [comment]
Makes sense to close it.
