### ISSUE TITLE
Make it easier to rearrange competencies

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#867]
We were trying to reorganize a competency framework and encountered the following scenario:

1. We want to move a competency to a new parent, at the end of the list for that parent's competencies
2. We were unable to do so and had to move it to one item up from the end of that list
3. We were then able to rearrange the children into the correct/desired order

The structure looked like this:

- Category 1
  - Child 1
  - Child 2
  - Child 3
- Category 2
  - Competency that wants to be Child 4
  - Child 5
  - etc

Instead of being able to move "Competency that wants to be Child 4" to be directly underneath "Child 3", we had to first move it to be between "Child 2" and "Child 3" and then drag "Child 3" up so that the correct order was maintained.

There's also no visual cue as to where a competency _can_ be dropped, which makes it tricky to figure out where to aim for. It didn't seem like there was a spot representing "drop here to put it at the end of the list" even when I very slowly dragged up or down, one pixel at a time (it seemed like I could only make "Competency that wants to be Child 4" be a sibling to "Category 1" and "Category 2" or a child of "Child 3").

Is there a way to rearrange competencies using the keyboard? For some reason the right/left arrow keys caused the whole tree to expand or collapse rather than moving a selected competency around.

**Comment by woodkri** [comment]
The arrow keys do expand/collapse when used on their own. You can move a competency by keyboard if you hold down shift plus the arrow key.

**Comment by woodkri** [comment]
Looked at in meeting 1/19.
