### ISSUE TITLE
Users Need to Default to Their Frameworks

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#868]
As a user who can only edit frameworks I create, it's really hard to find them.  Users need to see the frameworks they created.  This needs to be the default.  The filtering should allow for seeing others but often the search is flakey along with the filters and it takes several searches and too much time to find frameworks that belong to me that I can edit.   This adds unnecessary extra steps to get to a framework that needs editing.

**Comment by woodkri** [comment]
This is accomplished by adding show=mine to the URL parameters. The Credential Engine iframes used to use show=mine but it may have been changed at some point, as I'm now seeing show=all in the parameters.

**Comment by jeannekitchens** [comment]
@mparsons-ce change this on sandbox and let's look at it to see if there's any issues.

**Comment by jeannekitchens** [comment]
@mparsons-ce verified the show mine url parameter is working.  Closing this.
