### ISSUE TITLE
Indenting Competencies Doesn't Work

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#869]
I select one competency. I want to indent it to be a child the top competency, which is Essential Skills.  It needs to be indented to be a child of that top competency just as the Collaboration with Multiple Stakeholders is a child of Essential Skills.  I want to indent it using shift arrow right  I'm using shift arrow right because none of the other indent options work.  
 
![image](https://user-images.githubusercontent.com/20917206/121271936-9ae18100-c879-11eb-9cbe-83be369104b6.png)

When I use shift, arrow right it does not indent but the check mark moves itself up to the competency above it and it is highlighted.  
I want to indent it using shift arrow right  I'm using shift arrow right because none of the other indent options work.

**Comment by woodkri** [comment]
@jeannekitchens I just pushed up some recent changes to sandbox and this is working for me now. Let me know if you're still having trouble or if this is now working.
