### ISSUE TITLE
No Instructions Show While Creating a Framework 

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#870]
While working on a framework as shown below, no instructions show.  Add the Help to the top right of the interface shown below.  This is really a pain.  How would the user figure our where to find instructions?  You have to go back to the menu for frameworks and by doing that you are no longer working on the framework for which you need instructions.  

![image](https://user-images.githubusercontent.com/20917206/121272271-615d4580-c87a-11eb-9c22-8ea94f62fc59.png)

**Comment by woodkri** [comment]
Looked at in meeting 1/19.
