### ISSUE TITLE
Clicking cancel after creating a new competency should delete the competency

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#88]
Immediately after creating a new competency in a framework, clicking the cancel button should cancel the creation of the competency, instead of forcing the user to click delete.

**Comment by Lomilar** [comment]
Usability pass requested. There's assumptions here that it'd be good to validate:

1. Is Adding a competency the creation event or is Saving the competency?
ex: Google Docs creates the doc before editing. Word creates the doc on save.

Either way, it should be made more clear than Google Docs, if we can swing it from a usability standpoint.

**Comment by Lomilar** [comment]
Decided that if the competency is on the first edit, and cancel is clicked, that it should ask if the competency should be deleted or not.
