### ISSUE TITLE
Production: unable to edit a framework created by Nate

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#891]
I am unable to edit the framework: NICE Cybersecurity Workforce Framework: Skills:
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-bf139ee2-cc1e-4ea5-97c6-6dea17ebebeb

Nate and I are the only users for the owning org of the latter: U.S. Department of Commerce National Institute of Standards and Technology (NIST)

I logged in as Nate, and still could not edit the framework. 

I tried some other NICE frameworks and cannot edit those either.

**Comment by woodkri** [comment]
Can you edit the framework when logged in under the NIST organization?

Looking at the created date, I would guess that these frameworks were added to CaSS by CSV import before #614 was fixed.

**Comment by mparsons-ce** [comment]
I edited the framework after selecting NIST as the owning org. I am now able to edit the framework.
