### ISSUE TITLE
Visual error after creating a new competency

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#9]
Initially after creating a new competency in a framework, the competency's name and description are displayed right next to each other. Additionally, the competency is displayed too far over to the right.

Here is a screenshot of the issue:

![comp](https://user-images.githubusercontent.com/23706850/32522492-5e19b6b2-c3cc-11e7-9493-ce97920b3e9b.PNG)

This however is fixed when the framework is refreshed (like when another competency is added).

**Comment by miledivovic** [comment]
Fixed in 23d6588

**Comment by eddavies** [comment]
Fix verified
