### ISSUE TITLE
"Search" is not showing up properly in microsoft edge

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#90]
There is empty space in the window to add or search for a new competency.
![no search](https://user-images.githubusercontent.com/23706850/33625643-1674dd40-d9ad-11e7-9c24-4d9d7235cfbb.PNG)

**Comment by Lomilar** [comment]
Known issue with Edge.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5457477/
