### ISSUE TITLE
Allow instruction and sample rows in CTDL-ASN CSV import process

### ISSUE THREAD

**Issue by woodkri** [cassproject/cass-editor#914]

**Comment by sedula27** [comment]
@gloverkari We implemented the bulk upload pages for Competency Frameworks, Collections and Concepts schemes
https://sandbox.credentialengine.org/publisher/bulkupload/competencyframework
https://sandbox.credentialengine.org/publisher/bulkupload/collection
https://sandbox.credentialengine.org/publisher/bulkupload/conceptscheme
Here is a file, downloaded from the bulk upload page  which has Sample data that needs to be ignored during an import, There will be another another row with instructions that should be ignored when being imported to CASS
[CompetencyFramework Bulk Upload Sample (11).csv](https://github.com/cassproject/cass-editor/files/9073476/CompetencyFramework.Bulk.Upload.Sample.11.csv)
e

**Comment by jeannekitchens** [comment]
@gloverkari see the above linked template.  There's the 1st column to be ignored with:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jkitc/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jkitc/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



UploadComments
--
Sample Data
Sample Data
 



</body>

</html>

**Comment by sedula27** [comment]
@gloverkari  Here is the sample file, I used 
[CompetencyFramework Bulk Upload Sample (9) - CompetencyFramework Bulk Upload Sample (9).csv](https://github.com/cassproject/cass-editor/files/9669497/CompetencyFramework.Bulk.Upload.Sample.9.-.CompetencyFramework.Bulk.Upload.Sample.9.csv)

**Comment by sedula27** [comment]
@gloverkari  the bulk upload sheet for framework and collections work but not the concept scheme
Here is a sample of the sheet i used
[ConceptScheme Bulk Upload Sample (3) - ConceptScheme Bulk Upload Sample (3) (1).csv](https://github.com/cassproject/cass-editor/files/9853915/ConceptScheme.Bulk.Upload.Sample.3.-.ConceptScheme.Bulk.Upload.Sample.3.1.csv)
