### ISSUE TITLE
IsVersionOf is incorrectly included in Framework and is missing in Competency.

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#915]
IsVersionOf is **NOT** a property for Framework and is shown as an option in the editor. 

IsVersionOf **IS** a property for  Competency, but is not an option for Competency in the editor.

**Comment by mparsons-ce** [comment]
IsVersionOf  must be a URI, and validate before adding the property.

**Comment by woodkri** [comment]
Accepted in meeting 11/17
