### ISSUE TITLE
InLanguage issues on Sandbox

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#916]
While testing some imports today I encountered issues related to language. 
When attempting to select a new language for competency text, the dropdown list shows behind the language textbox for comment. In the example below, German was already selected for Comment:
![image](https://user-images.githubusercontent.com/58825866/131026438-030ac051-bbc4-4846-a909-a8cc93b8f801.png)

I did have issues where I would change a language, and close the edit window. Then upon re-opening the edit window, the values had reverted to the old values,
 
I uploaded a new framework (linked below) with inLanguage of 'fr'. After upload, I edited the framework and neither name or description had a language entered (each marked with an error regarding missing language). As well the InLanguage was set to 'en'.

[Upload french frameworks.csv](https://github.com/cassproject/cass-editor/files/7062403/Upload.french.frameworks.csv)

I will try again shortly with Spanish to confirm the issue
The Spanish import did work properly. I will have to try some more tests.

**Comment by woodkri** [comment]
I'm having trouble reproducing this. @mparsons-ce What browser were you using when you encountered these issues? In the screenshot, did you select German and the dropdown stayed up/moved behind the textbox? Or did you select the language and go back to edit later and the dropdown popped up behind it?

**Comment by siuc-nate** [comment]
Still seeing it when trying to create a new framework:
![image](https://user-images.githubusercontent.com/21346519/134073014-d8496a60-ef22-4cb6-88e6-67410e9450bb.png)

By the way, what is the source data for the language tag options?

**Comment by woodkri** [comment]
Thanks, I initially thought it was from the description language field. I'm now able to reproduce.

The file for the language tags is 'ietf-language-tags_json.json'. I found it a few years ago when we first added language tags but I'd have to dig a little more to figure out where it came from.

**Comment by woodkri** [comment]
Accepted in meeting 11/17
