### ISSUE TITLE
HTML Upload 

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#917]
The CaSS upload interface as an option for HTML that says "CaSS experimentally supports the import of frameworks in HTML document formats. Because HTML files come in many shapes and sizes there may be defects when importing frameworks. The import interface allows you to review and make changes to the detected framework before importing."

However, the download icon is green to communicate it's well supported.  Should this be changed to Yellow with an exclamation mark to be consistent with the other experimental uploads?

![image](https://user-images.githubusercontent.com/20917206/131033583-e4edc8cf-76bb-47d9-8438-d0323447f803.png)
![image](https://user-images.githubusercontent.com/20917206/131033655-eb6ebf26-62d9-4f9b-a2df-7d85599ec2bb.png)

**Comment by woodkri** [comment]
Accepted in meeting 9/22
