### ISSUE TITLE
Verify that the CTDL ASN JSON Example File is Correct 

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#918]
CaSS import has an option from the Import interface to upload a CTDL-ASN JSON file.  There's an example file attached to the interface.  Verify this file is correct and coud actually be directly imported, stored correctly, uses current properties, and publishes to Registry once stored.  Looking at the file name, it's an old file that likely needs to be deleted and replace with a correct file.  

![image](https://user-images.githubusercontent.com/20917206/131034401-ca3b5b82-67ce-4f35-849f-95b315dd587e.png)

I downloaded the file and put it in our CaSS folder here https://drive.google.com/drive/folders/1r3qDQLpLzGhXTU0sqLKaBkEqyWeyIrQ0?usp=sharing

**Comment by jeannekitchens** [comment]
@siuc-nate or @mparsons-ce please check this file.

**Comment by siuc-nate** [comment]
Where do I access the file in the CaSS interface? Is it via the "info" button on the import screen? Clicking that button doesn't do anything:
![image](https://user-images.githubusercontent.com/21346519/132541362-23812016-e8a3-4f6a-b008-3232e7883eea.png)

**Comment by woodkri** [comment]
@siuc-nate There should be a panel just to the right of your screenshot that says "Import From a File" at the top. Under supported file types, you can click on the JSON option to view more information about that type along with the example file.

**Comment by siuc-nate** [comment]
It looks okay to me.  Though I am curious why the `ceasn:hasChild` arrays are sometimes expanded/indented properly:
![image](https://user-images.githubusercontent.com/21346519/132543188-fa8ff3d9-766c-4e20-8490-4d7beff3dce3.png)

and sometimes not:
![image](https://user-images.githubusercontent.com/21346519/132543244-3b15ad62-dc3a-4ec6-853a-78aab3295a2a.png)

Was the file created manually?  It doesn't break anything, but it does look odd.

**Comment by woodkri** [comment]
I'm not sure how the file was created; I think it was here when I started. I assume we got it from your team though.
