### ISSUE TITLE
For many properties in the CaSS import a URI is expected. It should also accept a CTID and convert to a URI.

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#925]
[21-09-20 - modified to be more general]
In order to simplify entering data in a spreadsheet for uploads, the user should be able to just enter a CTID for properties that currently expect a full URI.

CaSS would then create the appropriate URI based on the current environment. 

Related Properties for this issue.
Competency Frameworks:
- derivedFrom
- conceptTerm
- publisher
- creator
- hasProgressionModel

Competency:
- ceasn:alignFrom
- ceasn:alignTo
- ceasn:broadAlignment
- conceptTerm
- derivedFrom
- asn:hasProgressionLevel
- ceasn:complexityLevel
- ceasn:comprisedOf
- ceasn:exactAlignment
- ceasn:knowledgeEmbodied
- ceasn:majorAlignment
- ceasn:minorAlignment
- ceasn:narrowAlignment
- ceasn:prerequisiteAlignment
- ceasn:skillEmbodied
- ceasn:taskEmbodied

**Comment by woodkri** [comment]
Also ceasn:abilityEmbodied

**Comment by sedula27** [comment]
Was able to import all the above  with the CTID instead of URI except for
 **ceasn:alignFrom, ceasn:alignTo, ceasn:comprisedOf, ceterms:hasTask** 
 These are not in the CASS interface yet
