### ISSUE TITLE
Properties missing from the CaSS interface

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#926]
The following properties are missing from the CaSS interface.
Framework:
- ceasn:author
- ceasn:localSubject
- cipList
- hasProgressionModel

Competency:
- creator
- hasProgressionLevel

**Comment by woodkri** [comment]
What's the multiplicity on author, localSubject and creator? I see localSubject is a langstring; is it one or many per language?

**Comment by mparsons-ce** [comment]
**Framework**:
ceasn:author **multiple**
ceasn:localSubject   **multiple per language** 
cipList **multiple**
hasProgressionModel  (TBD)

**Competency**:

creator **multiple**
hasProgressionLevel **multiple**

**Comment by woodkri** [comment]
hasProgressionModel is medium, others are high detail.

Headers still TBD.

**Comment by mparsons-ce** [comment]
Header categories
**Framework**:

- ceasn:author _general_
- ceasn:localSubject _tagging_
- cipList _tagging_
- hasProgressionModel _connections_

**Competency**:

- creator _general_
- hasProgressionLevel _connections_

**Comment by woodkri** [comment]
These are the first ASN properties we've included in your configuration and I'm running into some case sensitivity issues. We use capitalized ASN in CaSS's context, but you guys use lowercase asn, so the expand and compact operations aren't working. ASN uses the capitalized version. Would it break things on your end if you switched to the capitalized version? The lowercase URL doesn't appear to resolve.

**Comment by stuartasutton** [comment]
@woodkri, a couple points of clarification: (1) when you say "asn" are you actually talking about "asn" or "ceasn"; and (2) when you speak of case sensitivity, what's the context?

**Comment by woodkri** [comment]
I'm talking about "asn", the progression model properties use the asn context. By context in my comment above I meant the URL associated with the "asn" prefix - we use "http://purl.org/ASN/schema/core/" as does ASN and CE uses "http://purl.org/asn/schema/core/". JSON-LD operations break on the two different cases.

**Comment by stuartasutton** [comment]
Thanks for the clarification.

**Comment by mparsons-ce** [comment]
@siuc-nate @stuartasutton 
There are differences between the asn URL in our context files.
The ctdl context uses upper case:
http://credreg.net/ctdl/schema/context/json
![image](https://user-images.githubusercontent.com/58825866/144282565-43057c04-95f2-4b0c-ab22-542d5da2ad49.png)


The ctdlasn context uses lower case:
http://credreg.net/ctdlasn/schema/context/json
![image](https://user-images.githubusercontent.com/58825866/144282501-0fa08b50-a902-42b8-a8e0-aae5ef795564.png)



Should the ctdlasn context be changed to use the url with upper case ASN?

**Comment by stuartasutton** [comment]
Well, ASN has it uppercased. If it is causing problems, we need to change it on our end. It's not ASN's problem.

**Comment by mparsons-ce** [comment]
@siuc-nate Please update the **ctdlasn** context to use the URL with ASN in upper case .
asn: "http://purl.org/ASN/schema/core/"

**Comment by siuc-nate** [comment]
Both ways resolve to the same data, but I can make the change.

**Comment by woodkri** [comment]
Reviewed in meeting 1/5.
