### ISSUE TITLE
CaSS framework viewer not working in production

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#928]
@woodkri 
Today Scarlett reported that the competency framework viewer was not working production. An example learning opp page is: https://apps.credentialengine.org/publisher/detail/LearningOpportunity/3484

Upon checking I saw there were a few 404 errors:
![image](https://user-images.githubusercontent.com/58825866/132769099-7730a192-25ba-4c17-a739-02d9b5eb9c46.png)

The URL for the viewer is 
https://cass.credentialengine.org/cass-editor/index.html?server=https://cass.credentialengine.org/&ceasnDataFields=true&origin=https://apps.credentialengine.org&css=https://apps.credentialengine.org/publisher/Style/CassStyles&frameworkId=https://cass.credentialengine.org/api/data/32de4b23224ffd2dad5cf2b967897329

The editor is working fine. As well the embedded version (for aligning competencies to say a learning opp) is also working. 

The framework exists, as just entering https://cass.credentialengine.org/api/data/32de4b23224ffd2dad5cf2b967897329 will result in the framework being displayed.

I checked the sandbox and the display works correctly. 
https://cassproject.github.io/cass-editor/index.html?server=https://dev.cassproject.org/api/&ceasnDataFields=true&origin=https://sandbox.credentialengine.org&css=https://apps.credentialengine.org/publisher/Style/CassStyles&frameworkId=https://dev.cassproject.org/api/data/3b06e4c342ea60e1b4599990e162413f

**Comment by woodkri** [comment]
The problem seems to be with the frameworkId parameter. If you use the @id of the framework instead of the md5 (frameworkId=https://credentialengineregistry.org/resources/ce-b36df859-c73b-4c99-8d3d-49a1716aaf55), it works. I think this might have to do with the IIS URL rewrite rules on production as there's one that looks for /api/.

**Comment by mparsons-ce** [comment]
Thanks I made the change and verified in production.
