### ISSUE TITLE
Need consistent multiplicity for properties

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#935]
Properties shared across Competency Frameworks and Concept Schemes should be consistently either single or multi-value unless there is a good reason for them not to.

For example, currently, it appears that `ceasn:source` is an array for Competency Frameworks but a single value for Concept Schemes.  It should be the same way in both cases.

This should follow for other properties shared by both classes.  I don't know of a good way to find/figure out what CaSS currently uses/allows in terms of single/multiple values for its fields, though. Is there a good way to find this out?

**Comment by woodkri** [comment]
ceasn:source as multiple value for Frameworks and single value for Concept Schemes came directly from that mapping spreadsheet we used to use. If there is an updated version of that somewhere I can double check the multiplicity. If not, I can get you a list of all the properties in the editor and whether they're single or multiple value.

**Comment by siuc-nate** [comment]
A list like that would be a good starting point. I'm not sure how up to date any of the old spreadsheets are.

**Comment by stuartasutton** [comment]
First, let's remember that the CTDL-ASN does not define any constraints on properties (e.g., `ceasn:source`). That is a function of an application profile defining repeatability (i.e., arrays) of a property.  CTDL and concept schemes are separate schemas and have separate application profiles where different constrains might be applied. But, that said, my take is that for both should be singular--the source is the source is the source?

**Comment by stuartasutton** [comment]
Yes, and as I think more about this, there might well be a framework with competencies sourced in multiple other frameworks; but, the data representation in the Registry identifies the resource that aggregates those other sources.

**Comment by siuc-nate** [comment]
Thanks @woodkri, that's very helpful.

**Comment by woodkri** [comment]
**Competency**
ceasn:competencyLabel - multiple
ceasn:competencyText - multiple
ceasn:comment - multiple
ceasn:competencyCategory - multiple
ceasn:listID - single
ceasn:codedNotation - single
ceasn:abilityEmbodied - multiple
ceasn:knowledgeEmbodied - multiple
ceasn:skillEmbodied - multiple
ceasn:taskEmbodied - multiple
ceasn:conceptKeyword - multiple
ceasn:conceptTerm - multiple
ceasn:complexityLevel - multiple
ceasn:weight - single
socList - multiple
naicsList - multiple
cipList - multiple
@id - single
ceasn:broadAlignment - multiple
ceasn:exactAlignment - multiple
ceasn:majorAlignment - multiple
ceasn:minorAlignment - multiple
ceasn:narrowAlignment - multiple
ceasn:exactAlignment - multiple
ceasn:prerequisiteAlignment - multiple
ceasn:isVersionOf - single
ceasn:educationLevelType - multiple
ceasn:derivedFrom - single
ceasn:identifier - multiple

**Concept**
skos:prefLabel - multiple
skos:definition - multiple
skos:notation - multiple
skos:altLabel - multiple
skos:broadMatch - multiple
skos:closeMatch - multiple
skos:exactMatch - multiple
skos:narrowMatch - multiple
skos:related - multiple
@id - single
skos:hiddenLabel - multiple
skos:note - multiple
skos:changeNote multiple

**Comment by woodkri** [comment]
I've included one per language in the lists above.

**Comment by jeannekitchens** [comment]
See 1st tab identifying mismatches https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=251870571

**Comment by gloverkari** [comment]
Updated properties in CaSS based on the notes in "Multiplicity in CaSS" https://docs.google.com/spreadsheets/d/1dM5D113yQP23GxsHmck4EI89S8yhRatVkZ3sOPaRN-U/edit#gid=251870571
As noted in the spreadsheet, a few properties are listed in the Multiplicity tab but not in the corresponding specification tabs.
