### ISSUE TITLE
When doing a CSV bulk upload, the user should not have to provide a full URI for ceasn:educationLevelType

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#936]
To simplify the bulk upload of frameworks that include the educationLevelType, the user should only need to provide the actual term, and not have include the full URI. 
So instead of entering:
https://credreg.net/ctdl/vocabs/audLevel/BeginnerLevel | https://credreg.net/ctdl/vocabs/audLevel/AdvancedLevel

The user would just enter: 
BeginnerLevel | AdvancedLevel
and CaSS would prepend the base URI (**https://credreg.net/ctdl/vocabs/audLevel/**).

This request will relate to both a competency framework and a competency.

These are the valid values https://credreg.net/ctdl/terms/AudienceLevel#AudienceLevel

**Comment by woodkri** [comment]
Reviewed in meeting 1/5.
