### ISSUE TITLE
Error in production on attempting to publish/export

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#942]
Scarlett was attempting to publish the following framework:
B.S. in Nursing
ce-c4911333-c9d8-486d-aa71-82097e11d418
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-c4911333-c9d8-486d-aa71-82097e11d418

She gets the following error:
`TypeError: Cannot get property "length" of null`
I get the same error if try to export the framework from the CaSS interface. 
The framework was last published Mar. 23rd, 21.

**Comment by woodkri** [comment]
Has the framework been changed since this issue was created? It's exporting fine for me.
