### ISSUE TITLE
Collection Class - New CTDL-ASN Class 

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#952]
@mparsons-ce see the list of Collection properties below and verify single or multiple and an other data related information.  Please make any/all changes directy in this post. Don't create a new comment.  

@woodkri 
- this is updated to change all URLS that were pending to CTDL unstable as of Nov 1, 2021.  
- These terms will be changes to stable status based on Credential Engine policy determined by use.
---
- The cipList, naicsList and socList are ceterms, not ceasn terms.  You should be able to utilize these for the CaSS interface and in the Registry they will be published the same way they're published for competency frameworks and competencies.
---
In summary

- this new class, [Collection,](https://credreg.net/ctdl/terms/Collection has one new property (hasMember) 
- and is referenced by another new property (isMemberOf). 
- [Collection](https://credreg.net/ctdl/terms/Collection) is a flat list of URIs, and needs to support being the source/home for competencies similar to a Framework.  
- This class and majority of it's terms use ceterms namespace, not ceasn namespace.  
- Credential Engine policy is to only use ceasn for terms meant only for competency frameworks and competencies.  
- All other properties already exist in CTDL-ASN (ceasn) and CTDL (ceterms) but there are multiple CTDL properties not currently in CaSS that need to be added. 
- The Collection Class is applicable to other CTDL terms as well. However, CaSS will only need to handle collections of Competencies.  
---
**The CaSS interface needs to enable:**
1. Create collection (similar to creating a framework).
2. Add members (i.e., competencies to the collection) via URI (if they exist somewhere else) or via creating them as physical members of the collection (as with a Framework).
3. Edit the data for the collection itself (similar to editing a framework).
4. Edit the data for competencies in a collection if they only physically exist in that collection (ie are not referenced/borrowed from somewhere else).  E.g., you have a set of frameworks and want to add competencies to a collection.  You can  add the competencies from the framework you own and others but cannot edit those competencies in the collection to where you added them.  
---
**The CaSS interface needs to support:**
1. Bulk Upload of these new terms (in this context, ceasn:isMemberOf can be used for anything in order to allow a spreadsheet upload of multiple Collections at a time. In the real data, you would use ceasn:hasMember instead)
2. Manual Entry of these new terms.
3. Web Ingest of these new terms. 
---
**The same download/export options need to be used as a Framework:**
1. JSON-LD
2. CSV
---
**CaSS users can do the following with the Collection they own:**
1. Create collections via manual entry, bulk upload, or web ingest.
2. Name their collections
3. Describe their collections with supported CTDL terms.
4. Add, delete their own competency members to/in their collections. Edit competencies they've added that do not belong to any frameworks.
5. Add competencies created by others but they cannot change those competencies created by others that they choose to add as is.
6. Derive competencies from others (i.e., make a copy they can edit as a derivititive) in their own collection.
7. Align competencies in their collection to other competencies in other frameworks or collections.
8. Update and remove alignments to other competencies in other frameworks or collections.
9. Publish their Collections to the Registry.
10. Update their Collections and update the Registry.
11. Download their collections (via Cass) as CTDL ASN.
---
**[ceasn:Collection](https://credreg.net/ctdl/terms/Collection) - Aggregation of related resources.**
---
For CaSS, the resources that are members of collections will be competencies, which means that a Collection is comparable to a flat Competency Framework. There are two new properties of note. 
- [ceterms:hasMember](https://credreg.net/ctdl/terms/hasMember)needs to show in "Low Detail".
- Both of these properties accept multiple values

1. [ceterms:hasMember](https://credreg.net/ctdl/terms/hasMember) - Resource in a Collection. (range: ceasn:Collection)
2. [ceterms:isMemberOf](https://credreg.net/ctdl/terms/isMemberOf) - Collection to which this resource belongs. (range: ceasn:Collection) 
---
**These CTDL ASN properties were originally on the list to include with Collection. However, they AREN'T BEING USED WITH COLLECTION.**

1. https://credreg.net/ctdlasn/terms/author 
2. https://credreg.net/ctdlasn/terms/conceptKeyword
3. https://credreg.net/ctdlasn/terms/creator
4. https://credreg.net/ctdlasn/terms/dateCreated
6. https://credreg.net/ctdlasn/terms/identifier
7. https://credreg.net/ctdlasn/terms/inLanguage
9. https://credreg.net/ctdlasn/terms/name
10. https://credreg.net/ctdlasn/terms/publisher
11. https://credreg.net/ctdlasn/terms/publisherName
---
**Instead, these are the terms for Collection.  Whether a "single" or "multiple" should not change from current property type. **

1. https://credreg.net/ctdlasn/terms/license - (range: xsd:anyURI) / General / Single / low detail
2. https://credreg.net/ctdl/terms/classification - (range: skos:Concept)/ General / Multiple / medium detail
3. https://credreg.net/ctdl/terms/codedNotation  - (range: xsd:string) / General / Single / low detail
4. https://credreg.net/ctdl/terms/ctid - (required, range: xsd:string) / Single / high detail
5. https://credreg.net/ctdl/terms/dateEffective - (range: xsd:date) / General  / Single / low detail
6. https://credreg.net/ctdl/terms/description - (required, range: rdf:langString) / General / Single Per Language / low detail
7. https://credreg.net/ctdl/terms/expirationDate - (range: xsd:date) / General / Single / low detail
8. https://credreg.net/ctdl/terms/hasMember - (required unless subjectWebpage is provided, range: ceasn:Competency) / General / Multiple / low detail
9. https://credreg.net/ctdl/terms/industryType - (or naicsList) (range: ceterms:CredentialAlignmentObject) / Tagging / Multiple / Can use NaicsList / medium detail
10. https://credreg.net/ctdl/terms/inLanguage - (range: xsd:language) / Multiple / low detail
11. https://credreg.net/ctdl/terms/instructionalProgramType (or cipList) - (range: ceterms:CredentialAlignmentObject) Tagging / Multiple / Can use CipList / medium detail
12. https://credreg.net/ctdl/terms/keyword - (range: rdf:langString) Tagging / Mulitple Per Language / medium detail
13. https://credreg.net/ctdl/terms/name - (required, range: rdf:langString) General / Single Per Language / low detail
14. https://credreg.net/ctdl/terms/occupationType - (or socList) (range: ceterms:CredentialAlignmentObject) Tagging / Multiple (Can use socList) / medium detail
15. https://credreg.net/ctdl/terms/ownedBy - (required, range: ceterms:Organization/ceterms:CredentialOrganization/ceterms:QACredentialOrganization) General / Multiple / medium detail
16. https://credreg.net/ctdl/terms/subject - (range: ceterms:CredentialAlignmentObject) Tagging / Multiple / medium detail
17. https://credreg.net/ctdl/terms/subjectWebpage - (required unless hasMember is provided, range: xsd:anyURI) General / Multiple / low detail
---
**Defintions for competency headers:**
- General: Properties that are core or common to many/most competencies as Jeanne notes above including dates, rights (note that because of frequency of use, I'd put competency category up here instead of down in Context)
- Tagging: words/phrases/URI denoting the "aboutness" of the competency ("Pythagorean Theorem"; "George Washington", "Niagara Falls", "Confucianism", "cybersecurity")--i.e., conceptTerm, conceptKeyword
- Scales: Properties denoting some sort of measurement (e.g. weight)
- Context: Properties that provide some contextualization such as occupation, industry, categorization, environmental hazard type etc.
- Connections: Outbound links to related resources (broad alignment, skill embodied)
- Keys: Identifiers etc.

**Comment by jeannekitchens** [comment]
Just as with a competency framework a publisher can edit or add competencies, a publisher can/will edit or add competencies to a Collection. Just as with a competency framework, only a publisher of a Collection decides the members of a collection.

**Comment by jeannekitchens** [comment]
Need the Header definitions.  They're not evident in the instructions or in the interface.  Can people add others competencies to their frameworks now?  Or, can they only derive their own competencies from others and/or align to other's competencies? Once we know the definitions of the Headers, can determine if any new headers are needed.  For example the new "Type" might be best organized with a header but not sure if they may already fit with an existing header.

Yes to CSV and JSON LD exports.

@siuc-nate iplease use the original post in this issue and add any other information such as data type adjacent to new terms. And any other requirements we have.  @mparsons-ce please do the same.  Don't create a new comment.  Complete the original post in this issue to define the requirments.

**Comment by jeannekitchens** [comment]
@woodkri Colletion is now ready to implement.  I've asked @siuc-nate to edit the top post with this issue and identify all additonal information you need (e.g., single or multiple, data format).  Does the 1st post, once Nate adds the additional information, provide all you need to implement Collection?

**Comment by siuc-nate** [comment]
I had already edited the post last week.

**Comment by jeannekitchens** [comment]
@siuc-nate last week this post was not accurate.  We updated all of the properties.  They're mainly ceterms.  I don't see where this info is added.  You did add to the other post for the new competency terms.  This one is focused only on Collection.  Please edit the top post and add the single/multiple and data format for all of the properties listed as they have to be added to CaSS.  Thanks!

**Comment by siuc-nate** [comment]
Updated

**Comment by woodkri** [comment]
A few questions:

- Is it ok to use cipList, naicsList and socList as we've done for Frameworks and Competencies?
- What level of detail should each property go under? (low, medium, or high)
- In one place in the top post it says users should only be able to edit competencies within a collection if they don't exist anywhere else, while in another place it says they should be able to edit all competencies they own. Which should I go with?
- Which properties are required?

Thanks!

**Comment by jeannekitchens** [comment]
I'm making all updates in the top issue rather than them being in many comments.  I'll add information to address your questions and the 1st issue will be your go-to rather than all of the comments.

**Comment by siuc-nate** [comment]
I updated the post again. I'm not sure which things should go under low/medium/high detail (I imagine this would be similar to what we use for a Competency Framework).  For the edit policy question, we probably need to review this and make sure we're on the same page with regard to where Competencies "live", since that will determine where you can edit them.

**Comment by woodkri** [comment]
As discussed 11/17: For the export graph, if the competency was brought over from a framework, only include the URI in the hasMember field. If it was created within the collection, include the full object as we do for framework graphs.

**Comment by woodkri** [comment]
I noticed a few properties that are listed as both single and multiple: subjectWebpage, classification, inLanguage, ownedBy. So is hasMember but I assume this one is meant to be multiple. Can you let me know which are which?
