### ISSUE TITLE
New CTDL-ASN Properties For Competency Class

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#953]
@woodkri this is updated to replace all CTDL pending links with CTDL links.  The terms were changed from pending to ctdl unstable on Nov 1, 2021.  We're going to support all of the terms and change them to stable once they meet policy requirements for usage. I changed the links as all pending links would be broken.

@woodkri the information below (I think) is complete.  Please let me know of all questions and provide the level of effort to include these terms with CaSS.  The terms will be available on https://credreg.net, in the [CTDL handbook](https://credreg.net/ctdl/handbook#ctdlasnschema), and supported via the Registry Publishing Assistant API by 1st week of November.  We'd like these terms to be support in CaSS as soon as possible.  

The following are 16 new properties for (among others) the existing [Comptency Class](https://credreg.net/ctdlasn/terms#Competency).  Some of these terms come from CTDL, and others from CTDL-ASN.

As with the new "Collection" class, these properties are in CTDL-ASN pending and will be moved to CTDL-ASN on Oct 29th. The CaSS interface needs to support:

**1. Bulk Upload of these new terms via CSV.
2. Manual Entry of these new terms.
3. Web Ingest of these new terms (via a Competency Framework or Collection). 
4. Download of Frameworks with these terms.**

**The URL for these terms will change 1st of November to remove `?releaseid=pending` from the URLs.**

---
**The following are CTDL properties that expect a concept from a user-defined concept scheme.
- Show these on "High Detail"
- The Domain for these terms includes: Competency, Job, Task and WorkRole. 
- All four of these properties have a Range of skos:Concept (via URI).
- All four of these properties will accept multiple values.**

1. [ceterms:environmentalHazardType](https://credreg.net/ctdl/terms/environmentalHazardType?releaseid=pending) - Type of condition in the physical work performance environment that entails risk exposures requiring mitigating processes; select from an existing enumeration of such types. [header = Context] 
2. [ceterms:performanceLevelType](https://credreg.net/ctdl/terms/performanceLevelType?releaseid=pending) - Type of required or expected human performance level; select from an existing enumeration of such types. [header = Context]
3. [ceterms:physicalCapabilityType](https://credreg.net/ctdl/terms/physicalCapabilityType?releaseid=pending) - Type of physical activity required or expected in performance; select from an existing enumeration of such types. [header = Context]
4. [ceterms:sensoryCapabilityType](https://credreg.net/ctdl/terms/sensoryCapabilityType?releaseid=pending) - Type of required or expected sensory capability; select from an existing enumeration of such types. [header = Context]

---
**The following CTDL-ASN terms use a naming and definition convention for "substantiating[resource]".
- Show these on "High Detail".
- The domain for these terms includes: Competency.
- The range for each term is indicated by the term itself, but is also included below (all via URI).
- All of these properties will accept multiple values.**

1. [ceasn:substantiatingResource](https://credreg.net/ctdlasn/terms#substantiatingResource) (range: xsd:anyURI) - Aspects of the referenced resource provide some justification that the resource being described is useful. [header = Context]
2. [ceasn:substantiatingCompetencyFramework](https://credreg.net/ctdlasn/terms#substantiatingCompetencyFramework) (range: ceasn:CompetencyFramework) - Aspects of the referenced Competency Framework provide some justification that the resource being described is useful. [header = Context]
3. [ceasn:substantiatingCredential](https://credreg.net/ctdlasn/terms#substantiatingCredential) (range: ceterms:Credential subclass) - Aspects of the referenced Credential provide some justification that the resource being described is useful. [header = Context]
4. [ceasn:substantiatingJob](https://credreg.net/ctdlasn/terms#substantiatingJob) (range: ceterms:Job) - Aspects of the referenced Job provide some justification that the resource being described is useful. [header = Context]
5. [ceasn:substantiatingOccupation](https://credreg.net/ctdlasn/terms#substantiatingOccupation) (range:ceterms:Occupation) - Aspects of the referenced Occupation provide some justification that the resource being described is useful. [header = Context]
6. [ceasn:substantiatingOrganization](https://credreg.net/ctdlasn/terms#substantiatingOrganization) (range:ceterms:Organization or Organization subclass) - Aspects of the referenced Organization provide some justification that the resource being described is useful. [header = Context]
7. [ceasn:substantiatingTask](https://credreg.net/ctdlasn/terms#substantiatingTask) (range: ceterms:Task) - Aspects of the referenced Task provide some justification that the resource being described is useful. [header = Context]
8. [ceasn:substantiatingWorkRole](https://credreg.net/ctdlasn/terms#substantiatingWorkRole) (range: ceterms:WorkRole) - Aspects of the referenced Work Role provide some justification that the resource being described is useful. [header = Context]

---
**The following terms are also included.
- Show these on "High Detail".
- The domain for these terms includes: Competency.
- The range for each term is given below (all via URI).
- All of these properties will accept multiple values.**

1. [ceasn:sourceDocumentation](https://credreg.net/ctdlasn/terms#sourceDocumentation) (range: xsd:anyURI) - Human-readable information resource other than a competency framework from which this competency was generated or derived by humans or machines. [header = connections]
2. [ceasn:inferredCompetency](https://credreg.net/ctdlasn/terms#inferredCompetency) (range: ceasn:Competency from any published framework owned by anyone) - Competency deduced or arrive at by reasoning on the competency being described. [header = connections]
3. [ceterms:hasWorkforceDemand](https://credreg.net/ctdl/terms#hasWorkforceDemand) (range: ceterms:WorkforceDemandAction) - Indicates the level of demand for a resource via a demand level action. [header = connections] @woodkri hasWorkforceDemand points from a Competency to a WorkforceDemandAction, so yes, it will be a URI
---

**Defintions for competency headers:**

- General: Properties that are core or common to many/most competencies as Jeanne notes above including dates, rights (note that because of frequency of use, I'd put competency category up here instead of down in Context)
- Tagging: words/phrases/URI denoting the "aboutness" of the competency ("Pythagorean Theorem"; "George Washington", "Niagara Falls", "Confucianism", "cybersecurity")--i.e., conceptTerm, conceptKeyword
- Scales: Properties denoting some sort of measurement (e.g. weight)
- Context: Properties that provide some contextualization such as occupation, industry, categorization, environmental hazard type etc.
- Connections: Outbound links to related resources (broad alignment, skill embodied)
- Keys: Identifiers etc.

**Comment by woodkri** [comment]
Accepted in meeting 11/17

**Comment by siuc-nate** [comment]
Any luck with these? I don't see them in the concept scheme editor on the sandbox.

**Comment by woodkri** [comment]
They're in the competency editor on sandbox - all the way at the bottom of the available property list.
