### ISSUE TITLE
Tooltip visual error

### ISSUE THREAD

**Issue by eddavies** [cassproject/cass-editor#96]
![overlapping tooltips](https://user-images.githubusercontent.com/23706850/33633361-639b1536-d9c5-11e7-8e2e-d29ccbbed16b.PNG)

Steps to reproduce
1. access a framework
2. go to edit a competency.
3. hover over the competency description or name to cause the tooltip to popout
4. quickly click cancel

**Comment by Lomilar** [comment]
Seems fixed. Could not reproduce.
