### ISSUE TITLE
CaSS Editor Download Bugs

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#961]
@woodkri could you check this out and see if this two-part issue is a quick fix? 

1. The CaSS editor download has to be clicked twice to download.   Tried downloading with one click several times.  Second click immediately downloads two files. 
![image](https://user-images.githubusercontent.com/20917206/139731363-46caed29-9e2c-46da-8381-29f4c7931120.png)

2. The download format selected in CTDL ASN CSV.  This needs to download one CSV.  Two CSVs [download.](url).  One CTDL ASN file should download with all competencies.  I attached two files that downloaded from an  EDL framework. 
[Education Design Lab 21st Century SkillsDL1.csv](https://github.com/cassproject/cass-editor/files/7455766/Education.Design.Lab.21st.Century.SkillsDL1.csv)
[Education Design Lab 21st Century SkillsDL2.csv](https://github.com/cassproject/cass-editor/files/7455768/Education.Design.Lab.21st.Century.SkillsDL2.csv)

**Comment by woodkri** [comment]
@jeannekitchens It's just a little slow since it's doing all the translations to CTDL-ASN. The files you attached are the same file, just downloaded twice. If you click once and wait a bit, it should download the one CSV file. What I can do here is disable the export button until the download has finished.

**Comment by jeannekitchens** [comment]
Ohhhh... your logs should show over 30 seconds + but if I click a second time, it's fast.  If it is really that slow, if there's not already, need an icon to show download in progress.  However, I've tried multiple times with two quick back to back clicks and the download is immediate.
