### ISSUE TITLE
CaSS editor not showing results on production

### ISSUE THREAD

**Issue by siuc-nate** [cassproject/cass-editor#968]
After logging in and selecting the organization, no results show. The console shows several errors.

This is currently affecting production. Did something change?

![image](https://user-images.githubusercontent.com/21346519/140810684-cb8a8b56-dec5-4411-bb32-7d5a4a06d384.png)

**Comment by mparsons-ce** [comment]
Similar issue on staging
![image](https://user-images.githubusercontent.com/58825866/140811756-638c1208-7133-47a7-b2e3-0d75288cac24.png)

**Comment by woodkri** [comment]
Staging is down because I was in the middle of working on the new deployment. I'm looking into the issue on production now; we hadn't made any changes on that machine.

**Comment by woodkri** [comment]
It looks like the certificate for CaSS on production expired 11/6/21 so it will need to be updated.

**Comment by jeannekitchens** [comment]
@mparsons-ce Is this using LetsEncrypt? Per Kristin she cannot renew it but can help with the import.  I thought all certificates were switched and set to auto renew.

**Comment by mparsons-ce** [comment]
@woodkri 
I checked the current certificate and shows valid from 9/30/21 through 12/29/21/
![image](https://user-images.githubusercontent.com/58825866/140827654-77b8bc53-23c2-42ba-88e2-b9f9ffa41fe9.png)

I had a reminder to check this Nov. 12 - just missed. 
Based on the next expiry date, when will the certificate be actually renewed? I expect it might be a week or two before the expiry. 
Also it there some sort of query I can run regularly to check if the cert is expired?

**Comment by woodkri** [comment]
I see the updated certificate now and the searches are now working. We usually have the renewal automated on our linux servers but I'm not sure if the same is possible on windows or what it would look like.

**Comment by jeannekitchens** [comment]
This is on our next CE CaSS running topics list.  Let's see if Fritz can join and provide any insights.  Otherwise, since there's no new issue here, I'll close this.
