### ISSUE TITLE
Page Unresponsive CaSS Sandbox 

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#974]
I published a framework on Sandbox as Southern New Hampshire University.  It has 2,304 competencies that reference a concept scheme for levels.  It took about a minute to upload successfully.   However, the page is unresponsive.   [Link to framework](https://sandbox.credentialengine.org/cass-editor/?user=wait&link=true&newObjectEndpoint=https://sandbox.credentialengineregistry.org/resources/ce-&server=https://dev.cassproject.org/api/&ceasnDataFields=true&show=all&origin=https://sandbox.credentialengine.org&css=https://sandbox.credentialengine.org/publisher/Style/CassStyles&frameworkId=https://sandbox.credentialengineregistry.org/resources/ce-ba6dc1b5-364f-4270-9a10-4319f24ab18b#?user=wait&link=true&newObjectEndpoint=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-&server=https%3A%2F%2Fdev.cassproject.org%2Fapi%2F&ceasnDataFields=true&show=all&origin=https%3A%2F%2Fsandbox.credentialengine.org&css=https%3A%2F%2Fsandbox.credentialengine.org%2Fpublisher%2FStyle%2FCassStyles&frameworkId=https%3A%2F%2Fsandbox.credentialengineregistry.org%2Fresources%2Fce-ba6dc1b5-364f-4270-9a10-4319f24ab18b?frameworkId=https://sandbox.credentialengineregistry.org/resources/ce-ba6dc1b5-364f-4270-9a10-4319f24ab18b)  

![image](https://user-images.githubusercontent.com/20917206/143906164-cf3a4b06-7ff7-43a4-874e-bc93de533895.png)

**Comment by jeannekitchens** [comment]
Just opening it from the menu kills the page.

**Comment by woodkri** [comment]
@jeannekitchens This fix is now up on all 3 instances. Let me know if you're still seeing issues or if this can be closed.

**Comment by jeannekitchens** [comment]
@woodkri the page unresponsive is no longer an issue.  There's some other issues that likely need a different GitHub issues such as scrolling down to see high detail, or any detail of a large framework requires waiting for the competency data to render and the add competency link stays visible as you scroll down covering part of the screen rather than sticking to the top of the framework.

**Comment by woodkri** [comment]
It sounds like this one can be closed then. If there are other issues you've identified, new tickets would be great.
