### ISSUE TITLE
Attempts to save updates to a framework or concept scheme result in infinite spinner

### ISSUE THREAD

**Issue by mparsons-ce** [cassproject/cass-editor#978]
@woodkri 
**In production**
Jeff Grann was trying to save changes to the following framework:
https://apps.credentialengine.org/publisher/competencies/?frameworkctid=ce-c3285140-3cf8-11ec-aa33-0242ac160003

The editor seems to hang - the spinner is spinning but no save. 

I had a similar issue with saving a concept scheme.

**Comment by woodkri** [comment]
What kind of changes is he trying to make and save? I just tried creating a new framework in production and editing an old test one and they saved successfully.

**Comment by mparsons-ce** [comment]
He was updating Creator to make it a URL. 
I tried to recreate the latter and had the same error.

**Comment by woodkri** [comment]
I just tried editing the creator field in that framework to make it a URL and it saved for me. I then undid the change.

Our schema site briefly went down that day; I wonder if it happened to coincide with when you were trying to make edits. I have already created a ticket to put in a backup so viewing and editing will still work if that site becomes unavailable.

**Comment by woodkri** [comment]
@mparsons-ce Is this still an issue? I did put in the backup I mentioned in my above comment in case the schema site goes down again.
