### ISSUE TITLE
Providing CASS editor screen prompts to SKOS & ASN tabs in mapping spreadsheet

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#98]
It would help us in testing if the CASS team would fill in columns 'A' and 'H' for **both tabs** of the goggle sheet at [1] with the CASS editor screen prompts/labels. It'll help us make sure that: (1) we've got all properties handled; and (2) that the data is being mapped to the correct properties in the JSON-LD (columns 'D' and 'K' of the sheets.

[1] https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803

**Comment by Lomilar** [comment]
Done.
