### ISSUE TITLE
All Competency Framework URLs Resolve to the CaSS Instructions Instead of the Framework

### ISSUE THREAD

**Issue by jeannekitchens** [cassproject/cass-editor#980]
The link directly to a framework in CaSS does not  link to the framework.

![image](https://user-images.githubusercontent.com/20917206/144666658-140d3982-519e-4d3c-b5e4-5c7af3b661d0.png)
Pasted URL: https://cass.credentialengine.org/cass-editor/index.html?user=wait&editorRoot=/cass-editor/&server=https://cass.credentialengine.org/&ceasnDataFields=true&webSocketOverride=wss://cass.credentialengine.org:8080/ws/custom&newObjectEndpoint=https://credentialengineregistry.org/resources/ce-&show=all&origin=https://apps.credentialengine.org&css=https://apps.credentialengine.org/publisher/Style/CassStyles#/?frameworkId=https%3A%2F%2Fcredentialengineregistry.org%2Fresources%2Fce-e49dcaf3-5885-46e8-bd3c-cdbe765a8f1b

Goes to:
![image](https://user-images.githubusercontent.com/20917206/144666714-08f0aaec-4e6a-4508-ad6f-9e9fd594c2bd.png)

**Comment by woodkri** [comment]
Needs to be tested along with the param that directs user straight to framework page. It's currently taking them there rather than to the framework itself.
