### ISSUE TITLE
Dangling relation to a non-existent competency in editor.

### ISSUE THREAD

**Issue by stuartasutton** [cassproject/cass-editor#99]
There is a problem with the editor incorrectly displaying a "-" (or "+") where there is no subordinate node due to movement during editing

The "Compare and examine..." node had a child that was moved from child to sibling position but the original "+/-" did not disappear:

<img width="1044" alt="screenshot 2017-12-13 08 31 02" src="https://user-images.githubusercontent.com/2939046/33950001-0677d0d0-dfe0-11e7-999e-5c0f338f9709.png">

**Comment by Lomilar** [comment]
Repro: In the above screenshotted framework, there is a relation between 'dental arches' and a deleted competency.

**Comment by Lomilar** [comment]
@stuartasutton Did these come from an import or were they entered by hand?

**Comment by Lomilar** [comment]
Repro of framework: Deleting child competency does not delete the parent relation.
